/**
 * Generate the E2EE interoperability fixture consumed by native clients' test suites.
 *
 * Runs the REAL web-client crypto (shared/e2ee-crypto.ts, libsodium WASM) end to
 * end - KDF derivations, identity keypair, key wrapping, recovery wrapping,
 * conversation-key sealing, one message - and emits every input, intermediate,
 * and output as one JSON document. A native implementation (the Flutter app's
 * E2eeService) replays each step against the recorded inputs and must match
 * byte-for-byte; see docs/e2ee-interop-fixture.json for the committed copy and
 * the field-by-field verification contract in its `_readme`.
 *
 * Every secret in the output is generated fresh for the fixture and belongs to
 * no real account. Do not point this at real user data; there is no way to.
 *
 * Usage (from the repo root):
 *     bun run src/urbanlens/dashboard/frontend/ts/tools/generate-e2ee-fixture.ts > docs/e2ee-interop-fixture.json
 */
import sodium from "libsodium-wrappers-sumo";

import {
    KDF_MEMLIMIT,
    KDF_OPSLIMIT,
    cryptoReady,
    decryptMessage,
    deriveLoginKeys,
    encryptMessage,
    generateConversationKey,
    generateIdentity,
    generateRecoveryKey,
    randomSalt,
    sealToPublicKey,
    unseal,
    unwrapSecretKey,
    wrapSecretKey,
} from "../shared/e2ee-crypto";

function b64(bytes: Uint8Array): string {
    return sodium.to_base64(bytes, sodium.base64_variants.ORIGINAL);
}

async function main(): Promise<void> {
    await cryptoReady();

    const password = "correct horse battery staple (fixture-only)";
    const authSalt = randomSalt();
    const wrapSalt = randomSalt();
    const keys = deriveLoginKeys(password, authSalt, wrapSalt);

    const identity = generateIdentity();
    const wrappedPrivateKey = wrapSecretKey(identity.privateKey, keys.wrapKey);

    const recovery = generateRecoveryKey();
    const recoveryWrappedPrivateKey = wrapSecretKey(identity.privateKey, recovery.key);

    const conversationKey = generateConversationKey();
    const sealedConversationKey = sealToPublicKey(conversationKey, identity.publicKey);

    const plaintext = "Fixture message: héllo from the web client 🗺️";
    const message = encryptMessage(plaintext, conversationKey);

    // Self-check before emitting: every blob must round-trip through the same
    // module that produced it, or the fixture is corrupt by construction.
    const unwrapped = unwrapSecretKey(wrappedPrivateKey, keys.wrapKey);
    const recoveryUnwrapped = unwrapSecretKey(recoveryWrappedPrivateKey, recovery.key);
    const unsealed = unseal(sealedConversationKey, identity.publicKey, identity.privateKey);
    const decrypted = decryptMessage(message.ciphertext, message.nonce, conversationKey);
    if (
        unwrapped === null ||
        b64(unwrapped) !== b64(identity.privateKey) ||
        recoveryUnwrapped === null ||
        b64(recoveryUnwrapped) !== b64(identity.privateKey) ||
        unsealed === null ||
        b64(unsealed) !== b64(conversationKey) ||
        decrypted !== plaintext
    ) {
        throw new Error("Fixture self-check failed - refusing to emit a broken fixture.");
    }

    const fixture = {
        _readme: [
            "E2EE interoperability fixture, generated by the web client's own crypto",
            "(src/urbanlens/dashboard/frontend/ts/shared/e2ee-crypto.ts via libsodium).",
            "All secrets are fixture-only and belong to no real account.",
            "A conforming native implementation must reproduce, byte-for-byte:",
            "1. argon2id(password, auth_salt, kdf params) == expected.auth_key",
            "2. argon2id(password, wrap_salt, kdf params) == expected.wrap_key",
            "3. secretbox_open(wrapped_private_key = nonce||box, wrap_key) == identity.private_key",
            "4. secretbox_open(recovery.wrapped_private_key, recovery.key) == identity.private_key",
            "5. box_seal_open(conversation.sealed_to_public_key, identity keypair) == conversation.key",
            "6. secretbox_open(message.ciphertext, message.nonce, conversation.key) == message.plaintext",
            "   (message nonce and ciphertext are stored SEPARATELY; key-wrap blobs are nonce||box combined)",
            "7. base32-format recovery.key per the custom alphabet == recovery.display",
            "All base64 is the standard alphabet WITH padding.",
            "Regenerate: bun run src/urbanlens/dashboard/frontend/ts/tools/generate-e2ee-fixture.ts",
        ],
        kdf: {
            algorithm: "argon2id13",
            opslimit: KDF_OPSLIMIT,
            memlimit: KDF_MEMLIMIT,
            salt_bytes: sodium.crypto_pwhash_SALTBYTES,
            output_bytes: 32,
        },
        password,
        auth_salt: authSalt,
        wrap_salt: wrapSalt,
        expected: {
            auth_key: keys.authKey,
            wrap_key: b64(keys.wrapKey),
        },
        identity: {
            public_key: identity.publicKey,
            private_key: b64(identity.privateKey),
        },
        wrapped_private_key: wrappedPrivateKey,
        recovery: {
            key: b64(recovery.key),
            display: recovery.display,
            wrapped_private_key: recoveryWrappedPrivateKey,
        },
        conversation: {
            key: b64(conversationKey),
            sealed_to_public_key: sealedConversationKey,
        },
        message: {
            plaintext,
            ciphertext: message.ciphertext,
            nonce: message.nonce,
        },
    };

    console.log(JSON.stringify(fixture, null, 2));
}

await main();
