# Generated by Django 5.1.6 on 2026-02-07 20:34

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("church", "church"),
                            ("factory", "factory"),
                            ("home", "home"),
                            ("hospital", "hospital"),
                            ("school", "school"),
                            ("warehouse", "warehouse"),
                            ("office_building", "office_building"),
                            ("shopping_mall", "shopping_mall"),
                            ("hotel", "hotel"),
                            ("stadium", "stadium"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_categories",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "dashboard_tags",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeocodedLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("place_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "json_response",
                    models.CharField(blank=True, max_length=50000, null=True),
                ),
            ],
            options={
                "db_table": "dashboard_geocoded_locations",
                "get_latest_by": "updated",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="dashboard_g_latitud_9e6b87_idx",
                    ),
                    models.Index(
                        fields=["place_name"], name="dashboard_g_place_n_efe18b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("read", "Notifcation is unread: has not been seen."),
                            ("unread", "Notifcaiton has been seen."),
                            ("dismissed", "Notification was dismissed."),
                        ],
                        default="read",
                        max_length=17,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("lowest", "Lowest"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="lowest",
                        max_length=17,
                    ),
                ),
                (
                    "notificaiton_type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="error",
                        max_length=17,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=50000)),
            ],
            options={
                "db_table": "dashboard_notifications",
                "get_latest_by": "updated",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status"], name="dashboard_n_status_ff9f27_idx"
                    ),
                    models.Index(
                        fields=["importance"], name="dashboard_n_importa_7c7684_idx"
                    ),
                    models.Index(
                        fields=["notificaiton_type"],
                        name="dashboard_n_notific_045386_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("priority", models.IntegerField(default=0)),
                ("last_visited", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not visited", "Not Visited"),
                            ("visited", "Visited"),
                            ("wish to visit", "Wish To Visit"),
                            ("demolished", "Demolished"),
                        ],
                        default="wish to visit",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0),
                        geography=True,
                        srid=4326,
                    ),
                ),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("route", models.CharField(blank=True, max_length=80, null=True)),
                ("locality", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "administrative_area_level_1",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "administrative_area_level_2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "administrative_area_level_3",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("country", models.CharField(default="United States", max_length=20)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "zipcode_suffix",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "cached_place_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, default=list, to="urbanlens.dashboard.category"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_user_pins",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="urbanlens.dashboard.pin",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_images",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("avatar", models.ImageField(upload_to="")),
                ("instagram", models.CharField(blank=True, max_length=255, null=True)),
                ("discord", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("area", models.CharField(blank=True, max_length=255, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("started_exploring", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_profiles",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pin",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pins",
                to="urbanlens.dashboard.profile",
            ),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Requested", "Requested"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                            ("Removed", "Removed"),
                            ("Muted", "Muted"),
                            ("Blocked", "Blocked"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("Following", "Following"),
                            ("Friend", "Friend"),
                            ("Close Friend", "Close Friend"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "permissions",
                    models.CharField(
                        choices=[
                            ("Send Message", "Send Message"),
                            ("Invite to Events", "Invite to Events"),
                            ("Share Pins", "Share Pins"),
                            ("View Profile", "View Profile"),
                            ("View Friends", "View Friends"),
                            ("View Trips", "View Trips"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "from_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships",
                        to="urbanlens.dashboard.profile",
                    ),
                ),
                (
                    "to_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends_to_me",
                        to="urbanlens.dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_friendships",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500)),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="urbanlens.dashboard.pin",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="urbanlens.dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_comments",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review", models.TextField()),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="urbanlens.dashboard.pin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pin",
            name="tags",
            field=models.ManyToManyField(blank=True, default=list, to="urbanlens.dashboard.tag"),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0),
                        geography=True,
                        srid=4326,
                    ),
                ),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("route", models.CharField(blank=True, max_length=80, null=True)),
                ("locality", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "administrative_area_level_1",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "administrative_area_level_2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "administrative_area_level_3",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("country", models.CharField(default="United States", max_length=20)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "zipcode_suffix",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "cached_place_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        default=list,
                        related_name="locations",
                        to="urbanlens.dashboard.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        default=list,
                        related_name="locations",
                        to="urbanlens.dashboard.tag",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_locations",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "pins",
                    models.ManyToManyField(
                        blank=True, default=list, to="urbanlens.dashboard.pin"
                    ),
                ),
                (
                    "profiles",
                    models.ManyToManyField(
                        blank=True, related_name="trips", to="urbanlens.dashboard.profile"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trips",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="dashboard_p_user_id_eb17ed_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("from_profile", "to_profile")},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "pin")},
        ),
        migrations.AddIndex(
            model_name="pin",
            index=models.Index(
                fields=["profile"], name="dashboard_u_profile_945100_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pin",
            index=models.Index(
                fields=["profile", "priority"], name="dashboard_u_profile_f747ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pin",
            index=models.Index(
                fields=["profile", "last_visited"],
                name="dashboard_u_profile_67c4a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pin",
            index=models.Index(
                fields=["latitude", "longitude"], name="dashboard_u_latitud_b6864d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pin",
            unique_together={("latitude", "longitude", "profile")},
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["latitude", "longitude"], name="dashboard_l_latitud_ce2d4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["name"], name="dashboard_l_name_11ee30_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("latitude", "longitude")},
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["name"], name="dashboard_t_name_73c472_idx"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["start_date"], name="dashboard_t_start_d_978a04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["end_date"], name="dashboard_t_end_dat_1dca64_idx"
            ),
        ),
    ]
