# Generated by Django 6.0.6 on 2026-07-11 17:22, then split by hand.
#
# v0.4.0 upgrade, part 1 of 4: additive/safe schema changes only.
#   0002 (this file)  - new models, new columns, renames, safe alters, removals
#                       of old indexes/constraints. No data ops, no destructive
#                       column drops, no new indexes/constraints on existing
#                       tables.
#   0003 ..._data     - all RunPython backfills (pure data, no DDL).
#   0004 ..._cleanup  - destructive drops + NOT NULL enforcement + the
#                       location-coordinate freeze trigger (RunSQL).
#   0005 ..._indexes  - every AddIndex/AddConstraint, dead last.
# Keeping DDL and RunPython in separate migrations (= separate transactions)
# avoids PostgreSQL's "cannot CREATE INDEX/ALTER TABLE ... because it has
# pending trigger events" failures that killed earlier versions of this chain.
#
# Hand-fixes vs. the generated file:
#   - review.profile is added NULLABLE here (the generated default=0 would
#     write a dangling FK on every existing review row); 0003 backfills it
#     from review.user and 0004 makes it NOT NULL.
#   - AlterUniqueTogether(review) moved to 0004/0005 (the generated file ran
#     it before review.profile even existed).

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0001_initial",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Boundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "boundary_type",
                    models.CharField(
                        choices=[("property", "Property"), ("building", "Building")],
                        default="property",
                        max_length=20,
                    ),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "generated_polygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("default_radius_meters", models.IntegerField(default=50)),
            ],
            options={
                "verbose_name_plural": "boundaries",
                "db_table": "dashboard_boundaries",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("recipient_hash", models.CharField(max_length=64)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("join_invite", "Friend invitation"),
                            ("visit_invite", "Visit participant invitation"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_email_send_logs",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalVisitParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=100)),
                ("email_hash", models.CharField(blank=True, default="", max_length=64)),
                ("invite_sent", models.BooleanField(default=False)),
                ("suggestion_requested", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_external_visit_participants",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "google_email",
                    models.CharField(
                        blank=True,
                        help_text="Email of the connected Google account, for display only.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="Target calendar for imports/exports. 'primary' is the user's main calendar.",
                        max_length=255,
                    ),
                ),
                ("scopes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "dashboard_google_calendar_accounts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarkupMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("center_latitude", models.FloatField(blank=True, null=True)),
                ("center_longitude", models.FloatField(blank=True, null=True)),
                ("zoom", models.FloatField(blank=True, null=True)),
                (
                    "layer_mode",
                    models.CharField(
                        choices=[
                            ("street", "Street"),
                            ("satellite", "Satellite"),
                            ("topographic", "Topographic"),
                            ("dark", "Dark"),
                        ],
                        default="street",
                        max_length=20,
                    ),
                ),
                ("show_borders", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_markup_maps",
                "ordering": ["-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TripCalendarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "google_calendar_id",
                    models.CharField(default="primary", max_length=255),
                ),
                ("google_event_id", models.CharField(max_length=1024)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("imported", "Imported from Google Calendar"),
                            ("exported", "Exported to Google Calendar"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_trip_calendar_links",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UndoAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("model_label", models.CharField(max_length=50)),
                ("object_repr", models.CharField(max_length=255)),
                ("cache_key", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "dashboard_undo_actions",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wiki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "fences",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "alarms",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "cameras",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "signs",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "vps",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "plywood",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "locked",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=20000,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(20000)],
                    ),
                ),
                ("date_abandoned", models.DateField(blank=True, null=True)),
                ("date_last_active", models.DateField(blank=True, null=True)),
                (
                    "pin_type",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("building", "Building"),
                            ("entrance", "Entrance"),
                            ("poi", "Point of Interest"),
                            ("danger", "Danger"),
                            ("other", "Other"),
                        ],
                        default="location",
                        max_length=30,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "detail_bg_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("detail_bg_opacity", models.IntegerField(default=80)),
                (
                    "detail_border_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("detail_border_opacity", models.IntegerField(default=100)),
                ("viewed_by_other", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_wikis",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("nickname", "Nickname"),
                            ("official", "Official Name"),
                            ("alternate", "Alternate Name"),
                        ],
                        default="alternate",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(default="user", max_length=50)),
            ],
            options={
                "db_table": "dashboard_wiki_aliases",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("changes", models.JSONField()),
                ("reverted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_wiki_edits",
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiStatVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("danger", "Danger"),
                            ("vulnerability", "Vulnerability"),
                            ("priority", "Priority"),
                            ("rating", "Rating"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_wiki_stat_votes",
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="campus",
            name="campus_unique_location_default",
        ),
        migrations.RemoveConstraint(
            model_name="campus",
            name="campus_unique_pin",
        ),
        migrations.RemoveIndex(
            model_name="locationalias",
            name="idxdb_loc_alias_loc",
        ),
        migrations.RemoveConstraint(
            model_name="locationalias",
            name="db_loc_alias_unique",
        ),
        migrations.RemoveIndex(
            model_name="locationedit",
            name="idxdb_le_location",
        ),
        migrations.RemoveIndex(
            model_name="locationedit",
            name="idxdb_le_created",
        ),
        migrations.RemoveConstraint(
            model_name="pin",
            name="db_pin_unique_location_per_profile",
        ),
        migrations.RemoveConstraint(
            model_name="visitsuggestion",
            name="db_visit_suggestion_exactly_one_origin",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="idxdb_loc_name",
        ),
        migrations.RemoveIndex(
            model_name="pin",
            name="idxdb_pin_lat_long",
        ),
        migrations.RemoveIndex(
            model_name="pin",
            name="idxdb_pin_parent_loc",
        ),
        migrations.RemoveIndex(
            model_name="pinmarkup",
            name="idxdb_pm_location",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="instance_uuid",
            new_name="uuid",
        ),
        migrations.RenameIndex(
            model_name="pinalias",
            new_name="idxdb_palias_pin",
            old_name="idxdb_pin_alias_pin",
        ),
        migrations.RenameIndex(
            model_name="pinvisit",
            new_name="idxdb_pv_pin_vat",
            old_name="idxdb_pv_pin_visited",
        ),
        migrations.AddField(
            model_name="emailverification",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="image",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="checksum",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="copyright",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="exif_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="organize_dismissed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="image",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="wiki_safety_checkin",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="both",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="source_share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pins_created",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="unlogged_visit_dismissed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pinalias",
            name="kind",
            field=models.CharField(
                choices=[
                    ("nickname", "Nickname"),
                    ("official", "Official Name"),
                    ("alternate", "Alternate Name"),
                ],
                default="alternate",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pinalias",
            name="source",
            field=models.CharField(default="user", max_length=50),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="pin_shares", to="dashboard.image"
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="message",
            field=models.TextField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="parent_share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reshares",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="shared_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="tentative",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="community_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable features that allow you to interact with other users. Community wikis, Trips, and Friend Requests are included in this.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="deletion_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="distance_units",
            field=models.CharField(
                blank=True,
                choices=[("km", "Kilometers"), ("mi", "Miles")],
                help_text="Unit used for distances and travel stats. Defaults to your region.",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="external_apis_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow external services (weather, geocoding, place data, AI) to retrieve anonymized research data for you.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image_downscale_max_dimension",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tos_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="track_geolocation",
            field=models.BooleanField(
                default=True, help_text="Record visits from your live device location."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="track_pin_visits",
            field=models.BooleanField(
                default=True,
                help_text="Log visits to your pins from journal entries, imports, and photo tagging.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="track_routes",
            field=models.BooleanField(
                default=True, help_text="Save imported GPS routes/tracks."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="welcome_onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilenote",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="notify_community_wiki",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="wiki_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetypreference",
            name="auto_delete_after_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_name_source_priority",
            field=models.CharField(
                blank=True,
                default="google_places,wikipedia,nps",
                help_text="Comma-separated name-provider slugs, highest priority first, used to pick a location's official name from external candidates. Sources not listed rank last, in plugin order. Blank = plugin order only.",
                max_length=500,
                verbose_name="Name source priority",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_limit_per_day",
            field=models.IntegerField(
                default=20,
                help_text="Maximum user-triggered emails one user may send per day. Subscription roles can raise this. 0 = unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Email limit (per day)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_limit_per_hour",
            field=models.IntegerField(
                default=5,
                help_text="Maximum user-triggered emails (invitations etc.) one user may send per hour. Subscription roles can raise this. 0 = unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Email limit (per hour)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_limit_per_month",
            field=models.IntegerField(
                default=100,
                help_text="Maximum user-triggered emails one user may send per 30 days. Subscription roles can raise this. 0 = unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Email limit (per month)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="external_data_cache_days",
            field=models.IntegerField(
                default=7,
                help_text="Minimum number of days to cache external API responses before they are considered stale and re-fetched. Applies to every shared, Location-scoped external data source (Wikipedia, NPS, LoopNet, USGS, Nominatim, media archives, Google Places, web search, and satellite/street view imagery).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="External data cache (days)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_convert_webp",
            field=models.BooleanField(
                default=True,
                help_text="Re-encode processed uploads as WebP for additional storage savings.",
                verbose_name="Convert uploads to WebP",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_downscale_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Downscale uploaded photos that exceed the maximum dimension below, to save storage space. The original EXIF metadata is always preserved on the image record.",
                verbose_name="Downscale uploaded photos",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_downscale_max_dimension",
            field=models.IntegerField(
                default=1920,
                help_text="Longest edge (pixels) uploaded photos are downscaled to when downscaling is enabled. 1920px keeps plenty of detail for screens while reducing the size of a modern phone photo to roughly 1/8th.",
                validators=[
                    django.core.validators.MinValueValidator(256),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name="Max photo dimension (px)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_downscale_vip",
            field=models.BooleanField(
                default=False,
                help_text="Also downscale/convert uploads from users with an active subscription. When off, subscribers keep their original files (unless they opt into downscaling themselves).",
                verbose_name="Downscale subscriber uploads",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="storage_quota_gb",
            field=models.IntegerField(
                default=10,
                help_text="Storage quota (GB) for photo/video uploads per regular user. Subscription roles can override this with a larger quota. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="Default storage quota (GB)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="email_limit_per_day",
            field=models.IntegerField(
                blank=True,
                help_text="Max user-triggered emails per day for this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="email_limit_per_hour",
            field=models.IntegerField(
                blank=True,
                help_text="Max user-triggered emails per hour for this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="email_limit_per_month",
            field=models.IntegerField(
                blank=True,
                help_text="Max user-triggered emails per 30 days for this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="storage_quota_gb",
            field=models.IntegerField(
                blank=True,
                help_text="Storage quota (GB) for users with this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="from_my_activity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="origin_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestions",
                to="dashboard.image",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                max_length=10000,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.pin",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_images",
                to="dashboard.profile",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=10000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="pinmarkup",
            name="label",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Journal"),
                    ("history", "Imported"),
                    ("trip", "Trip"),
                    ("user", "A Friend's Journal"),
                    ("photo", "Photo"),
                    ("geolocation", "Geolocation"),
                    ("safety_checkin", "Safety Check-in"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="comment_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="friends",
                help_text="Who can see your contact methods (phone, Signal, Discord, etc.).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="friend_request_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_upload_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                help_text="Who can see the photos you upload to locations.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="trip_pin_location_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                help_text="When you share one of your pins as a trip activity, who can see the actual location? Members outside this setting will only see the pin name.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="viewer_photo_filter",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                help_text="Whose photos you want to see. Photos from users outside this setting will be blurred.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="safetypreference",
            name="default_message",
            field=models.TextField(
                blank=True,
                default="Hi! I went on a trip and set up an automated safety check-in: if I don't confirm I'm safe by my expected return time, this message is sent to my emergency contacts. If you're reading this, I didn't come home and may need help - please try to reach me, and if you can't, use the trip plan included with this alert to help find me. I may not be able to use my phone to contact anyone else for help, so it's important you try to help me.",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=10000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="tripactivity",
            name="notes",
            field=models.TextField(
                blank=True,
                max_length=10000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="tripcomment",
            name="text",
            field=models.TextField(
                max_length=10000,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="origin_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions_sent",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestions",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="trip_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestions",
                to="dashboard.tripactivity",
            ),
        ),
        migrations.AddField(
            model_name="boundary",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boundaries",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="boundary",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boundaries",
                to="dashboard.pin",
            ),
        ),
        migrations.AddField(
            model_name="boundary",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boundaries",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="emailsendlog",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_send_logs",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="externalvisitparticipant",
            name="matched_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_visit_participations",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="externalvisitparticipant",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_participants",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AddField(
            model_name="googlecalendaraccount",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_calendar_account",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="markupmap",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup_maps",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="markup_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="pinmarkup",
            name="parent_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="markup_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="markup_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_checkins",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="markup_maps",
            field=models.ManyToManyField(
                blank=True,
                related_name="attached_safety_checkins",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="tripcomment",
            name="markup_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trip_comments",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="tripcalendarlink",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_links",
                to="dashboard.tripactivity",
            ),
        ),
        migrations.AddField(
            model_name="tripcalendarlink",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_calendar_links",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="tripcalendarlink",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_links",
                to="dashboard.trip",
            ),
        ),
        migrations.AddField(
            model_name="undoaction",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="undo_actions",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="badges",
            field=models.ManyToManyField(
                blank=True, related_name="wikis", to="dashboard.badge"
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_wikis",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="wiki",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="parent_wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_wikis",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="boundary",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boundaries",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pins",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="pinmarkup",
            name="parent_wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup_items",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="wikialias",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_aliases_created",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wikialias",
            name="wiki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="wikiedit",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_edits",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wikiedit",
            name="reverted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reverts",
                to="dashboard.wikiedit",
            ),
        ),
        migrations.AddField(
            model_name="wikiedit",
            name="wiki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edits",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="wikistatvote",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wiki_stat_votes",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wikistatvote",
            name="wiki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stat_votes",
                to="dashboard.wiki",
            ),
        ),
    ]
