# Generated by Django 6.0.6 on 2026-07-05 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="pin_shared",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="visit_suggested",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="visit_participations", to="dashboard.profile"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("history", "History"),
                    ("trip", "Trip"),
                    ("user", "User"),
                    ("photo", "Photo"),
                    ("geolocation", "Geolocation"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VisitSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("visited_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "candidate_profiles",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="dashboard.profile"
                    ),
                ),
                (
                    "existing_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_suggestions",
                        to="dashboard.pinvisit",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_suggestions",
                        to="dashboard.location",
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_suggestion",
                        to="dashboard.notificationlog",
                    ),
                ),
                (
                    "origin_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions_sent",
                        to="dashboard.pinvisit",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_visit_suggestions",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "suggested_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_visit_suggestions",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "trip_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_suggestions",
                        to="dashboard.tripactivity",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_visit_suggestions",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["suggested_to", "status"],
                        name="dashboard_visit_st_status_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("origin_visit__isnull", False),
                            ("trip_activity__isnull", False),
                            _connector="XOR",
                        ),
                        name="dashboard_visit_suggestion_exactly_one_origin",
                    )
                ],
            },
        ),
    ]
