# Generated by Django 6.0.6 on 2026-07-07 17:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models
from django.db.models import F
from django.contrib.gis.geos import Point

# Smallest representable step at the field's decimal_places=6 precision. Used to
# nudge colliding root-pin coordinates apart (~0.1m, negligible on the map).
COORD_STEP = Decimal("0.000001")


def backfill_pin_coordinates(apps, schema_editor):
    Pin = apps.get_model("dashboard", "Pin")
    # Process rows with existing coordinates first so they claim their slot in
    # `seen` before NULL rows are backfilled and (if necessary) nudged.
    pins = (
        Pin.objects.select_related("location")
        .only(
            "latitude",
            "longitude",
            "point",
            "profile",
            "parent_pin",
            "parent_location",
            "location__latitude",
            "location__longitude",
        )
        .order_by(F("latitude").asc(nulls_last=True), F("longitude").asc(nulls_last=True), "pk")
    )
    updated = []
    # The db_pin_unique_location_per_profile partial unique constraint covers
    # (latitude, longitude, profile) for root pins (no parent_pin/parent_location).
    # Coordinates used to be nullable and Postgres treats NULLs as distinct, so a
    # profile could hold several root pins that now backfill to identical non-null
    # coordinates (e.g. duplicates sharing a Location, or the 0,0 fallback). Track
    # claimed coordinates and nudge collisions apart to avoid violating the
    # constraint mid-migration.
    seen: set[tuple[int | None, Decimal, Decimal]] = set()
    for pin in pins.iterator():
        latitude = pin.latitude
        longitude = pin.longitude

        if latitude is None and pin.location_id and pin.location.latitude is not None:
            latitude = pin.location.latitude
        if longitude is None and pin.location_id and pin.location.longitude is not None:
            longitude = pin.location.longitude

        if (latitude is None or longitude is None) and pin.point:
            latitude = latitude if latitude is not None else pin.point.y
            longitude = longitude if longitude is not None else pin.point.x

        # Legacy rows without a location or point should not exist for normal pins,
        # but use the historical PointField default so the NOT NULL migration can
        # complete instead of failing mid-deploy.
        latitude = latitude if latitude is not None else 0
        longitude = longitude if longitude is not None else 0

        latitude = Decimal(str(latitude)).quantize(COORD_STEP)
        longitude = Decimal(str(longitude)).quantize(COORD_STEP)

        is_root = pin.parent_pin_id is None and pin.parent_location_id is None
        if is_root:
            while (pin.profile_id, latitude, longitude) in seen:
                longitude += COORD_STEP
            seen.add((pin.profile_id, latitude, longitude))

        point = Point(float(longitude), float(latitude), srid=4326)
        if pin.latitude != latitude or pin.longitude != longitude or pin.point != point:
            pin.latitude = latitude
            pin.longitude = longitude
            pin.point = point
            updated.append(pin)

    if updated:
        Pin.objects.bulk_update(updated, ["latitude", "longitude", "point"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0001_initial_squashed_0006_alter_notificationlog_notification_type_and_more",
        ),
    ]

    operations = [        
        migrations.RunPython(backfill_pin_coordinates, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="visitsuggestion",
            name="db_visit_suggestion_exactly_one_origin",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="instance_uuid",
            new_name="uuid",
        ),
        migrations.RenameIndex(
            model_name="pinvisit",
            new_name="idxdb_pv_pin_vat",
            old_name="idxdb_pv_pin_visited",
        ),
        migrations.AddField(
            model_name="emailverification",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="image",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="map_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="tentative",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="distance_units",
            field=models.CharField(
                blank=True,
                choices=[("km", "Kilometers"), ("mi", "Miles")],
                help_text="Unit used for distances and travel stats. Defaults to your region.",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilenote",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="origin_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestions",
                to="dashboard.image",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campuses",
                to="dashboard.profile",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.pin",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_images",
                to="dashboard.profile",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="pin",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Journal"),
                    ("history", "Imported"),
                    ("trip", "Trip"),
                    ("user", "A Friend's Journal"),
                    ("photo", "Photo"),
                    ("geolocation", "Geolocation"),
                    ("safety_checkin", "Safety Check-in"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="origin_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions_sent",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestions",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="trip_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestions",
                to="dashboard.tripactivity",
            ),
        ),
        migrations.AddIndex(
            model_name="pinvisit",
            index=models.Index(fields=["pin", "tentative"], name="idxdb_pv_pin_tent"),
        ),
        migrations.AddIndex(
            model_name="pinvisit",
            index=models.Index(
                fields=["pin", "visited_at", "tentative"], name="idxdb_pv_pin_vat_tent"
            ),
        ),
        migrations.AddConstraint(
            model_name="visitsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("origin_visit__isnull", False),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", True),
                        ("origin_image__isnull", True),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", False),
                        ("safety_checkin__isnull", True),
                        ("origin_image__isnull", True),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", False),
                        ("origin_image__isnull", True),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", True),
                        ("origin_image__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="db_visit_suggestion_exactly_one_origin",
            ),
        ),
    ]
