# Generated by Django 6.0.6 on 2026-07-06 04:01

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContactDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("label", models.CharField(blank=True, default="", max_length=150)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "dashboard_safety_contact_defaults",
                "ordering": ["order", "created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gpx_track", "GPX Track"),
                            ("gpx_route", "GPX Route"),
                            (
                                "google_takeout_semantic",
                                "Google Takeout (Semantic History)",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True, srid=4326
                    ),
                ),
                ("raw_point_count", models.IntegerField(default=0)),
                ("simplified_point_count", models.IntegerField(default=0)),
                ("distance_meters", models.FloatField(default=0.0)),
                ("elevation_gain_meters", models.FloatField(blank=True, null=True)),
                ("elevation_loss_meters", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_routes",
                "ordering": ["-started_at", "-created"],
                "get_latest_by": "started_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("plan_details", models.TextField(blank=True, default="")),
                ("contact_message", models.TextField(blank=True, default="")),
                ("checkin_by", models.DateTimeField()),
                (
                    "grace_period",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("awaiting_checkin", "Awaiting Check-in"),
                            ("checked_in", "Checked In"),
                            ("overdue", "Overdue"),
                            ("found_safe", "Found Safe"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "destination_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_safety_checkins",
                "ordering": ["-checkin_by"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckinContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("found_safe_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_safety_checkin_contacts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckinMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
            ],
            options={
                "db_table": "dashboard_safety_checkin_messages",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("default_message", models.TextField(blank=True, default="")),
                (
                    "default_grace_period",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
            ],
            options={
                "db_table": "dashboard_safety_preferences",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VisitSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("visited_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_visit_suggestions",
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="googleplace",
            name="dashboard_google_place_unique_coordinates",
        ),
        migrations.RemoveConstraint(
            model_name="locationalias",
            name="dashboard_loc_alias_unique",
        ),
        migrations.RemoveConstraint(
            model_name="pin",
            name="dashboard_pin_unique_location_per_profile",
        ),
        migrations.RemoveConstraint(
            model_name="pin",
            name="dashboard_pin_unique_slug_per_profile",
        ),
        migrations.RemoveConstraint(
            model_name="pinalias",
            name="dashboard_pin_alias_unique",
        ),
        migrations.RemoveConstraint(
            model_name="pinshare",
            name="dashboard_pin_share_one_pending_per_pin_user",
        ),
        migrations.RenameIndex(
            model_name="apicalllog",
            new_name="idxdb_apilog_svc_cdt",
            old_name="api_log_service_created_idx",
        ),
        migrations.RenameIndex(
            model_name="badge",
            new_name="idxdb_badge_uuid",
            old_name="dashboard_badge_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="badge",
            new_name="idxdb_badge_profile",
            old_name="dashboard_t_profile_1073fa_idx",
        ),
        migrations.RenameIndex(
            model_name="badge",
            new_name="idxdb_badge_pfile_ord",
            old_name="dashboard_t_profile_a6ab65_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="idxdb_comment_uuid",
            old_name="dashboard_comment_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="geocodedlocation",
            new_name="idxdb_geoloc_lat_lng",
            old_name="dashboard_g_latitud_9e6b87_idx",
        ),
        migrations.RenameIndex(
            model_name="geocodedlocation",
            new_name="idxdb_geoloc_placename",
            old_name="dashboard_g_place_n_efe18b_idx",
        ),
        migrations.RenameIndex(
            model_name="googleplace",
            new_name="idxdb_gplace_lat_long",
            old_name="dashboard_g_latitud_4cc7c1_idx",
        ),
        migrations.RenameIndex(
            model_name="googleplace",
            new_name="idxdb_gplace_cid",
            old_name="dashboard_g_cid_617a60_idx",
        ),
        migrations.RenameIndex(
            model_name="image",
            new_name="idxdb_image_uuid",
            old_name="dashboard_image_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="idxdb_loc_uuid",
            old_name="dashboard_l_uuid_f3ca34_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="idxdb_loc_lat_long",
            old_name="dashboard_l_latitud_ce2d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="idxdb_loc_name",
            old_name="dashboard_l_name_11ee30_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="idxdb_loc_offname",
            old_name="dashboard_l_officia_b6eaaa_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="idxdb_loc_gplace",
            old_name="dashboard_l_google__6d26b1_idx",
        ),
        migrations.RenameIndex(
            model_name="locationalias",
            new_name="idxdb_loc_alias_loc",
            old_name="dashboard_loc_alias_loc_idx",
        ),
        migrations.RenameIndex(
            model_name="locationcache",
            new_name="idxdb_loccache_source",
            old_name="dashboard_l_locatio_5f8691_idx",
        ),
        migrations.RenameIndex(
            model_name="locationedit",
            new_name="idxdb_le_location",
            old_name="dashboard_le_location_idx",
        ),
        migrations.RenameIndex(
            model_name="locationedit",
            new_name="idxdb_le_created",
            old_name="dashboard_le_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="idxdb_notif_pfile_stat",
            old_name="dashboard_n_profile_f04aa9_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="idxdb_notif_status",
            old_name="dashboard_n_status_ff9f27_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="idxdb_notif_import",
            old_name="dashboard_n_importa_7c7684_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="idxdb_notif_type",
            old_name="dashboard_n_notific_025668_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_pin_uuid",
            old_name="dashboard_u_uuid_1898a2_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_pin_profile",
            old_name="dashboard_u_profile_945100_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_pin_pfile_prio",
            old_name="dashboard_u_profile_f747ec_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_pin_pfile_lvisit",
            old_name="dashboard_u_profile_67c4a2_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_profile_update",
            old_name="dashboard_profile_update_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_pin_lat_long",
            old_name="dashboard_u_latitud_b6864d_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_pin_parent_pin",
            old_name="dashboard_u_parent__483403_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="idxdb_pin_parent_loc",
            old_name="dashboard_parent_loc_idx",
        ),
        migrations.RenameIndex(
            model_name="pinalias",
            new_name="idxdb_pin_alias_pin",
            old_name="dashboard_pin_alias_pin_idx",
        ),
        migrations.RenameIndex(
            model_name="pinmarkup",
            new_name="idxdb_pm_pin",
            old_name="dashboard_pm_pin_idx",
        ),
        migrations.RenameIndex(
            model_name="pinmarkup",
            new_name="idxdb_pm_location",
            old_name="dashboard_pm_location_idx",
        ),
        migrations.RenameIndex(
            model_name="pinmarkup",
            new_name="idxdb_pm_profile",
            old_name="dashboard_pm_profile_idx",
        ),
        migrations.RenameIndex(
            model_name="pinnote",
            new_name="idxdb_pn_pin",
            old_name="dashboard_pn_pin_idx",
        ),
        migrations.RenameIndex(
            model_name="pinshare",
            new_name="idxdb_pinshr_to_pfl_stat",
            old_name="dashboard_p_to_prof_5d03ec_idx",
        ),
        migrations.RenameIndex(
            model_name="pinshare",
            new_name="idxdb_pinshr_f_pfl_cdt",
            old_name="dashboard_p_from_pr_1593ec_idx",
        ),
        migrations.RenameIndex(
            model_name="pinvisit",
            new_name="idxdb_pv_uuid",
            old_name="dashboard_pv_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="pinvisit",
            new_name="idxdb_pv_pin",
            old_name="dashboard_pv_pin_idx",
        ),
        migrations.RenameIndex(
            model_name="pinvisit",
            new_name="idxdb_pv_pin_visited",
            old_name="dashboard_pv_pin_visited_idx",
        ),
        migrations.RenameIndex(
            model_name="profile",
            new_name="idxdb_profile_user",
            old_name="dashboard_p_user_id_eb17ed_idx",
        ),
        migrations.RenameIndex(
            model_name="reaction",
            new_name="idxdb_react_trcomment",
            old_name="reaction_trip_comment_idx",
        ),
        migrations.RenameIndex(
            model_name="sociallink",
            new_name="idxdb_soc_link_pfile",
            old_name="dashboard_s_profile_85d0eb_idx",
        ),
        migrations.RenameIndex(
            model_name="trip",
            new_name="idxdb_trip_uuid",
            old_name="dashboard_trip_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="trip",
            new_name="idxdb_trip_start_date",
            old_name="dashboard_t_start_d_978a04_idx",
        ),
        migrations.RenameIndex(
            model_name="trip",
            new_name="idxdb_trip_end_date",
            old_name="dashboard_t_end_dat_1dca64_idx",
        ),
        migrations.RenameIndex(
            model_name="tripactivity",
            new_name="idxdb_ta_trip",
            old_name="dashboard_ta_trip_idx",
        ),
        migrations.RenameIndex(
            model_name="tripactivity",
            new_name="idxdb_ta_trip_dt",
            old_name="dashboard_ta_trip_dt_idx",
        ),
        migrations.RenameIndex(
            model_name="tripactivityvote",
            new_name="idxdb_tav_activity",
            old_name="dashboard_tav_activity_idx",
        ),
        migrations.RenameIndex(
            model_name="tripcomment",
            new_name="idxdb_tc_trip",
            old_name="dashboard_tc_trip_idx",
        ),
        migrations.RenameIndex(
            model_name="tripmembership",
            new_name="idxdb_tm_trip",
            old_name="dashboard_tm_trip_idx",
        ),
        migrations.AddField(
            model_name="image",
            name="taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="pin_shared",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="visit_suggested",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="visit_participations", to="dashboard.profile"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_document_import_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI to extract pins from uploaded plain-text and Word documents during pin import.",
                verbose_name="Document pin import",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_document_import_max_chars",
            field=models.IntegerField(
                default=20000,
                help_text="Maximum number of characters read from an uploaded .txt/.docx file before AI import rejects it outright, to bound token usage per document. Uploads longer than this are not truncated - the user is asked to shorten the file instead.",
                validators=[
                    django.core.validators.MinValueValidator(500),
                    django.core.validators.MaxValueValidator(200000),
                ],
                verbose_name="Document import max length (characters)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_admin_email",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email address that receives critical site notifications (e.g. pin import failures). Defaults to the UL_ADMIN_NOTIFICATION_EMAIL environment variable.",
                max_length=254,
                verbose_name="Admin notification email",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_gotify_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Gotify application token used to authenticate pushes to the server above. Defaults to the UL_GOTIFY_TOKEN environment variable.",
                max_length=200,
                verbose_name="Gotify app token",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_gotify_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base URL of a Gotify server (e.g. https://gotify.example.com) used to push critical site notifications. Defaults to the UL_GOTIFY_URL environment variable.",
                max_length=500,
                verbose_name="Gotify server URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_pin_import_errors_email",
            field=models.BooleanField(
                default=True,
                help_text="Email the admin notification address when a pin import fails to process an uploaded file.",
                verbose_name="Pin import errors (email)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_pin_import_errors_gotify",
            field=models.BooleanField(
                default=False,
                help_text="Send a Gotify push notification when a pin import fails to process an uploaded file.",
                verbose_name="Pin import errors (Gotify)",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("history", "History"),
                    ("trip", "Trip"),
                    ("user", "User"),
                    ("photo", "Photo"),
                    ("geolocation", "Geolocation"),
                    ("safety_checkin", "Safety Check-in"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="googleplace",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"),
                name="db_google_place_unique_coordinates",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationalias",
            constraint=models.UniqueConstraint(
                fields=("location", "name"), name="db_loc_alias_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("parent_location__isnull", True), ("parent_pin__isnull", True)
                ),
                fields=("latitude", "longitude", "profile"),
                name="db_pin_unique_location_per_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("profile", "slug"),
                name="db_pin_unique_slug_per_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="pinalias",
            constraint=models.UniqueConstraint(
                fields=("pin", "name"), name="db_pin_alias_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pinshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("pin", "to_profile"),
                name="db_pinshare_one_pending_per_pin_user",
            ),
        ),
        migrations.AddField(
            model_name="emergencycontactdefault",
            name="contact_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="emergencycontactdefault",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_contact_defaults",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="dashboard.route",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_checkins",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_checkins",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="pinmarkup",
            name="parent_safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup_items",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckincontact",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckincontact",
            name="contact_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinmessage",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinmessage",
            name="sender_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.safetycheckincontact",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinmessage",
            name="sender_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="safetypreference",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_preference",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="candidate_profiles",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="dashboard.profile"
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="existing_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merge_suggestions",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestions",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="notification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_suggestion",
                to="dashboard.notificationlog",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="origin_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions_sent",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_suggestions",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="suggested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_visit_suggestions",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="suggested_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_visit_suggestions",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="trip_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_suggestions",
                to="dashboard.tripactivity",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontactdefault",
            index=models.Index(fields=["owner"], name="idxdb_ecd_owner"),
        ),
        migrations.AddConstraint(
            model_name="emergencycontactdefault",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contact_profile__isnull", False),
                    ("email__isnull", False),
                    _connector="XOR",
                ),
                name="db_safety_contact_default_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["uuid"], name="idxdb_route_uuid"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["profile"], name="idxdb_route_profile"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["profile", "started_at"], name="idxdb_rte_pfile_start"
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(fields=["uuid"], name="idxdb_sc_uuid"),
        ),
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(
                fields=["profile", "status"], name="idxdb_sc_profile_status"
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(
                fields=["status", "checkin_by"], name="idxdb_sc_status_by"
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckincontact",
            index=models.Index(fields=["checkin"], name="idxdb_scc_checkin"),
        ),
        migrations.AddIndex(
            model_name="safetycheckincontact",
            index=models.Index(fields=["token"], name="idxdb_scc_token"),
        ),
        migrations.AddConstraint(
            model_name="safetycheckincontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contact_profile__isnull", False),
                    ("email__isnull", False),
                    _connector="XOR",
                ),
                name="db_safety_checkin_contact_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckinmessage",
            index=models.Index(fields=["checkin"], name="idxdb_scm_checkin"),
        ),
        migrations.AddIndex(
            model_name="visitsuggestion",
            index=models.Index(
                fields=["suggested_to", "status"], name="idxdb_visit_st_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="visitsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("origin_visit__isnull", False),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", True),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", False),
                        ("safety_checkin__isnull", True),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="db_visit_suggestion_exactly_one_origin",
            ),
        ),
    ]
