# Generated by Django 6.0.6 on 2026-07-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_v0_4_0b0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="image_convert_webp",
            field=models.BooleanField(
                default=True,
                help_text="Re-encode processed uploads as WebP for additional storage savings.",
                verbose_name="Convert uploads to WebP",
            ),
        ),
    ]
