# Generated by Django 6.0.6 on 2026-06-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("unread", "Notification is unread: has not been seen."),
                    ("read", "Notification has been seen."),
                    ("dismissed", "Notification was dismissed."),
                ],
                default="unread",
                max_length=17,
            ),
        ),
    ]
