# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_notificationpreference_pin_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_document_import_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI to extract pins from uploaded plain-text and Word documents during pin import.",
                verbose_name="Document pin import",
            ),
        ),
    ]
