# Generated by Django 6.0.6 on 2026-07-06 03:49

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_route_visitsuggestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContactDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("label", models.CharField(blank=True, default="", max_length=150)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "dashboard_safety_contact_defaults",
                "ordering": ["order", "created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("plan_details", models.TextField(blank=True, default="")),
                ("contact_message", models.TextField(blank=True, default="")),
                ("checkin_by", models.DateTimeField()),
                (
                    "grace_period",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("awaiting_checkin", "Awaiting Check-in"),
                            ("checked_in", "Checked In"),
                            ("overdue", "Overdue"),
                            ("found_safe", "Found Safe"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "destination_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_safety_checkins",
                "ordering": ["-checkin_by"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckinContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("found_safe_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_safety_checkin_contacts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckinMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
            ],
            options={
                "db_table": "dashboard_safety_checkin_messages",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("default_message", models.TextField(blank=True, default="")),
                (
                    "default_grace_period",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
            ],
            options={
                "db_table": "dashboard_safety_preferences",
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="visitsuggestion",
            name="db_visit_suggestion_exactly_one_origin",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_checkin_due", "Safety Check-in Due"),
                    ("safety_checkin_overdue", "Safety Check-in Overdue"),
                    ("safety_checkin_resolved", "Safety Check-in Resolved"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("history", "History"),
                    ("trip", "Trip"),
                    ("user", "User"),
                    ("photo", "Photo"),
                    ("geolocation", "Geolocation"),
                    ("safety_checkin", "Safety Check-in"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emergencycontactdefault",
            name="contact_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="emergencycontactdefault",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_contact_defaults",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_checkins",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_checkins",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="pinmarkup",
            name="parent_safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup_items",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_suggestions",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("origin_visit__isnull", False),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", True),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", False),
                        ("safety_checkin__isnull", True),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="db_visit_suggestion_exactly_one_origin",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckincontact",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckincontact",
            name="contact_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinmessage",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinmessage",
            name="sender_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.safetycheckincontact",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinmessage",
            name="sender_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="safetypreference",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_preference",
                to="dashboard.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontactdefault",
            index=models.Index(fields=["owner"], name="idxdb_ecd_owner"),
        ),
        migrations.AddConstraint(
            model_name="emergencycontactdefault",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contact_profile__isnull", False),
                    ("email__isnull", False),
                    _connector="XOR",
                ),
                name="db_safety_contact_default_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(fields=["uuid"], name="idxdb_sc_uuid"),
        ),
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(
                fields=["profile", "status"], name="idxdb_sc_profile_status"
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(
                fields=["status", "checkin_by"], name="idxdb_sc_status_by"
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckincontact",
            index=models.Index(fields=["checkin"], name="idxdb_scc_checkin"),
        ),
        migrations.AddIndex(
            model_name="safetycheckincontact",
            index=models.Index(fields=["token"], name="idxdb_scc_token"),
        ),
        migrations.AddConstraint(
            model_name="safetycheckincontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contact_profile__isnull", False),
                    ("email__isnull", False),
                    _connector="XOR",
                ),
                name="db_safety_checkin_contact_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckinmessage",
            index=models.Index(fields=["checkin"], name="idxdb_scm_checkin"),
        ),
    ]
