# Generated by Django 6.0.6 on 2026-07-10 01:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_image_convert_webp_default_true"),
    ]

    operations = [
        migrations.CreateModel(
            name="UndoAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("model_label", models.CharField(max_length=50)),
                ("object_repr", models.CharField(max_length=255)),
                ("cache_key", models.CharField(max_length=64, unique=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="undo_actions",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_undo_actions",
                "ordering": ["-created"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "created"], name="idxdb_undo_profile_created"
                    )
                ],
            },
        ),
    ]
