# Generated by Django 6.0.6 on 2026-06-26 18:22

from django.db import migrations, models


def copy_location_coordinates_to_pins(apps, schema_editor):
    """Populate null Pin coordinates from the linked Location before NOT NULL."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE dashboard_user_pins AS p
            SET latitude = l.latitude,
                longitude = l.longitude
            FROM dashboard_locations AS l
            WHERE p.location_id = l.id
              AND (p.latitude IS NULL OR p.longitude IS NULL)
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_notificationlog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="administrative_area_level_1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="administrative_area_level_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="administrative_area_level_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="cached_place_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="cid",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="country",
            field=models.CharField(default="United States", max_length=20),
        ),
        migrations.AddField(
            model_name="pin",
            name="locality",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="route",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="street_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="zipcode_suffix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(
            copy_location_coordinates_to_pins,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="pin",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="pin",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
