# Generated by Django 6.0.6

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sitesettings_ai_document_import_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_document_import_max_chars",
            field=models.IntegerField(
                default=20000,
                help_text=(
                    "Maximum number of characters read from an uploaded .txt/.docx file before AI import "
                    "rejects it outright, to bound token usage per document. Uploads longer than this are "
                    "not truncated - the user is asked to shorten the file instead."
                ),
                validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(200000)],
                verbose_name="Document import max length (characters)",
            ),
        ),
    ]
