# Generated by Django 6.0.6 on 2026-07-07 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models
_SECURITY_FIELDS = ("fences", "alarms", "cameras", "security", "signs", "vps", "plywood", "locked")


def _has_community_content(loc) -> bool:
    name = (loc.name or "").strip()
    if name and name != "Unnamed Location":
        return True
    if (loc.description or "").strip():
        return True
    if loc.date_abandoned or loc.date_last_active:
        return True
    if any(getattr(loc, f, "unknown") not in (None, "", "unknown") for f in _SECURITY_FIELDS):
        return True
    if loc.badges.exists():
        return True
    if loc.aliases.exists() or loc.edits.exists() or loc.comments.exists():
        return True
    return bool(loc.location_detail_pins.exists() or loc.markup_items.exists() or loc.images.exists())


def backfill_wikis(apps, schema_editor):
    Location = apps.get_model("dashboard", "Location")
    Wiki = apps.get_model("dashboard", "Wiki")
    WikiAlias = apps.get_model("dashboard", "WikiAlias")
    WikiEdit = apps.get_model("dashboard", "WikiEdit")

    for loc in Location.objects.all().iterator():
        if not _has_community_content(loc):
            continue

        wiki, created = Wiki.objects.get_or_create(
            location=loc,
            defaults={
                "name": (loc.name or loc.official_name or "Unnamed Location"),
                "description": loc.description,
                "date_abandoned": loc.date_abandoned,
                "date_last_active": loc.date_last_active,
                **{f: getattr(loc, f, "unknown") for f in _SECURITY_FIELDS},
            },
        )
        if not created:
            continue

        # Shared taxonomy.
        wiki.badges.set(loc.badges.all())

        # Aliases -> WikiAlias.
        for alias in loc.aliases.all():
            WikiAlias.objects.create(
                wiki=wiki,
                name=alias.name,
                created_by=alias.created_by,
            )

        # Edit history -> WikiEdit (two-pass so reverted_by self-links resolve).
        edit_map: dict[int, object] = {}
        for edit in loc.edits.all().order_by("created"):
            new_edit = WikiEdit.objects.create(
                wiki=wiki,
                changes=edit.changes,
                reverted=edit.reverted,
                editor=edit.editor,
            )
            edit_map[edit.id] = new_edit
        for edit in loc.edits.all():
            if edit.reverted_by_id and edit.reverted_by_id in edit_map and edit.id in edit_map:
                target = edit_map[edit.id]
                target.reverted_by = edit_map[edit.reverted_by_id]
                target.save(update_fields=["reverted_by"])

        # Repoint related rows from Location to Wiki.
        loc.comments.all().update(wiki=wiki)
        loc.location_detail_pins.all().update(parent_wiki=wiki)
        loc.markup_items.all().update(parent_wiki=wiki)
        loc.images.all().update(wiki=wiki)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_image_organize_dismissed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wiki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "fences",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "alarms",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "cameras",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "signs",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "vps",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "plywood",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "locked",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("no", "No"),
                            ("some", "Some"),
                            ("everywhere", "Everywhere"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_abandoned", models.DateField(blank=True, null=True)),
                ("date_last_active", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_wikis",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("nickname", "Nickname"),
                            ("official", "Official Name"),
                            ("alternate", "Alternate Name"),
                        ],
                        default="alternate",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User-defined Alias"),
                            ("google_places", "Google Places"),
                            ("wikipedia", "Wikipedia"),
                            ("other", "Other"),
                        ],
                        default="user",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_wiki_aliases",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("changes", models.JSONField()),
                ("reverted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_wiki_edits",
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="locationalias",
            name="idxdb_loc_alias_loc",
        ),
        migrations.RemoveConstraint(
            model_name="locationalias",
            name="db_loc_alias_unique",
        ),
        migrations.RemoveIndex(
            model_name="locationedit",
            name="idxdb_le_location",
        ),
        migrations.RemoveIndex(
            model_name="locationedit",
            name="idxdb_le_created",
        ),
        migrations.RemoveConstraint(
            model_name="pin",
            name="db_pin_unique_location_per_profile",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="idxdb_loc_name",
        ),
        migrations.RemoveIndex(
            model_name="pin",
            name="idxdb_pin_parent_loc",
        ),
        migrations.RemoveIndex(
            model_name="pinmarkup",
            name="idxdb_pm_location",
        ),
        migrations.RenameIndex(
            model_name="pinalias",
            new_name="idxdb_palias_pin",
            old_name="idxdb_pin_alias_pin",
        ),
        migrations.AddField(
            model_name="pinalias",
            name="kind",
            field=models.CharField(
                choices=[
                    ("nickname", "Nickname"),
                    ("official", "Official Name"),
                    ("alternate", "Alternate Name"),
                ],
                default="alternate",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pinalias",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User-defined Alias"),
                    ("google_places", "Google Places"),
                    ("wikipedia", "Wikipedia"),
                    ("other", "Other"),
                ],
                default="user",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="pinalias",
            index=models.Index(fields=["pin", "kind"], name="idxdb_palias_pin_kind"),
        ),
        migrations.AddIndex(
            model_name="pinalias",
            index=models.Index(
                fields=["pin", "source"], name="idxdb_palias_pin_source"
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="badges",
            field=models.ManyToManyField(
                blank=True, related_name="wikis", to="dashboard.badge"
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="parent_wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wiki_detail_pins",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="pinmarkup",
            name="parent_wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup_items",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddIndex(
            model_name="pin",
            index=models.Index(fields=["parent_wiki"], name="idxdb_pin_parent_wiki"),
        ),
        migrations.AddIndex(
            model_name="pinmarkup",
            index=models.Index(fields=["parent_wiki"], name="idxdb_pm_wiki"),
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("parent_pin__isnull", True), ("parent_wiki__isnull", True)
                ),
                fields=("latitude", "longitude", "profile"),
                name="db_pin_unique_location_per_profile",
            ),
        ),
        migrations.AddField(
            model_name="wikialias",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_aliases_created",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wikialias",
            name="wiki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="wikiedit",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_edits",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wikiedit",
            name="reverted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reverts",
                to="dashboard.wikiedit",
            ),
        ),
        migrations.AddField(
            model_name="wikiedit",
            name="wiki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edits",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddIndex(
            model_name="wiki",
            index=models.Index(fields=["uuid"], name="idxdb_wiki_uuid"),
        ),
        migrations.AddIndex(
            model_name="wiki",
            index=models.Index(fields=["name"], name="idxdb_wiki_name"),
        ),
        migrations.AddIndex(
            model_name="wiki",
            index=models.Index(fields=["location"], name="idxdb_wiki_location"),
        ),
        migrations.AddIndex(
            model_name="wikialias",
            index=models.Index(fields=["wiki"], name="idxdb_walias_wiki"),
        ),
        migrations.AddIndex(
            model_name="wikialias",
            index=models.Index(fields=["wiki", "kind"], name="idxdb_walias_wiki_kind"),
        ),
        migrations.AddIndex(
            model_name="wikialias",
            index=models.Index(
                fields=["wiki", "source"], name="idxdb_walias_wiki_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikialias",
            constraint=models.UniqueConstraint(
                fields=("wiki", "name"), name="db_walias_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="wikiedit",
            index=models.Index(fields=["wiki"], name="idxdb_we_wiki"),
        ),
        migrations.AddIndex(
            model_name="wikiedit",
            index=models.Index(fields=["wiki", "created"], name="idxdb_we_created"),
        ),
        migrations.RunPython(backfill_wikis, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="comment",
            name="location",
        ),
        migrations.RemoveField(
            model_name="image",
            name="location",
        ),
        migrations.DeleteModel(
            name="LocationAlias",
        ),
        migrations.DeleteModel(
            name="LocationEdit",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="location",
        ),
        migrations.RemoveField(
            model_name="locationedit",
            name="editor",
        ),
        migrations.RemoveField(
            model_name="locationedit",
            name="location",
        ),
        migrations.RemoveField(
            model_name="locationedit",
            name="reverted_by",
        ),
        migrations.RemoveField(
            model_name="location",
            name="alarms",
        ),
        migrations.RemoveField(
            model_name="location",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="location",
            name="cameras",
        ),
        migrations.RemoveField(
            model_name="location",
            name="date_abandoned",
        ),
        migrations.RemoveField(
            model_name="location",
            name="date_last_active",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.RemoveField(
            model_name="location",
            name="fences",
        ),
        migrations.RemoveField(
            model_name="location",
            name="locked",
        ),
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.RemoveField(
            model_name="location",
            name="plywood",
        ),
        migrations.RemoveField(
            model_name="location",
            name="security",
        ),
        migrations.RemoveField(
            model_name="location",
            name="signs",
        ),
        migrations.RemoveField(
            model_name="location",
            name="vps",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="parent_location",
        ),
        migrations.RemoveField(
            model_name="pinmarkup",
            name="parent_location",
        ),
    ]
