# Generated by Django 4.2.8 on 2024-01-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_geocodedlocation_place_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="friendship",
            name="from_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships",
                to="dashboard.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendship",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("Send Message", "Send Message"),
                    ("Invite to Events", "Invite to Events"),
                    ("Share Locations", "Share Locations"),
                    ("View Profile", "View Profile"),
                    ("View Friends", "View Friends"),
                    ("View Trips", "View Trips"),
                ],
                default="View Profile",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("Following", "Following"),
                    ("Friend", "Friend"),
                    ("Close Friend", "Close Friend"),
                ],
                default="Friend",
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("Requested", "Requested"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                    ("Removed", "Removed"),
                    ("Muted", "Muted"),
                    ("Blocked", "Blocked"),
                ],
                default="Accepted",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendship",
            name="to_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friends_to_me",
                to="dashboard.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends_list", to="dashboard.profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="started_exploring",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("from_profile", "to_profile")},
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="friend",
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="user",
        ),
    ]
