# Generated by Django 6.0.6 on 2026-07-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_visitsuggestion_origin_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="instance_uuid",
            new_name="uuid",
        ),
        migrations.RenameIndex(
            model_name="pinvisit",
            new_name="idxdb_pv_pin_vat",
            old_name="idxdb_pv_pin_visited",
        ),
        migrations.AddField(
            model_name="emailverification",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pinvisit",
            name="tentative",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.pin",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_images",
                to="dashboard.profile",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Journal"),
                    ("history", "Imported"),
                    ("trip", "Trip"),
                    ("user", "A Friend's Journal"),
                    ("photo", "Photo"),
                    ("geolocation", "Geolocation"),
                    ("safety_checkin", "Safety Check-in"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="pinvisit",
            index=models.Index(fields=["pin", "tentative"], name="idxdb_pv_pin_tent"),
        ),
        migrations.AddIndex(
            model_name="pinvisit",
            index=models.Index(
                fields=["pin", "visited_at", "tentative"], name="idxdb_pv_pin_vat_tent"
            ),
        ),
    ]
