# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_sitesettings_ai_document_import_max_chars"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="notify_admin_email",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email address that receives critical site notifications (e.g. pin import failures). Defaults to the UL_ADMIN_NOTIFICATION_EMAIL environment variable.",
                max_length=254,
                verbose_name="Admin notification email",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_gotify_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base URL of a Gotify server (e.g. https://gotify.example.com) used to push critical site notifications. Defaults to the UL_GOTIFY_URL environment variable.",
                max_length=500,
                verbose_name="Gotify server URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_gotify_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Gotify application token used to authenticate pushes to the server above. Defaults to the UL_GOTIFY_TOKEN environment variable.",
                max_length=200,
                verbose_name="Gotify app token",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_pin_import_errors_email",
            field=models.BooleanField(
                default=True,
                help_text="Email the admin notification address when a pin import fails to process an uploaded file.",
                verbose_name="Pin import errors (email)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_pin_import_errors_gotify",
            field=models.BooleanField(
                default=False,
                help_text="Send a Gotify push notification when a pin import fails to process an uploaded file.",
                verbose_name="Pin import errors (Gotify)",
            ),
        ),
    ]
