# Generated by Codex on 2026-07-07

from django.contrib.gis.geos import Point
from django.db import migrations, models


def backfill_pin_coordinates(apps, schema_editor):
    Pin = apps.get_model("dashboard", "Pin")
    pins = Pin.objects.select_related("location").only(
        "latitude",
        "longitude",
        "point",
        "location__latitude",
        "location__longitude",
    )
    updated = []
    for pin in pins.iterator():
        latitude = pin.latitude
        longitude = pin.longitude

        if latitude is None and pin.location_id and pin.location.latitude is not None:
            latitude = pin.location.latitude
        if longitude is None and pin.location_id and pin.location.longitude is not None:
            longitude = pin.location.longitude

        if (latitude is None or longitude is None) and pin.point:
            latitude = latitude if latitude is not None else pin.point.y
            longitude = longitude if longitude is not None else pin.point.x

        # Legacy rows without a location or point should not exist for normal pins,
        # but use the historical PointField default so the NOT NULL migration can
        # complete instead of failing mid-deploy.
        latitude = latitude if latitude is not None else 0
        longitude = longitude if longitude is not None else 0

        point = Point(float(longitude), float(latitude), srid=4326)
        if pin.latitude != latitude or pin.longitude != longitude or pin.point != point:
            pin.latitude = latitude
            pin.longitude = longitude
            pin.point = point
            updated.append(pin)

    if updated:
        Pin.objects.bulk_update(updated, ["latitude", "longitude", "point"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_rename_instance_uuid_sitesettings_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_pin_coordinates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pin",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="pin",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
