# Generated by Django 5.1.6 on 2026-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_pin_location_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pin",
            old_name="name",
            new_name="nickname",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="dashboard_l_cid_c72999_idx",
            old_name="dashboard_l_cid_idx",
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
