# Generated by Django 6.0.6 on 2026-07-10 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_undo_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiStatVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("danger", "Danger"),
                            ("vulnerability", "Vulnerability"),
                            ("priority", "Priority"),
                            ("rating", "Rating"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_stat_votes",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "wiki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_votes",
                        to="dashboard.wiki",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_wiki_stat_votes",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["wiki", "field"], name="idxdb_wsv_wiki_field")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wiki", "profile", "field"),
                        name="db_wiki_stat_vote_unique",
                    )
                ],
            },
        ),
    ]
