# Generated by Django 6.0.6 on 2026-07-07 22:00

from django.db import migrations, models
import django.db.models.deletion


def backfill_campus_wiki(apps, schema_editor):
    """Attach default campuses to their community Wiki rows."""
    Campus = apps.get_model("dashboard", "Campus")
    Wiki = apps.get_model("dashboard", "Wiki")

    for campus in Campus.objects.filter(wiki__isnull=True, pin__isnull=True, profile__isnull=True).iterator():
        location_id = campus.location_id
        if not location_id:
            continue
        wiki = Wiki.objects.filter(location_id=location_id).first()
        if wiki is None:
            location = campus.location
            official_name = getattr(location, "official_name", None) if location else None
            wiki = Wiki.objects.create(
                location_id=location_id,
                name=official_name or "Unnamed Location",
            )
        campus.wiki_id = wiki.pk
        campus.save(update_fields=["wiki"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_wiki_wikialias_wikiedit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="dashboard.wiki",
            ),
        ),
        migrations.RunPython(backfill_campus_wiki, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="campus",
            name="campus_unique_location_default",
        ),
        migrations.AddConstraint(
            model_name="campus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pin__isnull", True), ("profile__isnull", True)),
                fields=("wiki",),
                name="campus_unique_wiki_default",
            ),
        ),
    ]
