# Generated by Django 6.0.6 on 2026-07-08 00:28

from decimal import Decimal

from django.contrib.gis.geos import Point
from django.db import migrations, models
import django.db.models.deletion

# Smallest representable step at decimal_places=6 (~0.1 m). Used when nudging
# colliding coordinates apart during backfill.
COORD_STEP = Decimal("0.000001")


def _quantize_coord(value) -> Decimal:
    return Decimal(str(value)).quantize(COORD_STEP)


def _point_for(latitude: Decimal, longitude: Decimal) -> Point:
    return Point(float(longitude), float(latitude), srid=4326)


def _get_or_create_location(location_model, latitude, longitude, *, official_name=None):
    """Return an existing Location at these coords or create one."""
    latitude = _quantize_coord(latitude)
    longitude = _quantize_coord(longitude)
    location = location_model.objects.filter(latitude=latitude, longitude=longitude).first()
    if location is not None:
        return location
    return location_model.objects.create(
        official_name=official_name,
        latitude=latitude,
        longitude=longitude,
        point=_point_for(latitude, longitude),
    )


def _resolve_pin_location_id(pin_model, location_model, pin) -> int:
    """Choose or create the Location a pin must reference before NOT NULL is enforced."""
    if pin.location_id:
        return pin.location_id

    if pin.parent_wiki_id:
        parent_wiki = pin.parent_wiki
        if parent_wiki.location_id:
            return parent_wiki.location_id

    latitude = _quantize_coord(pin.latitude)
    longitude = _quantize_coord(pin.longitude)

    official_name = pin.official_name or None
    if not official_name and not pin.is_private:
        official_name = pin.name or None

    location = _get_or_create_location(
        location_model,
        latitude,
        longitude,
        official_name=official_name,
    )
    return location.pk


def backfill_pin_locations(apps, schema_editor):
    """Ensure every pin has a Location before the FK becomes required."""
    pin_model = apps.get_model("dashboard", "Pin")
    location_model = apps.get_model("dashboard", "Location")

    updated: list[object] = []
    for pin in pin_model.objects.filter(location__isnull=True).select_related("parent_wiki").iterator():
        pin.location_id = _resolve_pin_location_id(pin_model, location_model, pin)
        updated.append(pin)

    if updated:
        pin_model.objects.bulk_update(updated, ["location"], batch_size=500)


def backfill_wiki_locations(apps, schema_editor):
    """Ensure every wiki has a Location before the OneToOne becomes required."""
    Wiki = apps.get_model("dashboard", "Wiki")
    Location = apps.get_model("dashboard", "Location")
    Pin = apps.get_model("dashboard", "Pin")
    Campus = apps.get_model("dashboard", "Campus")

    updated: list[object] = []
    for wiki in Wiki.objects.filter(location__isnull=True).iterator():
        campus = Campus.objects.filter(wiki=wiki, location__isnull=False).order_by("pk").first()
        if campus is not None:
            wiki.location_id = campus.location_id
            updated.append(wiki)
            continue

        pin = Pin.objects.filter(parent_wiki=wiki, location__isnull=False).order_by("pk").first()
        if pin is not None:
            wiki.location_id = pin.location_id
            updated.append(wiki)
            continue

        pin = Pin.objects.filter(wiki=wiki, location__isnull=False).order_by("pk").first()
        if pin is not None:
            wiki.location_id = pin.location_id
            updated.append(wiki)
            continue

        # Orphan wiki with no spatial anchor: create a dedicated Location row.
        # Prefer a non-zero pin coordinate if any child pin exists.
        anchor = Pin.objects.filter(parent_wiki=wiki).order_by("pk").first()
        if anchor is None:
            anchor = Pin.objects.filter(wiki=wiki).order_by("pk").first()
        if anchor is not None:
            latitude = _quantize_coord(anchor.latitude)
            longitude = _quantize_coord(anchor.longitude)
        else:
            latitude = Decimal(0)
            longitude = Decimal(0)

        location = _get_or_create_location(
            Location,
            latitude,
            longitude,
            official_name=wiki.name or "Unnamed Location",
        )
        wiki.location_id = location.pk
        updated.append(wiki)

    if updated:
        Wiki.objects.bulk_update(updated, ["location"], batch_size=500)


def dedupe_wikis_per_location(apps, schema_editor):
    """OneToOne requires at most one wiki per Location."""
    Wiki = apps.get_model("dashboard", "Wiki")
    Location = apps.get_model("dashboard", "Location")

    seen_location_ids: set[int] = set()
    for wiki in Wiki.objects.filter(location__isnull=False).order_by("location_id", "pk").iterator():
        if wiki.location_id in seen_location_ids:
            source = Location.objects.get(pk=wiki.location_id)
            latitude = _quantize_coord(source.latitude)
            longitude = _quantize_coord(source.longitude)
            while Location.objects.filter(latitude=latitude, longitude=longitude).exists():
                longitude += COORD_STEP
            new_location = Location.objects.create(
                official_name=source.official_name or wiki.name,
                latitude=latitude,
                longitude=longitude,
                point=_point_for(latitude, longitude),
            )
            wiki.location_id = new_location.pk
            wiki.save(update_fields=["location"])
        else:
            seen_location_ids.add(wiki.location_id)


def backfill_pin_wiki(apps, schema_editor):
    """Link public pins to their community wiki when one exists for the Location."""
    Pin = apps.get_model("dashboard", "Pin")
    Wiki = apps.get_model("dashboard", "Wiki")

    updated: list[object] = []
    for pin in Pin.objects.filter(wiki__isnull=True, is_private=False, location__isnull=False).iterator():
        wiki = Wiki.objects.filter(location_id=pin.location_id).order_by("pk").first()
        if wiki is None:
            continue
        pin.wiki_id = wiki.pk
        updated.append(pin)

    if updated:
        Pin.objects.bulk_update(updated, ["wiki"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_campus_wiki"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pins",
                to="dashboard.wiki",
            ),
        ),
        migrations.RunPython(backfill_pin_locations, migrations.RunPython.noop),
        migrations.RunPython(backfill_wiki_locations, migrations.RunPython.noop),
        migrations.RunPython(dedupe_wikis_per_location, migrations.RunPython.noop),
        migrations.RunPython(backfill_pin_wiki, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pin",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pins",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="wiki",
                to="dashboard.location",
            ),
        ),
    ]
