# Generated by Django 6.0.6 on 2026-07-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_campus_wiki"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pins",
                to="dashboard.wiki",
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pins",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="wiki",
                to="dashboard.location",
            ),
        ),
    ]
