# Generated by Django 4.2.8 on 2024-01-16 16:37

from urbanlens.UrbanLens.settings.app import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.django.AUTH_USER_MODEL),
        ("dashboard", "0005_remove_profile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.django.AUTH_USER_MODEL,
            ),
        ),
    ]
