# Generated by Django 5.1.6 on 2026-05-22 21:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_rename_name_pin_nickname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("default_radius_meters", models.IntegerField(default=50)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campuses",
                        to="dashboard.location",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campuses",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_campuses",
                "get_latest_by": "updated",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("profile__isnull", False)),
                        fields=("location", "profile"),
                        name="campus_unique_user_location",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("profile__isnull", True)),
                        fields=("location",),
                        name="campus_unique_default_location",
                    ),
                ],
            },
        ),
    ]
