# Generated by Django 6.0.6 on 2026-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_sitesettings_environment_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Requested", "Requested"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                    ("Removed", "Removed"),
                    ("Muted", "Muted"),
                    ("Blocked", "Blocked"),
                    ("Ignored", "Ignored"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="default_map_view",
            field=models.CharField(
                choices=[
                    ("street", "Street"),
                    ("satellite", "Satellite"),
                    ("topographic", "Topographic"),
                    ("remember", "Remember"),
                ],
                default="satellite",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="theme_mode",
            field=models.CharField(
                choices=[
                    ("system", "System (follows your OS)"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="system",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="environment_override",
            field=models.CharField(
                choices=[
                    ("default", "Default (from environment variable)"),
                    ("production", "Production"),
                    ("development", "Development"),
                    ("testing", "Testing"),
                    ("staging", "Staging"),
                ],
                default="default",
                help_text="Override the deployment environment. Default uses the UL_ENVIRONMENT variable (or local when unset).",
                max_length=20,
                verbose_name="Environment",
            ),
        ),
    ]
