# Generated by Django 6.0.6 on 2026-07-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_wiki_stat_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="review",
        ),
    ]
