# Generated by Django 6.0.6

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_sitesettings_notify_admin_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gpx_track", "GPX Track"),
                            ("gpx_route", "GPX Route"),
                            ("google_takeout_semantic", "Google Takeout (Semantic History)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, default="", max_length=255)),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326),
                ),
                ("raw_point_count", models.IntegerField(default=0)),
                ("simplified_point_count", models.IntegerField(default=0)),
                ("distance_meters", models.FloatField(default=0.0)),
                ("elevation_gain_meters", models.FloatField(blank=True, null=True)),
                ("elevation_loss_meters", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_routes",
                "ordering": ["-started_at", "-created"],
                "get_latest_by": "started_at",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["uuid"], name="dash_route_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["profile"], name="dash_route_profile_idx"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["profile", "started_at"], name="dashboard_route_profile_started_idx"
            ),
        ),
    ]
