# Generated by Django 6.0.6 on 2026-07-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_safety_contact_optout_and_plan_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="profileemail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="safetypreference",
            name="default_message",
            field=models.TextField(
                blank=True,
                default="Hi! I'm heading out and set up this automatic check-in as a precaution. If you're seeing this, I haven't checked in by my expected time - please try to reach me, and if you can't, take a look at my trip plan and last known destination below to help figure out where I might be.",
            ),
        ),
    ]
