# Generated by Django 6.0.6 on 2026-07-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_pin_wiki_alter_pin_location_alter_wiki_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pin",
            name="db_pin_unique_location_per_profile",
        ),
        migrations.RemoveIndex(
            model_name="pin",
            name="idxdb_pin_lat_long",
        ),
        migrations.RemoveField(
            model_name="location",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="location",
            name="uuid",
        ),
        migrations.AddIndex(
            model_name="pin",
            index=models.Index(fields=["location"], name="idxdb_pin_location"),
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("parent_pin__isnull", True), ("parent_wiki__isnull", True)
                ),
                fields=("location", "profile"),
                name="db_pin_unique_location_per_profile",
            ),
        ),
        migrations.RemoveField(
            model_name="pin",
            name="administrative_area_level_1",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="administrative_area_level_2",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="administrative_area_level_3",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="country",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="google_place",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="locality",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="official_name",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="point",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="route",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="street_number",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="zipcode",
        ),
        migrations.RemoveField(
            model_name="pin",
            name="zipcode_suffix",
        ),
    ]
