# Generated by Django 6.0.6 on 2026-07-14 15:12

import django.contrib.gis.db.models.fields
import django.contrib.postgres.operations
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import urbanlens.dashboard.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models

from urbanlens.dashboard.models.fields import EncryptedTextField
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
import random

_field = EncryptedTextField()


def _encrypt_column(cursor, table: str, column: str) -> None:
    cursor.execute(f"SELECT id, {column} FROM {table} WHERE {column} IS NOT NULL AND {column} != ''")  # noqa: S608 # nosec B608 - table/column are hardcoded constants below, not user input
    rows = cursor.fetchall()
    for pk, plaintext in rows:
        ciphertext = _field.get_prep_value(plaintext)
        cursor.execute(f"UPDATE {table} SET {column} = %s WHERE id = %s", [ciphertext, pk])  # noqa: S608 # nosec B608 - table/column are hardcoded constants below, not user input


def encrypt_existing_tokens(apps, schema_editor) -> None:
    with schema_editor.connection.cursor() as cursor:
        _encrypt_column(cursor, "dashboard_google_calendar_accounts", "access_token")
        _encrypt_column(cursor, "dashboard_google_calendar_accounts", "refresh_token")
        _encrypt_column(cursor, "dashboard_site_settings", "notify_gotify_token")



def _slugify_base(name: str | None, uuid_value) -> str:
    from django.utils.text import slugify

    return slugify(name) or str(uuid_value)


def backfill_trip_slugs(apps, schema_editor):
    Trip = apps.get_model("dashboard", "Trip")
    for trip in Trip.objects.filter(slug__isnull=True).iterator():
        base = _slugify_base(trip.name, trip.uuid)[:255]
        candidate = base
        while Trip.objects.filter(slug=candidate).exclude(pk=trip.pk).exists():
            suffix = f"-{random.randint(2, 90_000)}"  # noqa: S311 # nosec: B311 - not for cryptographic use
            candidate = base[: 255 - len(suffix)] + suffix
        Trip.objects.filter(pk=trip.pk).update(slug=candidate)


def noop(apps, schema_editor):
    pass

import django.db.models.deletion
from django.db import migrations, models


def rename_permissions(apps, schema_editor):
    """Rename auth_permission codenames/names in place so existing Group/User grants survive.

    Django's post_migrate `create_permissions` hook only ever creates permissions for
    codenames declared on the current model state - it does not delete or rename ones
    left behind by a renamed model, so without this the old `*_badge*` permission rows
    would linger as orphans instead of becoming the new `*_label*` ones.
    """
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # (old content-type model name before this migration's RenameModel ops ran / after,
    # since ContentType.model is auto-updated by Django's RenameModel contenttypes hook)
    renames = [
        ("label", "add_badge", "add_label", "Can add label"),
        ("label", "change_badge", "change_label", "Can change label"),
        ("label", "delete_badge", "delete_label", "Can delete label"),
        ("label", "view_badge", "view_label", "Can view label"),
        ("label", "edit_global_badge", "edit_global_label", "Can edit global labels"),
        ("labelcustomization", "add_badgecustomization", "add_labelcustomization", "Can add label customization"),
        ("labelcustomization", "change_badgecustomization", "change_labelcustomization", "Can change label customization"),
        ("labelcustomization", "delete_badgecustomization", "delete_labelcustomization", "Can delete label customization"),
        ("labelcustomization", "view_badgecustomization", "view_labelcustomization", "Can view label customization"),
        ("profilelabelassignment", "add_profilebadgeassignment", "add_profilelabelassignment", "Can add profile label assignment"),
        ("profilelabelassignment", "change_profilebadgeassignment", "change_profilelabelassignment", "Can change profile label assignment"),
        ("profilelabelassignment", "delete_profilebadgeassignment", "delete_profilelabelassignment", "Can delete profile label assignment"),
        ("profilelabelassignment", "view_profilebadgeassignment", "view_profilelabelassignment", "Can view profile label assignment"),
    ]
    for model_name, old_codename, new_codename, new_name in renames:
        try:
            content_type = ContentType.objects.get(app_label="dashboard", model=model_name)
        except ContentType.DoesNotExist:
            continue
        Permission.objects.filter(content_type=content_type, codename=old_codename).update(codename=new_codename, name=new_name)


def rename_permissions_reverse(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    renames = [
        ("badge", "add_label", "add_badge", "Can add badge"),
        ("badge", "change_label", "change_badge", "Can change badge"),
        ("badge", "delete_label", "delete_badge", "Can delete badge"),
        ("badge", "view_label", "view_badge", "Can view badge"),
        ("badge", "edit_global_label", "edit_global_badge", "Can edit global badges"),
        ("badgecustomization", "add_labelcustomization", "add_badgecustomization", "Can add badge customization"),
        ("badgecustomization", "change_labelcustomization", "change_badgecustomization", "Can change badge customization"),
        ("badgecustomization", "delete_labelcustomization", "delete_badgecustomization", "Can delete badge customization"),
        ("badgecustomization", "view_labelcustomization", "view_badgecustomization", "Can view badge customization"),
        ("profilebadgeassignment", "add_profilelabelassignment", "add_profilebadgeassignment", "Can add profile badge assignment"),
        ("profilebadgeassignment", "change_profilelabelassignment", "change_profilebadgeassignment", "Can change profile badge assignment"),
        ("profilebadgeassignment", "delete_profilelabelassignment", "delete_profilebadgeassignment", "Can delete profile badge assignment"),
        ("profilebadgeassignment", "view_profilelabelassignment", "view_profilebadgeassignment", "Can view profile badge assignment"),
    ]
    for model_name, old_codename, new_codename, new_name in renames:
        try:
            content_type = ContentType.objects.get(app_label="dashboard", model=model_name)
        except ContentType.DoesNotExist:
            continue
        Permission.objects.filter(content_type=content_type, codename=old_codename).update(codename=new_codename, name=new_name)


def disable_auto_tagging(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Turn off auto-tagging for all existing profiles now that it defaults to opt-in."""
    Profile = apps.get_model("dashboard", "Profile")
    Profile.objects.update(ai_label_categories=False, ai_label_tags=False, ai_label_statuses=False)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_v0_4_0_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pinshare',
            name='bundled_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundled_shares', to='dashboard.pinshare'),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(choices=[('pin', 'Pins'), ('photo', 'Photos'), ('profile', 'People'), ('markup_map', 'Maps')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_custom_fields',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dashboard.customfield')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='dashboard.image')),
                ('markup_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='dashboard.markupmap')),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='dashboard.pin')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values_about', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_custom_field_values',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['profile', 'entity_type'], name='idxdb_cf_profile_entity'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('profile', 'entity_type', 'name'), name='db_cf_unique_name'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['field', 'value_number'], name='idxdb_cfv_field_number'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['field', 'value_date'], name='idxdb_cfv_field_date'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('pin__isnull', False)), fields=('field', 'pin'), name='db_cfv_unique_pin'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('image__isnull', False)), fields=('field', 'image'), name='db_cfv_unique_image'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('target_profile__isnull', False)), fields=('field', 'target_profile'), name='db_cfv_unique_profile'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('markup_map__isnull', False)), fields=('field', 'markup_map'), name='db_cfv_unique_map'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', True), ('markup_map__isnull', True), ('pin__isnull', False), ('target_profile__isnull', True)), models.Q(('image__isnull', False), ('markup_map__isnull', True), ('pin__isnull', True), ('target_profile__isnull', True)), models.Q(('image__isnull', True), ('markup_map__isnull', True), ('pin__isnull', True), ('target_profile__isnull', False)), models.Q(('image__isnull', True), ('markup_map__isnull', False), ('pin__isnull', True), ('target_profile__isnull', True)), _connector='OR'), name='db_cfv_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direct_message_visibility',
            field=models.CharField(choices=[('anyone', 'Anyone (Logged In)'), ('anything_in_common', 'Users with anything in common'), ('common_pin', 'Users with a pin in common'), ('common_friend', 'Users with a friend in common'), ('common_trip', 'Users with a trip in common'), ('friends', 'Friends Only'), ('no_one', 'No one')], default='anything_in_common', help_text='Who can send you direct messages.', max_length=20),
        ),
        migrations.CreateModel(
            name='DirectMessageImagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'dashboard_dm_image_permissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectMessageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pin', 'Pin'), ('trip', 'Trip'), ('friend', 'Friend recommendation')], max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_direct_message_shares',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectMessageTemporaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dashboard_dm_temporary_access',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=5000)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to='dashboard.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to='dashboard.profile')),
                ('deleted_by_recipient_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_sender_at', models.DateTimeField(blank=True, null=True)),
                ('images_revealed', models.BooleanField(default=False)),
                ('markup_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_messages', to='dashboard.markupmap')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='dashboard.directmessage')),
                ('sender_delete_after', models.CharField(choices=[('never', 'Never'), ('when_read', "As soon as they're read"), ('one_day', '1 day after being read'), ('thirty_days', '30 days after being read'), ('ninety_days', '90 days after being read'), ('one_year', '1 year after being read')], default='never', max_length=20)),
            ],
            options={
                'db_table': 'dashboard_direct_messages',
                'ordering': ['created'],
                'get_latest_by': 'created',
                'abstract': False,
                'indexes': [models.Index(fields=['sender', 'recipient'], name='idxdb_dm_sender_recipient'), models.Index(fields=['recipient', 'read_at'], name='idxdb_dm_recipient_read')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('recipient')), _negated=True), name='db_dm_no_self_message')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='direct_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='dashboard.directmessage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_friend_recommendations',
            field=models.BooleanField(default=True, help_text="Let other users recommend you as a friend to people they're messaging."),
        ),
        migrations.AddField(
            model_name='profile',
            name='direct_message_delete_after',
            field=models.CharField(choices=[('never', 'Never'), ('when_read', "As soon as they're read"), ('one_day', '1 day after being read'), ('thirty_days', '30 days after being read'), ('ninety_days', '90 days after being read'), ('one_year', '1 year after being read')], default='never', help_text="Messages you send disappear from the recipient's view this long after they've read them. You can always see your own messages.", max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='online_status_visibility',
            field=models.CharField(choices=[('anyone', 'Anyone (Logged In)'), ('anything_in_common', 'Users with anything in common'), ('common_pin', 'Users with a pin in common'), ('common_friend', 'Users with a friend in common'), ('common_trip', 'Users with a trip in common'), ('friends', 'Friends Only'), ('no_one', 'No one')], default='friends', help_text="Who can see when you're online in direct messages.", max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_receipt_visibility',
            field=models.CharField(choices=[('anyone', 'Anyone (Logged In)'), ('anything_in_common', 'Users with anything in common'), ('common_pin', 'Users with a pin in common'), ('common_friend', 'Users with a friend in common'), ('common_trip', 'Users with a trip in common'), ('friends', 'Friends Only'), ('no_one', 'No one')], default='friends', help_text="Who can see that you've read their direct messages.", max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='typing_indicator_visibility',
            field=models.CharField(choices=[('anyone', 'Anyone (Logged In)'), ('anything_in_common', 'Users with anything in common'), ('common_pin', 'Users with a pin in common'), ('common_friend', 'Users with a friend in common'), ('common_trip', 'Users with a trip in common'), ('friends', 'Friends Only'), ('no_one', 'No one')], default='friends', help_text="Who can see when you're typing a direct message reply.", max_length=20),
        ),
        migrations.AddField(
            model_name='reaction',
            name='direct_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='dashboard.directmessage'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['direct_message'], name='idxdb_react_dm'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('direct_message__isnull', False)), fields=('profile', 'emoji', 'direct_message'), name='unique_reaction_direct_message'),
        ),
        migrations.AddField(
            model_name='directmessageimagepermission',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='directmessageimagepermission',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='directmessageshare',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='dashboard.directmessage'),
        ),
        migrations.AddField(
            model_name='directmessageshare',
            name='pin_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_message_share', to='dashboard.pinshare'),
        ),
        migrations.AddField(
            model_name='directmessageshare',
            name='recommended_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='directmessageshare',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_message_shares', to='dashboard.trip'),
        ),
        migrations.AddField(
            model_name='directmessageshare',
            name='trip_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_message_share', to='dashboard.tripmembership'),
        ),
        migrations.AddField(
            model_name='directmessagetemporaryaccess',
            name='granted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_access_received', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='directmessagetemporaryaccess',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_access_grants', to='dashboard.profile'),
        ),
        migrations.AddConstraint(
            model_name='directmessageimagepermission',
            constraint=models.UniqueConstraint(fields=('viewer', 'sender'), name='db_dm_image_perm_unique'),
        ),
        migrations.AlterField(
            model_name='pinmarkup',
            name='markup_type',
            field=models.CharField(choices=[('line', 'Line'), ('arrow', 'Arrow'), ('text', 'Text'), ('square', 'Square'), ('circle', 'Circle'), ('polygon', 'Polygon'), ('pin', 'Pin')], max_length=20),
        ),
        migrations.CreateModel(
            name='AccountKdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_salt', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'dashboard_account_kdf',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wrapped_for_low', models.TextField()),
                ('wrapped_for_high', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'dashboard_e2ee_conversation_key',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessagingKeyBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public_key', models.CharField(max_length=128)),
                ('password_wrapped_secret', models.TextField(blank=True, default='')),
                ('password_wrap_salt', models.CharField(blank=True, default='', max_length=64)),
                ('password_wrap_stale', models.BooleanField(default=False)),
                ('recovery_wrapped_secret', models.TextField()),
                ('kdf_opslimit', models.IntegerField(default=2)),
                ('kdf_memlimit', models.IntegerField(default=67108864)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'dashboard_e2ee_key_bundle',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='directmessage',
            name='ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='key_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='body',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddConstraint(
            model_name='directmessage',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), ('ciphertext', ''), _connector='OR'), name='db_dm_body_xor_ciphertext'),
        ),
        migrations.AddField(
            model_name='accountkdf',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_kdf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationkey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_keys_created', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='conversationkey',
            name='profile_high',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_keys_high', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='conversationkey',
            name='profile_low',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_keys_low', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='messagingkeybundle',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_key_bundle', to='dashboard.profile'),
        ),
        migrations.AddIndex(
            model_name='conversationkey',
            index=models.Index(fields=['profile_low', 'profile_high'], name='idxdb_e2ee_convkey_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversationkey',
            constraint=models.UniqueConstraint(fields=('profile_low', 'profile_high', 'version'), name='db_e2ee_convkey_pair_version'),
        ),
        migrations.AddConstraint(
            model_name='conversationkey',
            constraint=models.CheckConstraint(condition=models.Q(('profile_low__lt', models.F('profile_high'))), name='db_e2ee_convkey_canonical_order'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='added_to_trip_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='added_to_trip_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='comment_liked_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='comment_liked_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='comment_reply_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='comment_reply_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='friend_accepted_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='friend_accepted_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='friend_request_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='friend_request_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='message_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='message_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='pin_shared_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='pin_shared_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='trip_updated_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='trip_updated_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='visit_suggested_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='visit_suggested_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='wiki_safety_checkin_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='wiki_safety_checkin_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='wiki_updated_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='wiki_updated_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripmembership',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined')], default='joined', max_length=20),
        ),
        migrations.CreateModel(
            name='PinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=10000)),
                ('is_smart', models.BooleanField(default=False)),
                ('smart_filter', models.JSONField(blank=True, null=True)),
                ('smart_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('markup_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_list', to='dashboard.markupmap')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_lists', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_pin_lists',
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PinListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('added_via', models.CharField(choices=[('manual', 'Manually added'), ('smart_filter', 'Smart filter match'), ('boundary', 'Inside boundary')], default='manual', max_length=20)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='dashboard.pin')),
                ('pin_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.pinlist')),
            ],
            options={
                'db_table': 'dashboard_pin_list_items',
                'ordering': ['order', 'created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_saved_filters',
                'ordering': ['order', '-created'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='pinlist',
            index=models.Index(fields=['profile'], name='idxdb_pinlist_profile'),
        ),
        migrations.AddConstraint(
            model_name='pinlist',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='uq_pin_list_profile_name'),
        ),
        migrations.AddIndex(
            model_name='pinlistitem',
            index=models.Index(fields=['pin_list'], name='idxdb_pli_list'),
        ),
        migrations.AddIndex(
            model_name='pinlistitem',
            index=models.Index(fields=['pin'], name='idxdb_pli_pin'),
        ),
        migrations.AddConstraint(
            model_name='pinlistitem',
            constraint=models.UniqueConstraint(fields=('pin_list', 'pin'), name='uq_pin_list_item'),
        ),
        migrations.AddIndex(
            model_name='savedfilter',
            index=models.Index(fields=['profile'], name='idxdb_savedfilter_profile'),
        ),
        migrations.AddConstraint(
            model_name='savedfilter',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='uq_saved_filter_profile_name'),
        ),
        migrations.CreateModel(
            name='ImmichAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('server_url', models.URLField(help_text="Base URL of the user's Immich server, e.g. https://photos.example.com", max_length=500)),
                ('api_key', urbanlens.dashboard.models.fields.EncryptedTextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, help_text='When the credentials were last confirmed to work.', null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immich_account', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_immich_accounts',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='googlecalendaraccount',
            name='access_token',
            field=urbanlens.dashboard.models.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='googlecalendaraccount',
            name='refresh_token',
            field=urbanlens.dashboard.models.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_gotify_token',
            field=urbanlens.dashboard.models.fields.EncryptedTextField(blank=True, default='', help_text='Gotify application token used to authenticate pushes to the server above. Defaults to the UL_GOTIFY_TOKEN environment variable.', verbose_name='Gotify app token'),
        ),
        migrations.RunPython(
            code=encrypt_existing_tokens,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='FlickrAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('oauth_token', urbanlens.dashboard.models.fields.EncryptedTextField()),
                ('oauth_token_secret', urbanlens.dashboard.models.fields.EncryptedTextField()),
                ('flickr_user_id', models.CharField(help_text='Flickr NSID (user id) of the connected account.', max_length=64)),
                ('flickr_username', models.CharField(blank=True, help_text='Flickr username, for display only.', max_length=255, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flickr_account', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_flickr_accounts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GooglePhotosAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('google_email', models.CharField(blank=True, help_text='Email of the connected Google account, for display only.', max_length=255, null=True)),
                ('access_token', urbanlens.dashboard.models.fields.EncryptedTextField()),
                ('refresh_token', urbanlens.dashboard.models.fields.EncryptedTextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_photos_account', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_google_photos_accounts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarkupMapShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
            ],
            options={
                'db_table': 'dashboard_markup_map_shares',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='markupmap',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='dashboard.markupmap'),
        ),
        migrations.AddField(
            model_name='markupmap',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='pin',
            name='inferred_source_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins_inferred', to='dashboard.pinshare'),
        ),
        migrations.AddField(
            model_name='pinshare',
            name='detected_via_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_pin_shares', to='dashboard.markupmap'),
        ),
        migrations.AddField(
            model_name='pinshare',
            name='markup_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_share_attachments', to='dashboard.markupmap'),
        ),
        migrations.AddField(
            model_name='pinshare',
            name='origin',
            field=models.CharField(choices=[('explicit', 'Explicit Share'), ('map_detected', 'Detected From Shared Map')], default='explicit', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('trip_updated', 'Trip Updated'), ('friend_request', 'New Friend Request'), ('message', 'New Message'), ('comment_reply', 'Reply to Comment'), ('comment_liked', 'Comment Likes'), ('friend_accepted', 'Friend Request Accepted'), ('added_to_trip', 'Trip Invitation'), ('wiki_updated', 'Community Wiki Updated'), ('pin_shared', 'Pin Shared'), ('map_shared', 'Map Shared'), ('visit_suggested', 'Visit Suggested'), ('safety_ci_due', 'Safety Check-in Due'), ('safety_ci_final_warning', 'Safety Check-in Final Warning'), ('safety_ci_overdue', 'Safety Check-in Overdue'), ('safety_ci_resolved', 'Safety Check-in Resolved'), ('safety_ci_plan_updated', 'Safety Check-in Plan Updated'), ('wiki_safety_checkin', 'Community Wiki Safety Check-in'), ('account_deletion_requested', 'Account Deletion Requested'), ('account_deletion_reminder', 'Account Deletion Reminder'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=30),
        ),
        migrations.AlterField(
            model_name='pinshare',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('already_pinned', 'Already pinned'), ('detected', 'Detected From Shared Map')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='markupmap',
            index=models.Index(fields=['profile', 'cloned_from'], name='idxdb_mm_profile_clonedfrom'),
        ),
        migrations.AddConstraint(
            model_name='pinshare',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'map_detected')), fields=('pin', 'to_profile'), name='db_pinshare_one_detected_per_pin_user'),
        ),
        migrations.AddField(
            model_name='markupmapshare',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_map_shares', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='markupmapshare',
            name='markup_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='dashboard.markupmap'),
        ),
        migrations.AddField(
            model_name='markupmapshare',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_share', to='dashboard.notificationlog'),
        ),
        migrations.AddField(
            model_name='markupmapshare',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_map_shares', to='dashboard.profile'),
        ),
        migrations.AddIndex(
            model_name='markupmapshare',
            index=models.Index(fields=['to_profile'], name='idxdb_mms_to_profile'),
        ),
        migrations.AddIndex(
            model_name='markupmapshare',
            index=models.Index(fields=['markup_map'], name='idxdb_mms_markup_map'),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('yelp', 'Yelp'), ('google_images', 'Google Images'), ('google_maps', 'Google Maps'), ('wikimedia', 'Wikimedia Commons'), ('smithsonian', 'Smithsonian Open Access'), ('library_of_congress', 'Library of Congress'), ('immich', 'Immich'), ('flickr', 'Flickr'), ('google_photos', 'Google Photos')], default='upload', max_length=30),
        ),
        migrations.AddField(
            model_name='pin',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_covers', to='dashboard.image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='media_gallery_sort',
            field=models.CharField(choices=[('relevant', 'Relevant first'), ('recent', 'Most recent')], default='relevant', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_wiki_cover_photos',
            field=models.BooleanField(default=True, help_text='Show the community-selected cover photo banner on wiki pages.'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_covers', to='dashboard.image'),
        ),
        migrations.CreateModel(
            name='MediaRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=30)),
                ('item_key', models.CharField(max_length=40)),
                ('is_relevant', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_relevance_marks', to='dashboard.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_relevance_marks', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_media_relevance',
                'abstract': False,
                'indexes': [models.Index(fields=['profile', 'location'], name='idxdb_medrel_profile_loc')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'location', 'source', 'item_key'), name='db_media_relevance_unique')],
            },
        ),
        django.contrib.postgres.operations.TrigramExtension(
        ),
        migrations.AddField(
            model_name='profile',
            name='generate_photo_keywords',
            field=models.BooleanField(default=True, help_text='Automatically generate searchable keywords for photos you upload.'),
        ),
        migrations.CreateModel(
            name='ImageKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='dashboard.image')),
            ],
            options={
                'db_table': 'dashboard_image_keywords',
                'abstract': False,
                'indexes': [models.Index(fields=['source'], name='idx_image_keyword_source')],
                'constraints': [models.UniqueConstraint(fields=('image', 'source', 'keyword'), name='uniq_image_keyword_per_source')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255)),
                ('last_used', models.DateTimeField(auto_now=True, db_index=True)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='dashboard.profile')),
            ],
            options={
                'verbose_name_plural': 'search histories',
                'db_table': 'dashboard_search_history',
                'ordering': ['-last_used'],
                'abstract': False,
                'indexes': [models.Index(fields=['profile', '-last_used'], name='idx_search_history_recent')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'query'), name='uniq_search_history_profile_query')],
            },
        ),
        migrations.CreateModel(
            name='PinSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin', models.CharField(choices=[('immich', 'Immich library scan'), ('local_scan', 'Local folder scan')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('visit_dates', models.JSONField(default=list)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('suggested_name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_suggestions', to='dashboard.location')),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_suggestions', to='dashboard.pin')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_suggestions', to='dashboard.profile')),
                ('sample_assets', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'dashboard_pin_suggestions',
                'abstract': False,
                'indexes': [models.Index(fields=['profile', 'status'], name='idxdb_pin_sugg_status')],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_features',
            field=models.CharField(blank=True, help_text='Comma-separated SiteFeature values granted to every user, including those with no active subscription.', max_length=500, verbose_name='Default features (everyone)'),
        ),
        migrations.AddField(
            model_name='tripcalendarlink',
            name='auto_sync',
            field=models.BooleanField(default=False, help_text='Push future changes to this trip and its activities to the linked calendar event automatically. One-way only - edits made on Google Calendar are never pulled back.'),
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, editable=False, max_length=64)),
                ('device_type', models.CharField(blank=True, editable=False, max_length=16)),
                ('backup_eligible', models.BooleanField(default=False, editable=False)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_webauthn_credential',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_backup_code',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('secret', urbanlens.dashboard.models.fields.EncryptedTextField()),
                ('last_used_step', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_totp_device',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='pin_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_images', to='dashboard.pinsuggestion'),
        ),
        migrations.CreateModel(
            name='ProfileNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(help_text='Private nickname the author uses to refer to the subject.', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_nicknames', to='dashboard.profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nicknames', to='dashboard.profile')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('author', 'subject'), name='unique_profile_nickname')],
            },
        ),
        migrations.AddField(
            model_name='tripmembership',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, help_text="When this member last opened the trip detail page. Powers the 'recently viewed' list on the trips overview page.", null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            code=backfill_trip_slugs,
            reverse_code=noop,
        ),
        migrations.AddField(
            model_name='markupmap',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_maps', to='dashboard.pin'),
        ),
        migrations.AddIndex(
            model_name='markupmap',
            index=models.Index(fields=['pin'], name='idxdb_mm_pin'),
        ),
        migrations.AddField(
            model_name='markupmap',
            name='inferred_pins',
            field=models.ManyToManyField(blank=True, related_name='inferred_maps', to='dashboard.pin'),
        ),
        migrations.RenameModel(
            old_name='Badge',
            new_name='Label',
        ),
        migrations.AlterModelTable(
            name='label',
            table='dashboard_labels',
        ),
        migrations.RenameIndex(
            model_name='label',
            new_name='idxdb_label_uuid',
            old_name='idxdb_badge_uuid',
        ),
        migrations.RenameIndex(
            model_name='label',
            new_name='idxdb_label_profile',
            old_name='idxdb_badge_profile',
        ),
        migrations.RenameIndex(
            model_name='label',
            new_name='idxdb_label_pfile_ord',
            old_name='idxdb_badge_pfile_ord',
        ),
        migrations.AlterField(
            model_name='label',
            name='custom_icon',
            field=models.ImageField(blank=True, null=True, upload_to='label_icons/'),
        ),
        migrations.AlterField(
            model_name='label',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_labels', to='dashboard.profile'),
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'get_latest_by': 'updated', 'ordering': ['-order', 'name'], 'permissions': [('edit_global_label', 'Can edit global labels')]},
        ),
        migrations.RenameModel(
            old_name='BadgeCustomization',
            new_name='LabelCustomization',
        ),
        migrations.AlterModelTable(
            name='labelcustomization',
            table='dashboard_label_customizations',
        ),
        migrations.RenameField(
            model_name='labelcustomization',
            old_name='badge',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='labelcustomization',
            name='label',
            field=models.ForeignKey(db_column='label_id', on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='dashboard.label'),
        ),
        migrations.AlterField(
            model_name='labelcustomization',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_customizations', to='dashboard.profile'),
        ),
        migrations.RemoveConstraint(
            model_name='labelcustomization',
            name='unique_tag_customization_per_profile',
        ),
        migrations.AddConstraint(
            model_name='labelcustomization',
            constraint=models.UniqueConstraint(fields=('profile', 'label'), name='unique_label_customization_per_profile'),
        ),
        migrations.RenameModel(
            old_name='ProfileBadgeAssignment',
            new_name='ProfileLabelAssignment',
        ),
        migrations.AlterModelTable(
            name='profilelabelassignment',
            table='dashboard_profile_label_assignments',
        ),
        migrations.RenameField(
            model_name='profilelabelassignment',
            old_name='badge',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='profilelabelassignment',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='dashboard.label'),
        ),
        migrations.AlterField(
            model_name='profilelabelassignment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_label_assignments', to='dashboard.profile'),
        ),
        migrations.AlterField(
            model_name='profilelabelassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_profile_label_assignments', to='dashboard.profile'),
        ),
        migrations.RemoveConstraint(
            model_name='profilelabelassignment',
            name='unique_profile_badge_assignment',
        ),
        migrations.AddConstraint(
            model_name='profilelabelassignment',
            constraint=models.UniqueConstraint(fields=('author', 'subject', 'label'), name='unique_profile_label_assignment'),
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='badges',
            new_name='labels',
        ),
        migrations.AlterField(
            model_name='pin',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='pins', to='dashboard.label'),
        ),
        migrations.RenameField(
            model_name='wiki',
            old_name='badges',
            new_name='labels',
        ),
        migrations.AlterField(
            model_name='wiki',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='wikis', to='dashboard.label'),
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ai_badge_tags',
            new_name='ai_label_tags',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ai_badge_categories',
            new_name='ai_label_categories',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ai_badge_statuses',
            new_name='ai_label_statuses',
        ),
        migrations.RunPython(
            code=rename_permissions,
            reverse_code=rename_permissions_reverse,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_name_source_priority',
            field=models.CharField(blank=True, default='nominatim,wikipedia,nps,google_places', help_text="Comma-separated name-provider slugs, highest priority first, used to pick a location's official name from external candidates. Sources not listed rank last, in plugin order. Blank = plugin order only.", max_length=500, verbose_name='Name source priority'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ai_label_categories',
            field=models.BooleanField(default=False, help_text='AI can automatically suggest and add categories when a pin is created.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ai_label_statuses',
            field=models.BooleanField(default=False, help_text='AI can automatically suggest and add statuses when a pin is created.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ai_label_tags',
            field=models.BooleanField(default=False, help_text='AI can automatically suggest and add tags when a pin is created.'),
        ),
        migrations.RunPython(
            code=disable_auto_tagging,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='comment',
            name='map_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='map_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripcomment',
            name='map_removed',
            field=models.BooleanField(default=False),
        ),
    ]
