# Generated by Django 4.2.8 on 2024-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_review_location_alter_review_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"get_latest_by": "created"},
        ),
        migrations.AlterField(
            model_name="geocodedlocation",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="geocodedlocation",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
