# Generated by Django 6.0.6 on 2026-07-10 17:56

from django.db import migrations, models


def backfill_existing_accounts(apps, schema_editor):
    """Treat pre-existing accounts as having implicitly accepted, as of profile creation.

    Only rows that have already been through (or bypassed) /welcome/ - i.e.
    welcome_onboarding_complete=True - are backfilled. Anyone still pending that page
    gets tos_accepted_at set for real when they submit the form.
    """
    profile = apps.get_model("dashboard", "Profile")
    profile.objects.filter(welcome_onboarding_complete=True, tos_accepted_at__isnull=True).update(tos_accepted_at=models.F("created"))


def backwards(apps, schema_editor):
    """No-op: the field itself is removed by the reverse of AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_markupmap_canonical_layer_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tos_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_existing_accounts, backwards),
    ]
