# Generated by Django 6.0.6 on 2026-07-21 15:15

import random
import uuid

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models.functions.text

import urbanlens.dashboard.models.account.model

# The following functions are manually ported from the migrations named
# below (squashmigrations can't auto-import a module whose name starts
# with a digit), each verbatim from its original migration file.


def _slugify_base(name):
    # From 0050_pin_list_slug.
    from django.utils.text import slugify

    return slugify(name) or "list"


def _0050_backfill_pin_list_slugs(apps, schema_editor):
    # From 0050_pin_list_slug.backfill_pin_list_slugs.
    PinList = apps.get_model("dashboard", "PinList")
    for pin_list in PinList.objects.filter(slug__isnull=True).iterator():
        base = _slugify_base(pin_list.name)[:255]
        candidate = base
        while PinList.objects.filter(profile_id=pin_list.profile_id, slug=candidate).exclude(pk=pin_list.pk).exists():
            suffix = f"-{random.randint(2, 90_000)}"  # noqa: S311 # nosec: B311 - not for cryptographic use
            candidate = base[: 255 - len(suffix)] + suffix
        PinList.objects.filter(pk=pin_list.pk).update(slug=candidate)


def _0056_backfill_share_locations_and_exposures(apps, schema_editor):
    # From 0056_backfill_share_locations_and_exposures.backfill.
    PinShare = apps.get_model("dashboard", "PinShare")
    LocationExposure = apps.get_model("dashboard", "LocationExposure")
    Pin = apps.get_model("dashboard", "Pin")

    for share in PinShare.objects.filter(location__isnull=True, pin__isnull=False).select_related("pin"):
        PinShare.objects.filter(pk=share.pk, location__isnull=True).update(location_id=share.pin.location_id)

    for share in PinShare.objects.filter(location__isnull=False).select_related("location"):
        prior_own_pin = Pin.objects.filter(
            profile_id=share.to_profile_id,
            parent_pin__isnull=True,
            location_id=share.location_id,
            created__lt=share.created,
            source_share__isnull=True,
        ).exists()
        if prior_own_pin:
            continue
        LocationExposure.objects.get_or_create(
            profile_id=share.to_profile_id,
            location_id=share.location_id,
            share_id=share.pk,
            defaults={"source": "share_received"},
        )


def _0082_invalidate_wikipedia_cache_for_article_seeding(apps, schema_editor):
    # From 0082_invalidate_wikipedia_cache_for_article_seeding.invalidate.
    LocationCache = apps.get_model("dashboard", "LocationCache")
    LocationCache.objects.filter(source="wikipedia").delete()


def _0086_invalidate_wikipedia_cache_for_pin_article_seeding(apps, schema_editor):
    # From 0086_invalidate_wikipedia_cache_for_pin_article_seeding.invalidate.
    LocationCache = apps.get_model("dashboard", "LocationCache")
    LocationCache.objects.filter(source="wikipedia").delete()


def _0087_seed_global_demolished_label(apps, schema_editor):
    # From 0087_seed_global_demolished_label.seed_global_demolished_label.
    Label = apps.get_model("dashboard", "Label")
    Label.objects.get_or_create(
        profile=None,
        name="Demolished",
        kind="status",
        defaults={
            "icon": "\U0001f480",
            "color": "#795548",
            "order": 60,
            "is_protected": True,
        },
    )


def _0087_remove_global_demolished_label(apps, schema_editor):
    # From 0087_seed_global_demolished_label.remove_global_demolished_label.
    Label = apps.get_model("dashboard", "Label")
    Label.objects.filter(profile=None, name="Demolished", kind="status").delete()


def _0088_cap_existing_value(apps, schema_editor):
    # From 0088_cap_max_upload_file_size_at_clamd_stream_max_length.cap_existing_value.
    SiteSettings = apps.get_model("dashboard", "SiteSettings")
    SiteSettings.objects.filter(max_upload_file_size_mb__gt=900).update(max_upload_file_size_mb=900)


def _0089_invalidate_wikipedia_cache(apps, schema_editor):
    # From 0089_invalidate_wikipedia_cache_for_infobox_seeding.invalidate_wikipedia_cache.
    LocationCache = apps.get_model("dashboard", "LocationCache")
    LocationCache.objects.filter(source="wikipedia").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_pinshare_bundled_with_markup_map_removed_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="images", to="dashboard.label"),
        ),
        migrations.AlterField(
            model_name="label",
            name="kind",
            field=models.CharField(choices=[("tag", "Tag"), ("category", "Category"), ("status", "Status"), ("user", "Person"), ("media", "Media")], db_index=True, default="tag", max_length=20),
        ),
        migrations.AddField(
            model_name="image",
            name="media_type",
            field=models.CharField(choices=[("photo", "Photo"), ("video", "Video"), ("document", "Document")], db_index=True, default="photo", max_length=10),
        ),
        migrations.AddField(
            model_name="image",
            name="ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="video_downscale_max_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_upload_file_size_mb",
            field=models.IntegerField(
                default=250,
                help_text="Maximum size (MB) for a single photo, video, or document upload. Enforced on both the frontend and backend.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)],
                verbose_name="Max upload file size (MB)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="video_downscale_enabled",
            field=models.BooleanField(default=True, help_text="Downscale uploaded videos that exceed the maximum height below, to save storage space.", verbose_name="Downscale uploaded videos"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="video_downscale_max_height",
            field=models.IntegerField(
                default=1080,
                help_text="Vertical resolution (px) uploaded videos are downscaled to when downscaling is enabled.",
                validators=[django.core.validators.MinValueValidator(240), django.core.validators.MaxValueValidator(8000)],
                verbose_name="Max video height (px)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="video_downscale_vip",
            field=models.BooleanField(
                default=False,
                help_text="Also downscale video uploads from users with an active subscription. When off, subscribers keep their original video resolution (unless they opt into downscaling themselves).",
                verbose_name="Downscale subscriber videos",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("max_upload_file_size_mb__gte", 1)), name="max_upload_file_size_mb_gte_1"),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("video_downscale_max_height__gte", 240)), name="video_downscale_max_height_gte_240"),
        ),
        migrations.AddField(
            model_name="profile",
            name="name_source_priority",
            field=models.CharField(blank=True, default="", help_text="Comma-separated name-provider slugs, highest priority first. Blank uses the site-wide default.", max_length=500),
        ),
        migrations.AddField(
            model_name="savedfilter",
            name="icon",
            field=models.CharField(blank=True, default="bookmark", max_length=64),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="body",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="markupmapshare",
            name="message",
            field=models.TextField(blank=True, max_length=5000, null=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name="pin",
            name="description",
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AlterField(
            model_name="pinlist",
            name="description",
            field=models.TextField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="message",
            field=models.TextField(blank=True, max_length=5000, null=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AlterField(
            model_name="tripactivity",
            name="notes",
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AlterField(
            model_name="tripcomment",
            name="text",
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="description",
            field=models.TextField(blank=True, max_length=50000, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.CreateModel(
            name="PinLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("wayback_url", models.URLField(blank=True, default="", max_length=2000)),
                ("order", models.IntegerField(default=0)),
                ("pin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="dashboard.pin")),
            ],
            options={
                "db_table": "dashboard_pin_links",
                "ordering": ["order", "id"],
                "abstract": False,
                "indexes": [models.Index(fields=["pin"], name="idxdb_plink_pin")],
            },
        ),
        migrations.CreateModel(
            name="WikiLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("wayback_url", models.URLField(blank=True, default="", max_length=2000)),
                ("order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wiki_links_created", to="dashboard.profile")),
                ("wiki", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="dashboard.wiki")),
            ],
            options={
                "db_table": "dashboard_wiki_links",
                "ordering": ["order", "id"],
                "abstract": False,
                "indexes": [models.Index(fields=["wiki"], name="idxdb_wlink_wiki")],
            },
        ),
        migrations.AddField(
            model_name="friendinvitation",
            name="message",
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name="friendship",
            name="request_message",
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.CreateModel(
            name="DirectMessageMute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="dashboard.profile")),
                ("viewer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="dashboard.profile")),
            ],
            options={
                "db_table": "dashboard_dm_mutes",
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("viewer", "sender"), name="db_dm_mute_unique")],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="keyword_label_categories",
            field=models.BooleanField(default=True, help_text="Keyword matches can automatically add categories when a pin is created."),
        ),
        migrations.AddField(
            model_name="profile",
            name="keyword_label_statuses",
            field=models.BooleanField(default=True, help_text="Keyword matches can automatically add a status when a pin is created."),
        ),
        migrations.AddField(
            model_name="profile",
            name="keyword_label_tags",
            field=models.BooleanField(default=True, help_text="Keyword matches can automatically add tags when a pin is created."),
        ),
        migrations.AddField(
            model_name="profile",
            name="keyword_tagging_enabled",
            field=models.BooleanField(default=True, help_text="Allow keyword-based auto-tagging on your account."),
        ),
        migrations.AlterField(
            model_name="profile",
            name="direct_message_delete_after",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("when_read", "As soon as they're read"),
                    ("one_day", "1 day after being read"),
                    ("thirty_days", "30 days after being read"),
                    ("ninety_days", "90 days after being read"),
                    ("one_year", "1 year after being read"),
                ],
                default="never",
                help_text="Messages you send are permanently deleted from our systems this long after the recipient reads them - this removes your own copy too. Set to Never to keep them indefinitely.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_friends_per_user",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of friends a user may have. Set to 0 for unlimited.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)],
                verbose_name="Max friends per user",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_group_chat_members",
            field=models.IntegerField(
                default=20,
                help_text="Maximum number of members allowed in a direct message group chat. Set to 0 for unlimited.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)],
                verbose_name="Max group chat members",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_pins_per_list",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of pins allowed in a single list. Set to 0 for unlimited.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)],
                verbose_name="Max pins per list",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_safety_checkin_contacts",
            field=models.IntegerField(
                default=5,
                help_text="Maximum number of contacts a user may notify per safety check-in. Set to 0 for unlimited.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)],
                verbose_name="Max contacts per safety check-in",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_trip_activities",
            field=models.IntegerField(
                default=100,
                help_text="Maximum number of activities allowed per trip. Set to 0 for unlimited.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)],
                verbose_name="Max activities per trip",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_upcoming_trips_per_user",
            field=models.IntegerField(
                default=100,
                help_text="Maximum number of upcoming (or undated, still-planning) trips a user may belong to at once. Set to 0 for unlimited.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)],
                verbose_name="Max upcoming trips per user",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("max_trip_activities__gte", 0)), name="max_trip_activities_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("max_upcoming_trips_per_user__gte", 0)), name="max_upcoming_trips_per_user_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("max_pins_per_list__gte", 0)), name="max_pins_per_list_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("max_friends_per_user__gte", 0)), name="max_friends_per_user_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("max_group_chat_members__gte", 0)), name="max_group_chat_members_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(condition=models.Q(("max_safety_checkin_contacts__gte", 0)), name="max_safety_checkin_contacts_gte_0"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="search_provider",
            field=models.CharField(
                choices=[("brave", "Brave Search"), ("google", "Google Custom Search"), ("searxng", "SearXNG (self-hosted, free)"), ("duckduckgo", "DuckDuckGo Instant Answer (free)"), ("mojeek", "Mojeek Search"), ("marginalia", "Marginalia Search")],
                default="brave",
                help_text="Preferred web search provider for pin news/search results, tried first. If it's unconfigured, rate-limited, or fails, the remaining providers (SearXNG, Google, Brave, DuckDuckGo, Mojeek, Marginalia) are tried automatically in that order.",
                max_length=20,
                verbose_name="Search provider",
            ),
        ),
        migrations.AddField(
            model_name="pinlist",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            code=_0050_backfill_pin_list_slugs,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="pinlist",
            constraint=models.UniqueConstraint(fields=("profile", "slug"), name="uq_pin_list_profile_slug"),
        ),
        migrations.CreateModel(
            name="EpaFacility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("registry_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                ("detail_fetched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_epa_facility",
                "abstract": False,
                "indexes": [models.Index(fields=["latitude", "longitude"], name="idxdb_epafac_lat_lng")],
            },
        ),
        migrations.AddField(
            model_name="apiratelimit",
            name="calls_per_30_days",
            field=models.IntegerField(
                blank=True, help_text="Maximum calls allowed per rolling 30-day window. Leave blank for no 30-day limit.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)]
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pin_detail_map_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enrichment_enabled",
            field=models.BooleanField(
                default=True, help_text="Proactively backfill official names, aliases, addresses, and boundaries for all pins and wikis in the background, within each API's configured rate limits.", verbose_name="Background enrichment"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enrichment_start_hour",
            field=models.IntegerField(
                default=0,
                help_text="UTC hour (0-23) the daily enrichment window opens. Set start and end to the same value to allow enrichment at any hour.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)],
                verbose_name="Enrichment window start (UTC hour)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enrichment_end_hour",
            field=models.IntegerField(
                default=0,
                help_text="UTC hour (0-23) the daily enrichment window closes. May be earlier than the start hour to wrap past midnight (e.g. 22 to 4).",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)],
                verbose_name="Enrichment window end (UTC hour)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enrichment_buffer_percent",
            field=models.IntegerField(
                default=10,
                help_text="Percentage of every API limit kept in reserve for organic traffic spikes. Background enrichment never spends into this buffer.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)],
                verbose_name="Enrichment rate-limit buffer (%)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enrichment_max_per_service_per_run",
            field=models.IntegerField(
                default=10,
                help_text="Maximum locations enriched per API service in one hourly run, even when the service's rate limit would allow more - keeps bursts against generous APIs polite.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)],
                verbose_name="Enrichment max items per service per run",
            ),
        ),
        migrations.CreateModel(
            name="DirectMessageLocationMention",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("coordinates", "Coordinates"), ("address", "Street Address")], default="coordinates", max_length=20)),
                ("matched_text", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "dashboard_dm_location_mentions",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationExposure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(choices=[("share_received", "Share Received"), ("pin_moved", "Pin Moved")], default="share_received", max_length=20)),
            ],
            options={
                "db_table": "dashboard_location_exposures",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pinshare",
            name="detected_via_message",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="detected_pin_shares", to="dashboard.directmessage"),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="location",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pin_shares", to="dashboard.location"),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="origin",
            field=models.CharField(choices=[("explicit", "Explicit Share"), ("map_detected", "Detected From Shared Map"), ("dm_detected", "Detected From Message"), ("trip_activity", "Shared As Trip Activity")], default="explicit", max_length=20),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="pin",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="dashboard.pin"),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("already_pinned", "Already pinned"), ("detected", "Detected")], default="pending", max_length=20),
        ),
        migrations.AddIndex(
            model_name="pinshare",
            index=models.Index(fields=["to_profile", "location"], name="idxdb_pinshr_to_pfl_loc"),
        ),
        migrations.AddField(
            model_name="directmessagelocationmention",
            name="location",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="dashboard.location"),
        ),
        migrations.AddField(
            model_name="directmessagelocationmention",
            name="message",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="location_mentions", to="dashboard.directmessage"),
        ),
        migrations.AddField(
            model_name="directmessagelocationmention",
            name="pin_share",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dm_mentions", to="dashboard.pinshare"),
        ),
        migrations.AddField(
            model_name="locationexposure",
            name="location",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exposures", to="dashboard.location"),
        ),
        migrations.AddField(
            model_name="locationexposure",
            name="profile",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="location_exposures", to="dashboard.profile"),
        ),
        migrations.AddField(
            model_name="locationexposure",
            name="share",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exposures", to="dashboard.pinshare"),
        ),
        migrations.AddIndex(
            model_name="directmessagelocationmention",
            index=models.Index(fields=["message"], name="idxdb_dmlocm_message"),
        ),
        migrations.AddConstraint(
            model_name="directmessagelocationmention",
            constraint=models.UniqueConstraint(fields=("message", "location"), name="db_dmlocm_one_per_msg_loc"),
        ),
        migrations.AddIndex(
            model_name="locationexposure",
            index=models.Index(fields=["profile", "location"], name="idxdb_locexp_pfl_loc"),
        ),
        migrations.AddConstraint(
            model_name="locationexposure",
            constraint=models.UniqueConstraint(fields=("profile", "location", "share"), name="db_locexp_one_per_pfl_loc_share"),
        ),
        migrations.RunPython(
            code=_0056_backfill_share_locations_and_exposures,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name="PinOwner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("company_name", models.CharField(blank=True, default="", max_length=200)),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("notes", models.TextField(blank=True, default="")),
                ("pin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owners", to="dashboard.pin")),
            ],
            options={
                "db_table": "dashboard_pin_owner",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PinPropertySale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sale_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("new_owners", models.ManyToManyField(blank=True, related_name="sales_as_new_owner", to="dashboard.pinowner")),
                ("pin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="property_sales", to="dashboard.pin")),
                ("previous_owners", models.ManyToManyField(blank=True, related_name="sales_as_previous_owner", to="dashboard.pinowner")),
            ],
            options={
                "db_table": "dashboard_pin_property_sale",
                "ordering": ["-sale_date", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiOwner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("company_name", models.CharField(blank=True, default="", max_length=200)),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("notes", models.TextField(blank=True, default="")),
                ("source", models.CharField(choices=[("user", "User contributed"), ("official", "Official")], default="user", max_length=10)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wiki_owners_created", to="dashboard.profile")),
                ("locations", models.ManyToManyField(blank=True, related_name="owners", to="dashboard.location")),
            ],
            options={
                "db_table": "dashboard_wiki_owner",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiPropertySale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sale_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("source", models.CharField(choices=[("user", "User contributed"), ("official", "Official")], default="user", max_length=10)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wiki_property_sales_created", to="dashboard.profile")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales", to="dashboard.location")),
                ("new_owners", models.ManyToManyField(blank=True, related_name="sales_as_new_owner", to="dashboard.wikiowner")),
                ("previous_owners", models.ManyToManyField(blank=True, related_name="sales_as_previous_owner", to="dashboard.wikiowner")),
            ],
            options={
                "db_table": "dashboard_wiki_property_sale",
                "ordering": ["-sale_date", "-created"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="pinowner",
            index=models.Index(fields=["pin"], name="idxdb_pinowner_pin"),
        ),
        migrations.AddIndex(
            model_name="pinpropertysale",
            index=models.Index(fields=["pin", "-sale_date"], name="idxdb_pin_sale_pin_date"),
        ),
        migrations.AddConstraint(
            model_name="pinpropertysale",
            constraint=models.CheckConstraint(condition=models.Q(("sale_price__isnull", True), ("sale_price__gte", 0), _connector="OR"), name="db_pin_sale_price_gte_0"),
        ),
        migrations.AddIndex(
            model_name="wikipropertysale",
            index=models.Index(fields=["location", "-sale_date"], name="idxdb_wiki_sale_location_date"),
        ),
        migrations.AddConstraint(
            model_name="wikipropertysale",
            constraint=models.CheckConstraint(condition=models.Q(("sale_price__isnull", True), ("sale_price__gte", 0), _connector="OR"), name="db_wiki_sale_price_gte_0"),
        ),
        migrations.RemoveField(
            model_name="undoaction",
            name="cache_key",
        ),
        migrations.AddField(
            model_name="undoaction",
            name="payload",
            field=models.JSONField(default=list),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pinlist",
            name="source_saved_filter",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="derived_pin_lists", to="dashboard.savedfilter"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="theme_mode",
            field=models.CharField(choices=[("system", "System (follows your OS)"), ("light", "Light"), ("dark", "Dark")], default="dark", max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="common_pins_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="friends",
                help_text="Who can see the specific pins you have in common with them. Requires both of you to allow it.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customfield",
            name="style",
            field=models.CharField(blank=True, choices=[("short", "Short (single line)"), ("long", "Long (multi-line)"), ("input", "Number input"), ("stars", "Star rating"), ("slider", "Slider")], default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_boolean",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(choices=[("text", "Text"), ("number", "Number"), ("date", "Date"), ("time", "Time"), ("select", "Select"), ("checkbox", "Checkbox"), ("url", "Link")], default="text", max_length=10),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(fields=["field", "value_time"], name="idxdb_cfv_field_time"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_image",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_field_references", to="dashboard.image"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_markup_map",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_field_references", to="dashboard.markupmap"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_pin",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_field_references", to="dashboard.pin"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_pin_list",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_field_references", to="dashboard.pinlist"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_profile",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_field_references", to="dashboard.profile"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_trip",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_field_references", to="dashboard.trip"),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_wiki",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_field_references", to="dashboard.wiki"),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(choices=[("text", "Text"), ("number", "Number"), ("date", "Date"), ("time", "Time"), ("select", "Select"), ("checkbox", "Checkbox"), ("url", "Link"), ("reference", "Reference")], default="text", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ref_image__isnull", True), ("ref_markup_map__isnull", True), ("ref_pin__isnull", True), ("ref_pin_list__isnull", True), ("ref_profile__isnull", True), ("ref_trip__isnull", True), ("ref_wiki__isnull", True)),
                    models.Q(("ref_image__isnull", True), ("ref_markup_map__isnull", True), ("ref_pin__isnull", False), ("ref_pin_list__isnull", True), ("ref_profile__isnull", True), ("ref_trip__isnull", True), ("ref_wiki__isnull", True)),
                    models.Q(("ref_image__isnull", True), ("ref_markup_map__isnull", True), ("ref_pin__isnull", True), ("ref_pin_list__isnull", True), ("ref_profile__isnull", True), ("ref_trip__isnull", True), ("ref_wiki__isnull", False)),
                    models.Q(("ref_image__isnull", True), ("ref_markup_map__isnull", False), ("ref_pin__isnull", True), ("ref_pin_list__isnull", True), ("ref_profile__isnull", True), ("ref_trip__isnull", True), ("ref_wiki__isnull", True)),
                    models.Q(("ref_image__isnull", True), ("ref_markup_map__isnull", True), ("ref_pin__isnull", True), ("ref_pin_list__isnull", True), ("ref_profile__isnull", True), ("ref_trip__isnull", False), ("ref_wiki__isnull", True)),
                    models.Q(("ref_image__isnull", False), ("ref_markup_map__isnull", True), ("ref_pin__isnull", True), ("ref_pin_list__isnull", True), ("ref_profile__isnull", True), ("ref_trip__isnull", True), ("ref_wiki__isnull", True)),
                    models.Q(("ref_image__isnull", True), ("ref_markup_map__isnull", True), ("ref_pin__isnull", True), ("ref_pin_list__isnull", False), ("ref_profile__isnull", True), ("ref_trip__isnull", True), ("ref_wiki__isnull", True)),
                    models.Q(("ref_image__isnull", True), ("ref_markup_map__isnull", True), ("ref_pin__isnull", True), ("ref_pin_list__isnull", True), ("ref_profile__isnull", False), ("ref_trip__isnull", True), ("ref_wiki__isnull", True)),
                    _connector="OR",
                ),
                name="db_cfv_at_most_one_ref",
            ),
        ),
        migrations.CreateModel(
            name="GroupChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("creator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_group_chats", to="dashboard.profile")),
            ],
            options={
                "db_table": "dashboard_group_chats",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="group_keys_created", to="dashboard.profile")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="keys", to="dashboard.groupchat")),
            ],
            options={
                "db_table": "dashboard_e2ee_group_key",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupKeyEnvelope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("wrapped_key", models.TextField()),
                ("key", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="envelopes", to="dashboard.groupkey")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_key_envelopes", to="dashboard.profile")),
            ],
            options={
                "db_table": "dashboard_e2ee_group_key_envelope",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True, default="", max_length=1000)),
                ("ciphertext", models.TextField(blank=True, default="")),
                ("nonce", models.CharField(blank=True, default="", max_length=64)),
                ("key_version", models.PositiveIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="dashboard.groupchat")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sent_group_messages", to="dashboard.profile")),
            ],
            options={
                "db_table": "dashboard_group_messages",
                "ordering": ["created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupMessageShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="dashboard.groupmessage")),
                ("pin_share", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="group_message_shares", to="dashboard.pinshare")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_message_shares", to="dashboard.profile")),
            ],
            options={
                "db_table": "dashboard_group_message_shares",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupChatMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("muted", models.BooleanField(default=False)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="dashboard.groupchat")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_chat_memberships", to="dashboard.profile")),
                ("removed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="dashboard.profile")),
            ],
            options={
                "db_table": "dashboard_group_chat_memberships",
                "abstract": False,
                "indexes": [models.Index(fields=["profile", "left_at"], name="idxdb_gcm_profile_active")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("left_at__isnull", True)), fields=("group", "profile"), name="db_group_chat_one_active_membership")],
            },
        ),
        migrations.AddConstraint(
            model_name="groupkey",
            constraint=models.UniqueConstraint(fields=("group", "version"), name="db_e2ee_groupkey_group_version"),
        ),
        migrations.AddConstraint(
            model_name="groupkeyenvelope",
            constraint=models.UniqueConstraint(fields=("key", "profile"), name="db_e2ee_groupkey_one_envelope"),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(fields=["group", "created"], name="idxdb_gmsg_group_created"),
        ),
        migrations.AddConstraint(
            model_name="groupmessage",
            constraint=models.CheckConstraint(condition=models.Q(("body", ""), ("ciphertext", ""), _connector="OR"), name="db_gmsg_body_xor_ciphertext"),
        ),
        migrations.AddConstraint(
            model_name="groupmessageshare",
            constraint=models.UniqueConstraint(fields=("message", "recipient"), name="db_gmsg_share_one_per_recipient"),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, default="", max_length=200000, validators=[django.core.validators.MaxLengthValidator(200000)])),
                ("content_html", models.TextField(blank=True, default="")),
                ("toc", models.JSONField(blank=True, default=list)),
                ("last_edited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles_last_edited", to="dashboard.profile")),
                ("pin", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="article", to="dashboard.pin")),
                ("wiki", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="article", to="dashboard.wiki")),
            ],
            options={
                "db_table": "dashboard_articles",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, default="", max_length=200000, validators=[django.core.validators.MaxLengthValidator(200000)])),
                ("edit_summary", models.CharField(blank=True, default="", max_length=255)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="dashboard.article")),
                ("editor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="article_revisions", to="dashboard.profile")),
                ("restored_from", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="restorations", to="dashboard.articlerevision")),
            ],
            options={
                "db_table": "dashboard_article_revisions",
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("pin__isnull", False), ("wiki__isnull", True)), models.Q(("pin__isnull", True), ("wiki__isnull", False)), _connector="OR"), name="article_exactly_one_host"),
        ),
        migrations.AddIndex(
            model_name="articlerevision",
            index=models.Index(fields=["article", "created"], name="idxdb_artrev_article_created"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_link_extraction_daily_limit",
            field=models.IntegerField(
                default=20,
                help_text="Maximum AI link-extraction runs each user may start per day, bounding per-user token spend.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)],
                verbose_name="Link extraction daily limit (per user)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_link_extraction_enabled",
            field=models.BooleanField(default=True, help_text="Allow users with the AI feature to have external links on their pins read by AI to fill in supported pin fields.", verbose_name="Link extraction"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="LinkExtraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=2000)),
                ("status", models.CharField(choices=[("pending", "Queued"), ("running", "Processing"), ("success", "Complete"), ("empty", "Nothing found"), ("failed", "Failed")], default="pending", max_length=10)),
                ("error", models.TextField(blank=True, default="")),
                ("results", models.JSONField(blank=True, default=list)),
                ("pin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="link_extractions", to="dashboard.pin")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="link_extractions", to="dashboard.profile")),
            ],
            options={
                "db_table": "dashboard_link_extractions",
                "ordering": ["-created"],
                "abstract": False,
                "indexes": [models.Index(fields=["profile", "created"], name="idxdb_linkext_profile_created")],
            },
        ),
        migrations.AddField(
            model_name="pin",
            name="date_built",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customfield",
            name="display",
            field=models.CharField(choices=[("default", "In the Custom Fields card"), ("section", "Its own section"), ("fixed", "Fixed on screen (draggable)")], default="default", max_length=10),
        ),
        migrations.AddField(
            model_name="pin",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_aliases",
            field=models.CharField(
                choices=[("off", "Off"), ("to_wiki", "Sync to wiki"), ("from_wiki", "Sync from wiki"), ("both", "Sync both ways")],
                default="from_wiki",
                help_text="Automatically copy newly-added alternate names between a pin and its community wiki. Never deletes an alias on either side.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_danger_to_wiki",
            field=models.BooleanField(default=True, help_text="When you set a pin's danger, also count it on its community wiki."),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_priority_to_wiki",
            field=models.BooleanField(default=True, help_text="When you set a pin's priority, also count it on its community wiki."),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_rating_to_wiki",
            field=models.BooleanField(default=True, help_text="When you rate a pin, also count that rating on its community wiki."),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_vulnerability_to_wiki",
            field=models.BooleanField(default=True, help_text="When you set a pin's vulnerability, also count it on its community wiki."),
        ),
        migrations.AlterField(
            model_name="undoaction",
            name="payload",
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.CreateModel(
            name="PinAutoRemoval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("alias", "Alias"), ("link", "Link"), ("label", "Label"), ("owner", "Owner")], max_length=10)),
                ("value", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "dashboard_pin_auto_removals",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiAutoRemoval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("alias", "Alias"), ("link", "Link"), ("label", "Label"), ("owner", "Owner")], max_length=10)),
                ("value", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "dashboard_wiki_auto_removals",
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            sql="\n                DELETE FROM dashboard_pin_aliases\n                WHERE id IN (\n                    SELECT id FROM (\n                        SELECT id,\n                               ROW_NUMBER() OVER (\n                                   PARTITION BY pin_id, LOWER(name)\n                                   ORDER BY (kind = 'official') DESC, id ASC\n                               ) AS rn\n                        FROM dashboard_pin_aliases\n                    ) ranked\n                    WHERE rn > 1\n                );\n            ",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="\n                DELETE FROM dashboard_wiki_aliases\n                WHERE id IN (\n                    SELECT id FROM (\n                        SELECT id,\n                               ROW_NUMBER() OVER (\n                                   PARTITION BY wiki_id, LOWER(name)\n                                   ORDER BY (kind = 'official') DESC, id ASC\n                               ) AS rn\n                        FROM dashboard_wiki_aliases\n                    ) ranked\n                    WHERE rn > 1\n                );\n            ",
            reverse_sql="",
        ),
        migrations.RemoveConstraint(
            model_name="pinalias",
            name="db_pin_alias_unique",
        ),
        migrations.RemoveConstraint(
            model_name="wikialias",
            name="db_walias_unique",
        ),
        migrations.AddConstraint(
            model_name="pinalias",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), models.F("pin"), name="db_pin_alias_unique"),
        ),
        migrations.AddConstraint(
            model_name="wikialias",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), models.F("wiki"), name="db_walias_unique"),
        ),
        migrations.AddField(
            model_name="pinautoremoval",
            name="pin",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="auto_removals", to="dashboard.pin"),
        ),
        migrations.AddField(
            model_name="wikiautoremoval",
            name="wiki",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="auto_removals", to="dashboard.wiki"),
        ),
        migrations.AddConstraint(
            model_name="pinautoremoval",
            constraint=models.UniqueConstraint(fields=("pin", "kind", "value"), name="db_pin_auto_removal_unique"),
        ),
        migrations.AddConstraint(
            model_name="wikiautoremoval",
            constraint=models.UniqueConstraint(fields=("wiki", "kind", "value"), name="db_wiki_auto_removal_unique"),
        ),
        migrations.AddIndex(
            model_name="pinautoremoval",
            index=models.Index(fields=["pin", "kind"], name="idxdb_pautorm_pin_kind"),
        ),
        migrations.AddIndex(
            model_name="wikiautoremoval",
            index=models.Index(fields=["wiki", "kind"], name="idxdb_wautorm_wiki_kind"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("friend_suggestion", "Friend Suggestion"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="home_widget_layout",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text='User-facing label, e.g. "Zapier".', max_length=100)),
                ("prefix", models.CharField(editable=False, max_length=12, unique=True)),
                ("key_hash", models.CharField(editable=False, max_length=128)),
                ("scopes", models.JSONField(default=urbanlens.dashboard.models.account.model._default_api_key_scopes, editable=False)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_keys", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "dashboard_api_key",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiKeyUsageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("api_key", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usage_log", to="dashboard.apikey")),
            ],
            options={
                "db_table": "dashboard_api_key_usage_log",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="apicalllog",
            name="cost_estimate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated USD cost of this call, from the service's ServiceDefaults.cost_per_call at call time. Null means no per-call cost is configured for this service (free, or not yet priced) - not necessarily that the call was free.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(
            code=_0082_invalidate_wikipedia_cache_for_article_seeding,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="image",
            name="source",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("yelp", "Yelp"),
                    ("google_images", "Google Images"),
                    ("google_maps", "Google Maps"),
                    ("wikimedia", "Wikimedia Commons"),
                    ("wikipedia_media", "Wikipedia"),
                    ("smithsonian", "Smithsonian Open Access"),
                    ("library_of_congress", "Library of Congress"),
                    ("internet_archive", "Internet Archive"),
                    ("immich", "Immich"),
                    ("flickr", "Flickr"),
                    ("google_photos", "Google Photos"),
                ],
                default="upload",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="direction",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="auto_create_pin_article_from_wikipedia",
            field=models.BooleanField(default=True, help_text="When a Wikipedia article is matched to one of your pins, automatically start that pin's article from it (if it doesn't have one yet)."),
        ),
        migrations.RunPython(
            code=_0086_invalidate_wikipedia_cache_for_pin_article_seeding,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="max_upload_file_size_mb",
            field=models.IntegerField(
                default=250,
                help_text="Maximum size (MB) for a single photo, video, or document upload. Enforced on both the frontend and backend.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(900)],
                verbose_name="Max upload file size (MB)",
            ),
        ),
        migrations.RunPython(
            code=_0088_cap_existing_value,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0089_invalidate_wikipedia_cache,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0087_seed_global_demolished_label,
            reverse_code=_0087_remove_global_demolished_label,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name_source_priority",
        ),
        migrations.AddField(
            model_name="comment",
            name="pending_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tripcomment",
            name="pending_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("comment_upload_failed", "Comment Upload Failed"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("friend_suggestion", "Friend Suggestion"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
    ]
