# Generated by Django 6.0.6 on 2026-07-11 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_pinshare_bundled_with"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("pin", "Pins"),
                            ("photo", "Photos"),
                            ("profile", "People"),
                            ("markup_map", "Maps"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_custom_fields",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value_text", models.TextField(blank=True, default="")),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=24, null=True
                    ),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="dashboard.customfield",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="dashboard.image",
                    ),
                ),
                (
                    "markup_map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="dashboard.markupmap",
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "target_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values_about",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_custom_field_values",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="customfield",
            index=models.Index(
                fields=["profile", "entity_type"], name="idxdb_cf_profile_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="customfield",
            constraint=models.UniqueConstraint(
                fields=("profile", "entity_type", "name"), name="db_cf_unique_name"
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["field", "value_number"], name="idxdb_cfv_field_number"
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["field", "value_date"], name="idxdb_cfv_field_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pin__isnull", False)),
                fields=("field", "pin"),
                name="db_cfv_unique_pin",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image__isnull", False)),
                fields=("field", "image"),
                name="db_cfv_unique_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_profile__isnull", False)),
                fields=("field", "target_profile"),
                name="db_cfv_unique_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("markup_map__isnull", False)),
                fields=("field", "markup_map"),
                name="db_cfv_unique_map",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("image__isnull", True),
                        ("markup_map__isnull", True),
                        ("pin__isnull", False),
                        ("target_profile__isnull", True),
                    ),
                    models.Q(
                        ("image__isnull", False),
                        ("markup_map__isnull", True),
                        ("pin__isnull", True),
                        ("target_profile__isnull", True),
                    ),
                    models.Q(
                        ("image__isnull", True),
                        ("markup_map__isnull", True),
                        ("pin__isnull", True),
                        ("target_profile__isnull", False),
                    ),
                    models.Q(
                        ("image__isnull", True),
                        ("markup_map__isnull", False),
                        ("pin__isnull", True),
                        ("target_profile__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="db_cfv_exactly_one_target",
            ),
        ),
    ]
