# Generated by Django 4.2.8 on 2024-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_geocodedlocation_json_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocodedlocation",
            name="json_response",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
