# Generated by Django 6.0.6 on 2026-07-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0008_remove_googleplace_dashboard_google_place_unique_coordinates_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pinshare",
            name="dashboard_pin_share_one_pending_per_pin_user",
        ),
        migrations.AddConstraint(
            model_name="pinshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("pin", "to_profile"),
                name="db_pinshare_one_pending_per_pin_user",
            ),
        ),
    ]
