# Generated by Django 6.0.6 on 2026-07-11 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="direct_message_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                help_text="Who can send you direct messages.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=5000)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_direct_messages",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_direct_messages",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_direct_messages",
                "ordering": ["created"],
                "get_latest_by": "created",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["sender", "recipient"], name="idxdb_dm_sender_recipient"
                    ),
                    models.Index(
                        fields=["recipient", "read_at"], name="idxdb_dm_recipient_read"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("recipient")), _negated=True
                        ),
                        name="db_dm_no_self_message",
                    )
                ],
            },
        ),
    ]
