# Generated by Django 6.0.6 on 2026-07-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_profile_tos_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="wiki",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_wikis",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="viewed_by_other",
            field=models.BooleanField(default=False),
        ),
    ]
