# Generated by Django 6.0.6 on 2026-07-22 16:04

from django.db import migrations, models


def mark_existing_types_as_user_provided(apps, schema_editor):
    """Treat every already-classified pin/wiki as deliberately classified.

    Until now the only way a row got a non-default ``pin_type`` was a human
    picking one out of the detail-pin dialog's Type select, so automatic
    classification (which this migration's new flag gates) must leave all of
    them alone. Rows still on the ``location`` default stay unflagged and
    remain eligible for auto-classification.
    """
    for model_name in ("Pin", "Wiki"):
        model = apps.get_model("dashboard", model_name)
        model.objects.exclude(pin_type="location").update(pin_type_is_user_provided=True)


def unmark_all(apps, schema_editor):
    """Reverse of :func:`mark_existing_types_as_user_provided`."""
    for model_name in ("Pin", "Wiki"):
        apps.get_model("dashboard", model_name).objects.update(pin_type_is_user_provided=False)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_image_source_add_loopnet_cris"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="buildings_offer_dismissed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pin",
            name="pin_type_is_user_provided",
            field=models.BooleanField(
                default=False,
                help_text="Prevents automatic building/parcel classification from overwriting a user-chosen pin type.",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="pin_type_is_user_provided",
            field=models.BooleanField(
                default=False,
                help_text="Prevents automatic building/parcel classification from overwriting an editor-chosen type.",
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="pin_type",
            field=models.CharField(
                choices=[
                    ("location", "Location"),
                    ("parcel", "Property / Parcel"),
                    ("building", "Building"),
                    ("entrance", "Entrance"),
                    ("poi", "Point of Interest"),
                    ("danger", "Danger"),
                    ("other", "Other"),
                ],
                default="location",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="pin_type",
            field=models.CharField(
                choices=[
                    ("location", "Location"),
                    ("parcel", "Property / Parcel"),
                    ("building", "Building"),
                    ("entrance", "Entrance"),
                    ("poi", "Point of Interest"),
                    ("danger", "Danger"),
                    ("other", "Other"),
                ],
                default="location",
                max_length=30,
            ),
        ),
        migrations.RunPython(
            code=mark_existing_types_as_user_provided,
            reverse_code=unmark_all,
        ),
    ]
