# Generated by Django 6.0.6 on 2026-07-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_profile_direct_message_visibility_directmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageImagePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("allowed", "Allowed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_dm_image_permissions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DirectMessageShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pin", "Pin"),
                            ("trip", "Trip"),
                            ("friend", "Friend recommendation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_direct_message_shares",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DirectMessageTemporaryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "dashboard_dm_temporary_access",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="directmessage",
            name="deleted_by_recipient_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="deleted_by_sender_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="images_revealed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="markup_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_messages",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="dashboard.directmessage",
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="sender_delete_after",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("when_read", "As soon as they're read"),
                    ("one_day", "1 day after being read"),
                    ("thirty_days", "30 days after being read"),
                    ("ninety_days", "90 days after being read"),
                    ("one_year", "1 year after being read"),
                ],
                default="never",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="direct_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.directmessage",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="allow_friend_recommendations",
            field=models.BooleanField(
                default=True,
                help_text="Let other users recommend you as a friend to people they're messaging.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="direct_message_delete_after",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("when_read", "As soon as they're read"),
                    ("one_day", "1 day after being read"),
                    ("thirty_days", "30 days after being read"),
                    ("ninety_days", "90 days after being read"),
                    ("one_year", "1 year after being read"),
                ],
                default="never",
                help_text="Messages you send disappear from the recipient's view this long after they've read them. You can always see your own messages.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="online_status_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="friends",
                help_text="Who can see when you're online in direct messages.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="read_receipt_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="friends",
                help_text="Who can see that you've read their direct messages.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="typing_indicator_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="friends",
                help_text="Who can see when you're typing a direct message reply.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="direct_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="dashboard.directmessage",
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(fields=["direct_message"], name="idxdb_react_dm"),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("direct_message__isnull", False)),
                fields=("profile", "emoji", "direct_message"),
                name="unique_reaction_direct_message",
            ),
        ),
        migrations.AddField(
            model_name="directmessageimagepermission",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="directmessageimagepermission",
            name="viewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="directmessageshare",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share",
                to="dashboard.directmessage",
            ),
        ),
        migrations.AddField(
            model_name="directmessageshare",
            name="pin_share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_message_share",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddField(
            model_name="directmessageshare",
            name="recommended_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="directmessageshare",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_message_shares",
                to="dashboard.trip",
            ),
        ),
        migrations.AddField(
            model_name="directmessageshare",
            name="trip_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_message_share",
                to="dashboard.tripmembership",
            ),
        ),
        migrations.AddField(
            model_name="directmessagetemporaryaccess",
            name="granted_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporary_access_received",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="directmessagetemporaryaccess",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporary_access_grants",
                to="dashboard.profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="directmessageimagepermission",
            constraint=models.UniqueConstraint(
                fields=("viewer", "sender"), name="db_dm_image_perm_unique"
            ),
        ),
    ]
