# Generated by Django 6.0.6 on 2026-07-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_wiki_created_by_and_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="copyright",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
