# Generated by Django 6.0.6 on 2026-07-25 15:04

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import urbanlens.dashboard.models.spotguessr.model
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_existing_types_as_user_provided(apps, schema_editor):
    """Treat every already-classified pin/wiki as deliberately classified.

    Until now the only way a row got a non-default ``pin_type`` was a human
    picking one out of the detail-pin dialog's Type select, so automatic
    classification (which this migration's new flag gates) must leave all of
    them alone. Rows still on the ``location`` default stay unflagged and
    remain eligible for auto-classification.
    """
    for model_name in ("Pin", "Wiki"):
        model = apps.get_model("dashboard", model_name)
        model.objects.exclude(pin_type="location").update(pin_type_is_user_provided=True)


def unmark_all(apps, schema_editor):
    """Reverse of :func:`mark_existing_types_as_user_provided`."""
    for model_name in ("Pin", "Wiki"):
        apps.get_model("dashboard", model_name).objects.update(pin_type_is_user_provided=False)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_image_source_add_loopnet_cris'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='buildings_offer_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_type_is_user_provided',
            field=models.BooleanField(default=False, help_text='Prevents automatic building/parcel classification from overwriting a user-chosen pin type.'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='pin_type_is_user_provided',
            field=models.BooleanField(default=False, help_text='Prevents automatic building/parcel classification from overwriting an editor-chosen type.'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_type',
            field=models.CharField(choices=[('location', 'Location'), ('parcel', 'Property / Parcel'), ('building', 'Building'), ('entrance', 'Entrance'), ('poi', 'Point of Interest'), ('danger', 'Danger'), ('other', 'Other')], default='location', max_length=30),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='pin_type',
            field=models.CharField(choices=[('location', 'Location'), ('parcel', 'Property / Parcel'), ('building', 'Building'), ('entrance', 'Entrance'), ('poi', 'Point of Interest'), ('danger', 'Danger'), ('other', 'Other')], default='location', max_length=30),
        ),
        migrations.RunPython(
            code=mark_existing_types_as_user_provided,
            reverse_code=unmark_all,
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='buildings_offer_dismissed',
            new_name='restructure_offer_dismissed',
        ),
        migrations.AddField(
            model_name='profile',
            name='suggest_pin_restructure',
            field=models.BooleanField(default=True, help_text='Offer to organize pins into buildings and child pins when you open a property that has several.'),
        ),
        migrations.CreateModel(
            name='PinTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pin_uuid', models.UUIDField(editable=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_tombstones', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_pin_tombstones',
                'ordering': ['created'],
                'abstract': False,
                'indexes': [models.Index(fields=['profile', 'created'], name='idxdb_pintomb_prof_created')],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transport', models.CharField(choices=[('unifiedpush', 'UnifiedPush endpoint (e.g. ntfy)'), ('fcm', 'Firebase Cloud Messaging token')], default='unifiedpush', max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_push_devices',
                'ordering': ['-created'],
                'abstract': False,
                'indexes': [models.Index(fields=['profile', 'revoked_at'], name='idxdb_pushdev_prof_revoked')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'address'), name='db_push_device_unique_address')],
            },
        ),
        migrations.AddField(
            model_name='pinsuggestion',
            name='suggested_aliases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pinsuggestion',
            name='suggested_description',
            field=models.TextField(blank=True, default='', max_length=50000, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AddField(
            model_name='pinsuggestion',
            name='suggested_links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pinsuggestion',
            name='suggested_pin_type',
            field=models.CharField(blank=True, choices=[('location', 'Location'), ('parcel', 'Property / Parcel'), ('building', 'Building'), ('entrance', 'Entrance'), ('poi', 'Point of Interest'), ('danger', 'Danger'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('yelp', 'Yelp'), ('google_images', 'Google Images'), ('google_maps', 'Google Maps'), ('wikimedia', 'Wikimedia Commons'), ('wikipedia_media', 'Wikipedia'), ('smithsonian', 'Smithsonian Open Access'), ('library_of_congress', 'Library of Congress'), ('internet_archive', 'Internet Archive'), ('immich', 'Immich'), ('flickr', 'Flickr'), ('google_photos', 'Google Photos'), ('loopnet', 'LoopNet'), ('cris', 'NY Historic Preservation (CRIS)'), ('external_api', 'External app')], default='upload', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='suggest_public_pins',
            field=models.BooleanField(default=True, help_text="Suggest community-approved public locations that you haven't pinned yet."),
        ),
        migrations.AlterField(
            model_name='pinsuggestion',
            name='origin',
            field=models.CharField(choices=[('immich', 'Immich library scan'), ('local_scan', 'Local folder scan'), ('external_api', 'External app'), ('community', 'Community public location')], max_length=20),
        ),
        migrations.CreateModel(
            name='PublicPinCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('suspended', 'Suspended'), ('passed', 'Passed'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_candidate', to='dashboard.location')),
            ],
            options={
                'db_table': 'dashboard_public_pin_candidates',
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='idxdb_ppc_status')],
            },
        ),
        migrations.CreateModel(
            name='PublicPinVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('make_public', models.BooleanField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dashboard.publicpincandidate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_pin_votes', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_public_pin_votes',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('candidate', 'profile'), name='db_public_pin_vote_unique')],
            },
        ),
        migrations.AddField(
            model_name='boundary',
            name='source',
            field=models.CharField(blank=True, choices=[('redata', 'County records (REData)'), ('overpass', 'OpenStreetMap (Overpass)')], default='', max_length=20),
        ),
        migrations.RemoveConstraint(
            model_name='boundary',
            name='boundary_unique_location_default',
        ),
        migrations.AddConstraint(
            model_name='boundary',
            constraint=models.UniqueConstraint(condition=models.Q(('pin__isnull', True), ('profile__isnull', True), ('source', ''), ('wiki__isnull', True)), fields=('location', 'boundary_type'), name='boundary_unique_location_default'),
        ),
        migrations.AddConstraint(
            model_name='boundary',
            constraint=models.UniqueConstraint(condition=models.Q(('pin__isnull', True), ('profile__isnull', True), ('wiki__isnull', True), models.Q(('source', ''), _negated=True)), fields=('location', 'boundary_type', 'source'), name='boundary_unique_source_candidate'),
        ),
        migrations.CreateModel(
            name='BoundaryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dashboard.boundary')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_votes', to='dashboard.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_votes', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_boundary_votes',
                'abstract': False,
                'indexes': [models.Index(fields=['location'], name='idxdb_bv_location')],
                'constraints': [models.UniqueConstraint(fields=('location', 'profile'), name='db_boundary_vote_unique')],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_trip_suggestions_enabled',
            field=models.BooleanField(default=True, help_text="Allow AI to suggest pins worth adding to a trip and a drive/weather/vote-aware activity order. Only ever sees pins every trip member already has and members' external-sharing preferences are honored.", verbose_name='Trip suggestions'),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('photos', 'Photos'), ('named_place', 'Named Place'), ('street_view', 'Street View')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('config', models.JSONField(default=dict)),
                ('total_rounds', models.PositiveSmallIntegerField(default=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_spotguessr_sessions', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_sessions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sequence_index', models.PositiveSmallIntegerField()),
                ('target_is_point', models.BooleanField(default=False)),
                ('target_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotguessr_rounds', to='dashboard.image')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_rounds', to='dashboard.location')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='dashboard.gamesession')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_rounds',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_participations', to='dashboard.profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.gamesession')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_session_participants',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('guess_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('guessed_date', models.DateField(blank=True, null=True)),
                ('date_points', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_guesses', to='dashboard.profile')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='dashboard.gameround')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_guesses',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationModeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('photos', 'Photos'), ('named_place', 'Named Place'), ('street_view', 'Street View')], max_length=20)),
                ('mu', models.FloatField(default=0.0)),
                ('phi', models.FloatField(default=2.014761872416068)),
                ('sigma', models.FloatField(default=0.06)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_ratings', to='dashboard.location')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_location_ratings',
                'abstract': False,
            },
            bases=(urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields, models.Model),
        ),
        migrations.CreateModel(
            name='PlayerModeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('photos', 'Photos'), ('named_place', 'Named Place'), ('street_view', 'Street View')], max_length=20)),
                ('mu', models.FloatField(default=0.0)),
                ('phi', models.FloatField(default=2.014761872416068)),
                ('sigma', models.FloatField(default=0.06)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_ratings', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_player_ratings',
                'abstract': False,
            },
            bases=(urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields, models.Model),
        ),
        migrations.CreateModel(
            name='SpotGuessrPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('show_ratings_to_friends', models.BooleanField(default=True)),
                ('last_config', models.JSONField(default=dict)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_preference', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_preferences',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_index'), name='db_sg_round_unique'),
        ),
        migrations.AddConstraint(
            model_name='gamesessionparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'profile'), name='db_sg_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.UniqueConstraint(fields=('round', 'profile'), name='db_sg_guess_unique'),
        ),
        migrations.AddConstraint(
            model_name='locationmoderating',
            constraint=models.UniqueConstraint(fields=('location', 'mode'), name='db_sg_location_rating_unique'),
        ),
        migrations.AddConstraint(
            model_name='playermoderating',
            constraint=models.UniqueConstraint(fields=('profile', 'mode'), name='db_sg_player_rating_unique'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='display_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamesessionparticipant',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined')], default='joined', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=12),
        ),
        migrations.CreateModel(
            name='GameSessionChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=1000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_chat_messages', to='dashboard.profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='dashboard.gamesession')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_chat_messages',
                'abstract': False,
                'indexes': [models.Index(fields=['session', 'created'], name='idxdb_sg_chat_session_created')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='media_item_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='media_source_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('trip_updated', 'Trip Updated'), ('friend_request', 'New Friend Request'), ('message', 'New Message'), ('comment_reply', 'Reply to Comment'), ('comment_liked', 'Comment Likes'), ('comment_upload_failed', 'Comment Upload Failed'), ('friend_accepted', 'Friend Request Accepted'), ('added_to_trip', 'Trip Invitation'), ('wiki_updated', 'Community Wiki Updated'), ('pin_shared', 'Pin Shared'), ('map_shared', 'Map Shared'), ('visit_suggested', 'Visit Suggested'), ('safety_ci_due', 'Safety Check-in Due'), ('safety_ci_final_warning', 'Safety Check-in Final Warning'), ('safety_ci_overdue', 'Safety Check-in Overdue'), ('safety_ci_resolved', 'Safety Check-in Resolved'), ('safety_ci_plan_updated', 'Safety Check-in Plan Updated'), ('wiki_safety_checkin', 'Community Wiki Safety Check-in'), ('account_deletion_requested', 'Account Deletion Requested'), ('account_deletion_reminder', 'Account Deletion Reminder'), ('ai_extraction', 'AI Link Analysis Complete'), ('friend_suggestion', 'Friend Suggestion'), ('spotguessr_invite', 'SpotGuessr Invitation'), ('pin_import_complete', 'Pin Import Complete'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=30),
        ),
        migrations.CreateModel(
            name='GamePhotoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('reported', 'Reported'), ('no_reaction', 'No Reaction')], max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotguessr_photo_feedback', to='dashboard.profile')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_feedback', to='dashboard.gameround')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_photo_feedback',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('round', 'profile'), name='db_sg_photo_feedback_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['location', 'media_source_key', 'media_item_key'], name='idxdb_image_media_key'),
        ),
        migrations.AddField(
            model_name='image',
            name='estimated_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='estimated_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='PhotoCoordinateGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('guess_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('is_correct', models.BooleanField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_guesses', to='dashboard.image')),
            ],
            options={
                'db_table': 'dashboard_spotguessr_photo_coordinate_guesses',
                'abstract': False,
                'indexes': [models.Index(fields=['image', 'is_correct'], name='idxdb_sg_cordgues_iscorrect')],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anthropic_model',
            field=models.CharField(default='claude-haiku-4-5', help_text='Anthropic (Claude) model name (e.g. claude-haiku-4-5, claude-sonnet-5). Only used when provider is Anthropic.', max_length=100, verbose_name='Anthropic model'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ai_provider',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare Workers AI'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='cloudflare', help_text='Which AI provider to use for all AI-powered features.', max_length=20, verbose_name='AI provider'),
        ),
        migrations.CreateModel(
            name='PlayerTriviaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mu', models.FloatField(default=0.0)),
                ('phi', models.FloatField(default=2.014761872416068)),
                ('sigma', models.FloatField(default=0.06)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_rating', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_trivia_player_ratings',
                'abstract': False,
            },
            bases=(urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields, models.Model),
        ),
        migrations.CreateModel(
            name='TriviaPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('show_ratings_to_friends', models.BooleanField(default=True)),
                ('last_config', models.JSONField(default=dict)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_preference', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_trivia_preferences',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('answer_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('user_submitted', 'User Submitted'), ('ai_generated', 'AI Generated'), ('deterministic', 'Deterministic')], max_length=20)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=100)),
                ('wiki_incorporated_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_questions', to='dashboard.location')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trivia_questions_submitted', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_trivia_questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriviaQuestionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mu', models.FloatField(default=0.0)),
                ('phi', models.FloatField(default=2.014761872416068)),
                ('sigma', models.FloatField(default=0.06)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('last_asked_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='dashboard.triviaquestion')),
            ],
            options={
                'db_table': 'dashboard_trivia_question_ratings',
                'abstract': False,
            },
            bases=(urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields, models.Model),
        ),
        migrations.CreateModel(
            name='TriviaQuestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote'), ('report', 'Report'), ('no_reaction', 'No Reaction')], max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_question_votes', to='dashboard.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dashboard.triviaquestion')),
            ],
            options={
                'db_table': 'dashboard_trivia_question_votes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriviaRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sequence_index', models.PositiveSmallIntegerField()),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_rounds', to='dashboard.triviaquestion')),
            ],
            options={
                'db_table': 'dashboard_trivia_rounds',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriviaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('raw_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('matched_via', models.CharField(choices=[('exact', 'Exact Match'), ('ai', 'AI Judged')], default='exact', max_length=10)),
                ('points', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_answers', to='dashboard.profile')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.triviaround')),
            ],
            options={
                'db_table': 'dashboard_trivia_answers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriviaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('config', models.JSONField(default=dict)),
                ('total_rounds', models.PositiveSmallIntegerField(default=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_trivia_sessions', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_trivia_sessions',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='triviaround',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='dashboard.triviasession'),
        ),
        migrations.CreateModel(
            name='TriviaSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined')], default='joined', max_length=10)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_participations', to='dashboard.profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.triviasession')),
            ],
            options={
                'db_table': 'dashboard_trivia_session_participants',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='triviaquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('location', 'dedupe_key'), name='db_trivia_question_dedupe_unique'),
        ),
        migrations.AddConstraint(
            model_name='triviaquestionvote',
            constraint=models.UniqueConstraint(fields=('question', 'profile'), name='db_trivia_vote_unique'),
        ),
        migrations.AddConstraint(
            model_name='triviaanswer',
            constraint=models.UniqueConstraint(fields=('round', 'profile'), name='db_trivia_answer_unique'),
        ),
        migrations.AddConstraint(
            model_name='triviaround',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_index'), name='db_trivia_round_unique'),
        ),
        migrations.AddConstraint(
            model_name='triviasessionparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'profile'), name='db_trivia_participant_unique'),
        ),
        migrations.CreateModel(
            name='TriviaSessionChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=1000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_chat_messages', to='dashboard.profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='dashboard.triviasession')),
            ],
            options={
                'db_table': 'dashboard_trivia_chat_messages',
                'abstract': False,
                'indexes': [models.Index(fields=['session', 'created'], name='idxdb_trivia_chat_created')],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_trivia_answer_check_enabled',
            field=models.BooleanField(default=True, help_text="Allow AI to judge a Trivia answer that doesn't exact-match as possibly correct but differently phrased. Only ever consulted on a normalized-string mismatch; users without the AI subscription feature always fall back to exact match only.", verbose_name='Trivia AI answer checking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_trivia_generation_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to generate candidate Trivia questions from wiki articles with substantial content. Every generated question still passes through the same moderation classifier before entering rotation.', verbose_name='Trivia question generation'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_trivia_moderation_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to classify user-submitted and AI-generated Trivia questions for person/bullying/in-group content before they enter rotation. When off, user submissions are held in pending review indefinitely and AI question generation is skipped entirely (moderation is never bypassed).', verbose_name='Trivia question moderation'),
        ),
        migrations.CreateModel(
            name='SafetyCheckinPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted')], default='invited', max_length=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_safety_checkin_partners',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='safety_checkin_partner_invite',
            field=models.CharField(choices=[('none', 'None'), ('site', 'Notification'), ('email', 'Email'), ('both', 'Notification and email')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='safety_checkin_partner_invite_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='safety_checkin_partner_invite_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_safety_checkin_partners',
            field=models.IntegerField(default=5, help_text='Maximum number of partners a user may add to one safety check-in. Set to 0 for unlimited.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Max partners per safety check-in'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('trip_updated', 'Trip Updated'), ('friend_request', 'New Friend Request'), ('message', 'New Message'), ('comment_reply', 'Reply to Comment'), ('comment_liked', 'Comment Likes'), ('comment_upload_failed', 'Comment Upload Failed'), ('friend_accepted', 'Friend Request Accepted'), ('added_to_trip', 'Trip Invitation'), ('wiki_updated', 'Community Wiki Updated'), ('pin_shared', 'Pin Shared'), ('map_shared', 'Map Shared'), ('visit_suggested', 'Visit Suggested'), ('safety_ci_due', 'Safety Check-in Due'), ('safety_ci_final_warning', 'Safety Check-in Final Warning'), ('safety_ci_overdue', 'Safety Check-in Overdue'), ('safety_ci_resolved', 'Safety Check-in Resolved'), ('safety_ci_plan_updated', 'Safety Check-in Plan Updated'), ('wiki_safety_checkin', 'Community Wiki Safety Check-in'), ('safety_ci_partner_invite', 'Safety Check-in Partner Request'), ('safety_ci_partner_accepted', 'Safety Check-in Partner Accepted'), ('account_deletion_requested', 'Account Deletion Requested'), ('account_deletion_reminder', 'Account Deletion Reminder'), ('ai_extraction', 'AI Link Analysis Complete'), ('friend_suggestion', 'Friend Suggestion'), ('spotguessr_invite', 'SpotGuessr Invitation'), ('trivia_invite', 'Trivia Invitation'), ('pin_import_complete', 'Pin Import Complete'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('max_safety_checkin_partners__gte', 0)), name='max_safety_checkin_partners_gte_0'),
        ),
        migrations.AddField(
            model_name='safetycheckinpartner',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='dashboard.safetycheckin'),
        ),
        migrations.AddField(
            model_name='safetycheckinpartner',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='safetycheckinpartner',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checkin_partner_roles', to='dashboard.profile'),
        ),
        migrations.AddIndex(
            model_name='safetycheckinpartner',
            index=models.Index(fields=['checkin', 'status'], name='idxdb_scp_checkin_status'),
        ),
        migrations.AddIndex(
            model_name='safetycheckinpartner',
            index=models.Index(fields=['profile', 'status'], name='idxdb_scp_profile_status'),
        ),
        migrations.AlterUniqueTogether(
            name='safetycheckinpartner',
            unique_together={('checkin', 'profile')},
        ),
        migrations.AddField(
            model_name='pin',
            name='indoor_outdoor',
            field=models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside'), ('both', 'Both')], help_text="Whether this pin's location is inside, outside, or both; unset when not yet classified.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wiki',
            name='indoor_outdoor',
            field=models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside'), ('both', 'Both')], help_text='Whether this place is inside, outside, or both; unset when not yet classified.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tripmembership',
            name='rsvp',
            field=models.CharField(blank=True, choices=[('yes', 'Going'), ('no', 'Not Coming'), ('maybe', 'Maybe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='safetycheckin',
            name='live_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='safetycheckin',
            name='live_location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetycheckin',
            name='live_location_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safetycheckin',
            name='live_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetycheckin',
            name='live_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guess',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='permissions',
            field=models.CharField(choices=[('Send Message', 'Send Message'), ('Invite to Events', 'Invite to Events'), ('Share Pins', 'Share Pins'), ('View Profile', 'View Profile'), ('View Friends', 'View Friends'), ('View Trips', 'View Trips')], default='View Profile', max_length=16),
        ),
        migrations.CreateModel(
            name="TripActivityRSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rsvp",
                    models.CharField(
                        choices=[
                            ("yes", "Going"),
                            ("no", "Not Coming"),
                            ("maybe", "Maybe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="dashboard.tripactivity",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_rsvp_overrides",
                        to="dashboard.tripmembership",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trip_activity_rsvps",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["activity"], name="idxdb_taar_activity")
                ],
                "unique_together": {("activity", "membership")},
            },
        ),
    ]
