# Generated by Django 6.0.6 on 2026-06-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_badge_color_alter_pin_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pin",
            old_name="nickname",
            new_name="name",
        ),
    ]
