# Generated by Django 6.0.6 on 2026-07-08 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_location_identity_immutable"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="dashboard.location",
            ),
        ),
    ]
