# Generated by Django 5.1 on 2026-07-08

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def _backfill_checksums(apps, schema_editor):
    """Hash existing image files so duplicate detection covers pre-existing photos.

    Files that are missing from storage (or unreadable) are skipped - their rows
    keep a NULL checksum, which the duplicate check ignores; they are also
    backfilled lazily by process_image_upload if ever reprocessed.
    """
    import hashlib

    Image = apps.get_model("dashboard", "Image")
    for image in Image.objects.filter(checksum__isnull=True).exclude(image="").iterator():
        try:
            with image.image.open("rb") as fh:
                digest = hashlib.sha256()
                for chunk in iter(lambda: fh.read(1024 * 1024), b""):
                    digest.update(chunk)
            Image.objects.filter(pk=image.pk).update(checksum=digest.hexdigest())
        except OSError as exc:
            logger.warning("checksum backfill: could not read image %s: %s", image.pk, exc)


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_image_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="checksum",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.RunPython(_backfill_checksums, migrations.RunPython.noop),
    ]
