# Generated by Django 6.0.6 on 2026-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_v0_6_0"),
    ]

    operations = [
        # These two fields belong to an earlier feature (AI article expansion
        # from linked pages) that shipped with no migration of its own - see
        # docs/PROBLEMS.md. Trivia wiki incorporation directly reuses that
        # feature's writing/safety pipeline, so this migration adds them
        # alongside the field this migration actually exists for, rather than
        # leaving every SiteSettings-touching test broken on a fresh DB.
        migrations.AddField(
            model_name="sitesettings",
            name="ai_article_expansion_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow the link-extraction pipeline to ask a writing assistant for new plain-text paragraphs to append to the pin article (and the location wiki article when one exists). Every draft still passes through article safety moderation before it is saved; when this toggle is off, field extraction still runs and article expansion is skipped.",
                verbose_name="Article expansion from links",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_article_safety_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI to judge article text drafted from a linked page for appropriateness and safety-related implications (entry methods, trespass how-tos, harassment, etc.) before it is appended. When off, article expansion is skipped entirely — moderation is never bypassed.",
                verbose_name="Article expansion safety review",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_trivia_wiki_incorporation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI to draft a plain-text paragraph folding a well-upvoted user-submitted Trivia question into its location's wiki article. Every draft still passes through the same article safety moderation as link-based article expansion before it is appended; when off, well-upvoted questions are simply never considered (moderation is never bypassed).",
                verbose_name="Trivia wiki incorporation",
            ),
        ),
    ]
