# Generated by Django 6.0.6 on 2026-07-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_parcel_scope_pin_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="suggest_pin_restructure",
            field=models.BooleanField(
                default=True,
                help_text="Offer to organize pins into buildings and child pins when you open a property that has several.",
            ),
        ),
    ]
