# Generated by Django 5.1.6 on 2026-05-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_social_link_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sociallink",
            new_name="dashboard_s_profile_85d0eb_idx",
            old_name="dashboard_s_profile_idx",
        ),
    ]
