# Generated by Django 6.0.6 on 2026-07-30 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_v0_6_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiratelimit",
            name="last_call_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Internal bookkeeping: when this service's last reserved call was made. Used to enforce min_interval_seconds.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apiratelimit",
            name="min_interval_seconds",
            field=models.FloatField(
                blank=True,
                help_text="Minimum seconds required between consecutive calls, enforced independently of the per-minute/day/30-day budgets above - for providers whose ToS is a hard spacing requirement (e.g. Nominatim's 1 req/second) rather than just a rolling total, which a rolling-window count alone can't guarantee since it still allows a burst to land well within budget. Leave blank for no minimum spacing.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
