# Generated by Django 6.0.6 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_image_attribution_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendarAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "google_email",
                    models.CharField(
                        blank=True,
                        help_text="Email of the connected Google account, for display only.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="Target calendar for imports/exports. 'primary' is the user's main calendar.",
                        max_length=255,
                    ),
                ),
                ("scopes", models.TextField(blank=True, default="")),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_account",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_google_calendar_accounts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TripCalendarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("google_calendar_id", models.CharField(default="primary", max_length=255)),
                ("google_event_id", models.CharField(max_length=1024)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("imported", "Imported from Google Calendar"),
                            ("exported", "Exported to Google Calendar"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_calendar_links",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_links",
                        to="dashboard.trip",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trip_calendar_links",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "google_event_id"],
                        name="idxdb_tcl_profile_event",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "profile"),
                        name="db_trip_calendar_link_unique",
                    )
                ],
            },
        ),
    ]
