# Generated by Django 6.0.6 on 2026-07-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_dm_expansion_foundations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinmarkup",
            name="markup_type",
            field=models.CharField(
                choices=[
                    ("line", "Line"),
                    ("arrow", "Arrow"),
                    ("text", "Text"),
                    ("square", "Square"),
                    ("circle", "Circle"),
                    ("polygon", "Polygon"),
                    ("pin", "Pin"),
                ],
                max_length=20,
            ),
        ),
    ]
