# Generated by Django 6.0.6 on 2026-07-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_parcel_scope_pin_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pin",
            old_name="buildings_offer_dismissed",
            new_name="restructure_offer_dismissed",
        ),
        migrations.AddField(
            model_name="profile",
            name="suggest_pin_restructure",
            field=models.BooleanField(
                default=True,
                help_text="Offer to organize pins into buildings and sub pins when you open a property that has several.",
            ),
        ),
    ]
