# Generated by Django 6.0.6 on 2026-07-10 23:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_google_calendar_sync"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("recipient_hash", models.CharField(max_length=64)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("join_invite", "Friend invitation"),
                            ("visit_invite", "Visit participant invitation"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_email_send_logs",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalVisitParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=100)),
                ("email_hash", models.CharField(blank=True, default="", max_length=64)),
                ("invite_sent", models.BooleanField(default=False)),
                ("suggestion_requested", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_external_visit_participants",
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="tripcalendarlink",
            name="db_trip_calendar_link_unique",
        ),
        migrations.AddField(
            model_name="pin",
            name="source_share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pins_created",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="parent_share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reshares",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_limit_per_day",
            field=models.IntegerField(
                default=20,
                help_text="Maximum user-triggered emails one user may send per day. Subscription roles can raise this. 0 = unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Email limit (per day)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_limit_per_hour",
            field=models.IntegerField(
                default=5,
                help_text="Maximum user-triggered emails (invitations etc.) one user may send per hour. Subscription roles can raise this. 0 = unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Email limit (per hour)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_limit_per_month",
            field=models.IntegerField(
                default=100,
                help_text="Maximum user-triggered emails one user may send per 30 days. Subscription roles can raise this. 0 = unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Email limit (per month)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="email_limit_per_day",
            field=models.IntegerField(
                blank=True,
                help_text="Max user-triggered emails per day for this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="email_limit_per_hour",
            field=models.IntegerField(
                blank=True,
                help_text="Max user-triggered emails per hour for this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="email_limit_per_month",
            field=models.IntegerField(
                blank=True,
                help_text="Max user-triggered emails per 30 days for this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tripcalendarlink",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_links",
                to="dashboard.tripactivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("email_limit_per_hour__gte", 0)),
                name="email_limit_per_hour_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("email_limit_per_day__gte", 0)),
                name="email_limit_per_day_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("email_limit_per_month__gte", 0)),
                name="email_limit_per_month_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripcalendarlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("activity__isnull", True)),
                fields=("trip", "profile"),
                name="db_trip_calendar_link_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripcalendarlink",
            constraint=models.UniqueConstraint(
                fields=("trip", "profile", "activity"),
                name="db_trip_calendar_link_activity_unique",
            ),
        ),
        migrations.AddField(
            model_name="emailsendlog",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_send_logs",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="externalvisitparticipant",
            name="matched_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_visit_participations",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="externalvisitparticipant",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_participants",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AddIndex(
            model_name="emailsendlog",
            index=models.Index(
                fields=["sender", "created"], name="idxdb_esl_sender_created"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsendlog",
            index=models.Index(
                fields=["sender", "recipient_hash"], name="idxdb_esl_sender_recipient"
            ),
        ),
        migrations.AddIndex(
            model_name="externalvisitparticipant",
            index=models.Index(fields=["email_hash"], name="idxdb_evp_email_hash"),
        ),
        migrations.AddIndex(
            model_name="externalvisitparticipant",
            index=models.Index(fields=["visit"], name="idxdb_evp_visit"),
        ),
    ]
