# Generated by Django 6.0.6 on 2026-07-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depends on the latest *committed* migration, not the untracked
        # 0011_trivia_wiki_incorporation_setting.py sitting in this checkout from
        # another in-progress change - see CLAUDE.md's migration-dependency gotcha.
        # (The ai_article_expansion_enabled/ai_article_safety_enabled SiteSettings
        # fields auto-detected alongside this migration are that same in-progress
        # work's model changes, already missing their own migration independent of
        # anything here - deliberately not bundled into this one.)
        ("dashboard", "0010_v0_6_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetycheckin",
            name="archive_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="resolved_by_label",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.CreateModel(
            name="SafetyCheckinArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ciphertext", models.TextField()),
                ("nonce", models.CharField(max_length=64)),
                ("sealed_key", models.TextField()),
                ("key_bundle_version", models.PositiveIntegerField()),
                ("encrypted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive",
                        to="dashboard.safetycheckin",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_safety_checkin_archives",
                "abstract": False,
            },
        ),
    ]
