# Generated by Django 6.0.6 on 2026-07-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_image_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="unlogged_visit_dismissed",
            field=models.BooleanField(default=False),
        ),
    ]
