# Generated by Django 5.0.1 on 2024-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_location_cached_place_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("church", "church"),
                    ("factory", "factory"),
                    ("home", "home"),
                    ("hospital", "hospital"),
                    ("school", "school"),
                    ("warehouse", "warehouse"),
                    ("office_building", "office_building"),
                    ("shopping_mall", "shopping_mall"),
                    ("hotel", "hotel"),
                    ("stadium", "stadium"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, default=list, to="dashboard.location"
                    ),
                ),
                (
                    "profiles",
                    models.ManyToManyField(
                        blank=True, related_name="trips", to="dashboard.profile"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trips",
                "get_latest_by": "updated",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="dashboard_t_name_73c472_idx"),
                    models.Index(
                        fields=["start_date"], name="dashboard_t_start_d_978a04_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="dashboard_t_end_dat_1dca64_idx"
                    ),
                ],
            },
        ),
    ]
