# Generated by Django 6.0.6 on 2026-07-12 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_pinmarkup_markup_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountKdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("auth_salt", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "dashboard_account_kdf",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConversationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("wrapped_for_low", models.TextField()),
                ("wrapped_for_high", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "dashboard_e2ee_conversation_key",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessagingKeyBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("public_key", models.CharField(max_length=128)),
                ("password_wrapped_secret", models.TextField(blank=True, default="")),
                (
                    "password_wrap_salt",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("password_wrap_stale", models.BooleanField(default=False)),
                ("recovery_wrapped_secret", models.TextField()),
                ("kdf_opslimit", models.IntegerField(default=2)),
                ("kdf_memlimit", models.IntegerField(default=67108864)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "dashboard_e2ee_key_bundle",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="directmessage",
            name="ciphertext",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="key_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="nonce",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="body",
            field=models.TextField(blank=True, default="", max_length=5000),
        ),
        migrations.AddConstraint(
            model_name="directmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("body", ""), ("ciphertext", ""), _connector="OR"),
                name="db_dm_body_xor_ciphertext",
            ),
        ),
        migrations.AddField(
            model_name="accountkdf",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_kdf",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversationkey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversation_keys_created",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="conversationkey",
            name="profile_high",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_keys_high",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="conversationkey",
            name="profile_low",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_keys_low",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="messagingkeybundle",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messaging_key_bundle",
                to="dashboard.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationkey",
            index=models.Index(
                fields=["profile_low", "profile_high"], name="idxdb_e2ee_convkey_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationkey",
            constraint=models.UniqueConstraint(
                fields=("profile_low", "profile_high", "version"),
                name="db_e2ee_convkey_pair_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationkey",
            constraint=models.CheckConstraint(
                condition=models.Q(("profile_low__lt", models.F("profile_high"))),
                name="db_e2ee_convkey_canonical_order",
            ),
        ),
    ]
