# Generated by Django 6.0.6 on 2026-07-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_child_pin_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("pin_uuid", models.UUIDField(editable=False, unique=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_tombstones",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_tombstones",
                "ordering": ["created"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "created"], name="idxdb_pintomb_prof_created"
                    )
                ],
            },
        ),
    ]
