# Generated by Django 6.0.6 on 2026-07-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # NOTE: depends on 0010, not the numerically-adjacent 0011, because
        # 0011_sitesettings_boundary_cache_days is untracked (another
        # in-progress session's work) as of when this migration was written -
        # see CLAUDE.md's migration-dependency gotcha. Repoint at 0011 once it
        # is committed, if it lands before this one does.
        ("dashboard", "0010_boundaryvote_consensusanswer_consensusprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinMergeSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            (
                                "legacy_cid_collision",
                                "Legacy CID coordinate repair collision",
                            )
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="", max_length=500)),
                (
                    "pin_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_suggestions_as_a",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "pin_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_suggestions_as_b",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_merge_suggestions",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "suggested_survivor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.pin",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_merge_suggestions",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "status"], name="idxdb_pin_merge_sugg_status"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pin_a", models.F("pin_b")), _negated=True),
                        name="db_pin_merge_suggestion_distinct_pins",
                    )
                ],
            },
        ),
    ]
