# Generated by Django 6.0.6 on 2026-07-31 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_api_rate_limit_min_interval"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinImportFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("cid", models.DecimalField(decimal_places=0, max_digits=20)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=50000,
                        validators=[django.core.validators.MaxLengthValidator(50000)],
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (
                                "no_location_found",
                                "Google has no location data for this place",
                            ),
                            ("lookup_stalled", "Lookup didn't finish in time"),
                            ("lookup_error", "Location lookup service was unreachable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_failure",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_import_failures",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_import_failures",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "status"],
                        name="idxdb_pin_import_fail_status",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "cid"),
                        name="uq_pin_import_failure_profile_cid",
                    )
                ],
            },
        ),
    ]
