# Generated by Django 6.0.6 on 2026-07-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_emailsendlog_externalvisitparticipant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="comment_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="friends",
                help_text="Who can see your contact methods (phone, Signal, Discord, etc.).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="friend_request_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_upload_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                help_text="Who can see the photos you upload to locations.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="trip_pin_location_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                help_text="When you share one of your pins as a trip activity, who can see the actual location? Members outside this setting will only see the pin name.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="viewer_photo_filter",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anything_in_common",
                help_text="Whose photos you want to see. Photos from users outside this setting will be blurred.",
                max_length=20,
            ),
        ),
    ]
