# Generated by Django 6.0.6 on 2026-07-31 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_pin_import_failures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitsuggestion",
            name="origin_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_suggestions",
                to="dashboard.image",
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="origin_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions_sent",
                to="dashboard.pinvisit",
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="safety_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_suggestions",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AlterField(
            model_name="visitsuggestion",
            name="trip_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_suggestions",
                to="dashboard.tripactivity",
            ),
        ),
    ]
