# Generated by Django 6.0.6 on 2026-07-23 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_pintombstone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("unifiedpush", "UnifiedPush endpoint (e.g. ntfy)"),
                            ("fcm", "Firebase Cloud Messaging token"),
                        ],
                        default="unifiedpush",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_push_devices",
                "ordering": ["-created"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "revoked_at"],
                        name="idxdb_pushdev_prof_revoked",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "address"),
                        name="db_push_device_unique_address",
                    )
                ],
            },
        ),
    ]
