# Generated by Django 6.0.6 on 2026-07-08 22:43

from django.db import migrations, models

OLD_DEFAULT = (
    "Hi! I'm heading out and set up this automatic check-in as a precaution. If you're seeing this, "
    "I haven't checked in by my expected time - please try to reach me, and if you can't, take a look "
    "at my trip plan and last known destination below to help figure out where I might be."
)

NEW_DEFAULT = (
    "Hi! Before heading out, I set up an automated safety check-in: if I don't confirm I'm safe by "
    "my expected return time, this message is sent to my emergency contacts. If you're reading it, "
    "I'm overdue and may need help - please try to reach me, and if you can't, use the trip plan and "
    "destination included with this alert to help figure out where I might be."
)


def upgrade_unchanged_defaults(apps, schema_editor):
    """Swap the new default text into preferences the user never customized."""
    SafetyPreference = apps.get_model("dashboard", "SafetyPreference")
    SafetyPreference.objects.filter(default_message=OLD_DEFAULT).update(default_message=NEW_DEFAULT)


def downgrade_unchanged_defaults(apps, schema_editor):
    """Restore the previous default text on preferences still holding the new one."""
    SafetyPreference = apps.get_model("dashboard", "SafetyPreference")
    SafetyPreference.objects.filter(default_message=NEW_DEFAULT).update(default_message=OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_pin_unlogged_visit_dismissed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetypreference",
            name="default_message",
            field=models.TextField(
                blank=True,
                default=NEW_DEFAULT,
            ),
        ),
        migrations.RunPython(upgrade_unchanged_defaults, downgrade_unchanged_defaults),
    ]
