# Generated by Django 6.0.6 on 2026-07-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Depends on the latest *committed* migration, not the untracked
        # 0011_trivia_wiki_incorporation_setting.py / 0012_safety_checkin_archive.py
        # sitting in this checkout from another in-progress session - see
        # CLAUDE.md's migration-dependency gotcha (0012 itself follows the same
        # convention, for the same reason).
        ("dashboard", "0010_v0_6_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetycheckin",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_checkins",
                to="dashboard.trip",
            ),
        ),
        migrations.RemoveIndex(
            model_name="safetycheckin",
            name="idxdb_sc_profile_status",
        ),
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(fields=["profile", "trip", "status"], name="idxdb_sc_profile_trip_status"),
        ),
    ]
