# Generated by Django 6.0.6 on 2026-07-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_notificationpreference_added_to_trip_sms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripmembership",
            name="status",
            field=models.CharField(
                choices=[("invited", "Invited"), ("joined", "Joined")],
                default="joined",
                max_length=20,
            ),
        ),
    ]
