# Generated by Django 5.1.6 on 2025-03-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_category_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="Pin",
        ),
    ]
