# Generated by Django 6.0.6 on 2026-07-25

from django.db import migrations, models


def _backfill_intro_seen(apps, schema_editor):
    """Mark the new-user map dialog as already seen for every existing profile.

    ``map_pin_suggestions_intro_seen`` defaults to False so it only appears
    for accounts created after this migration - existing users should never
    be nagged with a "new" onboarding dialog on their next map visit.
    """
    Profile = apps.get_model("dashboard", "Profile")
    Profile.objects.update(map_pin_suggestions_intro_seen=True)


class Migration(migrations.Migration):
    dependencies = [
        # Merges the three parallel leaves left by concurrent in-progress
        # sessions (see 0012/0013's own dependency comments for how this
        # happened) - a migration may depend on more than one parent instead
        # of needing a separate empty --merge migration.
        ("dashboard", "0011_trivia_wiki_incorporation_setting"),
        ("dashboard", "0012_safety_checkin_archive"),
        ("dashboard", "0013_safety_checkin_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pin_suggestions_enabled",
            field=models.BooleanField(default=True, help_text="Suggest pins based on your photos, public locations, and connected apps."),
        ),
        migrations.AddField(
            model_name="profile",
            name="suggest_pins_from_photos",
            field=models.BooleanField(default=True, help_text="Suggest pins found by scanning your Immich library or local photo folders."),
        ),
        migrations.AddField(
            model_name="profile",
            name="suggest_pins_from_external_apis",
            field=models.BooleanField(default=True, help_text="Suggest pins submitted by connected external apps."),
        ),
        migrations.AddField(
            model_name="profile",
            name="map_pin_suggestions_intro_seen",
            field=models.BooleanField(default=False, help_text="Internal: whether the new-user pin-suggestions intro dialog has been shown on the map."),
        ),
        migrations.RunPython(_backfill_intro_seen, migrations.RunPython.noop),
    ]
