# Generated by Django 6.0.6 on 2026-07-23 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsuggestion",
            name="suggested_aliases",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="pinsuggestion",
            name="suggested_description",
            field=models.TextField(
                blank=True,
                default="",
                max_length=50000,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
        migrations.AddField(
            model_name="pinsuggestion",
            name="suggested_links",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="pinsuggestion",
            name="suggested_pin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("location", "Location"),
                    ("parcel", "Property / Parcel"),
                    ("building", "Building"),
                    ("entrance", "Entrance"),
                    ("poi", "Point of Interest"),
                    ("danger", "Danger"),
                    ("other", "Other"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="source",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("yelp", "Yelp"),
                    ("google_images", "Google Images"),
                    ("google_maps", "Google Maps"),
                    ("wikimedia", "Wikimedia Commons"),
                    ("wikipedia_media", "Wikipedia"),
                    ("smithsonian", "Smithsonian Open Access"),
                    ("library_of_congress", "Library of Congress"),
                    ("internet_archive", "Internet Archive"),
                    ("immich", "Immich"),
                    ("flickr", "Flickr"),
                    ("google_photos", "Google Photos"),
                    ("loopnet", "LoopNet"),
                    ("cris", "NY Historic Preservation (CRIS)"),
                    ("external_api", "External app"),
                ],
                default="upload",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pinsuggestion",
            name="origin",
            field=models.CharField(
                choices=[
                    ("immich", "Immich library scan"),
                    ("local_scan", "Local folder scan"),
                    ("external_api", "External app"),
                ],
                max_length=20,
            ),
        ),
    ]
