# Generated by Django 6.0.6 on 2026-07-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_safetypreference_default_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_name_source_priority",
            field=models.CharField(
                blank=True,
                default="google_places,wikipedia,nps",
                help_text="Comma-separated name-provider slugs, highest priority first, used to pick a location's official name from external candidates. Sources not listed rank last, in plugin order. Blank = plugin order only.",
                max_length=500,
                verbose_name="Name source priority",
            ),
        ),
        migrations.AlterField(
            model_name="pinalias",
            name="source",
            field=models.CharField(default="user", max_length=50),
        ),
        migrations.AlterField(
            model_name="safetypreference",
            name="default_message",
            field=models.TextField(
                blank=True,
                default="Hi! Before heading out, I went on a trip and set up an automated safety check-in: if I don't confirm I'm safe by my expected return time, this message is sent to my emergency contacts. If you're reading it, I didn't come home and may need help - please try to reach me, and if you can't, use the trip plan and destination included with this alert to help figure out where I might be. I may not be able to use my phone to contact anyone else for help, so it's important you try to help me.",
            ),
        ),
        migrations.AlterField(
            model_name="wikialias",
            name="source",
            field=models.CharField(default="user", max_length=50),
        ),
    ]
