# Generated by Django 6.0.6 on 2026-07-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_visibility_anything_in_common"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="pin",
            name="description",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="pinmarkup",
            name="label",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="tripactivity",
            name="notes",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="tripcomment",
            name="text",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="description",
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
