# Generated by Django 6.0.6 on 2026-07-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_first_party_oauth_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="client_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="client_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="directmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_uuid__isnull", False)),
                fields=("sender", "client_uuid"),
                name="db_dm_unique_client_uuid_per_sender",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_uuid__isnull", False)),
                fields=("sender", "client_uuid"),
                name="db_gmsg_unique_client_uuid_per_sender",
            ),
        ),
    ]
