# Generated by Django 6.0.6 on 2026-07-25 19:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_pin_suggestion_settings"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pinowner",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("pin"),
                name="uq_pinowner_pin_name_ci",
            ),
        ),
    ]
