# Generated by Django 6.0.6 on 2026-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_boundary_generated_from_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="wiki",
            name="officially_created",
            field=models.BooleanField(default=True),
        ),
    ]
