# Generated by Django 6.0.6 on 2026-07-12 07:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_trip_membership_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=10000),
                ),
                ("is_smart", models.BooleanField(default=False)),
                ("smart_filter", models.JSONField(blank=True, null=True)),
                (
                    "smart_boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "markup_map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pin_list",
                        to="dashboard.markupmap",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_lists",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_lists",
                "ordering": ["-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PinListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "added_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manually added"),
                            ("smart_filter", "Smart filter match"),
                            ("boundary", "Inside boundary"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_memberships",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "pin_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dashboard.pinlist",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_list_items",
                "ordering": ["order", "created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("criteria", models.JSONField(default=dict)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_saved_filters",
                "ordering": ["order", "-created"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="pinlist",
            index=models.Index(fields=["profile"], name="idxdb_pinlist_profile"),
        ),
        migrations.AddConstraint(
            model_name="pinlist",
            constraint=models.UniqueConstraint(
                fields=("profile", "name"), name="uq_pin_list_profile_name"
            ),
        ),
        migrations.AddIndex(
            model_name="pinlistitem",
            index=models.Index(fields=["pin_list"], name="idxdb_pli_list"),
        ),
        migrations.AddIndex(
            model_name="pinlistitem",
            index=models.Index(fields=["pin"], name="idxdb_pli_pin"),
        ),
        migrations.AddConstraint(
            model_name="pinlistitem",
            constraint=models.UniqueConstraint(
                fields=("pin_list", "pin"), name="uq_pin_list_item"
            ),
        ),
        migrations.AddIndex(
            model_name="savedfilter",
            index=models.Index(fields=["profile"], name="idxdb_savedfilter_profile"),
        ),
        migrations.AddConstraint(
            model_name="savedfilter",
            constraint=models.UniqueConstraint(
                fields=("profile", "name"), name="uq_saved_filter_profile_name"
            ),
        ),
    ]
