# Generated by Django 6.0.6 on 2026-07-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_comment_text_alter_pin_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="community_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable features that allow you to interact with other users. Community wikis, Trips, and Friend Requests are included in this.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="external_apis_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow external services (weather, geocoding, place data, AI) to retrieve anonymized research data for you.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="track_pin_visits",
            field=models.BooleanField(
                default=True,
                help_text="Log visits to your pins from journal entries, imports, and photo tagging.",
            ),
        ),
        migrations.AlterField(
            model_name="safetypreference",
            name="default_message",
            field=models.TextField(
                blank=True,
                default="Hi! I went on a trip and set up an automated safety check-in: if I don't confirm I'm safe by my expected return time, this message is sent to my emergency contacts. If you're reading this, I didn't come home and may need help - please try to reach me, and if you can't, use the trip plan included with this alert to help find me. I may not be able to use my phone to contact anyone else for help, so it's important you try to help me.",
            ),
        ),
    ]
