# Generated by Django 5.1.6 on 2026-05-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_pin_custom_icon_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"get_latest_by": "updated", "ordering": ["-order", "name"]},
        ),
        migrations.RenameIndex(
            model_name="tag",
            new_name="dashboard_t_profile_1073fa_idx",
            old_name="dashboard_tag_profile_idx",
        ),
        migrations.RenameIndex(
            model_name="tag",
            new_name="dashboard_t_profile_a6ab65_idx",
            old_name="dashboard_tag_profile_order_idx",
        ),
    ]
