# Generated by Django 5.1.6 on 2026-05-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="categories",
            field=models.ManyToManyField(
                blank=True, default=list, related_name="pins", to="dashboard.category"
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="tags",
            field=models.ManyToManyField(
                blank=True, default=list, related_name="pins", to="dashboard.tag"
            ),
        ),
    ]
