# Generated by Django 6.0.6 on 2026-07-12 15:58

import django.db.models.deletion
import urbanlens.dashboard.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_pinlist_pinlistitem_savedfilter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmichAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "server_url",
                    models.URLField(
                        help_text="Base URL of the user's Immich server, e.g. https://photos.example.com",
                        max_length=500,
                    ),
                ),
                ("api_key", urbanlens.dashboard.models.fields.EncryptedTextField()),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_verified",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the credentials were last confirmed to work.",
                        null=True,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immich_account",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_immich_accounts",
                "abstract": False,
            },
        ),
    ]
