# Generated by Django 6.0.6 on 2026-07-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_backfill_current_name_aliases"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="visitsuggestion",
            name="db_visit_suggestion_exactly_one_origin",
        ),
        migrations.AddField(
            model_name="visitsuggestion",
            name="from_my_activity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="visitsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("origin_visit__isnull", False),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", True),
                        ("origin_image__isnull", True),
                        ("from_my_activity", False),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", False),
                        ("safety_checkin__isnull", True),
                        ("origin_image__isnull", True),
                        ("from_my_activity", False),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", False),
                        ("origin_image__isnull", True),
                        ("from_my_activity", False),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", True),
                        ("origin_image__isnull", False),
                        ("from_my_activity", False),
                    ),
                    models.Q(
                        ("origin_visit__isnull", True),
                        ("trip_activity__isnull", True),
                        ("safety_checkin__isnull", True),
                        ("origin_image__isnull", True),
                        ("from_my_activity", True),
                    ),
                    _connector="OR",
                ),
                name="db_visit_suggestion_exactly_one_origin",
            ),
        ),
    ]
