# Generated by Django 6.0.6 on 2026-07-11 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_profile_community_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                max_length=10000,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=10000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="pinmarkup",
            name="label",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=10000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="tripactivity",
            name="notes",
            field=models.TextField(
                blank=True,
                max_length=10000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="tripcomment",
            name="text",
            field=models.TextField(
                max_length=10000,
                validators=[django.core.validators.MaxLengthValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=20000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(20000)],
            ),
        ),
    ]
