# Generated by Django 6.0.6 on 2026-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_wiki_officially_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="source",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("yelp", "Yelp"),
                    ("google_images", "Google Images"),
                    ("google_maps", "Google Maps"),
                    ("wikimedia", "Wikimedia Commons"),
                    ("wikipedia_media", "Wikipedia"),
                    ("smithsonian", "Smithsonian Open Access"),
                    ("library_of_congress", "Library of Congress"),
                    ("internet_archive", "Internet Archive"),
                    ("immich", "Immich"),
                    ("flickr", "Flickr"),
                    ("google_photos", "Google Photos"),
                    ("loopnet", "LoopNet"),
                    ("cris", "NY Historic Preservation (CRIS)"),
                    ("external_api", "External app"),
                    ("google_street_view", "Google Street View"),
                    ("google_satellite", "Google Satellite"),
                ],
                default="upload",
                max_length=30,
            ),
        ),
    ]
