# Generated by Django 6.0.6 on 2026-07-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_notificationlog_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinnote",
            name="text",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="notes",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
