# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Originally generated depending on 0014 (the latest *committed* migration at
        # the time - see CLAUDE.md's migration-dependency gotcha), since
        # 0015_pinowner_unique_name_per_pin.py was untracked in this checkout from a
        # concurrent in-progress change and so invisible to makemigrations. Both ended
        # up as sibling leaves off 0014 once both landed in the same working tree -
        # resequenced here (rather than a merge migration) since neither has been
        # pushed/deployed anywhere yet, same resolution CLAUDE.md documents for the
        # analogous 2026-07-25 0027_* incident. Index creation belongs dead last in a
        # migration chain anyway, so 0015's unique constraint correctly precedes this.
        ("dashboard", "0015_pinowner_unique_name_per_pin"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="safetycheckin",
            index=models.Index(fields=["archive_scheduled_at"], name="idxdb_sc_archive_scheduled_at"),
        ),
    ]
