# Generated by Django 6.0.6 on 2026-07-12 16:11

import urbanlens.dashboard.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_immich_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlecalendaraccount",
            name="access_token",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="googlecalendaraccount",
            name="refresh_token",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="notify_gotify_token",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Gotify application token used to authenticate pushes to the server above. Defaults to the UL_GOTIFY_TOKEN environment variable.",
                verbose_name="Gotify app token",
            ),
        ),
    ]
