# Generated by Django 6.0.6 on 2026-07-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_safety_checkin_archive_scheduled_at_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessionparticipant",
            name="rating_delta",
            field=models.FloatField(default=0.0),
        ),
    ]
