# Generated by Django 6.0.6 on 2026-07-11 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_alter_comment_text_alter_pin_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinshare",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="pin_shares", to="dashboard.image"
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="message",
            field=models.TextField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="shared_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
