# Generated by Django 6.0.6 on 2026-07-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_alter_pinnote_text_alter_pinvisit_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pinnote",
            options={"ordering": ["-created", "-pk"]},
        ),
    ]
