# Generated by Django 6.0.6 on 2026-08-01 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_add_google_street_view_satellite_image_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("#F44336", "Red"),
                            ("#E91E63", "Pink"),
                            ("#9C27B0", "Purple"),
                            ("#673AB7", "Deep Purple"),
                            ("#3F51B5", "Indigo"),
                            ("#2196F3", "Blue"),
                            ("#03A9F4", "Light Blue"),
                            ("#00BCD4", "Cyan"),
                            ("#009688", "Teal"),
                            ("#4CAF50", "Green"),
                            ("#8BC34A", "Light Green"),
                            ("#CDDC39", "Lime"),
                            ("#FFEB3B", "Yellow"),
                            ("#FFC107", "Amber"),
                            ("#FF9800", "Orange"),
                            ("#FF5722", "Deep Orange"),
                            ("#795548", "Brown"),
                            ("#607D8B", "Blue Grey"),
                            ("#9E9E9E", "Grey"),
                            ("#FFFFFF", "White"),
                            ("#000000", "Black"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("layers", "Layers"),
                            ("route", "Route"),
                            ("terrain", "Terrain"),
                            ("warning", "Warning"),
                            ("explore", "Explore"),
                            ("place", "Place"),
                            ("hiking", "Hiking"),
                            ("construction", "Construction"),
                            ("water", "Water"),
                            ("landscape", "Landscape"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("default_visible", models.BooleanField(default=False)),
                (
                    "parent_pin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_layers",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "parent_wiki",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_layers",
                        to="dashboard.wiki",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_layers",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_custom_layers",
                "ordering": ["order", "created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pinmarkup",
            name="layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="dashboard.customlayer",
            ),
        ),
        migrations.AddIndex(
            model_name="pinmarkup",
            index=models.Index(fields=["layer"], name="idxdb_pm_layer"),
        ),
        migrations.AddIndex(
            model_name="customlayer",
            index=models.Index(fields=["parent_pin"], name="idxdb_cl_pin"),
        ),
        migrations.AddIndex(
            model_name="customlayer",
            index=models.Index(fields=["parent_wiki"], name="idxdb_cl_wiki"),
        ),
        migrations.AddIndex(
            model_name="customlayer",
            index=models.Index(fields=["profile"], name="idxdb_cl_profile"),
        ),
    ]
