# Generated by Django 6.0.6 on 2026-07-24 04:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import urbanlens.dashboard.models.spotguessr.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_ai_trip_suggestions_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("photos", "Photos"),
                            ("named_place", "Named Place"),
                            ("street_view", "Street View"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("total_rounds", models.PositiveSmallIntegerField(default=5)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "host_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_spotguessr_sessions",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_sessions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sequence_index", models.PositiveSmallIntegerField()),
                ("target_is_point", models.BooleanField(default=False)),
                (
                    "target_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spotguessr_rounds",
                        to="dashboard.image",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotguessr_rounds",
                        to="dashboard.location",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="dashboard.gamesession",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_rounds",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameSessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotguessr_participations",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="dashboard.gamesession",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_session_participants",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "guess_point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("distance_meters", models.FloatField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("guessed_date", models.DateField(blank=True, null=True)),
                ("date_points", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotguessr_guesses",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="dashboard.gameround",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_guesses",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationModeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("photos", "Photos"),
                            ("named_place", "Named Place"),
                            ("street_view", "Street View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mu", models.FloatField(default=0.0)),
                ("phi", models.FloatField(default=2.014761872416068)),
                ("sigma", models.FloatField(default=0.06)),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotguessr_ratings",
                        to="dashboard.location",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_location_ratings",
                "abstract": False,
            },
            bases=(
                urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PlayerModeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("photos", "Photos"),
                            ("named_place", "Named Place"),
                            ("street_view", "Street View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mu", models.FloatField(default=0.0)),
                ("phi", models.FloatField(default=2.014761872416068)),
                ("sigma", models.FloatField(default=0.06)),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("last_played_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotguessr_ratings",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_player_ratings",
                "abstract": False,
            },
            bases=(
                urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SpotGuessrPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("show_ratings_to_friends", models.BooleanField(default=True)),
                ("last_config", models.JSONField(default=dict)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotguessr_preference",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_preferences",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="gameround",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence_index"), name="db_sg_round_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamesessionparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "profile"), name="db_sg_participant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="guess",
            constraint=models.UniqueConstraint(
                fields=("round", "profile"), name="db_sg_guess_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationmoderating",
            constraint=models.UniqueConstraint(
                fields=("location", "mode"), name="db_sg_location_rating_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="playermoderating",
            constraint=models.UniqueConstraint(
                fields=("profile", "mode"), name="db_sg_player_rating_unique"
            ),
        ),
    ]
