# Generated by Django 5.1.6 on 2025-03-01 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_rename_location_pin_point_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="location",
            new_name="pin",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="location",
            new_name="pin",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="location",
            new_name="area",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="location",
            new_name="pin",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="locations",
            new_name="pins",
        ),
        migrations.AlterField(
            model_name="pin",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pins",
                to="dashboard.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "pin")},
        ),
    ]
