# Generated by Django 6.0.6 on 2026-07-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_spotguessr_participant_rating_delta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triviasessionparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("joined", "Joined"),
                    ("left", "Left"),
                ],
                default="joined",
                max_length=10,
            ),
        ),
    ]
