# Generated by Django 6.0.6 on 2026-07-28 01:52
#
# friend_request_visibility's default changes from ANYTHING_IN_COMMON to
# ANYONE: invite_by_email's unregistered-address branch always sends the
# invitation, so the old default made having an account harder to reach by
# friend request than not having one. See models/profile/model.py's comment
# on the field.
#
# The AlterField only changes what *new* profiles get - existing rows keep
# whatever is already stored. The RunPython backfills any row still at the
# old default, on the same reasoning as 0002/0003's welcome_onboarding_complete
# backfill: a row at the default was never deliberately changed by its owner,
# so it should follow the default forward. A row at any other choice
# (including one a user deliberately set back to ANYTHING_IN_COMMON) is left
# alone.

from django.db import migrations, models


def backfill_unchanged_default(apps, schema_editor):
    Profile = apps.get_model("dashboard", "Profile")
    Profile.objects.filter(friend_request_visibility="anything_in_common").update(friend_request_visibility="anyone")


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_alter_pinnote_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="friend_request_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="anyone",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            code=backfill_unchanged_default,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
