# Generated by Django 6.0.6 on 2026-07-09 03:03

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def _backfill_vip_storage_quota(apps, schema_editor):
    """Give the pre-existing built-in VIP role its default 500 GB quota.

    Only rows still at NULL are touched, so an admin who later blanks the quota
    (meaning "use the site default") is not re-overridden by ensure_defaults -
    that helper only sets the quota when it creates the role.
    """
    SubscriptionRole = apps.get_model("dashboard", "SubscriptionRole")
    SubscriptionRole.objects.filter(slug="vip", storage_quota_gb__isnull=True).update(storage_quota_gb=500)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_notificationpreference_wiki_safety_checkin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="exif_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="image_downscale_max_dimension",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_convert_webp",
            field=models.BooleanField(
                default=False,
                help_text="Re-encode processed uploads as WebP for additional storage savings. Original EXIF metadata is preserved on the image record.",
                verbose_name="Convert uploads to WebP",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_downscale_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Downscale uploaded photos that exceed the maximum dimension below, to save storage space.",
                verbose_name="Downscale uploaded photos",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_downscale_max_dimension",
            field=models.IntegerField(
                default=1920,
                help_text="Longest edge (pixels) uploaded photos are downscaled to when downscaling is enabled. 1920px keeps plenty of detail for screens while reducing the size of a modern phone photo to roughly 1/8th.",
                validators=[
                    django.core.validators.MinValueValidator(256),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name="Max photo dimension (px)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_downscale_vip",
            field=models.BooleanField(
                default=False,
                help_text="Also downscale/convert uploads from users with an active subscription. When off, subscribers keep their original files (unless they opt into downscaling themselves).",
                verbose_name="Downscale subscriber uploads",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="storage_quota_gb",
            field=models.IntegerField(
                default=10,
                help_text="Storage quota (GB) for photo/video uploads per regular user. Subscription roles can override this with a larger quota. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="Default storage quota (GB)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="storage_quota_gb",
            field=models.IntegerField(
                blank=True,
                help_text="Storage quota (GB) for users with this role. Blank uses the site default; 0 means unlimited.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("storage_quota_gb__gte", 0)),
                name="storage_quota_gb_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("image_downscale_max_dimension__gte", 256)),
                name="image_downscale_max_dim_gte_256",
            ),
        ),
        migrations.RunPython(_backfill_vip_storage_quota, migrations.RunPython.noop),
    ]
