# Generated by Django 6.0.6 on 2026-08-01 23:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import urbanlens.dashboard.models.achievements.model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_custom_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="achievement_earned",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="achievement_earned_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="achievement_earned_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("comment_upload_failed", "Comment Upload Failed"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("safety_ci_partner_invite", "Safety Check-in Partner Request"),
                    ("safety_ci_partner_accepted", "Safety Check-in Partner Accepted"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("friend_suggestion", "Friend Suggestion"),
                    ("spotguessr_invite", "SpotGuessr Invitation"),
                    ("trivia_invite", "Trivia Invitation"),
                    ("consensus_invite", "Consensus Invitation"),
                    ("pin_import_complete", "Pin Import Complete"),
                    ("achievement_earned", "Achievement Unlocked"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metric",
                    models.CharField(
                        choices=urbanlens.dashboard.models.achievements.model.metric_choices,
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("threshold", models.PositiveIntegerField(default=1)),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="trophy", max_length=50, null=True
                    ),
                ),
                (
                    "custom_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievement_icons/"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#FFC107",
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex colour such as #FFC107.",
                            )
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_secret", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dashboard_achievements",
                "ordering": ["order", "metric", "threshold", "name"],
                "get_latest_by": "created",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["metric", "threshold"], name="idxdb_achv_metric_thresh"
                    ),
                    models.Index(fields=["is_active"], name="idxdb_achv_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileActivityDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "Logged in"),
                            ("photo", "Uploaded a photo"),
                            ("wiki_edit", "Edited a wiki"),
                            ("pin", "Pinned a spot"),
                            ("comment", "Left a comment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("day", models.DateField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_days",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_profile_activity_days",
                "ordering": ["-day"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "kind", "-day"],
                        name="idxdb_pactday_pfile_kind",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "kind", "day"),
                        name="uniq_profile_activity_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "Logged in"),
                            ("photo", "Uploaded a photo"),
                            ("wiki_edit", "Edited a wiki"),
                            ("pin", "Pinned a spot"),
                            ("comment", "Left a comment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("current_length", models.PositiveIntegerField(default=0)),
                ("longest_length", models.PositiveIntegerField(default=0)),
                ("last_day", models.DateField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaks",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_profile_streaks",
                "ordering": ["kind"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "kind"), name="uniq_profile_streak_kind"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("value_at_award", models.PositiveIntegerField(default=0)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="dashboard.achievement",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_user_achievements",
                "ordering": ["-earned_at"],
                "get_latest_by": "earned_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "-earned_at"],
                        name="idxdb_uachv_profile_date",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "achievement"),
                        name="uniq_profile_achievement",
                    )
                ],
            },
        ),
    ]
