# Generated by Django 6.0.6 on 2026-07-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_spotguessr"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameround",
            name="display_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamesessionparticipant",
            name="status",
            field=models.CharField(
                choices=[("invited", "Invited"), ("joined", "Joined")],
                default="joined",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("lobby", "Lobby"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="active",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("comment_upload_failed", "Comment Upload Failed"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("friend_suggestion", "Friend Suggestion"),
                    ("spotguessr_invite", "SpotGuessr Invitation"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="GameSessionChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.CharField(max_length=1000)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotguessr_chat_messages",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="dashboard.gamesession",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_chat_messages",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["session", "created"],
                        name="idxdb_sg_chat_session_created",
                    )
                ],
            },
        ),
    ]
