# Generated by Django 6.0.6 on 2026-07-25 22:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # NOTE: 0018_trivia_participant_left_status exists on disk but is
        # untracked (another in-progress feature's uncommitted migration,
        # per CLAUDE.md's makemigrations-dependency gotcha) - depending on
        # it here would break any other checkout that doesn't have that
        # file yet. Depend on the actual latest *committed* migration
        # instead; a merge migration will be needed once 0018 lands.
        ("dashboard", "0017_spotguessr_participant_rating_delta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsensusProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("trust_alpha", models.FloatField(default=2.0)),
                ("trust_beta", models.FloatField(default=2.0)),
                ("checks_seen", models.PositiveIntegerField(default=0)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_config", models.JSONField(default=dict)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_profile",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_profiles",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsensusRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sequence_index", models.PositiveSmallIntegerField()),
                (
                    "field_kind",
                    models.CharField(
                        choices=[
                            ("wiki_name", "Place Name"),
                            ("wiki_description", "Description"),
                            ("wiki_indoor_outdoor", "Indoor/Outdoor"),
                            ("wiki_pin_type", "Place Type"),
                            ("wiki_alias", "Alias/Nickname"),
                            ("photo_coordinates", "Photo Location"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_check_round", models.BooleanField(default=False)),
                ("known_answer_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("agreed", "Agreed"),
                            ("vote_open", "Vote Open"),
                            ("vote_resolved", "Vote Resolved"),
                            ("tentative", "Tentative"),
                            ("skipped", "Skipped"),
                            ("check_passed", "Check Passed"),
                            ("check_failed", "Check Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("vote_opened_at", models.DateTimeField(blank=True, null=True)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consensus_rounds",
                        to="dashboard.image",
                    ),
                ),
                (
                    "wiki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_rounds",
                        to="dashboard.wiki",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_rounds",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsensusAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text_value", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "normalized_text",
                    models.CharField(
                        blank=True, db_index=True, max_length=500, null=True
                    ),
                ),
                (
                    "guess_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("is_correct_for_check", models.BooleanField(null=True)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_answers",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="dashboard.consensusround",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_answers",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="wikiedit",
            name="consensus_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_edits",
                to="dashboard.consensusround",
            ),
        ),
        migrations.CreateModel(
            name="ConsensusRoundPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_round_photos",
                        to="dashboard.image",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_round_photos",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="dashboard.consensusround",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_round_photos",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsensusSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Lobby"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("total_rounds", models.PositiveSmallIntegerField(default=5)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "host_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_consensus_sessions",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_sessions",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="consensusround",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="dashboard.consensussession",
            ),
        ),
        migrations.CreateModel(
            name="ConsensusSessionChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.CharField(max_length=1000)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_chat_messages",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="dashboard.consensussession",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_chat_messages",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsensusSessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("invited", "Invited"), ("joined", "Joined")],
                        default="joined",
                        max_length=10,
                    ),
                ),
                ("total_points_this_session", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_participations",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="dashboard.consensussession",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_session_participants",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsensusTentativeAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text_value", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "normalized_text",
                    models.CharField(
                        blank=True, db_index=True, max_length=500, null=True
                    ),
                ),
                (
                    "guess_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("support_count", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("first_suggested_at", models.DateTimeField(auto_now_add=True)),
                ("last_suggested_at", models.DateTimeField(auto_now=True)),
                (
                    "field_kind",
                    models.CharField(
                        choices=[
                            ("wiki_name", "Place Name"),
                            ("wiki_description", "Description"),
                            ("wiki_indoor_outdoor", "Indoor/Outdoor"),
                            ("wiki_pin_type", "Place Type"),
                            ("wiki_alias", "Alias/Nickname"),
                            ("photo_coordinates", "Photo Location"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tentative_answers_created",
                        to="dashboard.consensusround",
                    ),
                ),
                (
                    "target_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consensus_tentative_answers",
                        to="dashboard.image",
                    ),
                ),
                (
                    "wiki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_tentative_answers",
                        to="dashboard.wiki",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_tentative_answers",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsensusVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "chosen_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_for",
                        to="dashboard.consensusanswer",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_votes",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="dashboard.consensusround",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_consensus_votes",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="consensusanswer",
            constraint=models.UniqueConstraint(
                fields=("round", "profile"), name="db_consensus_answer_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="consensusround",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence_index"), name="db_consensus_round_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="consensussessionchatmessage",
            index=models.Index(
                fields=["session", "created"],
                name="idxdb_consensus_chat_session_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="consensussessionparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "profile"), name="db_consensus_participant_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="consensustentativeanswer",
            index=models.Index(
                fields=["wiki", "field_kind"], name="idxdb_ctent_wiki_field"
            ),
        ),
        migrations.AddConstraint(
            model_name="consensustentativeanswer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("text_value"),
                models.F("wiki"),
                models.F("field_kind"),
                name="db_consensus_tentative_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="consensusvote",
            constraint=models.UniqueConstraint(
                fields=("round", "profile"), name="db_consensus_vote_unique"
            ),
        ),
    ]
