# Generated by Django 6.0.6 on 2026-07-12 16:15

import django.db.models.deletion
import urbanlens.dashboard.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_encrypt_external_tokens_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlickrAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("oauth_token", urbanlens.dashboard.models.fields.EncryptedTextField()),
                (
                    "oauth_token_secret",
                    urbanlens.dashboard.models.fields.EncryptedTextField(),
                ),
                (
                    "flickr_user_id",
                    models.CharField(
                        help_text="Flickr NSID (user id) of the connected account.",
                        max_length=64,
                    ),
                ),
                (
                    "flickr_username",
                    models.CharField(
                        blank=True,
                        help_text="Flickr username, for display only.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flickr_account",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_flickr_accounts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GooglePhotosAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "google_email",
                    models.CharField(
                        blank=True,
                        help_text="Email of the connected Google account, for display only.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    urbanlens.dashboard.models.fields.EncryptedTextField(),
                ),
                (
                    "refresh_token",
                    urbanlens.dashboard.models.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_photos_account",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_google_photos_accounts",
                "abstract": False,
            },
        ),
    ]
