# Generated by Django 6.0.6 on 2026-08-02 21:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_notificationpreference_achievement_earned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="public_costs_page_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show the public /costs/ page with the site's estimated running costs and cost-per-user. Off by default.",
                verbose_name="Public costs page",
            ),
        ),
        migrations.CreateModel(
            name="CostComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "replacement_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="One-time replacement cost in USD, e.g. 1000.00.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "deprecation_years",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Years over which the replacement cost is amortized, e.g. 10.0.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "retired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this component stopped counting toward costs. Blank means still active.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Component",
                "verbose_name_plural": "Cost Components",
                "db_table": "dashboard_cost_components",
                "ordering": ["order", "name"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["retired_at"], name="idxdb_costcmp_retired")
                ],
            },
        ),
        migrations.CreateModel(
            name="OperatingCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "monthly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Recurring monthly cost in USD, e.g. 100.00.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "retired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this cost stopped being charged. Blank means still active.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating Cost",
                "verbose_name_plural": "Operating Costs",
                "db_table": "dashboard_operating_costs",
                "ordering": ["order", "name"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["retired_at"], name="idxdb_opcost_retired")
                ],
            },
        ),
    ]
