# Generated by Django 6.0.6 on 2026-07-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_spotguessr_multiplayer"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePhotoFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("thumbs_up", "Thumbs Up"),
                            ("thumbs_down", "Thumbs Down"),
                            ("reported", "Reported"),
                            ("no_reaction", "No Reaction"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_photo_feedback",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="media_item_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="media_source_key",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("comment_upload_failed", "Comment Upload Failed"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("friend_suggestion", "Friend Suggestion"),
                    ("spotguessr_invite", "SpotGuessr Invitation"),
                    ("pin_import_complete", "Pin Import Complete"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="gamephotofeedback",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spotguessr_photo_feedback",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="gamephotofeedback",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_feedback",
                to="dashboard.gameround",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamephotofeedback",
            constraint=models.UniqueConstraint(
                fields=("round", "profile"), name="db_sg_photo_feedback_unique"
            ),
        ),
        # Index creation goes dead last in the migration chain (see this
        # project's CLAUDE.md) - all schema for the fields it covers must
        # already exist first.
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["location", "media_source_key", "media_item_key"],
                name="idxdb_image_media_key",
            ),
        ),
    ]
