# Generated by Django 6.0.6 on 2026-06-29 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_api_rate_limit_api_call_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicalllog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="apiratelimit",
            name="calls_per_day",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum calls allowed per calendar day (UTC). Leave blank for no daily limit.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="apiratelimit",
            name="calls_per_minute",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum calls allowed per rolling minute. Leave blank for no per-minute limit.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="apiratelimit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
