# Generated by Django 6.0.6 on 2026-07-12 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_flickr_google_photos_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkupMapShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_markup_map_shares",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="markupmap",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="markupmap",
            name="shared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="inferred_source_share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pins_inferred",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="detected_via_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detected_pin_shares",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="markup_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pin_share_attachments",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="origin",
            field=models.CharField(
                choices=[
                    ("explicit", "Explicit Share"),
                    ("map_detected", "Detected From Shared Map"),
                ],
                default="explicit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("already_pinned", "Already pinned"),
                    ("detected", "Detected From Shared Map"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="markupmap",
            index=models.Index(
                fields=["profile", "cloned_from"], name="idxdb_mm_profile_clonedfrom"
            ),
        ),
        migrations.AddConstraint(
            model_name="pinshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin", "map_detected")),
                fields=("pin", "to_profile"),
                name="db_pinshare_one_detected_per_pin_user",
            ),
        ),
        migrations.AddField(
            model_name="markupmapshare",
            name="from_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_map_shares",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="markupmapshare",
            name="markup_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="markupmapshare",
            name="notification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_share",
                to="dashboard.notificationlog",
            ),
        ),
        migrations.AddField(
            model_name="markupmapshare",
            name="to_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_map_shares",
                to="dashboard.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="markupmapshare",
            index=models.Index(fields=["to_profile"], name="idxdb_mms_to_profile"),
        ),
        migrations.AddIndex(
            model_name="markupmapshare",
            index=models.Index(fields=["markup_map"], name="idxdb_mms_markup_map"),
        ),
    ]
