# Generated by Django 6.0.6 on 2026-07-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_trivia_participant_left_status"),
        ("dashboard", "0019_consensus"),
    ]

    operations = []
