# Generated by Django 6.0.6 on 2026-07-09 06:24

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_profile_deletion_reminder_sent_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="search_cache_hours",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="external_data_cache_days",
            field=models.IntegerField(
                default=7,
                help_text="Minimum number of days to cache external API responses before they are considered stale and re-fetched. Applies to every shared, Location-scoped external data source (Wikipedia, NPS, LoopNet, USGS, Nominatim, media archives, Google Places, web search, and satellite/street view imagery).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="External data cache (days)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="image_convert_webp",
            field=models.BooleanField(
                default=False,
                help_text="Re-encode processed uploads as WebP for additional storage savings.",
                verbose_name="Convert uploads to WebP",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="image_downscale_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Downscale uploaded photos that exceed the maximum dimension below, to save storage space. The original EXIF metadata is always preserved on the image record.",
                verbose_name="Downscale uploaded photos",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("external_data_cache_days__gte", 1)),
                name="external_data_cache_days_gte_1",
            ),
        ),
    ]
