# Generated by Django 6.0.6 on 2026-07-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_map_sharing_and_pin_share_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="source",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("yelp", "Yelp"),
                    ("google_images", "Google Images"),
                    ("google_maps", "Google Maps"),
                    ("wikimedia", "Wikimedia Commons"),
                    ("smithsonian", "Smithsonian Open Access"),
                    ("library_of_congress", "Library of Congress"),
                    ("immich", "Immich"),
                    ("flickr", "Flickr"),
                    ("google_photos", "Google Photos"),
                ],
                default="upload",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pin",
            name="cover_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pin_covers",
                to="dashboard.image",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="media_gallery_sort",
            field=models.CharField(
                choices=[("relevant", "Relevant first"), ("recent", "Most recent")],
                default="relevant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_wiki_cover_photos",
            field=models.BooleanField(
                default=True,
                help_text="Show the community-selected cover photo banner on wiki pages.",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="cover_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_covers",
                to="dashboard.image",
            ),
        ),
        migrations.CreateModel(
            name="MediaRelevance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=30)),
                ("item_key", models.CharField(max_length=40)),
                ("is_relevant", models.BooleanField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_relevance_marks",
                        to="dashboard.location",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_relevance_marks",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_media_relevance",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "location"], name="idxdb_medrel_profile_loc"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "location", "source", "item_key"),
                        name="db_media_relevance_unique",
                    )
                ],
            },
        ),
    ]
