# Generated by Django 6.0.6 on 2026-07-24 19:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_spotguessr_photo_relevance"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="estimated_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="estimated_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.CreateModel(
            name="PhotoCoordinateGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "guess_point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("is_correct", models.BooleanField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinate_guesses",
                        to="dashboard.image",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_spotguessr_photo_coordinate_guesses",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["image", "is_correct"],
                        name="idxdb_sg_cordgues_iscorrect",
                    )
                ],
            },
        ),
    ]
