# Generated by Django 6.0.6 on 2026-07-29 18:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_friendship_muted_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="track_device_scans",
            field=models.BooleanField(
                default=True,
                help_text="Associate wireless device scans you upload with your account (enables personal scan history). When off, your scans are stored anonymously.",
            ),
        ),
        migrations.CreateModel(
            name="DeviceScanUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "client_session_uuid",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_scan_uploads",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_device_scan_uploads",
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceScanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "device_type_guess",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("camera", "Camera"),
                            ("sensor", "Sensor"),
                            ("tracker", "Tracker"),
                            ("access_point", "Access Point"),
                            ("phone", "Phone"),
                            ("wearable", "Wearable"),
                            ("iot", "IoT Device"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("detected", models.BooleanField(default=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="dashboard.devicescanupload",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_device_scan_entries",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceSignalReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("signal_strength", models.IntegerField(blank=True, null=True)),
                ("observed_at", models.DateTimeField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="dashboard.devicescanentry",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_device_signal_readings",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScannedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mac_address",
                    models.CharField(editable=False, max_length=17, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("camera", "Camera"),
                            ("sensor", "Sensor"),
                            ("tracker", "Tracker"),
                            ("access_point", "Access Point"),
                            ("phone", "Phone"),
                            ("wearable", "Wearable"),
                            ("iot", "IoT Device"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "device_type_source",
                    models.CharField(
                        choices=[
                            ("unset", "Unset"),
                            ("client", "Reported by client"),
                            ("heuristic", "Server heuristic"),
                        ],
                        default="unset",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_scanned_devices",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["mac_address"], name="idxdb_scandev_mac")
                ],
            },
        ),
        migrations.AddField(
            model_name="devicescanentry",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_entries",
                to="dashboard.scanneddevice",
            ),
        ),
        migrations.CreateModel(
            name="WikiDeviceMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("presumed_removed", "Presumed Removed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("radius_meters", models.FloatField(default=0.0)),
                ("manually_placed", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0.0)),
                ("observation_count", models.PositiveIntegerField(default=0)),
                ("absence_streak", models.PositiveIntegerField(default=0)),
                ("avg_signal_strength", models.FloatField(blank=True, null=True)),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="dashboard.scanneddevice",
                    ),
                ),
                (
                    "wiki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_markers",
                        to="dashboard.wiki",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_wiki_device_markers",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="devicescanentry",
            name="expected_marker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scan_entries",
                to="dashboard.wikidevicemarker",
            ),
        ),
        migrations.AddIndex(
            model_name="wikidevicemarker",
            index=models.Index(
                fields=["wiki", "device"], name="idxdb_wikidevmark_wiki_dev"
            ),
        ),
        migrations.AddIndex(
            model_name="wikidevicemarker",
            index=models.Index(fields=["status"], name="idxdb_wikidevmark_status"),
        ),
        migrations.AddIndex(
            model_name="devicescanentry",
            index=models.Index(fields=["device"], name="idxdb_scanentry_device"),
        ),
    ]
