# Generated by Django 6.0.6 on 2026-07-26 02:14
#
# Split out of the auto-generated Facts migration: this catches up
# NotificationLog.notification_type's `choices` to include CONSENSUS_INVITE
# (added to the model when Consensus shipped, but never migrated - `choices`
# isn't enforced at the DB level, so this is a state-only formality, not an
# actual schema/data change) rather than bundling an unrelated fix into the
# Facts migration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_merge_20260725_2214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("comment_upload_failed", "Comment Upload Failed"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("safety_ci_partner_invite", "Safety Check-in Partner Request"),
                    ("safety_ci_partner_accepted", "Safety Check-in Partner Accepted"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("friend_suggestion", "Friend Suggestion"),
                    ("spotguessr_invite", "SpotGuessr Invitation"),
                    ("trivia_invite", "Trivia Invitation"),
                    ("consensus_invite", "Consensus Invitation"),
                    ("pin_import_complete", "Pin Import Complete"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
    ]
