# Generated by Django 6.0.6 on 2026-08-02 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_seed_vip_subscription_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="monthly_price_cents",
            field=models.IntegerField(
                blank=True,
                help_text="Fixed monthly price in cents, e.g. 500 for $5.00. Blank means not offered at a fixed price.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="pay_what_you_want",
            field=models.BooleanField(
                default=False,
                help_text="Let users choose their own monthly pledge instead of (or as well as) the fixed price above.",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="pwyw_dynamic_threshold",
            field=models.BooleanField(
                default=False,
                help_text="Requires pay_what_you_want. Grants this role only in months the user's pledge meets or exceeds the site's current cost-per-user (services.admin.cost_tracking.cost_per_user), recalculated at each successful charge - not a fixed minimum.",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="pwyw_minimum_cents",
            field=models.IntegerField(
                blank=True,
                help_text="Static minimum pledge (cents) required to hold this role when pay_what_you_want is on and pwyw_dynamic_threshold is off. Blank or 0 means any pledge grants it.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrole",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Product id for this role, created lazily on first checkout. Prices are generated inline per checkout/pledge instead of being pre-created, so editing monthly_price_cents needs no Stripe sync.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="BillingCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stripe_customer_id", models.CharField(max_length=255, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoleSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=255)),
                (
                    "pledged_amount_cents",
                    models.IntegerField(
                        help_text="The amount currently being charged per period, in cents."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete (expired)"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("trialing", "Trialing"),
                            ("paused", "Paused"),
                        ],
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "threshold_met",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the current pledge clears the role's pay-what-you-want access threshold.",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_subscriptions",
                        to="dashboard.subscriptionrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "canceled"), _negated=True),
                        fields=("user", "role"),
                        name="unique_active_role_subscription",
                    )
                ],
            },
        ),
    ]
