# Generated by Django 6.0.6 on 2026-07-12 19:27

from django.contrib.postgres.operations import TrigramExtension
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_media_yelp_cover_photos"),
    ]

    operations = [
        # Fuzzy (typo-tolerant) matching in global search uses TrigramSimilarity,
        # which needs the pg_trgm extension. The dockerized PostGIS image runs
        # migrations as a superuser, so CREATE EXTENSION succeeds there.
        TrigramExtension(),
        migrations.AddField(
            model_name="profile",
            name="generate_photo_keywords",
            field=models.BooleanField(
                default=True,
                help_text="Automatically generate searchable keywords for photos you upload.",
            ),
        ),
        migrations.CreateModel(
            name="ImageKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(db_index=True, max_length=100)),
                ("source", models.CharField(max_length=50)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="dashboard.image",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_image_keywords",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["source"], name="idx_image_keyword_source")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("image", "source", "keyword"),
                        name="uniq_image_keyword_per_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(max_length=255)),
                ("last_used", models.DateTimeField(auto_now=True, db_index=True)),
                ("use_count", models.PositiveIntegerField(default=1)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "search histories",
                "db_table": "dashboard_search_history",
                "ordering": ["-last_used"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "-last_used"],
                        name="idx_search_history_recent",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "query"),
                        name="uniq_search_history_profile_query",
                    )
                ],
            },
        ),
    ]
