# Generated by Django 6.0.6 on 2026-07-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_spotguessr_photo_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="anthropic_model",
            field=models.CharField(
                default="claude-haiku-4-5",
                help_text="Anthropic (Claude) model name (e.g. claude-haiku-4-5, claude-sonnet-5). Only used when provider is Anthropic.",
                max_length=100,
                verbose_name="Anthropic model",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("cloudflare", "Cloudflare Workers AI"),
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic (Claude)"),
                ],
                default="cloudflare",
                help_text="Which AI provider to use for all AI-powered features.",
                max_length=20,
                verbose_name="AI provider",
            ),
        ),
    ]
