# Generated by Django 6.0.6 on 2026-07-26 02:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_notificationlog_consensus_invite_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("point", "Point"),
                            ("bool", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        max_length=6,
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=500, null=True)),
                ("value_number", models.FloatField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "value_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("value_bool", models.BooleanField(null=True)),
                ("key", models.CharField(db_index=True, max_length=64)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("wiki", "Wiki"),
                            ("image", "Image"),
                        ],
                        editable=False,
                        max_length=8,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unconfirmed", "Unconfirmed"),
                            ("tentative", "Tentative"),
                            ("confirmed", "Confirmed"),
                            ("contested", "Contested"),
                        ],
                        default="unconfirmed",
                        max_length=11,
                    ),
                ),
                ("evidence_count", models.PositiveIntegerField(default=0)),
                ("last_evidence_at", models.DateTimeField(blank=True, null=True)),
                ("last_recomputed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="dashboard.image",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="dashboard.location",
                    ),
                ),
                (
                    "wiki",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="dashboard.wiki",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_facts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FactEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("point", "Point"),
                            ("bool", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        max_length=6,
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=500, null=True)),
                ("value_number", models.FloatField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "value_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("value_bool", models.BooleanField(null=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("player_anonymous", "Anonymous player"),
                            ("player_attributed", "Attributed player"),
                            ("wiki_edit", "Manual wiki edit"),
                            ("ai_agent", "AI agent"),
                            ("external_source", "External data source"),
                            ("admin", "Admin/staff"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("submitter_trust_snapshot", models.FloatField(blank=True, null=True)),
                ("source_reliability", models.FloatField(default=1.0)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("superseded", models.BooleanField(default=False)),
                (
                    "consensus_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fact_evidence",
                        to="dashboard.consensusround",
                    ),
                ),
                (
                    "fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="dashboard.fact",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fact_evidence",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_fact_evidence",
                "abstract": False,
            },
        ),
        # Uniqueness per (subject, key) - one AddConstraint per subject type,
        # since Fact has one nullable FK per possible subject rather than a
        # single GenericForeignKey (no precedent for that pattern in this
        # codebase - see ConsensusRound.wiki/.target_image).
        migrations.AddConstraint(
            model_name="fact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", False)),
                fields=("location", "key"),
                name="db_fact_unique_location_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="fact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("wiki__isnull", False)),
                fields=("wiki", "key"),
                name="db_fact_unique_wiki_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="fact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image__isnull", False)),
                fields=("image", "key"),
                name="db_fact_unique_image_key",
            ),
        ),
        # "Exactly one of location/wiki/image is set" can't be expressed as a
        # single Django CheckConstraint across three nullable FKs, so it's
        # backstopped here as an unbypassable floor beneath Fact.save()'s own
        # enforcement - mirrors Location's immutable-coordinates DB trigger
        # (see models/location/model.py and migration 0009).
        migrations.RunSQL(
            sql=(
                "ALTER TABLE dashboard_facts ADD CONSTRAINT db_fact_exactly_one_subject "
                "CHECK ("
                "(location_id IS NOT NULL)::int + (wiki_id IS NOT NULL)::int + (image_id IS NOT NULL)::int = 1"
                ");"
            ),
            reverse_sql="ALTER TABLE dashboard_facts DROP CONSTRAINT db_fact_exactly_one_subject;",
        ),
        # Indexes dead last, per this project's migration convention.
        migrations.AddIndex(
            model_name="fact",
            index=models.Index(fields=["status"], name="idxdb_fact_status"),
        ),
        migrations.AddIndex(
            model_name="factevidence",
            index=models.Index(
                fields=["fact", "created"], name="idxdb_factev_fact_created"
            ),
        ),
        migrations.AddIndex(
            model_name="factevidence",
            index=models.Index(fields=["source_kind"], name="idxdb_factev_source_kind"),
        ),
    ]
