# Generated by Django 6.0.6 on 2026-08-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_paid_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolesubscription",
            name="amount_used_cents",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative reference cost 'spent' from total_paid_cents so far, one billing period at a time.",
            ),
        ),
        migrations.AddField(
            model_name="rolesubscription",
            name="total_paid_cents",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative amount actually paid via Stripe invoices, ever. Pay-what-you-want roles only.",
            ),
        ),
        migrations.AddField(
            model_name="rolesubscription",
            name="usage_covered_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Point in time through which the usage ledger has confirmed sufficient balance - grants access independent of live Stripe status, even after cancellation, for as long as cumulative overpayment covers it.",
                null=True,
            ),
        ),
    ]
