# Generated by Django 6.0.6 on 2026-07-09 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_external_data_cache_days"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pin",
            name="db_pin_unique_location_per_profile",
        ),
        migrations.RemoveIndex(
            model_name="pin",
            name="idxdb_pin_parent_wiki",
        ),
        migrations.AddField(
            model_name="wiki",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="wiki",
            name="detail_bg_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="wiki",
            name="detail_bg_opacity",
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name="wiki",
            name="detail_border_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="wiki",
            name="detail_border_opacity",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="wiki",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wiki",
            name="parent_wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_wikis",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="pin_type",
            field=models.CharField(
                choices=[
                    ("location", "Location"),
                    ("building", "Building"),
                    ("entrance", "Entrance"),
                    ("poi", "Point of Interest"),
                    ("danger", "Danger"),
                    ("other", "Other"),
                ],
                default="location",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="wiki",
            index=models.Index(fields=["parent_wiki"], name="idxdb_wiki_parent_wiki"),
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_pin__isnull", True)),
                fields=("location", "profile"),
                name="db_pin_unique_location_per_profile",
            ),
        ),
        migrations.RemoveField(
            model_name="pin",
            name="parent_wiki",
        ),
    ]
