# Generated by Django 6.0.6 on 2026-07-24 23:59

from django.db import migrations, models
import django.db.models.deletion

import urbanlens.dashboard.models.spotguessr.model


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_sitesettings_anthropic_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerTriviaRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("mu", models.FloatField(default=0.0)),
                ("phi", models.FloatField(default=2.014761872416068)),
                ("sigma", models.FloatField(default=0.06)),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("last_played_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_rating",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_player_ratings",
                "abstract": False,
            },
            bases=(
                urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TriviaPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("show_ratings_to_friends", models.BooleanField(default=True)),
                ("last_config", models.JSONField(default=dict)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_preference",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_preferences",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TriviaQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField()),
                ("answer", models.CharField(max_length=255)),
                (
                    "answer_normalized",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user_submitted", "User Submitted"),
                            ("ai_generated", "AI Generated"),
                            ("deterministic", "Deterministic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dedupe_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("wiki_incorporated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_questions",
                        to="dashboard.location",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trivia_questions_submitted",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_questions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TriviaQuestionRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("mu", models.FloatField(default=0.0)),
                ("phi", models.FloatField(default=2.014761872416068)),
                ("sigma", models.FloatField(default=0.06)),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("last_asked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="dashboard.triviaquestion",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_question_ratings",
                "abstract": False,
            },
            bases=(
                urbanlens.dashboard.models.spotguessr.model._Glicko2RatingFields,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TriviaQuestionVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("upvote", "Upvote"),
                            ("downvote", "Downvote"),
                            ("report", "Report"),
                            ("no_reaction", "No Reaction"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_question_votes",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="dashboard.triviaquestion",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_question_votes",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TriviaRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sequence_index", models.PositiveSmallIntegerField()),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_rounds",
                        to="dashboard.triviaquestion",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_rounds",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TriviaAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("raw_answer", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField()),
                (
                    "matched_via",
                    models.CharField(
                        choices=[("exact", "Exact Match"), ("ai", "AI Judged")],
                        default="exact",
                        max_length=10,
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_answers",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="dashboard.triviaround",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_answers",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TriviaSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Lobby"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("total_rounds", models.PositiveSmallIntegerField(default=5)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "host_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_trivia_sessions",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_sessions",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="triviaround",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="dashboard.triviasession",
            ),
        ),
        migrations.CreateModel(
            name="TriviaSessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("invited", "Invited"), ("joined", "Joined")],
                        default="joined",
                        max_length=10,
                    ),
                ),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_participations",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="dashboard.triviasession",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_trivia_session_participants",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="triviaquestion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key", ""), _negated=True),
                fields=("location", "dedupe_key"),
                name="db_trivia_question_dedupe_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="triviaquestionvote",
            constraint=models.UniqueConstraint(
                fields=("question", "profile"), name="db_trivia_vote_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="triviaanswer",
            constraint=models.UniqueConstraint(
                fields=("round", "profile"), name="db_trivia_answer_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="triviaround",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence_index"), name="db_trivia_round_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="triviasessionparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "profile"), name="db_trivia_participant_unique"
            ),
        ),
    ]
