# Generated by Django 6.0.6 on 2026-07-12 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_profile_generate_photo_keywords_imagekeyword_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("immich", "Immich library scan"),
                            ("local_scan", "Local folder scan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("visit_dates", models.JSONField(default=list)),
                ("hit_count", models.PositiveIntegerField(default=1)),
                (
                    "suggested_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pin_suggestions",
                        to="dashboard.location",
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_suggestions",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_suggestions",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_suggestions",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "status"], name="idxdb_pin_sugg_status"
                    )
                ],
            },
        ),
    ]
