# Generated by Django 6.0.6 on 2026-08-03 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_banked_access_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="additional_preferences",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Anything else you'd like other users to know about interacting with you.",
                max_length=1000,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="exploring_with_others_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("prefer_alone", "I prefer to explore alone."),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you prefer to explore locations solo or with others.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="exploring_with_others_preference_other",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="friend_request_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("met_in_person", "Only if we've met in person"),
                    ("talk_regularly", "Only if we talk regularly"),
                    ("mutual_friends", "Only if we have mutual friends"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="When you're open to receiving friend requests.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="friend_request_preference_other",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="meetup_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("dislike", "I do not like meetups"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you're interested in meetups with other users.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="meetup_preference_other",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_sharing_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("no", "Please don't"),
                    ("blur_face", "Please blur my face"),
                    ("ask_first", "Please ask first"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you're OK with people sharing or posting your photo, on or off this site.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_sharing_preference_other",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_tagging_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("no", "Please don't"),
                    ("ask_first", "Please ask first"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you're OK with being tagged or identified in photos, on or off this site.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_tagging_preference_other",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_taking_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("no", "Please don't"),
                    ("ask_first", "Please ask first"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you're OK with people taking your photo, on or off this site.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_taking_preference_other",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
