# Generated by Django 6.0.6 on 2026-07-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_pin_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_features",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated SiteFeature values granted to every user, including those with no active subscription.",
                max_length=500,
                verbose_name="Default features (everyone)",
            ),
        ),
    ]
