# Generated by Django 5.1.6 on 2026-05-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_detail_pins"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="location",
            new_name="dashboard_l_uuid_f3ca34_idx",
            old_name="dashboard_loc_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="locationedit",
            new_name="dashboard_le_created_idx",
            old_name="dashboard_le_location_created_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="dashboard_u_uuid_1898a2_idx",
            old_name="dashboard_pin_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="dashboard_u_parent__483403_idx",
            old_name="dashboard_pin_parent_idx",
        ),
        migrations.AlterField(
            model_name="locationedit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="pinvisit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
            ),
        ),
    ]
