# Generated by Django 6.0.6 on 2026-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_profile_interaction_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo_usage_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("feel_free", "Feel free!"),
                    ("with_attribution", "With Attribution"),
                    ("tell_me_about_it", "As long as you tell me about it."),
                    ("ask_first", "Ask first"),
                    ("no", "Please don't"),
                    ("other", "Other (specify...)"),
                ],
                default="",
                help_text="Whether you're OK with people using your photos, on or off this site.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_usage_preference_other",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="exploring_with_others_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("prefer_alone", "I prefer exploring alone."),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you prefer to explore locations solo or with others.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_sharing_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("no", "Please don't"),
                    ("without_face", "Only when my face isn't visible"),
                    ("blur_face", "Please blur my face"),
                    ("ask_first", "Please ask first"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you're OK with people sharing or posting your photo, on or off this site.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_tagging_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("no", "Please don't"),
                    ("without_face", "Only when my face isn't visible"),
                    ("ask_first", "Please ask first"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you're OK with being tagged or identified in photos, on or off this site.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_taking_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, please."),
                    ("no", "Please don't"),
                    ("without_face", "Only when my face isn't visible"),
                    ("ask_first", "Please ask first"),
                    ("other", "Other (please specify below)"),
                ],
                default="",
                help_text="Whether you're OK with people taking your photo, on or off this site.",
                max_length=20,
            ),
        ),
    ]
