# Generated by Django 6.0.6 on 2026-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_profile_onboarding_and_feature_toggles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
