# Generated by Codex on 2026-07-01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_pin_sharing"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("user_id_snapshot", models.PositiveIntegerField()),
                ("username", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("archive_path", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("archiving", "Archiving"), ("archived", "Archived"), ("deleted", "Deleted"), ("purged", "Purged"), ("failed", "Failed")], default="archiving", max_length=20)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("purge_after", models.DateTimeField()),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["request_id"], name="dashboard_d_request_4577b2_idx"), models.Index(fields=["purge_after", "status"], name="dashboard_d_purge_a_18beb7_idx")],
            },
        ),
    ]
