# Generated by Django 6.0.6 on 2026-08-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_profile_photo_usage_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="redata_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="redata_model_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="redata_scored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="redata_scorer",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
