# Generated by Django 6.0.6 on 2026-07-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_trivia_multiplayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_trivia_answer_check_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI to judge a Trivia answer that doesn't exact-match as possibly correct but differently phrased. Only ever consulted on a normalized-string mismatch; users without the AI subscription feature always fall back to exact match only.",
                verbose_name="Trivia AI answer checking",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_trivia_generation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI to generate candidate Trivia questions from wiki articles with substantial content. Every generated question still passes through the same moderation classifier before entering rotation.",
                verbose_name="Trivia question generation",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_trivia_moderation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow AI to classify user-submitted and AI-generated Trivia questions for person/bullying/in-group content before they enter rotation. When off, user submissions are held in pending review indefinitely and AI question generation is skipped entirely (moderation is never bypassed).",
                verbose_name="Trivia question moderation",
            ),
        ),
    ]
