# Generated by Django 6.0.6 on 2026-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_vip_add_search_feature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pinshare",
            options={},
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="dashboard_l_officia_b6eaaa_idx",
            old_name="dashboard_l_offici_1cbd21_idx",
        ),
        migrations.RenameIndex(
            model_name="pinshare",
            new_name="dashboard_p_to_prof_5d03ec_idx",
            old_name="dashboard_p_to_prof_d9fbff_idx",
        ),
        migrations.RenameIndex(
            model_name="pinshare",
            new_name="dashboard_p_from_pr_1593ec_idx",
            old_name="dashboard_p_from_pr_27c1ce_idx",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
