# Generated by Django 6.0.6 on 2026-07-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_sitesettings_default_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripcalendarlink",
            name="auto_sync",
            field=models.BooleanField(
                default=False,
                help_text="Push future changes to this trip and its activities to the linked calendar event automatically. One-way only - edits made on Google Calendar are never pulled back.",
            ),
        ),
    ]
