# Generated by Django 5.1.6 on 2026-05-24 00:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0025_aliases",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="pin",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
