# Generated by Django 6.0.6 on 2026-07-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_markupmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetycheckin",
            name="markup_maps",
            field=models.ManyToManyField(
                blank=True,
                related_name="attached_safety_checkins",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="safetypreference",
            name="auto_delete_after_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
