# Generated by Django 5.1.6 on 2026-05-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0024_rename_dashboard_loc_uuid_idx_dashboard_l_uuid_f3ca34_idx_and_more",
        ),
        ("dashboard", "0026_alter_location_uuid_alter_pin_uuid"),
    ]

    operations = []
