# Generated by Django 6.0.6 on 2026-07-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_campus_pin_scoping"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicalllog",
            name="was_service_disabled",
            field=models.BooleanField(
                default=False,
                help_text="True if this entry records a call that was skipped due to service being disabled.",
            ),
        ),
    ]
