# Generated by Django 6.0.6 on 2026-07-25 04:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depends on the latest *committed* migration, not the untracked
        # 0026_pin_indoor_outdoor_wiki_indoor_outdoor.py sitting in this checkout
        # from another in-progress feature - see CLAUDE.md's migration-dependency
        # gotcha. Whoever commits that migration first will need a trivial merge
        # migration; that's expected when two features branch off the same parent.
        ("dashboard", "0025_trivia_ai_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyCheckinPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("invited", "Invited"), ("accepted", "Accepted")],
                        default="invited",
                        max_length=10,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_safety_checkin_partners",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="safety_checkin_partner_invite",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="both",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="safety_checkin_partner_invite_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="safety_checkin_partner_invite_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_safety_checkin_partners",
            field=models.IntegerField(
                default=5,
                help_text="Maximum number of partners a user may add to one safety check-in. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Max partners per safety check-in",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("trip_updated", "Trip Updated"),
                    ("friend_request", "New Friend Request"),
                    ("message", "New Message"),
                    ("comment_reply", "Reply to Comment"),
                    ("comment_liked", "Comment Likes"),
                    ("comment_upload_failed", "Comment Upload Failed"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("added_to_trip", "Trip Invitation"),
                    ("wiki_updated", "Community Wiki Updated"),
                    ("pin_shared", "Pin Shared"),
                    ("map_shared", "Map Shared"),
                    ("visit_suggested", "Visit Suggested"),
                    ("safety_ci_due", "Safety Check-in Due"),
                    ("safety_ci_final_warning", "Safety Check-in Final Warning"),
                    ("safety_ci_overdue", "Safety Check-in Overdue"),
                    ("safety_ci_resolved", "Safety Check-in Resolved"),
                    ("safety_ci_plan_updated", "Safety Check-in Plan Updated"),
                    ("wiki_safety_checkin", "Community Wiki Safety Check-in"),
                    ("safety_ci_partner_invite", "Safety Check-in Partner Request"),
                    ("safety_ci_partner_accepted", "Safety Check-in Partner Accepted"),
                    ("account_deletion_requested", "Account Deletion Requested"),
                    ("account_deletion_reminder", "Account Deletion Reminder"),
                    ("ai_extraction", "AI Link Analysis Complete"),
                    ("friend_suggestion", "Friend Suggestion"),
                    ("spotguessr_invite", "SpotGuessr Invitation"),
                    ("trivia_invite", "Trivia Invitation"),
                    ("pin_import_complete", "Pin Import Complete"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_safety_checkin_partners__gte", 0)),
                name="max_safety_checkin_partners_gte_0",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinpartner",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="dashboard.safetycheckin",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinpartner",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="safetycheckinpartner",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_checkin_partner_roles",
                to="dashboard.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckinpartner",
            index=models.Index(
                fields=["checkin", "status"], name="idxdb_scp_checkin_status"
            ),
        ),
        migrations.AddIndex(
            model_name="safetycheckinpartner",
            index=models.Index(
                fields=["profile", "status"], name="idxdb_scp_profile_status"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="safetycheckinpartner",
            unique_together={("checkin", "profile")},
        ),
    ]
