# Generated by Django 6.0.6 on 2026-07-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_totp_backup_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="pin_suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_images",
                to="dashboard.pinsuggestion",
            ),
        ),
        migrations.AddField(
            model_name="pinsuggestion",
            name="sample_assets",
            field=models.JSONField(default=list),
        ),
    ]
