# Generated by Django 6.0.6 on 2026-07-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_apicalllog_was_service_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinmarkup",
            name="parent_pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup_items",
                to="dashboard.pin",
            ),
        ),
        migrations.AddField(
            model_name="pinmarkup",
            name="parent_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup_items",
                to="dashboard.location",
            ),
        ),
        migrations.AddIndex(
            model_name="pinmarkup",
            index=models.Index(fields=["parent_location"], name="dashboard_pm_location_idx"),
        ),
    ]
