# Generated by Django 6.0.6 on 2026-07-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_safety_checkin_partners"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="indoor_outdoor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inside", "Inside"),
                    ("outside", "Outside"),
                    ("both", "Both"),
                ],
                help_text="Whether this pin's location is inside, outside, or both; unset when not yet classified.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="indoor_outdoor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inside", "Inside"),
                    ("outside", "Outside"),
                    ("both", "Both"),
                ],
                help_text="Whether this place is inside, outside, or both; unset when not yet classified.",
                max_length=10,
                null=True,
            ),
        ),
    ]
