# Generated by Django 6.0.6 on 2026-07-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0028_pin_indoor_outdoor_wiki_indoor_outdoor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripmembership",
            name="rsvp",
            field=models.CharField(blank=True, choices=[("yes", "Going"), ("no", "Not Coming"), ("maybe", "Maybe")], max_length=20, null=True),
        ),
    ]
