# Generated by Django 6.0.6 on 2026-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_places_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedfilter",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("#F44336", "Red"),
                    ("#E91E63", "Pink"),
                    ("#9C27B0", "Purple"),
                    ("#673AB7", "Deep Purple"),
                    ("#3F51B5", "Indigo"),
                    ("#2196F3", "Blue"),
                    ("#03A9F4", "Light Blue"),
                    ("#00BCD4", "Cyan"),
                    ("#009688", "Teal"),
                    ("#4CAF50", "Green"),
                    ("#8BC34A", "Light Green"),
                    ("#CDDC39", "Lime"),
                    ("#FFEB3B", "Yellow"),
                    ("#FFC107", "Amber"),
                    ("#FF9800", "Orange"),
                    ("#FF5722", "Deep Orange"),
                    ("#795548", "Brown"),
                    ("#607D8B", "Blue Grey"),
                    ("#9E9E9E", "Grey"),
                    ("#FFFFFF", "White"),
                    ("#000000", "Black"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="savedfilter",
            name="opacity",
            field=models.IntegerField(default=100),
        ),
    ]
