# Generated by Django 6.0.6 on 2026-07-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_pin_suggestion_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileNickname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "nickname",
                    models.CharField(
                        help_text="Private nickname the author uses to refer to the subject.",
                        max_length=100,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_nicknames",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_nicknames",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author", "subject"), name="unique_profile_nickname"
                    )
                ],
            },
        ),
    ]
