# Generated by Django 6.0.6 on 2026-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_alter_tripmembership_rsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_article_expansion_enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Allow the link-extraction pipeline to ask a writing assistant for new plain-text "
                    "paragraphs to append to the pin article (and the location wiki article when one "
                    "exists). Every draft still passes through article safety moderation before it is saved; "
                    "when this toggle is off, field extraction still runs and article expansion is skipped."
                ),
                verbose_name="Article expansion from links",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ai_article_safety_enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Allow AI to judge article text drafted from a linked page for appropriateness and "
                    "safety-related implications (entry methods, trespass how-tos, harassment, etc.) before "
                    "it is appended. When off, article expansion is skipped entirely — moderation is never bypassed."
                ),
                verbose_name="Article expansion safety review",
            ),
        ),
    ]
