# Generated by Django 6.0.6 on 2026-07-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_alter_tripmembership_rsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetycheckin",
            name="live_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="live_location_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="live_location_sharing_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="live_location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="live_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
