# Generated by Django 6.0.6 on 2026-07-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_profile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripmembership",
            name="last_viewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this member last opened the trip detail page. Powers the 'recently viewed' list on the trips overview page.",
                null=True,
            ),
        ),
    ]
