# Generated by Django 6.0.6 on 2026-08-05 14:39

from django.db import migrations, models

import urbanlens.dashboard.models.images.model


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_saved_filter_color_opacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                max_length=255,
                upload_to=urbanlens.dashboard.models.images.model.pin_image_upload_path,
            ),
        ),
    ]
