# Generated by Django 6.0.6 on 2026-08-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_image_upload_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_supporter_badge",
            field=models.BooleanField(default=True, help_text="Show a small supporter badge next to your name when you have an active subscription."),
        ),
    ]
