# Generated by Django 5.1.6 on 2026-05-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_trip_planning"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pin",
            name="dashboard_pin_unique_location_per_profile",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="dashboard_t_name_73c472_idx",
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("parent_location__isnull", True), ("parent_pin__isnull", True),
                ),
                fields=("latitude", "longitude", "profile"),
                name="dashboard_pin_unique_location_per_profile",
            ),
        ),
    ]
