# Generated by Django 6.0.6 on 2026-07-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_safety_checkin_live_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="guess",
            name="bonus_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
