# Generated by Django 6.0.6 on 2026-07-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_trip_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="markupmap",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="associated_maps",
                to="dashboard.pin",
            ),
        ),
        migrations.AddIndex(
            model_name="markupmap",
            index=models.Index(fields=["pin"], name="idxdb_mm_pin"),
        ),
    ]
