# Generated by Django 6.0.6 on 2026-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_spotguessr_guess_bonus_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("Send Message", "Send Message"),
                    ("Invite to Events", "Invite to Events"),
                    ("Share Pins", "Share Pins"),
                    ("View Profile", "View Profile"),
                    ("View Friends", "View Friends"),
                    ("View Trips", "View Trips"),
                ],
                default="View Profile",
                max_length=16,
            ),
        ),
    ]
