# Generated by Django 6.0.6 on 2026-08-05 16:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_profile_show_supporter_badge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="", max_length=50000)),
                (
                    "kind",
                    models.CharField(
                        choices=[("plain", "Album"), ("timelapse", "Timelapse")],
                        db_index=True,
                        default="plain",
                        max_length=20,
                    ),
                ),
                ("manual_order", models.BooleanField(default=False)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="album_covers",
                        to="dashboard.image",
                    ),
                ),
                (
                    "parent_pin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "parent_wiki",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="dashboard.wiki",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_albums",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AlbumItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="album_items_added",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dashboard.album",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_memberships",
                        to="dashboard.image",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_album_items",
                "ordering": ["order", "created"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(fields=("parent_pin", "slug"), name="uq_album_pin_slug"),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(fields=("parent_wiki", "slug"), name="uq_album_wiki_slug"),
        ),
        migrations.AddConstraint(
            model_name="albumitem",
            constraint=models.UniqueConstraint(fields=("album", "image"), name="uq_album_item"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["parent_pin"], name="idxdb_album_pin"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["parent_wiki"], name="idxdb_album_wiki"),
        ),
        migrations.AddIndex(
            model_name="albumitem",
            index=models.Index(fields=["album"], name="idxdb_albumitem_album"),
        ),
        migrations.AddIndex(
            model_name="albumitem",
            index=models.Index(fields=["image"], name="idxdb_albumitem_image"),
        ),
    ]
