# Generated by Django 6.0.6 on 2026-08-05 19:20

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


def mark_existing_external_media_exempt(apps, schema_editor):
    """Backfill the exemption onto already-cached external media.

    Every existing row carrying the (media_source_key, media_item_key) gallery
    identity was materialized by services.media.media_materialize, which from
    now on stamps the exemption at creation. Without this, photos cached
    before the rule existed would keep counting against their upvoter's quota
    while identical ones cached afterwards did not.

    The community-contribution exemption is deliberately NOT backfilled: it's
    a forward-looking reward, and granting it retroactively would require
    replaying vote history against a threshold that didn't exist yet.
    """
    Image = apps.get_model("dashboard", "Image")
    Image.objects.exclude(media_source_key__isnull=True).exclude(media_source_key="").exclude(media_item_key__isnull=True).exclude(media_item_key="").update(
        quota_exempt_reason="external_media"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_albums"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="quota_exempt_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("external_media", "Cached external media"),
                    ("community", "Community-valued contribution"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="community_photo_quota_bonus_votes",
            field=models.IntegerField(
                default=5,
                help_text=(
                    "How many other users must mark one of a user's wiki-shared photos as relevant before that photo stops counting against their storage quota. "
                    "The uploader's own vote never counts. Set to 0 to turn the reward off."
                ),
                validators=[MinValueValidator(0), MaxValueValidator(10000)],
                verbose_name="Relevant votes earning a quota bonus",
            ),
        ),
        migrations.RunPython(mark_existing_external_media_exempt, migrations.RunPython.noop),
    ]
