# Generated by Django 6.0.6 on 2026-09-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_v0_8_0_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcomment',
            name='parent_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
