# Generated by Django 6.0.6 on 2026-08-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """Swap the standalone quota_exempt_reason index for a composite one.

    0033 added ``db_index=True`` on ``quota_exempt_reason``. That column holds
    three values, so a standalone index on it is almost never the planner's
    choice while still costing a write on every photo upload. Both quota
    queries filter by ``profile`` first, so the composite is what actually
    serves them.
    """

    dependencies = [
        ("dashboard", "0033_quota_exemptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="quota_exempt_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("external_media", "Cached external media"),
                    ("community", "Community-valued contribution"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(fields=["profile", "quota_exempt_reason"], name="idxdb_image_profile_quota"),
        ),
    ]
