# Generated by Django 6.0.8 on 2026-10-02 06:52

import urbanlens.dashboard.models.proxied_media_render.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_reresolve_fiat_building_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxiedMediaRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('render_digest', models.CharField(editable=False, help_text="SHA-256 of the proxy's cache key and the size.", max_length=64, unique=True)),
                ('source_key', models.CharField(help_text="The proxy's cache key for the original file.", max_length=255)),
                ('size', models.CharField(help_text="Which rendering: a gallery tile's, or the lightbox's.", max_length=16)),
                ('file', models.FileField(max_length=255, upload_to=urbanlens.dashboard.models.proxied_media_render.model.proxied_media_render_path)),
                ('content_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'dashboard_proxied_media_renders',
                'abstract': False,
            },
        ),
    ]
