# Generated by Django 6.0.6 on 2026-08-06 00:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_image_profile_quota_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapImageOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('nw_latitude', models.FloatField()),
                ('nw_longitude', models.FloatField()),
                ('ne_latitude', models.FloatField()),
                ('ne_longitude', models.FloatField()),
                ('se_latitude', models.FloatField()),
                ('se_longitude', models.FloatField()),
                ('sw_latitude', models.FloatField()),
                ('sw_longitude', models.FloatField()),
                ('opacity', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0)),
                ('default_visible', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_overlays', to='dashboard.image')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_overlays', to='dashboard.customlayer')),
                ('parent_pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_overlays', to='dashboard.pin')),
                ('parent_wiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_overlays', to='dashboard.wiki')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_overlays', to='dashboard.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['parent_pin', 'order'], name='idx_overlay_pin_order'), models.Index(fields=['parent_wiki', 'order'], name='idx_overlay_wiki_order')],
            },
        ),
    ]
