# Generated by Django 6.0.6 on 2026-07-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_rename_badge_to_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="default_name_source_priority",
            field=models.CharField(
                blank=True,
                default="nominatim,wikipedia,nps,google_places",
                help_text="Comma-separated name-provider slugs, highest priority first, used to pick a location's official name from external candidates. Sources not listed rank last, in plugin order. Blank = plugin order only.",
                max_length=500,
                verbose_name="Name source priority",
            ),
        ),
    ]
