# Generated by Django 6.0.6 on 2026-08-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_undo_kind_redo_stack"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="albumitem",
            options={"ordering": ["pk"]},
        ),
        migrations.AddField(
            model_name="album",
            name="parent_profile",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="vault_albums", to="dashboard.profile"),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(fields=("parent_profile", "slug"), name="uq_album_profile_slug"),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("parent_pin__isnull", False), ("parent_profile__isnull", True), ("parent_wiki__isnull", True)), models.Q(("parent_pin__isnull", True), ("parent_profile__isnull", True), ("parent_wiki__isnull", False)), models.Q(("parent_pin__isnull", True), ("parent_profile__isnull", False), ("parent_wiki__isnull", True)), _connector="OR"), name="ck_album_exactly_one_owner"),
        ),
    ]
