# Generated by Django 6.0.8 on 2026-10-02 08:11

import urbanlens.dashboard.models.remote_image_copy.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_proxied_media_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteimagecopy',
            name='thumb_file',
            field=models.FileField(blank=True, default='', db_default='', help_text="A gallery tile's size, made from the same download when the copy is larger.", max_length=255, upload_to=urbanlens.dashboard.models.remote_image_copy.model.remote_image_copy_path),
        ),
    ]
