# Generated by Django 6.0.6 on 2026-07-14 05:30

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def disable_auto_tagging(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Turn off auto-tagging for all existing profiles now that it defaults to opt-in."""
    Profile = apps.get_model("dashboard", "Profile")
    Profile.objects.update(ai_label_categories=False, ai_label_tags=False, ai_label_statuses=False)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_alter_sitesettings_default_name_source_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ai_label_categories",
            field=models.BooleanField(
                default=False,
                help_text="AI can automatically suggest and add categories when a pin is created.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ai_label_statuses",
            field=models.BooleanField(
                default=False,
                help_text="AI can automatically suggest and add statuses when a pin is created.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ai_label_tags",
            field=models.BooleanField(
                default=False,
                help_text="AI can automatically suggest and add tags when a pin is created.",
            ),
        ),
        migrations.RunPython(disable_auto_tagging, migrations.RunPython.noop),
    ]
