# Generated by Django 6.0.6 on 2026-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_auto_tag_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="map_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="map_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tripcomment",
            name="map_removed",
            field=models.BooleanField(default=False),
        ),
    ]
