# Generated by Django 6.0.8 on 2026-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_remoteimagecopy_thumb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessionparticipant',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left')], default='joined', max_length=10),
        ),
    ]
