# Generated by Django 6.0.6 on 2026-08-31 11:24

import urbanlens.dashboard.models.fields
import urbanlens.dashboard.models.images.model
from django.db import migrations, models


class Migration(migrations.Migration):
    """Record an upload's true filename/parsed date off to the side, so the stored file can be anonymized."""

    dependencies = [
        ("dashboard", "0036_album_vault_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="filename_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="marker_thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=urbanlens.dashboard.models.images.model.pin_image_marker_thumbnail_path,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="original_filename",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
    ]
