# Generated by Django 6.0.6 on 2026-08-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_image_source_digital_commonwealth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='search_provider',
        ),
    ]
