# Generated by Django 6.0.6 on 2026-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0007_pinshare_bundled_with_squashed_0037_markup_map_removed_flags",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="dashboard.label"
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="kind",
            field=models.CharField(
                choices=[
                    ("tag", "Tag"),
                    ("category", "Category"),
                    ("status", "Status"),
                    ("user", "Person"),
                    ("media", "Media"),
                ],
                db_index=True,
                default="tag",
                max_length=20,
            ),
        ),
    ]
