# Generated by Django 6.0.6 on 2026-08-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_drop_search_provider'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='idxdb_comment_uuid',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='idxdb_image_uuid',
        ),
        migrations.RemoveIndex(
            model_name='label',
            name='idxdb_label_uuid',
        ),
        migrations.RemoveIndex(
            model_name='pin',
            name='idxdb_pin_uuid',
        ),
        migrations.RemoveIndex(
            model_name='pinvisit',
            name='idxdb_pv_uuid',
        ),
        migrations.RemoveIndex(
            model_name='safetycheckin',
            name='idxdb_sc_uuid',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='idxdb_trip_uuid',
        ),
        migrations.RemoveIndex(
            model_name='wiki',
            name='idxdb_wiki_uuid',
        ),
    ]
