# Generated by Django 6.0.6 on 2026-08-10 02:29

import django.core.validators
from django.db import migrations

import urbanlens.dashboard.models.fields
from urbanlens.dashboard.models.fields import EncryptedTextField

_field = EncryptedTextField()


def _encrypt_column(cursor, table: str, column: str) -> None:
    """Encrypt every existing non-empty value in ``table.column`` in place.

    Mirrors ``encrypt_existing_tokens``/``_encrypt_column`` in
    ``0007_pinshare_bundled_with_markup_map_removed_flags.py``. Uses a raw
    cursor rather than the ORM/historical model so it works regardless of
    operation order relative to the ``AlterField``s above - the historical
    model's field type at this point in the migration is irrelevant since
    nothing here goes through Django's field conversion.
    """
    cursor.execute(f"SELECT id, {column} FROM {table} WHERE {column} IS NOT NULL AND {column} != ''")  # noqa: S608 # nosec B608 - table/column are hardcoded constants below, not user input
    rows = cursor.fetchall()
    for pk, plaintext in rows:
        ciphertext = _field.get_prep_value(plaintext)
        cursor.execute(f"UPDATE {table} SET {column} = %s WHERE id = %s", [ciphertext, pk])  # noqa: S608 # nosec B608 - table/column are hardcoded constants below, not user input


#: Every (table, column) the forward pass encrypts - shared with the reverse
#: so the two can never drift.
_ENCRYPTED_COLUMNS = (
    ("dashboard_safety_contact_defaults", "email"),
    ("dashboard_google_calendar_accounts", "google_email"),
    ("dashboard_google_photos_accounts", "google_email"),
    ("dashboard_profiles", "area"),
    ("dashboard_profiles", "bio"),
    ("dashboard_profiles", "discord_username"),
    ("dashboard_profiles", "matrix_handle"),
    ("dashboard_profiles", "phone_number"),
    ("dashboard_profiles", "signal_username"),
    ("dashboard_profiles", "telegram_username"),
    ("dashboard_profiles", "whatsapp_number"),
    ("dashboard_profileemail", "email"),
    ("dashboard_profilenote", "content"),
)


def encrypt_existing_contact_and_note_fields(apps, schema_editor) -> None:
    with schema_editor.connection.cursor() as cursor:
        for table, column in _ENCRYPTED_COLUMNS:
            _encrypt_column(cursor, table, column)


def _decrypt_column(cursor, table: str, column: str) -> None:
    """Decrypt every Fernet-encrypted value in ``table.column`` in place.

    A value not shaped like a Fernet token (they always begin ``gAAAA`` - a
    version byte of 0x80, base64'd) is left untouched: it was written before
    the forward pass ran, or the forward pass never reached it, and
    re-processing it would corrupt real plaintext. A token-shaped value that
    no configured key can decrypt raises, aborting (and rolling back) the
    reverse rather than writing garbage where the pre-0039 code expects
    plaintext.
    """
    cursor.execute(f"SELECT id, {column} FROM {table} WHERE {column} LIKE 'gAAAA%%'")  # noqa: S608 # nosec B608 - table/column are hardcoded constants above, not user input
    rows = cursor.fetchall()
    for pk, ciphertext in rows:
        plaintext = _field.from_db_value(ciphertext, None, None)
        cursor.execute(f"UPDATE {table} SET {column} = %s WHERE id = %s", [plaintext, pk])  # noqa: S608 # nosec B608 - table/column are hardcoded constants above, not user input


def decrypt_existing_contact_and_note_fields(apps, schema_editor) -> None:
    """Real reverse for the in-place encryption above.

    ``RunPython.noop`` here would let ``migrate dashboard 0038`` *succeed*
    while leaving ciphertext in columns the pre-0039 code reads as plaintext -
    a silent-corruption rollback. Decrypting is symmetric and cheap, so the
    reverse does it properly (and raises, wholesale, if any value cannot be
    decrypted under the configured keys).
    """
    with schema_editor.connection.cursor() as cursor:
        for table, column in _ENCRYPTED_COLUMNS:
            _decrypt_column(cursor, table, column)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_drop_redundant_uuid_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontactdefault",
            name="email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, fail_soft=True, null=True, validators=[django.core.validators.validate_email]
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendaraccount",
            name="google_email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                fail_soft=True,
                help_text="Email of the connected Google account, for display only.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="googlephotosaccount",
            name="google_email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                fail_soft=True,
                help_text="Email of the connected Google account, for display only.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="area",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, fail_soft=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                fail_soft=True,
                max_length=50000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="discord_username",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="matrix_handle",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="signal_username",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telegram_username",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp_number",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
        migrations.AlterField(
            model_name="profileemail",
            name="email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                fail_soft=True, validators=[django.core.validators.validate_email]
            ),
        ),
        migrations.AlterField(
            model_name="profilenote",
            name="content",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default="", fail_soft=True
            ),
        ),
        migrations.RunPython(
            code=encrypt_existing_contact_and_note_fields,
            reverse_code=decrypt_existing_contact_and_note_fields,
        ),
    ]
