# Generated by Django 6.0.6 on 2026-08-10 02:29

import django.core.validators
from django.db import migrations

import urbanlens.dashboard.models.fields
from urbanlens.dashboard.models.fields import EncryptedTextField

_field = EncryptedTextField()


def _encrypt_column(cursor, table: str, column: str) -> None:
    """Encrypt every existing non-empty value in ``table.column`` in place.

    Mirrors ``encrypt_existing_tokens``/``_encrypt_column`` in
    ``0007_pinshare_bundled_with_markup_map_removed_flags.py``. Uses a raw
    cursor rather than the ORM/historical model so it works regardless of
    operation order relative to the ``AlterField``s above - the historical
    model's field type at this point in the migration is irrelevant since
    nothing here goes through Django's field conversion.
    """
    cursor.execute(f"SELECT id, {column} FROM {table} WHERE {column} IS NOT NULL AND {column} != ''")  # noqa: S608 # nosec B608 - table/column are hardcoded constants below, not user input
    rows = cursor.fetchall()
    for pk, plaintext in rows:
        ciphertext = _field.get_prep_value(plaintext)
        cursor.execute(f"UPDATE {table} SET {column} = %s WHERE id = %s", [ciphertext, pk])  # noqa: S608 # nosec B608 - table/column are hardcoded constants below, not user input


def encrypt_existing_contact_and_note_fields(apps, schema_editor) -> None:
    with schema_editor.connection.cursor() as cursor:
        _encrypt_column(cursor, "dashboard_safety_contact_defaults", "email")
        _encrypt_column(cursor, "dashboard_google_calendar_accounts", "google_email")
        _encrypt_column(cursor, "dashboard_google_photos_accounts", "google_email")
        _encrypt_column(cursor, "dashboard_profiles", "area")
        _encrypt_column(cursor, "dashboard_profiles", "bio")
        _encrypt_column(cursor, "dashboard_profiles", "discord_username")
        _encrypt_column(cursor, "dashboard_profiles", "matrix_handle")
        _encrypt_column(cursor, "dashboard_profiles", "phone_number")
        _encrypt_column(cursor, "dashboard_profiles", "signal_username")
        _encrypt_column(cursor, "dashboard_profiles", "telegram_username")
        _encrypt_column(cursor, "dashboard_profiles", "whatsapp_number")
        _encrypt_column(cursor, "dashboard_profileemail", "email")
        _encrypt_column(cursor, "dashboard_profilenote", "content")


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_drop_redundant_uuid_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontactdefault",
            name="email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, null=True, validators=[django.core.validators.validate_email]
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendaraccount",
            name="google_email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                help_text="Email of the connected Google account, for display only.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="googlephotosaccount",
            name="google_email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                help_text="Email of the connected Google account, for display only.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="area",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                max_length=50000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="discord_username",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="matrix_handle",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="signal_username",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telegram_username",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp_number",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="profileemail",
            name="email",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                validators=[django.core.validators.validate_email]
            ),
        ),
        migrations.AlterField(
            model_name="profilenote",
            name="content",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.RunPython(
            code=encrypt_existing_contact_and_note_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
