# Generated by Django 6.0.6 on 2026-07-14 17:09

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_add_image_media_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("document", "Document"),
                ],
                db_index=True,
                default="photo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="video_downscale_max_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_upload_file_size_mb",
            field=models.IntegerField(
                default=250,
                help_text="Maximum size (MB) for a single photo, video, or document upload. Enforced on both the frontend and backend.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name="Max upload file size (MB)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="video_downscale_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Downscale uploaded videos that exceed the maximum height below, to save storage space.",
                verbose_name="Downscale uploaded videos",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="video_downscale_max_height",
            field=models.IntegerField(
                default=1080,
                help_text="Vertical resolution (px) uploaded videos are downscaled to when downscaling is enabled.",
                validators=[
                    django.core.validators.MinValueValidator(240),
                    django.core.validators.MaxValueValidator(8000),
                ],
                verbose_name="Max video height (px)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="video_downscale_vip",
            field=models.BooleanField(
                default=False,
                help_text="Also downscale video uploads from users with an active subscription. When off, subscribers keep their original video resolution (unless they opt into downscaling themselves).",
                verbose_name="Downscale subscriber videos",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_upload_file_size_mb__gte", 1)),
                name="max_upload_file_size_mb_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("video_downscale_max_height__gte", 240)),
                name="video_downscale_max_height_gte_240",
            ),
        ),
    ]
