# Generated by Django 6.0.6 on 2026-08-31 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_sync_placeaccessgrant_reason_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceExternalTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("overture", "Overture Maps"),
                            ("osm", "OpenStreetMap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_tags",
                        to="dashboard.place",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_place_external_tags",
                "ordering": ["-is_primary", "source", "key"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["place", "source"], name="idxdb_place_exttag_placesrc"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("place", "source", "key", "value"),
                        name="place_external_tag_unique",
                    )
                ],
            },
        ),
    ]
