# Generated by Django 5.1.6 on 2026-05-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_merge_tags_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"kind": "tag"},
                related_name="locations",
                to="dashboard.tag",
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"kind": "tag"},
                related_name="pins",
                to="dashboard.tag",
            ),
        ),
    ]
