# Generated by Django 6.0.6 on 2026-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_add_video_document_upload_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name_source_priority",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated name-provider slugs, highest priority first. Blank uses the site-wide default.",
                max_length=500,
            ),
        ),
    ]
