# Generated by Django 6.0.6 on 2026-08-31 21:58

from django.db import migrations


class Migration(migrations.Migration):
    """Rejoin two 0038 leaves: Image.pending_scan and the PlaceExternalTag branch.

    Both were generated against 0037 independently, so the graph had two leaf
    nodes and every ``migrate`` refused to run. No operations: the two branches
    touch unrelated models and neither needs the other applied first.
    """

    dependencies = [
        ("dashboard", "0038_image_pending_scan"),
        ("dashboard", "0039_place_external_tag"),
    ]

    operations = []
