# Generated by Django 6.0.6 on 2026-08-11 22:40

import urbanlens.dashboard.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_encrypt_contact_and_note_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_gotify_token',
            field=urbanlens.dashboard.models.fields.EncryptedTextField(blank=True, default='', fail_soft=True, help_text='Gotify application token used to authenticate pushes to the server above. Defaults to the UL_GOTIFY_TOKEN environment variable.', verbose_name='Gotify app token'),
        ),
    ]
