# Generated by Django 6.0.6 on 2026-09-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_backfill_trip_comment_location_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='media_unreadable_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
