# Generated by Django 6.0.6 on 2026-08-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_gotify_token_fail_soft'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinimportfailure',
            name='maps_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
