# Generated by Django 6.0.6 on 2026-09-13 12:00

from django.db import migrations

import urbanlens.dashboard.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_image_media_unreadable_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='embedded_keywords',
            field=urbanlens.dashboard.models.fields.EncryptedJSONField(blank=True, fail_soft=True, null=True),
        ),
    ]
