# Generated by Django 6.0.6 on 2026-07-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0040_add_profile_name_source_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedfilter",
            name="icon",
            field=models.CharField(blank=True, default="bookmark", max_length=64),
        ),
    ]
