# Generated by Django 6.0.6 on 2026-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    """Sync PlaceAccessGrant.reason's migration state with its current choices text.

    Pre-existing drift found while adding PlaceExternalTag: the model's
    ``GrantReason`` display strings had diverged from what the last migration
    touching this field recorded, unrelated to that change. Django stores no
    data for ``choices`` (validation/display metadata only), so this is a
    no-op at the database level - split out on its own rather than bundled
    into an unrelated feature migration.
    """

    dependencies = [
        ("dashboard", "0041_alter_notificationlog_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeaccessgrant",
            name="reason",
            field=models.CharField(
                choices=[
                    ("backfill", "Held before places existed"),
                    (
                        "split",
                        "Held the split family - originally, or by earning every current member",
                    ),
                    (
                        "engagement",
                        "Viewed the wiki or shared content to it while access was held",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
