# Generated by Django 6.0.6 on 2026-07-15 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0041_add_saved_filter_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                max_length=1000,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="body",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="markupmapshare",
            name="message",
            field=models.TextField(
                blank=True,
                max_length=5000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(5000)],
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=50000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
        migrations.AlterField(
            model_name="pinlist",
            name="description",
            field=models.TextField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="message",
            field=models.TextField(
                blank=True,
                max_length=5000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(5000)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                max_length=50000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=50000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
        migrations.AlterField(
            model_name="tripactivity",
            name="notes",
            field=models.TextField(
                blank=True,
                max_length=50000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
        migrations.AlterField(
            model_name="tripcomment",
            name="text",
            field=models.TextField(
                max_length=1000,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=50000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
            ),
        ),
    ]
