# Generated by Django 6.0.6 on 2026-07-15 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0042_sync_text_field_validators"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.URLField(max_length=2000)),
                (
                    "wayback_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="dashboard.pin",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_links",
                "ordering": ["order", "id"],
                "abstract": False,
                "indexes": [models.Index(fields=["pin"], name="idxdb_plink_pin")],
            },
        ),
        migrations.CreateModel(
            name="WikiLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.URLField(max_length=2000)),
                (
                    "wayback_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_links_created",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "wiki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="dashboard.wiki",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_wiki_links",
                "ordering": ["order", "id"],
                "abstract": False,
                "indexes": [models.Index(fields=["wiki"], name="idxdb_wlink_wiki")],
            },
        ),
    ]
