# Generated by Django 6.0.6 on 2026-08-31 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0042_sync_placeaccessgrant_reason_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalTagGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_external_tag_groups",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalTagVocabularyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("overture", "Overture Maps"),
                            ("osm", "OpenStreetMap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                ("is_preferred", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="dashboard.externaltaggroup",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_external_tag_vocabulary",
                "ordering": ["source", "key", "value"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["group"], name="idxdb_exttag_vocab_group")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "key", "value"),
                        name="external_tag_vocabulary_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("group",),
                        name="external_tag_vocabulary_one_preferred_per_group",
                    ),
                ],
            },
        ),
    ]
