# Generated by Django 6.0.6 on 2026-07-15 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_add_pin_wiki_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendinvitation",
            name="message",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="request_message",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
    ]
