# Generated by Django 6.0.6 on 2026-08-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_label_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeProcessedRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stripe_refund_id", models.CharField(max_length=255, unique=True)),
                ("stripe_charge_id", models.CharField(blank=True, max_length=255)),
                (
                    "amount_cents",
                    models.IntegerField(
                        default=0,
                        help_text="The refunded amount applied against the banked balance, in cents.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
