# Generated by Django 6.0.6 on 2026-07-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0044_friendinvitation_message_friendship_request_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageMute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_dm_mutes",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("viewer", "sender"), name="db_dm_mute_unique"
                    )
                ],
            },
        ),
    ]
