# Generated by Django 6.0.6 on 2026-08-15 15:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0044_stripe_processed_refund"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="login_ip_max_attempts",
            field=models.IntegerField(
                default=30,
                help_text="Maximum number of failed login attempts from a single IP address (across any accounts) before further attempts from that address are temporarily blocked. Set to 0 to disable the per-IP throttle.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Max failed login attempts per IP",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("login_ip_max_attempts__gte", 0)),
                name="login_ip_max_attempts_gte_0",
            ),
        ),
    ]
