# Generated by Django 5.1.6 on 2026-05-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0044_rename_tag_to_badge"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="badgecustomization",
            name="unique_tag_customization_per_profile",
        ),
        migrations.AlterField(
            model_name="badgecustomization",
            name="badge",
            field=models.ForeignKey(
                db_column="tag_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customizations",
                to="dashboard.badge",
            ),
        ),
        migrations.AlterField(
            model_name="badgecustomization",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="badgecustomization",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge_customizations",
                to="dashboard.profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgecustomization",
            constraint=models.UniqueConstraint(
                fields=("profile", "badge"), name="unique_tag_customization_per_profile"
            ),
        ),
    ]
