# Generated by Django 6.0.6 on 2026-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0045_directmessagemute"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="keyword_label_categories",
            field=models.BooleanField(
                default=True,
                help_text="Keyword matches can automatically add categories when a pin is created.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="keyword_label_statuses",
            field=models.BooleanField(
                default=True,
                help_text="Keyword matches can automatically add a status when a pin is created.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="keyword_label_tags",
            field=models.BooleanField(
                default=True,
                help_text="Keyword matches can automatically add tags when a pin is created.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="keyword_tagging_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow keyword-based auto-tagging on your account.",
            ),
        ),
    ]
