# Generated by Django 6.0.6 on 2026-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_drop_duplicate_fk_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendlog',
            name='email_type',
            field=models.CharField(choices=[('join_invite', 'Friend invitation'), ('visit_invite', 'Visit participant invitation'), ('email_verification', 'Secondary-email verification')], max_length=20),
        ),
    ]
