# Generated by Django 5.1.6 on 2026-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_rename_m2m_tag_id_to_badge_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="badgecustomization",
            name="unique_tag_customization_per_profile",
        ),
        migrations.AddConstraint(
            model_name="badgecustomization",
            constraint=models.UniqueConstraint(
                fields=("profile", "badge"), name="unique_tag_customization_per_profile",
            ),
        ),
    ]
