# Generated by Django 6.0.6 on 2026-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_profile_keyword_tagging_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="direct_message_delete_after",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("when_read", "As soon as they're read"),
                    ("one_day", "1 day after being read"),
                    ("thirty_days", "30 days after being read"),
                    ("ninety_days", "90 days after being read"),
                    ("one_year", "1 year after being read"),
                ],
                default="never",
                help_text="Messages you send are permanently deleted from our systems this long after the recipient reads them - this removes your own copy too. Set to Never to keep them indefinitely.",
                max_length=20,
            ),
        ),
    ]
