# Generated by Django 6.0.6 on 2026-08-15 17:55
"""Encrypt free-text preferences, the saved-contact label, and the invite note.

Same class as the fields encrypted in 0039: user-authored content with no
external source of truth, never matched by value, and - for the contact label
and the invitation note - describing a third party who never consented to being
in this database (in the invitation's case, someone without an account at all).
All are ``fail_soft=True``.

``FriendInvitation.email`` deliberately does NOT follow: it is indexed and
exact-matched at signup to find open invitations. ``FriendInvitation.message``
stays ``null=True`` to match the existing ``bio``/``area`` shape, which means it
does not get the save-time ciphertext preservation that string-defaulted fields
do (see ``models.fields.UndecryptableValue`` and follow-up 4 in
docs/DATA_ENCRYPTION.md).
"""

from cryptography.fernet import InvalidToken
import django.core.validators
from django.db import migrations

import urbanlens.dashboard.models.fields
from urbanlens.dashboard.models.fields import EncryptedTextField, _fernet

_field = EncryptedTextField()

#: ``(table, column)`` pairs to encrypt in place. Hardcoded, never interpolated
#: from user input - see the noqa justifications in ``_encrypt_column``.
_COLUMNS = [
    ("dashboard_friendinvitation", "message"),
    ("dashboard_safety_contact_defaults", "label"),
    ("dashboard_profiles", "additional_preferences"),
    ("dashboard_profiles", "exploring_with_others_preference_other"),
    ("dashboard_profiles", "friend_request_preference_other"),
    ("dashboard_profiles", "meetup_preference_other"),
    ("dashboard_profiles", "photo_sharing_preference_other"),
    ("dashboard_profiles", "photo_tagging_preference_other"),
    ("dashboard_profiles", "photo_taking_preference_other"),
    ("dashboard_profiles", "photo_usage_preference_other"),
]


def _already_encrypted(value: str) -> bool:
    """True when ``value`` is already ciphertext this install can read.

    Makes the pass idempotent. The 0007/0039 versions of this helper were not:
    running one of them a second time encrypts the ciphertext again, and the
    ORM's single decrypt then yields the inner ciphertext instead of the
    plaintext - silent, permanent-looking corruption. Django applies a migration
    once, so that was latent rather than live, but a squash replay or a manual
    re-run of the function is enough to trigger it, and skipping already-readable
    values costs one decrypt attempt per row.

    Args:
        value: The raw stored column value.

    Returns:
        True when the value decrypts under some configured key.
    """
    try:
        _fernet().decrypt(value.encode())
    except (InvalidToken, UnicodeEncodeError):
        return False
    return True


def _encrypt_column(cursor, table: str, column: str) -> None:
    """Encrypt every existing non-empty value in ``table.column`` in place.

    Mirrors ``_encrypt_column`` in 0039 (and 0007 before it). Uses a raw cursor
    rather than the ORM so it is unaffected by the historical model's field
    type, and therefore by operation order relative to the ``AlterField``s.
    Without this pass, every pre-existing row would raise ``InvalidToken`` on
    its first read after deploy - the retrofit hazard documented in
    docs/DATA_ENCRYPTION.md.
    """
    cursor.execute(f"SELECT id, {column} FROM {table} WHERE {column} IS NOT NULL AND {column} != ''")  # noqa: S608 # nosec B608 - identifiers come from _COLUMNS, not user input
    for pk, stored in cursor.fetchall():
        if _already_encrypted(stored):
            continue
        cursor.execute(f"UPDATE {table} SET {column} = %s WHERE id = %s", [_field.get_prep_value(stored), pk])  # noqa: S608 # nosec B608 - identifiers come from _COLUMNS, not user input


def encrypt_existing_preference_fields(apps, schema_editor) -> None:
    """Encrypt the pre-existing plaintext values for every column in ``_COLUMNS``."""
    with schema_editor.connection.cursor() as cursor:
        for table, column in _COLUMNS:
            _encrypt_column(cursor, table, column)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0047_link_url_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendinvitation",
            name="message",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                fail_soft=True,
                max_length=1000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="emergencycontactdefault",
            name="label",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=150,
                validators=[django.core.validators.MaxLengthValidator(150)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="additional_preferences",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                help_text="Anything else you'd like other users to know about interacting with you.",
                max_length=1000,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="exploring_with_others_preference_other",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="friend_request_preference_other",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="meetup_preference_other",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_sharing_preference_other",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_tagging_preference_other",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_taking_preference_other",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_usage_preference_other",
            field=urbanlens.dashboard.models.fields.EncryptedTextField(
                blank=True,
                default="",
                fail_soft=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
        migrations.RunPython(
            code=encrypt_existing_preference_fields,
            # Irreversible by design: reversing would need to decrypt under
            # whatever key is active at rollback time, and getting that wrong
            # writes garbage over real data. Restore from a backup instead.
            reverse_code=migrations.RunPython.noop,
        ),
    ]
