# Generated by Django 6.0.6 on 2026-07-15 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0047_alter_profile_direct_message_delete_after"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="max_friends_per_user",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of friends a user may have. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="Max friends per user",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_group_chat_members",
            field=models.IntegerField(
                default=20,
                help_text="Maximum number of members allowed in a direct message group chat. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="Max group chat members",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_pins_per_list",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of pins allowed in a single list. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="Max pins per list",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_safety_checkin_contacts",
            field=models.IntegerField(
                default=5,
                help_text="Maximum number of contacts a user may notify per safety check-in. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Max contacts per safety check-in",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_trip_activities",
            field=models.IntegerField(
                default=100,
                help_text="Maximum number of activities allowed per trip. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="Max activities per trip",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_upcoming_trips_per_user",
            field=models.IntegerField(
                default=100,
                help_text="Maximum number of upcoming (or undated, still-planning) trips a user may belong to at once. Set to 0 for unlimited.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="Max upcoming trips per user",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_trip_activities__gte", 0)),
                name="max_trip_activities_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_upcoming_trips_per_user__gte", 0)),
                name="max_upcoming_trips_per_user_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_pins_per_list__gte", 0)),
                name="max_pins_per_list_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_friends_per_user__gte", 0)),
                name="max_friends_per_user_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_group_chat_members__gte", 0)),
                name="max_group_chat_members_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_safety_checkin_contacts__gte", 0)),
                name="max_safety_checkin_contacts_gte_0",
            ),
        ),
    ]
