# Generated by Django 6.0.8 on 2026-09-16 14:37

import django.contrib.postgres.indexes
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_pgvector_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='label',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper(django.db.models.functions.comparison.Cast('name', output_field=models.TextField())), name='gin_trgm_ops'), name='idxdb_label_name_upper_trgm'),
        ),
    ]
