# Generated by Django 6.0.6 on 2026-08-16 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0048_encrypt_preference_and_contact_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="credential_prompt_snoozed_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webauthncredential",
            name="is_login_factor",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="E2EEPasskeyWrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("prf_input", models.CharField(max_length=64)),
                ("wrapped_secret", models.TextField()),
                ("bundle_version", models.PositiveIntegerField()),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_wraps",
                        to="dashboard.messagingkeybundle",
                    ),
                ),
                (
                    "credential",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e2ee_wrap",
                        to="dashboard.webauthncredential",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_e2ee_passkey_wrap",
                "abstract": False,
            },
        ),
    ]
