# Generated by Django 6.0.6 on 2026-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0048_site_settings_new_limits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="search_provider",
            field=models.CharField(
                choices=[
                    ("brave", "Brave Search"),
                    ("google", "Google Custom Search"),
                    ("searxng", "SearXNG (self-hosted, free)"),
                    ("duckduckgo", "DuckDuckGo Instant Answer (free)"),
                    ("mojeek", "Mojeek Search"),
                    ("marginalia", "Marginalia Search"),
                ],
                default="brave",
                help_text="Preferred web search provider for pin news/search results, tried first. If it's unconfigured, rate-limited, or fails, the remaining providers (SearXNG, Google, Brave, DuckDuckGo, Mojeek, Marginalia) are tried automatically in that order.",
                max_length=20,
                verbose_name="Search provider",
            ),
        ),
    ]
