# Generated by Django 6.0.6 on 2026-09-02 22:05

import urbanlens.dashboard.models.images.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_friendinvitation_email_normalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="analysis_thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=urbanlens.dashboard.models.images.model.pin_image_analysis_thumbnail_path,
            ),
        ),
    ]
