# Generated by Django 6.0.6 on 2026-07-15 19:29

import random

from django.db import migrations, models


def _slugify_base(name: str | None) -> str:
    from django.utils.text import slugify

    return slugify(name) or "list"


def backfill_pin_list_slugs(apps, schema_editor):
    """Mint a slug for every pre-existing PinList row, unique per profile.

    Mirrors ``backfill_trip_slugs`` (see the 0007 squashed migration) but
    scopes the uniqueness check to ``profile_id`` instead of checking
    globally, since PinList slugs only need to be unique per-user.
    """
    PinList = apps.get_model("dashboard", "PinList")
    for pin_list in PinList.objects.filter(slug__isnull=True).iterator():
        base = _slugify_base(pin_list.name)[:255]
        candidate = base
        while PinList.objects.filter(profile_id=pin_list.profile_id, slug=candidate).exclude(pk=pin_list.pk).exists():
            suffix = f"-{random.randint(2, 90_000)}"  # noqa: S311 # nosec: B311 - not for cryptographic use
            candidate = base[: 255 - len(suffix)] + suffix
        PinList.objects.filter(pk=pin_list.pk).update(slug=candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_search_provider_fallback_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinlist",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(backfill_pin_list_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="pinlist",
            constraint=models.UniqueConstraint(
                fields=("profile", "slug"), name="uq_pin_list_profile_slug"
            ),
        ),
    ]
