# Generated by Django 6.0.6 on 2026-07-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0050_pin_list_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpaFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "registry_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                ("detail_fetched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_epa_facility",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"], name="idxdb_epafac_lat_lng"
                    )
                ],
            },
        ),
    ]
