# Generated by Django 6.0.8 on 2026-09-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_notification_log_message_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_comments', to='dashboard.profile'),
        ),
    ]
