# Generated by Django 6.0.6 on 2026-08-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_merge_20260817_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='buildings_auto_nested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_create_building_pins',
            field=models.BooleanField(default=True, help_text='Automatically add child pins for the buildings on a property when they are confidently identified. Ambiguous buildings still wait for your approval.'),
        ),
    ]
