# Generated by Django 6.0.6 on 2026-07-16 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0051_epa_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiratelimit",
            name="calls_per_30_days",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum calls allowed per rolling 30-day window. Leave blank for no 30-day limit.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000000),
                ],
            ),
        ),
    ]
