# Generated by Django 6.0.6 on 2026-08-18 02:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_nest_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('building_ref', models.CharField(blank=True, default='', max_length=255)),
                ('building_name', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('floor_count', models.IntegerField(blank=True, null=True)),
                ('labels', models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label')),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floorplans', to='dashboard.pin')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floorplans', to='dashboard.place')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_floorplans',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorplanReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('pdf', 'PDF'), ('video', 'Video'), ('document', 'Document'), ('model', '3D model / CAD file'), ('other', 'Other')], default='other', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_pool', to='dashboard.floorplan')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplan_references', to='dashboard.image')),
            ],
            options={
                'db_table': 'dashboard_floorplan_references',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorplanFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('level', models.SmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('elevation_meters', models.FloatField(blank=True, null=True)),
                ('height_meters', models.FloatField(blank=True, null=True)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='dashboard.floorplan')),
                ('labels', models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label')),
                ('references', models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference')),
            ],
            options={
                'db_table': 'dashboard_floorplan_floors',
                'ordering': ('level',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='floorplan',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference'),
        ),
        migrations.CreateModel(
            name='FloorplanRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('height_meters', models.FloatField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dashboard.floorplanfloor')),
                ('labels', models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label')),
                ('references', models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference')),
            ],
            options={
                'db_table': 'dashboard_floorplan_rooms',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorplanElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('wall', 'Wall'), ('floor', 'Floor surface'), ('ceiling', 'Ceiling'), ('roof', 'Roof'), ('column', 'Column'), ('window', 'Window'), ('door', 'Door'), ('stair', 'Stair'), ('fixture', 'Fixture'), ('key', 'Key'), ('other', 'Other')], max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('material', models.CharField(blank=True, default='', max_length=255)),
                ('base_elevation_meters', models.FloatField(blank=True, null=True)),
                ('height_meters', models.FloatField(blank=True, null=True)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='dashboard.floorplan')),
                ('labels', models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label')),
                ('mounted_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounted_elements', to='dashboard.floorplanelement')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='dashboard.floorplanfloor')),
                ('references', models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='dashboard.floorplanroom')),
            ],
            options={
                'db_table': 'dashboard_floorplan_elements',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorplanSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('note', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floorplan_sources', to='dashboard.image')),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pool', to='dashboard.floorplan')),
            ],
            options={
                'db_table': 'dashboard_floorplan_sources',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='floorplanroom',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
        migrations.CreateModel(
            name='FloorplanLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('key_attributes', models.JSONField(blank=True, default=dict)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='dashboard.floorplanelement')),
                ('labels', models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label')),
                ('references', models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource')),
            ],
            options={
                'db_table': 'dashboard_floorplan_locks',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='floorplanfloor',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
        migrations.AddField(
            model_name='floorplanelement',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
    ]
