# Generated by Django 6.0.6 on 2026-08-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_floorplans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplanelement',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='floorplanlock',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='floorplanroom',
            options={'ordering': ('id',)},
        ),
    ]
