# Generated by Django 6.0.6 on 2026-07-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0052_api_rate_limit_30_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pin_detail_map_height",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
