# Generated by Django 6.0.6 on 2026-08-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_floorplan_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': [models.OrderBy(models.F('valid_from'), descending=True, nulls_last=True), '-created']},
        ),
        migrations.AlterModelOptions(
            name='floorplanelement',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='floorplanfloor',
            options={'ordering': ('level', 'sort_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='floorplanlock',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='floorplanroom',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AddField(
            model_name='floorplan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='wiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='dashboard.wiki'),
        ),
        migrations.AddField(
            model_name='floorplanelement',
            name='connects_rooms',
            field=models.ManyToManyField(blank=True, related_name='connecting_elements', to='dashboard.floorplanroom'),
        ),
        migrations.AddField(
            model_name='floorplanelement',
            name='rotation_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplanelement',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplanelement',
            name='spans_floors',
            field=models.ManyToManyField(blank=True, related_name='spanning_elements', to='dashboard.floorplanfloor'),
        ),
        migrations.AddField(
            model_name='floorplanelement',
            name='thickness_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplanfloor',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplanlock',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplanroom',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboard.floorplanroom'),
        ),
        migrations.AddField(
            model_name='floorplanroom',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplanroom',
            name='spans_floors',
            field=models.ManyToManyField(blank=True, related_name='spanning_rooms', to='dashboard.floorplanfloor'),
        ),
        migrations.AlterField(
            model_name='floorplanelement',
            name='kind',
            field=models.CharField(choices=[('wall', 'Wall'), ('floor', 'Floor surface'), ('ceiling', 'Ceiling'), ('roof', 'Roof'), ('column', 'Column'), ('window', 'Window'), ('door', 'Door'), ('stair', 'Stair'), ('fixture', 'Fixture'), ('furniture', 'Furniture'), ('key', 'Key'), ('other', 'Other')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='floorplan',
            index=models.Index(fields=['place', 'profile', 'valid_from'], name='idx_floorplan_place_owner_date'),
        ),
        migrations.AddIndex(
            model_name='floorplanelement',
            index=models.Index(fields=['floorplan', 'kind'], name='idx_floorplan_element_kind'),
        ),
    ]
