# Generated by Django 5.1.6 on 2026-05-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0054_comment_extensions_reactions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"get_latest_by": "updated", "ordering": ["created"]},
        ),
        migrations.RemoveIndex(
            model_name="notificationlog",
            name="dashboard_n_notific_045386_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationlog",
            name="dashboard_notif_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationlog",
            name="dashboard_notif_importance_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="dashboard_n_profile_f04aa9_idx",
            old_name="dashboard_notif_profile_status_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="dashboard_n_notific_025668_idx",
            old_name="dashboard_notif_type_idx",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="importance",
            field=models.CharField(
                choices=[
                    ("lowest", "Lowest"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("highest", "Highest"),
                ],
                default="lowest",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("read", "Notifcation is unread: has not been seen."),
                    ("unread", "Notifcaiton has been seen."),
                    ("dismissed", "Notification was dismissed."),
                ],
                default="read",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="added_to_trip",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="comment_liked",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="comment_reply",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="friend_accepted",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="friend_request",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="message",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="trip_updated",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="wiki_updated",
            field=models.CharField(
                choices=[
                    ("none", "Do not deliver."),
                    ("site", "In-site notification only."),
                    ("email", "Email only."),
                    ("both", "In-site and email."),
                ],
                default="site",
                max_length=10,
            ),
        ),
    ]
