# Generated by Django 6.0.6 on 2026-09-05 12:28

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_merge_reciprocal_friendships'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('from_profile_id', 'to_profile_id'), django.db.models.functions.comparison.Greatest('from_profile_id', 'to_profile_id'), name='friendship_one_row_per_pair'),
        ),
    ]
