# Generated by Django 6.0.6 on 2026-07-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0054_site_settings_background_enrichment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageLocationMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("coordinates", "Coordinates"),
                            ("address", "Street Address"),
                        ],
                        default="coordinates",
                        max_length=20,
                    ),
                ),
                (
                    "matched_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "db_table": "dashboard_dm_location_mentions",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("share_received", "Share Received"),
                            ("pin_moved", "Pin Moved"),
                        ],
                        default="share_received",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_location_exposures",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pinshare",
            name="detected_via_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detected_pin_shares",
                to="dashboard.directmessage",
            ),
        ),
        migrations.AddField(
            model_name="pinshare",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pin_shares",
                to="dashboard.location",
            ),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="origin",
            field=models.CharField(
                choices=[
                    ("explicit", "Explicit Share"),
                    ("map_detected", "Detected From Shared Map"),
                    ("dm_detected", "Detected From Message"),
                    ("trip_activity", "Shared As Trip Activity"),
                ],
                default="explicit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="dashboard.pin",
            ),
        ),
        migrations.AlterField(
            model_name="pinshare",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("already_pinned", "Already pinned"),
                    ("detected", "Detected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="pinshare",
            index=models.Index(
                fields=["to_profile", "location"], name="idxdb_pinshr_to_pfl_loc"
            ),
        ),
        migrations.AddField(
            model_name="directmessagelocationmention",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="directmessagelocationmention",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_mentions",
                to="dashboard.directmessage",
            ),
        ),
        migrations.AddField(
            model_name="directmessagelocationmention",
            name="pin_share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dm_mentions",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddField(
            model_name="locationexposure",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exposures",
                to="dashboard.location",
            ),
        ),
        migrations.AddField(
            model_name="locationexposure",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_exposures",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="locationexposure",
            name="share",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exposures",
                to="dashboard.pinshare",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessagelocationmention",
            index=models.Index(fields=["message"], name="idxdb_dmlocm_message"),
        ),
        migrations.AddConstraint(
            model_name="directmessagelocationmention",
            constraint=models.UniqueConstraint(
                fields=("message", "location"), name="db_dmlocm_one_per_msg_loc"
            ),
        ),
        migrations.AddIndex(
            model_name="locationexposure",
            index=models.Index(
                fields=["profile", "location"], name="idxdb_locexp_pfl_loc"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationexposure",
            constraint=models.UniqueConstraint(
                fields=("profile", "location", "share"),
                name="db_locexp_one_per_pfl_loc_share",
            ),
        ),
    ]
