# Generated by Django 6.0.8 on 2026-09-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_common_pins_hidden_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicalllog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The upstream's HTTP status. Null when no response arrived (refused before sending, a network error) or the caller had none to record.", null=True),
        ),
    ]
