# Generated by Django 6.0.6 on 2026-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_protect_want_to_go'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disable_auto_tagging',
            field=models.BooleanField(default=False, help_text='Turn off automatic tagging of your pins. Individual labels can also be excluded on the Organize page.'),
        ),
    ]
