# Generated by Django 6.0.6 on 2026-09-07 00:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_friendship_one_row_per_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationevent',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6),
        ),
        migrations.AddField(
            model_name='reputationevent',
            name='weight_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
