# Generated by Django 6.0.8 on 2026-09-24 00:57

import django.db.models.deletion
import urbanlens.dashboard.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_apicalllog_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendlog',
            name='email_type',
            field=models.CharField(choices=[('join_invite', 'Friend invitation'), ('visit_invite', 'Visit participant invitation'), ('email_verification', 'Secondary-email verification'), ('trip_invite', 'Trip invitation')], max_length=20),
        ),
        migrations.CreateModel(
            name='TripInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', urbanlens.dashboard.models.fields.EncryptedTextField(blank=True, default='', fail_soft=True)),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('trip_response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('friend_response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_trip_invitations', to='dashboard.profile')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trip_invitations', to='dashboard.profile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_invitations', to='dashboard.trip')),
            ],
            options={
                'db_table': 'dashboard_trip_invitations',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('trip', 'email_hash'), name='trip_invitation_one_per_address')],
            },
        ),
    ]
