# Generated by Django 6.0.6 on 2026-07-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0056_backfill_share_locations_and_exposures"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="dashboard.pin",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_owner",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PinPropertySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "new_owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sales_as_new_owner",
                        to="dashboard.pinowner",
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_sales",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "previous_owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sales_as_previous_owner",
                        to="dashboard.pinowner",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_pin_property_sale",
                "ordering": ["-sale_date", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User contributed"),
                            ("official", "Official"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_owners_created",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, related_name="owners", to="dashboard.location"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_wiki_owner",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiPropertySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User contributed"),
                            ("official", "Official"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_property_sales_created",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="dashboard.location",
                    ),
                ),
                (
                    "new_owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sales_as_new_owner",
                        to="dashboard.wikiowner",
                    ),
                ),
                (
                    "previous_owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sales_as_previous_owner",
                        to="dashboard.wikiowner",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_wiki_property_sale",
                "ordering": ["-sale_date", "-created"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="pinowner",
            index=models.Index(fields=["pin"], name="idxdb_pinowner_pin"),
        ),
        migrations.AddIndex(
            model_name="pinpropertysale",
            index=models.Index(
                fields=["pin", "-sale_date"], name="idxdb_pin_sale_pin_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="pinpropertysale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_price__isnull", True),
                    ("sale_price__gte", 0),
                    _connector="OR",
                ),
                name="db_pin_sale_price_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="wikipropertysale",
            index=models.Index(
                fields=["location", "-sale_date"], name="idxdb_wiki_sale_location_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikipropertysale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_price__isnull", True),
                    ("sale_price__gte", 0),
                    _connector="OR",
                ),
                name="db_wiki_sale_price_gte_0",
            ),
        ),
    ]
