# Generated by Django 6.0.6 on 2026-07-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0056_backfill_share_locations_and_exposures"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, related_name="owners", to="dashboard.location"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_property_owner",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="dashboard.location",
                    ),
                ),
                (
                    "new_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_as_new_owner",
                        to="dashboard.owner",
                    ),
                ),
                (
                    "previous_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_as_previous_owner",
                        to="dashboard.owner",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_property_sale",
                "ordering": ["-sale_date", "-created"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["location", "-sale_date"],
                        name="idxdb_property_sale_location_date",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sale_price__isnull", True),
                            ("sale_price__gte", 0),
                            _connector="OR",
                        ),
                        name="db_property_sale_price_gte_0",
                    )
                ],
            },
        ),
    ]
