# Generated by Django 6.0.6 on 2026-07-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0057_owner_and_property_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertysale",
            name="new_owner",
        ),
        migrations.RemoveField(
            model_name="propertysale",
            name="previous_owner",
        ),
        migrations.AddField(
            model_name="owner",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owners_created",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="pins",
            field=models.ManyToManyField(
                blank=True, related_name="private_owners", to="dashboard.pin"
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="source",
            field=models.CharField(
                choices=[("user", "User contributed"), ("official", "Official")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private (only visible on your own pin)"),
                    ("shared", "Shared (visible to everyone with a pin here)"),
                ],
                default="shared",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="propertysale",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="property_sales_created",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="propertysale",
            name="new_owners",
            field=models.ManyToManyField(
                blank=True, related_name="sales_as_new_owner", to="dashboard.owner"
            ),
        ),
        migrations.AddField(
            model_name="propertysale",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_sales",
                to="dashboard.pin",
            ),
        ),
        migrations.AddField(
            model_name="propertysale",
            name="previous_owners",
            field=models.ManyToManyField(
                blank=True, related_name="sales_as_previous_owner", to="dashboard.owner"
            ),
        ),
        migrations.AddField(
            model_name="propertysale",
            name="source",
            field=models.CharField(
                choices=[("user", "User contributed"), ("official", "Official")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="propertysale",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private (only visible on your own pin)"),
                    ("shared", "Shared (visible to everyone with a pin here)"),
                ],
                default="shared",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source", "user"), ("visibility", "shared"), _connector="OR"
                ),
                name="db_property_owner_official_is_shared",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertysale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source", "user"), ("visibility", "shared"), _connector="OR"
                ),
                name="db_property_sale_official_is_shared",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertysale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("visibility", "shared"), ("pin__isnull", False), _connector="OR"
                ),
                name="db_property_sale_private_requires_pin",
            ),
        ),
    ]
