# Generated by Django 5.1.6 on 2026-05-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0057_tripactivity_new_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="added_to_trip",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="comment_liked",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="comment_reply",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="friend_accepted",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="friend_request",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="message",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="trip_updated",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="wiki_updated",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("site", "Notification"),
                    ("email", "Email"),
                    ("both", "Notification and email"),
                ],
                default="site",
                max_length=10,
            ),
        ),
    ]
