# Generated by Django 6.0.6 on 2026-08-21 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_directional_friendship_mute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorplanMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('kind', models.CharField(choices=[('photo', 'Photo location'), ('hazard', 'Hazard'), ('entrance', 'Entrance'), ('stair', 'Stair'), ('elevator', 'Elevator / shaft'), ('note', 'Note'), ('fixture', 'Fixture')], default='note', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('facing_degrees', models.FloatField(blank=True, null=True)),
                ('connector_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'dashboard_floorplan_markers',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorplanOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('door', 'Door'), ('doorway', 'Doorway (no door)'), ('window', 'Window'), ('hatch', 'Hatch')], default='door', max_length=16)),
                ('t_start', models.FloatField()),
                ('t_end', models.FloatField()),
                ('swing', models.CharField(choices=[('none', 'Not known'), ('left', 'Left'), ('right', 'Right'), ('double', 'Double')], default='none', max_length=8)),
                ('sill_meters', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_floorplan_openings',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorplanRoomSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('height_meters', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_floorplan_room_seeds',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorplanWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('ax', models.FloatField()),
                ('ay', models.FloatField()),
                ('bx', models.FloatField()),
                ('by', models.FloatField()),
                ('kind', models.CharField(choices=[('exterior', 'Exterior wall'), ('interior', 'Interior wall'), ('virtual', 'Virtual (open edge)'), ('collapsed', 'Collapsed / ruined')], default='interior', max_length=16)),
                ('thickness', models.CharField(choices=[('thin', 'Thin'), ('normal', 'Normal'), ('thick', 'Thick')], default='normal', max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'dashboard_floorplan_walls',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='floorplanelement',
            name='idx_floorplan_element_kind',
        ),
        migrations.RemoveField(
            model_name='floorplanroom',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='floorplanroom',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='floorplanroom',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='floorplanroom',
            name='references',
        ),
        migrations.RemoveField(
            model_name='floorplanroom',
            name='source',
        ),
        migrations.RemoveField(
            model_name='floorplanroom',
            name='spans_floors',
        ),
        migrations.RemoveField(
            model_name='floorplanfloor',
            name='geometry',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='origin_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='origin_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='rotation_degrees',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='floorplans', to='dashboard.place'),
        ),
        migrations.AddField(
            model_name='floorplanmarker',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='dashboard.floorplanfloor'),
        ),
        migrations.AddField(
            model_name='floorplanmarker',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label'),
        ),
        migrations.AddField(
            model_name='floorplanmarker',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference'),
        ),
        migrations.AddField(
            model_name='floorplanmarker',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
        migrations.AddField(
            model_name='floorplanopening',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label'),
        ),
        migrations.AddField(
            model_name='floorplanopening',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference'),
        ),
        migrations.AddField(
            model_name='floorplanopening',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
        migrations.AddField(
            model_name='floorplanroomseed',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dashboard.floorplanfloor'),
        ),
        migrations.AddField(
            model_name='floorplanroomseed',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label'),
        ),
        migrations.AddField(
            model_name='floorplanroomseed',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference'),
        ),
        migrations.AddField(
            model_name='floorplanroomseed',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
        migrations.AddField(
            model_name='floorplanwall',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='dashboard.floorplanfloor'),
        ),
        migrations.AddField(
            model_name='floorplanwall',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label'),
        ),
        migrations.AddField(
            model_name='floorplanwall',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference'),
        ),
        migrations.AddField(
            model_name='floorplanwall',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource'),
        ),
        migrations.AddField(
            model_name='floorplanopening',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='dashboard.floorplanwall'),
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='connects_rooms',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='floorplan',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='mounted_on',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='references',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='room',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='source',
        ),
        migrations.RemoveField(
            model_name='floorplanelement',
            name='spans_floors',
        ),
        migrations.DeleteModel(
            name='FloorplanLock',
        ),
        migrations.DeleteModel(
            name='FloorplanRoom',
        ),
        migrations.DeleteModel(
            name='FloorplanElement',
        ),
        # Indexes and constraints last, after every schema and cleanup step -
        # see migrations/CLAUDE.md.
        migrations.AddIndex(
            model_name='floorplanmarker',
            index=models.Index(fields=['connector_id'], name='idx_floorplan_marker_connector'),
        ),
        migrations.AddIndex(
            model_name='floorplanwall',
            index=models.Index(fields=['floor', 'kind'], name='idx_floorplan_wall_kind'),
        ),
        migrations.AddConstraint(
            model_name='floorplanopening',
            constraint=models.CheckConstraint(condition=models.Q(('t_start__gte', 0), ('t_end__lte', 1), ('t_start__lt', models.F('t_end'))), name='floorplan_opening_within_wall'),
        ),
    ]
