# Generated by Django 6.0.8 on 2026-09-24 01:49

from django.db import migrations, models
from django.db.models import F


def trust_verified_signups(apps, schema_editor):
    """Treat the current primary of every account that verified its signup address as verified.

    Nothing recorded which address was verified, so an address changed since signup is trusted too.
    """
    Profile = apps.get_model("dashboard", "Profile")
    Profile.objects.filter(user__email_verification__verified_at__isnull=False).update(verified_primary_email=F("primary_email_normalized"))


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0057_trip_invitations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tripinvitation",
            name="trip_invitation_one_per_address",
        ),
        migrations.AddField(
            model_name="profile",
            name="verified_primary_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddConstraint(
            model_name="tripinvitation",
            constraint=models.UniqueConstraint(fields=("trip", "inviter", "email_hash"), name="trip_invitation_one_per_inviter_address"),
        ),
        migrations.RunPython(trust_verified_signups, migrations.RunPython.noop),
    ]
