# Generated by Django 6.0.8 on 2026-09-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_verified_primary_email_and_per_inviter_trip_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendlog',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_friend_invitations', to='dashboard.profile'),
        ),
    ]
