# Generated by Django 6.0.6 on 2026-08-21 15:02
#
# Re-adds the lock table dropped by 0058. It now hangs off FloorplanOpening
# rather than the deleted FloorplanElement, so nothing survived to migrate -
# 0058 deleted those rows outright. One CreateModel, no index or constraint
# operations, so nothing has to be ordered after anything.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_floorplans_wall_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorplanLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('built_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(choices=[('unknown', 'Not known'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], default='unknown', max_length=16)),
                ('key_attributes', models.JSONField(blank=True, default=dict)),
                ('labels', models.ManyToManyField(blank=True, related_name='floorplan_%(class)ss', to='dashboard.label')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='dashboard.floorplanopening')),
                ('references', models.ManyToManyField(blank=True, related_name='%(class)ss', to='dashboard.floorplanreference')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.floorplansource')),
            ],
            options={
                'db_table': 'dashboard_floorplan_locks',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
