# Generated by Django 6.0.6 on 2026-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_floorplan_locks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplanmarker',
            name='kind',
            field=models.CharField(choices=[('hazard', 'Hazard'), ('stair', 'Stair'), ('elevator', 'Elevator / shaft')], default='hazard', max_length=16),
        ),
    ]
