# Generated by Django 5.1.6 on 2026-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0059_friendship_ignored_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="friend_request_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("no_one", "No one"),
                ],
                default="anyone",
                max_length=20,
            ),
        ),
    ]
