# Generated by Django 6.0.6 on 2026-07-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0059_pinlist_source_saved_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="theme_mode",
            field=models.CharField(
                choices=[
                    ("system", "System (follows your OS)"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="dark",
                max_length=10,
            ),
        ),
    ]
