# Generated by Django 6.0.6 on 2026-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0060_profile_theme_default_dark"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="common_pins_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone (Logged In)"),
                    ("anything_in_common", "Users with anything in common"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("friends", "Friends Only"),
                    ("no_one", "No one"),
                ],
                default="friends",
                help_text="Who can see the specific pins you have in common with them. Requires both of you to allow it.",
                max_length=20,
            ),
        ),
    ]
