# Generated by Django 6.0.6 on 2026-08-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0060_alter_floorplanmarker_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplanmarker",
            name="linked_pin",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="floorplan_marker", to="dashboard.pin"),
        ),
        migrations.AlterField(
            model_name="pin",
            name="pin_type",
            field=models.CharField(choices=[("location", "Location"), ("parcel", "Property / Parcel"), ("building", "Building"), ("entrance", "Entrance"), ("poi", "Point of Interest"), ("danger", "Danger"), ("stair", "Stair"), ("elevator", "Elevator / shaft"), ("other", "Other")], default="location", max_length=30),
        ),
        migrations.AlterField(
            model_name="pinsuggestion",
            name="suggested_pin_type",
            field=models.CharField(blank=True, choices=[("location", "Location"), ("parcel", "Property / Parcel"), ("building", "Building"), ("entrance", "Entrance"), ("poi", "Point of Interest"), ("danger", "Danger"), ("stair", "Stair"), ("elevator", "Elevator / shaft"), ("other", "Other")], default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="pin_type",
            field=models.CharField(choices=[("location", "Location"), ("parcel", "Property / Parcel"), ("building", "Building"), ("entrance", "Entrance"), ("poi", "Point of Interest"), ("danger", "Danger"), ("stair", "Stair"), ("elevator", "Elevator / shaft"), ("other", "Other")], default="location", max_length=30),
        ),
    ]
