# Generated by Django 6.0.6 on 2026-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0061_profile_common_pins_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customfield",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("short", "Short (single line)"),
                    ("long", "Long (multi-line)"),
                    ("input", "Number input"),
                    ("stars", "Star rating"),
                    ("slider", "Slider"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_boolean",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="value_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("url", "Link"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["field", "value_time"], name="idxdb_cfv_field_time"
            ),
        ),
    ]
