# Generated by Django 6.0.6 on 2026-07-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0062_custom_field_styles_and_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_references",
                to="dashboard.image",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_markup_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_references",
                to="dashboard.markupmap",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_references",
                to="dashboard.pin",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_pin_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_references",
                to="dashboard.pinlist",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_references",
                to="dashboard.profile",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_references",
                to="dashboard.trip",
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="ref_wiki",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_references",
                to="dashboard.wiki",
            ),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("url", "Link"),
                    ("reference", "Reference"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ref_image__isnull", True),
                        ("ref_markup_map__isnull", True),
                        ("ref_pin__isnull", True),
                        ("ref_pin_list__isnull", True),
                        ("ref_profile__isnull", True),
                        ("ref_trip__isnull", True),
                        ("ref_wiki__isnull", True),
                    ),
                    models.Q(
                        ("ref_image__isnull", True),
                        ("ref_markup_map__isnull", True),
                        ("ref_pin__isnull", False),
                        ("ref_pin_list__isnull", True),
                        ("ref_profile__isnull", True),
                        ("ref_trip__isnull", True),
                        ("ref_wiki__isnull", True),
                    ),
                    models.Q(
                        ("ref_image__isnull", True),
                        ("ref_markup_map__isnull", True),
                        ("ref_pin__isnull", True),
                        ("ref_pin_list__isnull", True),
                        ("ref_profile__isnull", True),
                        ("ref_trip__isnull", True),
                        ("ref_wiki__isnull", False),
                    ),
                    models.Q(
                        ("ref_image__isnull", True),
                        ("ref_markup_map__isnull", False),
                        ("ref_pin__isnull", True),
                        ("ref_pin_list__isnull", True),
                        ("ref_profile__isnull", True),
                        ("ref_trip__isnull", True),
                        ("ref_wiki__isnull", True),
                    ),
                    models.Q(
                        ("ref_image__isnull", True),
                        ("ref_markup_map__isnull", True),
                        ("ref_pin__isnull", True),
                        ("ref_pin_list__isnull", True),
                        ("ref_profile__isnull", True),
                        ("ref_trip__isnull", False),
                        ("ref_wiki__isnull", True),
                    ),
                    models.Q(
                        ("ref_image__isnull", False),
                        ("ref_markup_map__isnull", True),
                        ("ref_pin__isnull", True),
                        ("ref_pin_list__isnull", True),
                        ("ref_profile__isnull", True),
                        ("ref_trip__isnull", True),
                        ("ref_wiki__isnull", True),
                    ),
                    models.Q(
                        ("ref_image__isnull", True),
                        ("ref_markup_map__isnull", True),
                        ("ref_pin__isnull", True),
                        ("ref_pin_list__isnull", False),
                        ("ref_profile__isnull", True),
                        ("ref_trip__isnull", True),
                        ("ref_wiki__isnull", True),
                    ),
                    models.Q(
                        ("ref_image__isnull", True),
                        ("ref_markup_map__isnull", True),
                        ("ref_pin__isnull", True),
                        ("ref_pin_list__isnull", True),
                        ("ref_profile__isnull", False),
                        ("ref_trip__isnull", True),
                        ("ref_wiki__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="db_cfv_at_most_one_ref",
            ),
        ),
    ]
