# Generated by Django 6.0.6 on 2026-08-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_floorplan_fence_and_gate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplanreference',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='floorplansource',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AddField(
            model_name='floorplanreference',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplansource',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
