# Generated by Django 6.0.6 on 2026-07-17 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0063_custom_field_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_group_chats",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_group_chats",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_keys_created",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="dashboard.groupchat",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_e2ee_group_key",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupKeyEnvelope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("wrapped_key", models.TextField()),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envelopes",
                        to="dashboard.groupkey",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_key_envelopes",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_e2ee_group_key_envelope",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True, default="", max_length=1000)),
                ("ciphertext", models.TextField(blank=True, default="")),
                ("nonce", models.CharField(blank=True, default="", max_length=64)),
                ("key_version", models.PositiveIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="dashboard.groupchat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_group_messages",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_group_messages",
                "ordering": ["created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupMessageShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="dashboard.groupmessage",
                    ),
                ),
                (
                    "pin_share",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_message_shares",
                        to="dashboard.pinshare",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_message_shares",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_group_message_shares",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupChatMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("muted", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="dashboard.groupchat",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_chat_memberships",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_group_chat_memberships",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["profile", "left_at"], name="idxdb_gcm_profile_active"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("left_at__isnull", True)),
                        fields=("group", "profile"),
                        name="db_group_chat_one_active_membership",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="groupkey",
            constraint=models.UniqueConstraint(
                fields=("group", "version"), name="db_e2ee_groupkey_group_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupkeyenvelope",
            constraint=models.UniqueConstraint(
                fields=("key", "profile"), name="db_e2ee_groupkey_one_envelope"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(
                fields=["group", "created"], name="idxdb_gmsg_group_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("body", ""), ("ciphertext", ""), _connector="OR"),
                name="db_gmsg_body_xor_ciphertext",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmessageshare",
            constraint=models.UniqueConstraint(
                fields=("message", "recipient"), name="db_gmsg_share_one_per_recipient"
            ),
        ),
    ]
