# Generated by Django 6.0.6 on 2026-08-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_floorplan_pool_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source_media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='floorplanreference',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floorplan_references', to='dashboard.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('linked_url', 'Linked URL'), ('yelp', 'Yelp'), ('google_images', 'Google Images'), ('google_maps', 'Google Maps'), ('wikimedia', 'Wikimedia Commons'), ('wikipedia_media', 'Wikipedia'), ('smithsonian', 'Smithsonian Open Access'), ('library_of_congress', 'Library of Congress'), ('internet_archive', 'Internet Archive'), ('digital_commonwealth', 'Digital Commonwealth'), ('immich', 'Immich'), ('flickr', 'Flickr'), ('google_photos', 'Google Photos'), ('loopnet', 'LoopNet'), ('cris', 'NY Historic Preservation (CRIS)'), ('external_api', 'External app'), ('google_street_view', 'Google Street View'), ('google_satellite', 'Google Satellite')], default='upload', max_length=30),
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_attachments_added', to='dashboard.profile')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.image')),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_attachments', to='dashboard.pin')),
                ('wiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_attachments', to='dashboard.wiki')),
            ],
            options={
                'db_table': 'dashboard_image_attachments',
                'abstract': False,
                'indexes': [models.Index(fields=['pin'], name='idxdb_imgatt_pin'), models.Index(fields=['wiki'], name='idxdb_imgatt_wiki')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('pin__isnull', False), ('wiki__isnull', True)), models.Q(('pin__isnull', True), ('wiki__isnull', False)), _connector='OR'), name='ck_image_attachment_one_owner'), models.UniqueConstraint(condition=models.Q(('pin__isnull', False)), fields=('image', 'pin'), name='uq_image_attachment_pin'), models.UniqueConstraint(condition=models.Q(('wiki__isnull', False)), fields=('image', 'wiki'), name='uq_image_attachment_wiki')],
            },
        ),
    ]
