# Generated by Django 6.0.6 on 2026-07-17 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0064_groupchat_groupkey_groupkeyenvelope_groupmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=200000,
                        validators=[django.core.validators.MaxLengthValidator(200000)],
                    ),
                ),
                ("content_html", models.TextField(blank=True, default="")),
                ("toc", models.JSONField(blank=True, default=list)),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles_last_edited",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "pin",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="dashboard.pin",
                    ),
                ),
                (
                    "wiki",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="dashboard.wiki",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_articles",
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=200000,
                        validators=[django.core.validators.MaxLengthValidator(200000)],
                    ),
                ),
                (
                    "edit_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="dashboard.article",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_revisions",
                        to="dashboard.profile",
                    ),
                ),
                (
                    "restored_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restorations",
                        to="dashboard.articlerevision",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_article_revisions",
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("pin__isnull", False), ("wiki__isnull", True)),
                    models.Q(("pin__isnull", True), ("wiki__isnull", False)),
                    _connector="OR",
                ),
                name="article_exactly_one_host",
            ),
        ),
        migrations.AddIndex(
            model_name="articlerevision",
            index=models.Index(
                fields=["article", "created"], name="idxdb_artrev_article_created"
            ),
        ),
    ]
