# Generated by Django 6.0.6 on 2026-07-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0066_link_extraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="date_built",
            field=models.DateField(blank=True, null=True),
        ),
    ]
