# Generated by Django 6.0.6 on 2026-08-24 13:20

import django.db.models.deletion
import django.utils.timezone
import urbanlens.dashboard.models.reputation.model
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_encrypt_image_exif_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('lifetime_earned', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to='dashboard.profile')),
            ],
            options={
                'db_table': 'dashboard_profile_reputation',
                'ordering': ['-total'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReputationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rule_key', models.CharField(choices=urbanlens.dashboard.models.reputation.model.rule_choices, db_index=True, max_length=64)),
                ('target_kind', models.CharField(choices=[('none', 'No target'), ('wiki_edit', 'Wiki edit'), ('image', 'Photo'), ('comment', 'Comment'), ('pin', 'Pin'), ('wiki', 'Wiki'), ('article_revision', 'Article revision'), ('friend_invitation', 'Invitation'), ('profile', 'Profile')], default='none', max_length=32)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('period_key', models.CharField(db_index=True, max_length=7)),
                ('retracted', models.BooleanField(default=False)),
                ('retracted_reason', models.CharField(blank=True, default='', max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_events', to='dashboard.profile')),
                ('wiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_events', to='dashboard.wiki')),
            ],
            options={
                'db_table': 'dashboard_reputation_events',
                'ordering': ['-occurred_at'],
                'get_latest_by': 'occurred_at',
                'abstract': False,
                'indexes': [models.Index(fields=['profile', '-occurred_at'], name='idxdb_repev_profile_date'), models.Index(fields=['profile', 'rule_key', 'period_key'], name='idxdb_repev_pf_rule_per'), models.Index(fields=['profile', 'wiki'], name='idxdb_repev_profile_wiki')],
                'constraints': [models.UniqueConstraint(fields=('rule_key', 'target_kind', 'target_id'), name='uniq_reputation_event_target')],
            },
        ),
    ]
