# Generated by Django 5.1.6 on 2026-06-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0067_trip_permissions_and_organizers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="allow_add_activities",
            field=models.CharField(
                choices=[
                    ("none", "No one (creator only)"),
                    ("organizers", "Organizers"),
                    ("everyone", "Everyone"),
                ],
                default="everyone",
                help_text="Who can add activities.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="allow_add_members",
            field=models.CharField(
                choices=[
                    ("none", "No one (creator only)"),
                    ("organizers", "Organizers"),
                    ("everyone", "Everyone"),
                ],
                default="none",
                help_text="Who can add new members.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="allow_comments",
            field=models.CharField(
                choices=[
                    ("none", "No one (creator only)"),
                    ("organizers", "Organizers"),
                    ("everyone", "Everyone"),
                ],
                default="everyone",
                help_text="Who can leave comments.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="allow_edit_activities",
            field=models.CharField(
                choices=[
                    ("none", "No one (creator only)"),
                    ("organizers", "Organizers"),
                    ("everyone", "Everyone"),
                ],
                default="everyone",
                help_text="Who can edit or delete activities.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tripactivityvote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
