# Generated by Django 6.0.6 on 2026-08-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_reputation_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiFieldRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=64)),
                ('value', models.TextField(blank=True, default='')),
                ('is_null', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('user', 'User'), ('automatic', 'Automatic'), ('system', 'System')], db_index=True, max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_revisions', to='dashboard.wiki')),
            ],
            options={
                'db_table': 'dashboard_wiki_field_revisions',
                'ordering': ['target', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['target', 'field_name', '-id'], name='idxdb_wikirev_tgt_fld_id'), models.Index(fields=['target', 'source'], name='idxdb_wikirev_tgt_source'), models.Index(fields=['target', 'actor'], name='idxdb_wikirev_tgt_actor')],
            },
        ),
    ]
