# Generated by Django 6.0.6 on 2026-07-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0067_pin_date_built"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="display",
            field=models.CharField(
                choices=[
                    ("default", "In the Custom Fields card"),
                    ("section", "Its own section"),
                    ("fixed", "Fixed on screen (draggable)"),
                ],
                default="default",
                max_length=10,
            ),
        ),
    ]
