# Generated by Django 6.0.6 on 2026-07-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0068_custom_field_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
