# Generated by Django 6.0.6 on 2026-08-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_wiki_field_revisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='officially_created',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='viewed_by_other',
        ),
    ]
