# Generated by Django 6.0.6 on 2026-07-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0069_pin_last_viewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sync_aliases",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("to_wiki", "Sync to wiki"),
                    ("from_wiki", "Sync from wiki"),
                    ("both", "Sync both ways"),
                ],
                default="from_wiki",
                help_text="Automatically copy newly-added alternate names between a pin and its community wiki. Never deletes an alias on either side.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_danger_to_wiki",
            field=models.BooleanField(
                default=True,
                help_text="When you set a pin's danger, also count it on its community wiki.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_priority_to_wiki",
            field=models.BooleanField(
                default=True,
                help_text="When you set a pin's priority, also count it on its community wiki.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_rating_to_wiki",
            field=models.BooleanField(
                default=True,
                help_text="When you rate a pin, also count that rating on its community wiki.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_vulnerability_to_wiki",
            field=models.BooleanField(
                default=True,
                help_text="When you set a pin's vulnerability, also count it on its community wiki.",
            ),
        ),
    ]
