# Generated by Django 6.0.6 on 2026-08-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0069_drop_wiki_draft_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetycheckin",
            name="archive_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetycheckin",
            name="archive_failure_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_safety_checkin_archival_failed_email",
            field=models.BooleanField(
                default=True,
                help_text="Email the admin notification address when a safety check-in gives up on archival after repeated failures.",
                verbose_name="Safety check-in archival failures (email)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_safety_checkin_archival_failed_gotify",
            field=models.BooleanField(
                default=False,
                help_text="Send a Gotify push notification when a safety check-in gives up on archival after repeated failures.",
                verbose_name="Safety check-in archival failures (Gotify)",
            ),
        ),
    ]
