# Generated by Django 6.0.6 on 2026-07-18 09:39

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0070_profile_wiki_sync_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="undoaction",
            name="payload",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
