# Generated by Django 6.0.6 on 2026-08-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0070_safety_checkin_archive_failure_tracking"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="safetycontactoptout",
            constraint=models.UniqueConstraint(
                models.F("contact_profile"),
                models.F("email"),
                models.F("scope"),
                models.F("owner"),
                models.F("checkin"),
                name="uq_safety_contact_optout_target_scope",
                nulls_distinct=False,
            ),
        ),
    ]
