# Generated by Django 6.0.6 on 2026-08-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0071_safety_contact_optout_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="quota_exempt_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("external_media", "Cached external media"),
                    ("community", "Community-valued contribution"),
                    ("shared_copy", "Copy of a shared photo"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
