# Generated by Django 6.0.6 on 2026-07-18 19:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0071_alter_undoaction_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinAutoRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("alias", "Alias"),
                            ("link", "Link"),
                            ("label", "Label"),
                            ("owner", "Owner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "dashboard_pin_auto_removals",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiAutoRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("alias", "Alias"),
                            ("link", "Link"),
                            ("label", "Label"),
                            ("owner", "Owner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "dashboard_wiki_auto_removals",
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="pinalias",
            name="db_pin_alias_unique",
        ),
        migrations.RemoveConstraint(
            model_name="wikialias",
            name="db_walias_unique",
        ),
        migrations.AddConstraint(
            model_name="pinalias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("pin"),
                name="db_pin_alias_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="wikialias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("wiki"),
                name="db_walias_unique",
            ),
        ),
        migrations.AddField(
            model_name="pinautoremoval",
            name="pin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_removals",
                to="dashboard.pin",
            ),
        ),
        migrations.AddField(
            model_name="wikiautoremoval",
            name="wiki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_removals",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddConstraint(
            model_name="pinautoremoval",
            constraint=models.UniqueConstraint(
                fields=("pin", "kind", "value"), name="db_pin_auto_removal_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikiautoremoval",
            constraint=models.UniqueConstraint(
                fields=("wiki", "kind", "value"), name="db_wiki_auto_removal_unique"
            ),
        ),
        # Index creation last (see CLAUDE.md migration conventions).
        migrations.AddIndex(
            model_name="pinautoremoval",
            index=models.Index(fields=["pin", "kind"], name="idxdb_pautorm_pin_kind"),
        ),
        migrations.AddIndex(
            model_name="wikiautoremoval",
            index=models.Index(fields=["wiki", "kind"], name="idxdb_wautorm_wiki_kind"),
        ),
    ]
