# Generated by Django 6.0.6 on 2026-07-18 19:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0071_alter_undoaction_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinAutoRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("alias", "Alias"),
                            ("link", "Link"),
                            ("label", "Label"),
                            ("owner", "Owner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "dashboard_pin_auto_removals",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WikiAutoRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("alias", "Alias"),
                            ("link", "Link"),
                            ("label", "Label"),
                            ("owner", "Owner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "dashboard_wiki_auto_removals",
                "abstract": False,
            },
        ),
        # Existing data can already have case-insensitive duplicates (e.g. "Aloha
        # Stadium" and "aloha stadium" on the same pin) predating this constraint -
        # the new case-insensitive unique index below fails to create otherwise
        # (IntegrityError: could not create unique index "db_pin_alias_unique").
        # Per group, keep one row - preferring an `official`-kind alias if one
        # exists (more likely the canonical spelling from an external source),
        # otherwise the lowest id (oldest) - and delete the rest. These are true
        # duplicates (same name, different case, same pin/wiki), so nothing
        # meaningful is lost; irreversible, hence reverse_sql=noop.
        migrations.RunSQL(
            sql="""
                DELETE FROM dashboard_pin_aliases
                WHERE id IN (
                    SELECT id FROM (
                        SELECT id,
                               ROW_NUMBER() OVER (
                                   PARTITION BY pin_id, LOWER(name)
                                   ORDER BY (kind = 'official') DESC, id ASC
                               ) AS rn
                        FROM dashboard_pin_aliases
                    ) ranked
                    WHERE rn > 1
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM dashboard_wiki_aliases
                WHERE id IN (
                    SELECT id FROM (
                        SELECT id,
                               ROW_NUMBER() OVER (
                                   PARTITION BY wiki_id, LOWER(name)
                                   ORDER BY (kind = 'official') DESC, id ASC
                               ) AS rn
                        FROM dashboard_wiki_aliases
                    ) ranked
                    WHERE rn > 1
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name="pinalias",
            name="db_pin_alias_unique",
        ),
        migrations.RemoveConstraint(
            model_name="wikialias",
            name="db_walias_unique",
        ),
        migrations.AddConstraint(
            model_name="pinalias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("pin"),
                name="db_pin_alias_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="wikialias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("wiki"),
                name="db_walias_unique",
            ),
        ),
        migrations.AddField(
            model_name="pinautoremoval",
            name="pin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_removals",
                to="dashboard.pin",
            ),
        ),
        migrations.AddField(
            model_name="wikiautoremoval",
            name="wiki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_removals",
                to="dashboard.wiki",
            ),
        ),
        migrations.AddConstraint(
            model_name="pinautoremoval",
            constraint=models.UniqueConstraint(
                fields=("pin", "kind", "value"), name="db_pin_auto_removal_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikiautoremoval",
            constraint=models.UniqueConstraint(
                fields=("wiki", "kind", "value"), name="db_wiki_auto_removal_unique"
            ),
        ),
        # Index creation last (see CLAUDE.md migration conventions).
        migrations.AddIndex(
            model_name="pinautoremoval",
            index=models.Index(fields=["pin", "kind"], name="idxdb_pautorm_pin_kind"),
        ),
        migrations.AddIndex(
            model_name="wikiautoremoval",
            index=models.Index(fields=["wiki", "kind"], name="idxdb_wautorm_wiki_kind"),
        ),
    ]
