# Generated by Django 6.0.6 on 2026-06-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0073_clear_stale_map_center_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="map_center_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Center on my pins"),
                    ("gps", "Use my current location"),
                    ("custom", "Custom location"),
                ],
                default="gps",
                max_length=10,
            ),
        ),
    ]
