# Generated by Django 6.0.6 on 2026-07-18 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0073_friend_suggestion_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyJurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "fips",
                    models.CharField(
                        db_index=True,
                        help_text="5-digit Census FIPS county code (2-digit state + 3-digit county).",
                        max_length=5,
                        unique=True,
                    ),
                ),
                (
                    "county_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="USPS state abbreviation.",
                        max_length=2,
                    ),
                ),
                (
                    "adapter_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Not yet researched"),
                            ("arcgis_rest", "ArcGIS REST (Tier 1)"),
                            ("socrata", "Socrata / CKAN (Tier 1)"),
                            ("known_vendor", "Known vendor platform (Tier 2)"),
                            ("custom_scraper", "Custom scraper (Tier 3)"),
                            ("manual_only", "Manual only (Tier 4)"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "gis_rest_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "gis_id_field",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "gis_geo_field",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("field_map", models.JSONField(blank=True, default=dict)),
                (
                    "assessor_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "treasurer_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "recorder_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Known vendor platform slug (Tyler, BS&A, qPublic, ...), once Tier 2 adapters exist.",
                        max_length=100,
                    ),
                ),
                ("scrape_recipe", models.JSONField(blank=True, default=dict)),
                (
                    "requires_captcha",
                    models.BooleanField(
                        default=False,
                        help_text="County site puts a CAPTCHA in front of search - never attempted programmatically (see plan compliance section).",
                    ),
                ),
                (
                    "manual_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Shown to users when this jurisdiction has no automated path (phone/mail/in-person only).",
                    ),
                ),
                (
                    "last_verified",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a human or the discovery command last confirmed these endpoints still work.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "discovered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.profile",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_property_jurisdiction",
                "ordering": ["state", "county_name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["adapter_type"], name="idxdb_propjuris_adapter"
                    )
                ],
            },
        ),
    ]
