# Generated by Django 6.0.6 on 2026-07-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0074_property_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="home_widget_layout",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
