# Generated by Django 6.0.6 on 2026-07-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_profile_home_widget_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
