# Generated by Django 6.0.6 on 2026-07-19 04:11

import django.db.models.deletion
import urbanlens.dashboard.models.account.model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0076_comment_parent_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='User-facing label, e.g. "Zapier".', max_length=100
                    ),
                ),
                (
                    "prefix",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                ("key_hash", models.CharField(editable=False, max_length=128)),
                (
                    "scopes",
                    models.JSONField(
                        default=urbanlens.dashboard.models.account.model._default_api_key_scopes,
                        editable=False,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_api_key",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
