# Generated by Django 6.0.6 on 2026-07-19 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0077_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKeyUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("endpoint", models.CharField(max_length=255)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_log",
                        to="dashboard.apikey",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_api_key_usage_log",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
