# Generated by Django 6.0.6 on 2026-07-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0078_api_key_usage_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicalllog",
            name="cost_estimate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated USD cost of this call, from the service's ServiceDefaults.cost_per_call at call time. Null means no per-call cost is configured for this service (free, or not yet priced) - not necessarily that the call was free.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
