# Generated by Django 6.0.6 on 2026-07-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0079_api_call_log_cost_estimate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyjurisdiction",
            name="requires_captcha",
            field=models.BooleanField(
                default=False,
                help_text="County site puts a CAPTCHA in front of search - never attempted programmatically (see plan compliance section).",
            ),
        ),
        migrations.AlterField(
            model_name="propertyjurisdiction",
            name="vendor",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Known vendor platform slug (Tyler, BS&A, qPublic, ...) matching a registered vendor template.",
                max_length=100,
            ),
        ),
    ]
