# Generated by Django 6.0.6 on 2026-07-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0080_alter_propertyjurisdiction_requires_captcha_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="propertyjurisdiction",
            name="idxdb_propjuris_adapter",
        ),
        migrations.DeleteModel(
            name="PropertyJurisdiction",
        ),
    ]
