# Generated by Django 6.0.6 on 2026-07-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0082_invalidate_wikipedia_cache_for_article_seeding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="source",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("yelp", "Yelp"),
                    ("google_images", "Google Images"),
                    ("google_maps", "Google Maps"),
                    ("wikimedia", "Wikimedia Commons"),
                    ("wikipedia_media", "Wikipedia"),
                    ("smithsonian", "Smithsonian Open Access"),
                    ("library_of_congress", "Library of Congress"),
                    ("internet_archive", "Internet Archive"),
                    ("immich", "Immich"),
                    ("flickr", "Flickr"),
                    ("google_photos", "Google Photos"),
                ],
                default="upload",
                max_length=30,
            ),
        ),
    ]
