# Generated by Django 6.0.6 on 2026-07-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0083_add_wikipedia_and_internet_archive_image_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="direction",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
