# Generated by Django 6.0.8 on 2026-09-24 10:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_recordedweatherday_unique_cell_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOutboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=200)),
                ('args', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('kwargs', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('queue', models.CharField(blank=True, default='', max_length=64)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'dashboard_task_outbox',
                'ordering': ['next_attempt_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['next_attempt_at'], name='idxdb_taskoutbox_next')],
            },
        ),
    ]
