# Generated by Django 6.0.6 on 2026-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0084_image_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_create_pin_article_from_wikipedia",
            field=models.BooleanField(
                default=True,
                help_text="When a Wikipedia article is matched to one of your pins, automatically start that pin's article from it (if it doesn't have one yet).",
            ),
        ),
    ]
