# Generated by Django 6.0.6 on 2026-06-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0084_comment_map_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="kind",
            field=models.CharField(
                choices=[
                    ("tag", "Tag"),
                    ("category", "Category"),
                    ("status", "Status"),
                ],
                db_index=True,
                default="tag",
                max_length=20,
            ),
        ),
    ]
