# Generated by Django 6.0.8 on 2026-09-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_task_outbox_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicescanupload',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicescanupload',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicescanupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='devicescanupload',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'processing'])), fields=['status', 'created'], name='idxdb_scanupload_unfinished'),
        ),
    ]
