# Generated by Django 6.0.8 on 2026-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_device_scan_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='needs_recompute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(condition=models.Q(('needs_recompute', True)), fields=['updated'], name='idxdb_fact_needs_recompute'),
        ),
    ]
