# Generated by Django 6.0.8 on 2026-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_fact_needs_recompute'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcalendarlink',
            name='push_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripcalendarlink',
            name='push_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tripcalendarlink',
            index=models.Index(condition=models.Q(('push_requested_at__isnull', False)), fields=['push_requested_at'], name='idxdb_tcl_push_requested'),
        ),
    ]
