# Generated by Django 6.0.6 on 2026-07-20 17:58

import django.core.validators
from django.db import migrations, models


def cap_existing_value(apps, schema_editor):
    """Clamp any already-persisted value above the new ceiling.

    The field validator only runs on form/full_clean() validation, not on
    save() - a value saved before this cap existed (e.g. via site_admin's own
    manual clamping, which previously had no upper bound for this field)
    could still be sitting above clamd's StreamMaxLength. Bring it in line so
    the "too large to scan" mismatch this migration closes doesn't linger for
    an environment that already has an oversized value stored.
    """
    SiteSettings = apps.get_model("dashboard", "SiteSettings")
    SiteSettings.objects.filter(max_upload_file_size_mb__gt=900).update(max_upload_file_size_mb=900)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0086_invalidate_wikipedia_cache_for_pin_article_seeding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="max_upload_file_size_mb",
            field=models.IntegerField(
                default=250,
                help_text="Maximum size (MB) for a single photo, video, or document upload. Enforced on both the frontend and backend.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(900),
                ],
                verbose_name="Max upload file size (MB)",
            ),
        ),
        migrations.RunPython(cap_existing_value, migrations.RunPython.noop),
    ]
