# Generated by Django 6.0.8 on 2026-09-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_calendar_push_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaGenerationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attempted_at', models.DateTimeField()),
                ('questions_created', models.PositiveSmallIntegerField(default=0)),
                ('wiki', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_generation_attempt', to='dashboard.wiki')),
            ],
            options={
                'db_table': 'dashboard_trivia_generation_attempts',
                'abstract': False,
                'indexes': [models.Index(fields=['attempted_at'], name='idxdb_trivia_gen_attempted')],
            },
        ),
    ]
