# Generated by Django 6.0.8 on 2026-09-24 11:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_trivia_generation_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='device_scan_retention_days',
            field=models.IntegerField(default=730, help_text='Delete device-scan uploads, with their entries and signal readings, once they are this many days old. Marker clustering ignores scans older than 720 days, so a shorter period also drops scans it still uses. 0 keeps them forever.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(36500)], verbose_name='Device scan retention (days)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_retention_days',
            field=models.IntegerField(default=365, help_text='Delete notifications a user has read once they are this many days old. Unread ones are kept. 0 keeps them forever.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(36500)], verbose_name='Read notification retention (days)'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('notification_retention_days__gte', 0)), name='notification_retention_days_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('device_scan_retention_days__gte', 0)), name='device_scan_retention_days_gte_0'),
        ),
    ]
