# Generated by Django 6.0.6 on 2026-07-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0089_invalidate_wikipedia_cache_for_infobox_seeding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name_source_priority",
        ),
    ]
