# Generated by Django 6.0.6 on 2026-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0090_remove_profile_name_source_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="pending_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tripcomment",
            name="pending_scan",
            field=models.BooleanField(default=False),
        ),
    ]
