# Generated by Django 6.0.8 on 2026-09-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_drop_non_http_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicescanupload',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_scan_uploads', to='dashboard.profile'),
        ),
    ]
