# Generated by Django 6.0.8 on 2026-09-24 11:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_alter_devicescanupload_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('boundary_type', models.CharField(choices=[('property', 'Property'), ('building', 'Building')], max_length=20)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_revisions', to='dashboard.wiki')),
            ],
            options={
                'db_table': 'dashboard_boundary_revisions',
                'abstract': False,
            },
        ),
    ]
