# Generated by Django 6.0.6 on 2026-06-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0098_profile_notes_and_user_badges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="kind",
            field=models.CharField(
                choices=[
                    ("tag", "Tag"),
                    ("category", "Category"),
                    ("status", "Status"),
                    ("user", "Person"),
                ],
                db_index=True,
                default="tag",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="friendinvitation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profilebadgeassignment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profilenote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
