# Generated by Django 6.0.6 on 2026-06-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0100_notificationlog_source_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo_upload_visibility",
            field=models.CharField(
                choices=[
                    ("anyone", "Anyone"),
                    ("friends", "Friends Only"),
                    ("common_pin", "Users with a pin in common"),
                    ("common_friend", "Users with a friend in common"),
                    ("common_trip", "Users with a trip in common"),
                    ("no_one", "No one"),
                ],
                default="anyone",
                help_text="Who can see the photos you upload to locations.",
                max_length=20,
            ),
        ),
    ]
