# Generated by Django 6.0.6 on 2026-06-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0100_profilenote_multi_remove_unique"),
        ("dashboard", "0103_sitesettings_search_cache_hours"),
    ]

    operations = []
