# Generated by Django 6.0.6 on 2026-06-22 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0108_sitesettings_bootstrap_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("Encountered", "Encountered"),
                    ("Connected", "Connected"),
                    ("Friend", "Friend"),
                    ("Close Friend", "Close Friend"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="max_bbox_area_km2",
            field=models.FloatField(
                default=2600.0,
                help_text="Maximum allowed area (km²) for a location bounding box. Default ≈ Chernobyl Exclusion Zone.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2600.0),
                ],
            ),
        ),
    ]
