# Generated by Django 6.0.8 on 2026-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_device_scans_are_kept'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicescanentry',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devicescanupload',
            name='routable_wikis',
            field=models.ManyToManyField(blank=True, related_name='+', to='dashboard.wiki'),
        ),
        migrations.AddField(
            model_name='devicescanupload',
            name='routing_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
