# Generated by Django 6.0.8 on 2026-09-30 18:42

import urbanlens.dashboard.models.remote_image_copy.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_device_scans_are_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteImageCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url_digest', models.CharField(editable=False, help_text='SHA-256 of source_url.', max_length=64, unique=True)),
                ('source_url', models.TextField(help_text="The image's address at its provider.")),
                ('edition', models.CharField(blank=True, default='', help_text='Which edition of a changing picture this is, e.g. the month of a current-imagery export.', max_length=16)),
                ('provider', models.CharField(blank=True, default='', help_text='Which feature or provider the image came from.', max_length=64)),
                ('page_url', models.TextField(blank=True, default='', help_text="The provider's page for the image, when known.")),
                ('file', models.FileField(blank=True, default='', max_length=255, upload_to=urbanlens.dashboard.models.remote_image_copy.model.remote_image_copy_path)),
                ('content_type', models.CharField(blank=True, default='', max_length=50)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 of the stored file.', max_length=64)),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When the source was downloaded and stored.', null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_remote_image_copies',
                'abstract': False,
            },
        ),
    ]
