# Generated by Django 6.0.8 on 2026-09-30 20:23

import django.db.models.deletion
import urbanlens.dashboard.models.remote_tiles.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_friendship_blocked_at_only_while_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteTileSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('template_digest', models.CharField(editable=False, help_text='SHA-256 of template.', max_length=64, unique=True)),
                ('template', models.TextField(help_text='The XYZ template at its host, as it was given.')),
                ('provider', models.CharField(blank=True, default='', help_text='Where the template came from, e.g. an archive import.', max_length=64)),
                ('kept_tiles', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'dashboard_remote_tile_sources',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('z', models.PositiveSmallIntegerField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, default='', max_length=255, upload_to=urbanlens.dashboard.models.remote_tiles.model.remote_tile_path)),
                ('content_type', models.CharField(blank=True, default='', max_length=50)),
                ('absent', models.BooleanField(default=False, help_text='The host answered that it has no tile here.')),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='dashboard.remotetilesource')),
            ],
            options={
                'db_table': 'dashboard_remote_tiles',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('source', 'z', 'x', 'y'), name='remote_tile_one_row_per_coordinate')],
            },
        ),
    ]
