# Generated by Django 4.2.8 on 2024-01-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodedLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("place_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "dashboard_geocoded_locations",
                "get_latest_by": "updated",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="dashboard_g_latitud_9e6b87_idx",
                    )
                ],
            },
        ),
    ]
