# Generated by Django 4.2.8 on 2024-01-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_geocodedlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocodedlocation",
            name="place_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
