# Generated by Django 4.2.8 on 2023-12-24 16:33

from django.db import migrations
import django.db.models.manager
import djangofoundry.models.fields.relationships
import djangofoundry.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_friendship_review_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("postgres", djangofoundry.models.manager.PostgresManager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("postgres", djangofoundry.models.manager.PostgresManager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="friendship",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("postgres", djangofoundry.models.manager.PostgresManager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="image",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("postgres", djangofoundry.models.manager.PostgresManager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="location",
            name="categories",
            field=djangofoundry.models.fields.relationships.ManyToManyField(
                blank=True, to="dashboard.category"
            ),
        ),
    ]
