# Generated by Django 4.2.8 on 2024-01-01 03:59

from django.db import migrations
import djangofoundry.models.fields.relationships


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_location_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="categories",
            field=djangofoundry.models.fields.relationships.ManyToManyField(
                blank=True, default=list, to="dashboard.category"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="tags",
            field=djangofoundry.models.fields.relationships.ManyToManyField(
                blank=True, default=list, to="dashboard.tag"
            ),
        ),
    ]
