# Generated by Django 4.2.8 on 2024-01-01 04:17

from django.db import migrations
import djangofoundry.models.fields.char


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_location_categories_alter_location_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="status",
            field=djangofoundry.models.fields.char.CharField(
                choices=[("visited", "Visited"), ("wish_to_visit", "Wish To Visit")],
                default="wish_to_visit",
            ),
        ),
    ]
