# Generated by Django 4.2.8 on 2024-01-01 04:19

from django.db import migrations
import djangofoundry.models.fields.char


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_location_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="status",
            field=djangofoundry.models.fields.char.CharField(
                choices=[
                    ("not visited", "Not Visited"),
                    ("visited", "Visited"),
                    ("wish to visit", "Wish To Visit"),
                    ("demolished", "Demolished"),
                ],
                default="wish to visit",
            ),
        ),
    ]
