# Generated by Django 4.2.8 on 2024-01-01 15:43

import django.core.validators
from django.db import migrations
import djangofoundry.models.fields.number


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_alter_location_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=djangofoundry.models.fields.number.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
