# Generated by Django 5.0.1 on 2024-03-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_alter_geocodedlocation_json_response"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="dashboard_l_name_11ee30_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="dashboard_l_priorit_4ab683_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="dashboard_l_last_vi_f65ca3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("latitude", "longitude", "profile")},
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["profile"], name="dashboard_l_profile_f707a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["profile", "priority"], name="dashboard_l_profile_0fc6af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["profile", "last_visited"],
                name="dashboard_l_profile_c4846c_idx",
            ),
        ),
    ]
