# Generated by Django 5.1.6 on 2025-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_rename_location_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("Send Message", "Send Message"),
                    ("Invite to Events", "Invite to Events"),
                    ("Share Pins", "Share Pins"),
                    ("View Profile", "View Profile"),
                    ("View Friends", "View Friends"),
                    ("View Trips", "View Trips"),
                ],
                max_length=16,
            ),
        ),
    ]
