# Generated by Django 5.1.6 on 2025-03-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_friendship_permissions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pin",
            new_name="dashboard_u_profile_945100_idx",
            old_name="dashboard_l_profile_f707a0_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="dashboard_u_profile_f747ec_idx",
            old_name="dashboard_l_profile_0fc6af_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="dashboard_u_profile_67c4a2_idx",
            old_name="dashboard_l_profile_c4846c_idx",
        ),
        migrations.RenameIndex(
            model_name="pin",
            new_name="dashboard_u_latitud_b6864d_idx",
            old_name="dashboard_l_latitud_ce2d4e_idx",
        ),
        migrations.AlterModelTable(
            name="pin",
            table="dashboard_user_pins",
        ),
    ]
