# Generated by Django 5.1.6 on 2025-03-01 18:53

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0016_rename_dashboard_l_profile_f707a0_idx_dashboard_u_profile_945100_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pin",
            old_name="location",
            new_name="point",
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0),
                        geography=True,
                        srid=4326,
                    ),
                ),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("route", models.CharField(blank=True, max_length=80, null=True)),
                ("locality", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "administrative_area_level_1",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "administrative_area_level_2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "administrative_area_level_3",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("country", models.CharField(default="United States", max_length=20)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "zipcode_suffix",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "cached_place_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        default=list,
                        related_name="locations",
                        to="dashboard.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        default=list,
                        related_name="locations",
                        to="dashboard.tag",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_locations",
                "get_latest_by": "updated",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="dashboard_l_latitud_ce2d4e_idx",
                    ),
                    models.Index(fields=["name"], name="dashboard_l_name_11ee30_idx"),
                ],
                "unique_together": {("latitude", "longitude")},
            },
        ),
    ]
