"""Tag model - a named label applied to pins, with optional user ownership and hierarchy."""

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db.models import CASCADE, CharField, ForeignKey, ImageField, Index, IntegerField, ManyToManyField, TextField

from urbanlens.dashboard.models import abstract
from urbanlens.dashboard.models.tags.queryset import TagManager

if TYPE_CHECKING:
    from urbanlens.dashboard.models.categories.model import Category
    from urbanlens.dashboard.models.pin.model import Pin
    from urbanlens.dashboard.models.profile.model import Profile


ICON_CHOICES = [
    ("bookmark", "Bookmark"),
    ("star", "Star"),
    ("heart", "Heart"),
    ("flag", "Flag"),
    ("camera", "Camera"),
    ("home", "Home"),
    ("place", "Place"),
    ("explore", "Explore"),
    ("hiking", "Hiking"),
    ("warning", "Warning"),
    ("check_circle", "Check Circle"),
    ("schedule", "Schedule"),
    ("visibility", "Visibility"),
    ("lock", "Private"),
    ("archive", "Archive"),
    ("label", "Label"),
    ("local_offer", "Tag"),
    ("category", "Category"),
]

# Emoji / icon categories for the picker UI.
# Structure: { cat_id: (label, [(icon, display_label), ...]) }
ICON_CATEGORIES = {
    "places": (
        "Places",
        [
            ("🏠", "House"),
            ("🏡", "Home"),
            ("🏚️", "Abandoned"),
            ("🏢", "Office"),
            ("🏣", "Building"),
            ("🏤", "Post Office"),
            ("🏥", "Hospital"),
            ("🏦", "Bank"),
            ("🏧", "ATM"),
            ("🏨", "Hotel"),
            ("🏩", "Love Hotel"),
            ("🏪", "Shop"),
            ("🏫", "School"),
            ("🏬", "Mall"),
            ("🏭", "Factory"),
            ("🏯", "Fort"),
            ("🏰", "Castle"),
            ("🏗️", "Construction"),
            ("🏛️", "Building"),
            ("🏟️", "Stadium"),
            ("🗼", "Tower"),
            ("🗽", "Monument"),
            ("🗾", "Island"),
            ("🕌", "Mosque"),
            ("🕍", "Synagogue"),
            ("🛕", "Temple"),
            ("⛪", "Church"),
            ("⛩️", "Shrine"),
            ("🕋", "Kaaba"),
            ("⛲", "Fountain"),
            ("⛺", "Tent"),
            ("🏕️", "Campsite"),
            ("🛖", "Hut"),
            ("🏙️", "City"),
            ("🌆", "Cityscape"),
            ("🌇", "Sunset City"),
            ("🌃", "Night City"),
            ("🌉", "Bridge Night"),
            ("🌁", "Fog"),
            ("🏘️", "Houses"),
            ("🏔️", "Mountain"),
            ("⛰️", "Hill"),
            ("🌋", "Volcano"),
        ],
    ),
    "transport": (
        "Transport",
        [
            ("🚂", "Train"),
            ("🚃", "Rail Car"),
            ("🚄", "Bullet Train"),
            ("🚅", "High Speed"),
            ("🚆", "Train"),
            ("🚇", "Metro"),
            ("🚈", "Light Rail"),
            ("🚉", "Station"),
            ("🚊", "Tram"),
            ("🚝", "Monorail"),
            ("🚞", "Mountain Rail"),
            ("🚋", "Tram Car"),
            ("🚌", "Bus"),
            ("🚍", "Bus"),
            ("🚎", "Trolley"),
            ("🚐", "Minibus"),
            ("🚑", "Ambulance"),
            ("🚒", "Fire Truck"),
            ("🚓", "Police Car"),
            ("🚔", "Police"),
            ("🚕", "Taxi"),
            ("🚖", "Taxi"),
            ("🚗", "Car"),
            ("🚘", "Car"),
            ("🚙", "SUV"),
            ("🚚", "Truck"),
            ("🚛", "Semi Truck"),
            ("🚜", "Tractor"),
            ("🏎️", "Race Car"),
            ("🏍️", "Motorcycle"),
            ("🛵", "Scooter"),
            ("🚲", "Bicycle"),
            ("🛴", "Kick Scooter"),
            ("🛺", "Rickshaw"),
            ("🚁", "Helicopter"),
            ("🛸", "UFO"),
            ("✈️", "Airplane"),
            ("🛩️", "Small Plane"),
            ("🛫", "Takeoff"),
            ("🛬", "Landing"),
            ("🪂", "Parachute"),
            ("🚀", "Rocket"),
            ("🛶", "Canoe"),
            ("⛵", "Sailboat"),
            ("🚤", "Speedboat"),
            ("🛥️", "Motorboat"),
            ("🚢", "Ship"),
            ("⛴️", "Ferry"),
            ("🛳️", "Cruise"),
            ("⚓", "Anchor"),
            ("🌉", "Bridge"),
            ("⛽", "Fuel"),
            ("🛣️", "Road"),
            ("🛤️", "Railway"),
        ],
    ),
    "nature": (
        "Nature",
        [
            ("🌲", "Tree"),
            ("🌳", "Deciduous"),
            ("🌴", "Palm"),
            ("🌵", "Cactus"),
            ("🌾", "Field"),
            ("🌿", "Leaf"),
            ("☘️", "Clover"),
            ("🍀", "Four Leaf"),
            ("🍁", "Maple"),
            ("🍂", "Fallen Leaf"),
            ("🍃", "Leaves"),
            ("🪴", "Plant"),
            ("🌱", "Seedling"),
            ("🌻", "Sunflower"),
            ("🌸", "Blossom"),
            ("🌺", "Flower"),
            ("🌹", "Rose"),
            ("💐", "Bouquet"),
            ("🌊", "Wave"),
            ("💧", "Water Drop"),
            ("🌧️", "Rain"),
            ("❄️", "Snow"),
            ("⛄", "Snowman"),
            ("🌨️", "Snowfall"),
            ("🌩️", "Lightning"),
            ("⚡", "Electric"),
            ("🔥", "Fire"),
            ("💨", "Wind"),
            ("🌪️", "Tornado"),
            ("🌈", "Rainbow"),
            ("☀️", "Sun"),
            ("🌙", "Moon"),
            ("⭐", "Star"),
            ("🌟", "Glowing Star"),
            ("☁️", "Cloud"),
            ("⛅", "Partly Cloudy"),
            ("🌤️", "Sun Behind Cloud"),
            ("🌫️", "Fog"),
            ("🏕️", "Campfire"),
            ("🏖️", "Beach"),
            ("🏜️", "Desert"),
            ("🏝️", "Island"),
            ("🏞️", "Park"),
            ("🗻", "Mount Fuji"),
            ("🪨", "Rocks"),
            ("🌎", "Globe"),
            ("🌍", "Earth"),
            ("💦", "Splashing Water"),
            ("🫗", "Pouring"),
            ("🏊", "Swimming"),
            ("🤿", "Diving"),
            ("🏄", "Surfing"),
            ("🚣", "Rowing"),
        ],
    ),
    "animals": (
        "Animals",
        [
            ("🐶", "Dog"),
            ("🐱", "Cat"),
            ("🐭", "Mouse"),
            ("🐹", "Hamster"),
            ("🐰", "Rabbit"),
            ("🦊", "Fox"),
            ("🐻", "Bear"),
            ("🐼", "Panda"),
            ("🐨", "Koala"),
            ("🐯", "Tiger"),
            ("🦁", "Lion"),
            ("🐮", "Cow"),
            ("🐷", "Pig"),
            ("🐸", "Frog"),
            ("🐵", "Monkey"),
            ("🦆", "Duck"),
            ("🦅", "Eagle"),
            ("🦉", "Owl"),
            ("🦇", "Bat"),
            ("🐺", "Wolf"),
            ("🐗", "Boar"),
            ("🦝", "Raccoon"),
            ("🦨", "Skunk"),
            ("🦡", "Badger"),
            ("🦦", "Otter"),
            ("🦥", "Sloth"),
            ("🐿️", "Chipmunk"),
            ("🦔", "Hedgehog"),
            ("🐢", "Turtle"),
            ("🦎", "Lizard"),
            ("🐍", "Snake"),
            ("🦕", "Dinosaur"),
            ("🦖", "T-Rex"),
            ("🦎", "Gecko"),
            ("🐛", "Caterpillar"),
            ("🦋", "Butterfly"),
            ("🐝", "Bee"),
            ("🐞", "Ladybug"),
            ("🕷️", "Spider"),
            ("🦂", "Scorpion"),
            ("🐟", "Fish"),
            ("🐠", "Tropical Fish"),
            ("🐡", "Blowfish"),
            ("🦈", "Shark"),
            ("🐙", "Octopus"),
            ("🦀", "Crab"),
            ("🦞", "Lobster"),
            ("🦐", "Shrimp"),
            ("🐾", "Paw Prints"),
            ("🦌", "Deer"),
            ("🦬", "Bison"),
            ("🦣", "Mammoth"),
        ],
    ),
    "urbex": (
        "Urbex",
        [
            ("📷", "Camera"),
            ("📸", "Selfie"),
            ("🔭", "Telescope"),
            ("🔦", "Flashlight"),
            ("🗺️", "Map"),
            ("🧭", "Compass"),
            ("⛏️", "Pickaxe"),
            ("🪜", "Ladder"),
            ("🔑", "Key"),
            ("🗝️", "Old Key"),
            ("🧱", "Bricks"),
            ("🚪", "Door"),
            ("🪟", "Window"),
            ("🔐", "Locked"),
            ("🔓", "Unlocked"),
            ("💡", "Light"),
            ("🕯️", "Candle"),
            ("📡", "Antenna"),
            ("🕸️", "Cobweb"),
            ("🦇", "Bat"),
            ("💀", "Skull"),
            ("☠️", "Crossbones"),
            ("⚰️", "Coffin"),
            ("🪦", "Grave"),
            ("🔮", "Crystal Ball"),
            ("🧲", "Magnet"),
            ("🔩", "Bolt"),
            ("⚙️", "Gear"),
            ("🪝", "Hook"),
            ("🧰", "Toolbox"),
            ("🔧", "Wrench"),
            ("🔨", "Hammer"),
            ("⛏️", "Pick"),
            ("🪚", "Saw"),
            ("🗜️", "Clamp"),
            ("🧯", "Extinguisher"),
            ("🪣", "Bucket"),
            ("🧪", "Test Tube"),
            ("⚗️", "Flask"),
            ("🔬", "Microscope"),
            ("🏚️", "Abandoned"),
            ("🏗️", "Ruin"),
            ("🕳️", "Hole"),
            ("⛔", "No Entry"),
            ("🚧", "Caution"),
            ("⚠️", "Warning"),
            ("☢️", "Radioactive"),
            ("☣️", "Biohazard"),
        ],
    ),
    "military": (
        "Military",
        [
            ("🎖️", "Medal"),
            ("🏅", "Award"),
            ("🥇", "Gold"),
            ("🥈", "Silver"),
            ("🥉", "Bronze"),
            ("🏆", "Trophy"),
            ("⚔️", "Swords"),
            ("🗡️", "Dagger"),
            ("🛡️", "Shield"),
            ("🪖", "Helmet"),
            ("💂", "Guard"),
            ("🎗️", "Ribbon"),
            ("🏴", "Black Flag"),
            ("🏳️", "White Flag"),
            ("🚩", "Red Flag"),
            ("⚑", "Flag"),
            ("🎌", "Crossed Flags"),
            ("💣", "Bomb"),
            ("🧨", "Firecracker"),
            ("💥", "Explosion"),
            ("🔫", "Pistol"),
            ("🪃", "Boomerang"),
            ("🏹", "Bow"),
            ("🗺️", "Map"),
            ("🧲", "Magnet"),
            ("🔭", "Binoculars"),
            ("📻", "Radio"),
            ("📟", "Pager"),
            ("☢️", "Nuclear"),
            ("☣️", "Biohazard"),
            ("⚡", "Electric"),
            ("🔥", "Fire"),
            ("💨", "Gas"),
            ("🚁", "Helicopter"),
            ("✈️", "Aircraft"),
            ("🛸", "Craft"),
            ("⛽", "Fuel"),
            ("🔋", "Power"),
            ("🛞", "Wheel"),
        ],
    ),
    "objects": (
        "Objects",
        [
            ("📦", "Box"),
            ("📫", "Mailbox"),
            ("📮", "Postbox"),
            ("🗳️", "Ballot Box"),
            ("📝", "Notepad"),
            ("📋", "Clipboard"),
            ("📁", "Folder"),
            ("🗂️", "Files"),
            ("🗃️", "Card Box"),
            ("🗑️", "Wastebasket"),
            ("📌", "Pushpin"),
            ("📍", "Pin"),
            ("📎", "Paperclip"),
            ("🖇️", "Linked"),
            ("📐", "Triangle Ruler"),
            ("📏", "Ruler"),
            ("✂️", "Scissors"),
            ("🔪", "Knife"),
            ("🗡️", "Dagger"),
            ("🔧", "Wrench"),
            ("🪛", "Screwdriver"),
            ("🔨", "Hammer"),
            ("🪝", "Hook"),
            ("🧰", "Toolbox"),
            ("⛏️", "Pickaxe"),
            ("🪚", "Saw"),
            ("🔩", "Nut"),
            ("⚙️", "Gear"),
            ("🧲", "Magnet"),
            ("🔋", "Battery"),
            ("💡", "Bulb"),
            ("🔦", "Flashlight"),
            ("🕯️", "Candle"),
            ("🪔", "Diya Lamp"),
            ("🧯", "Extinguisher"),
            ("🛢️", "Oil Drum"),
            ("💰", "Money Bag"),
            ("💵", "Dollar"),
            ("💎", "Diamond"),
            ("🔐", "Locked"),
            ("🔑", "Key"),
            ("🗝️", "Old Key"),
            ("🔓", "Unlocked"),
            ("🚪", "Door"),
            ("🪟", "Window"),
            ("🪑", "Chair"),
            ("🛋️", "Couch"),
            ("🛏️", "Bed"),
            ("🚿", "Shower"),
            ("🛁", "Bathtub"),
            ("🪠", "Plunger"),
            ("🧹", "Broom"),
            ("🧺", "Basket"),
            ("🪣", "Bucket"),
            ("🧻", "Roll"),
            ("🪞", "Mirror"),
            ("🖼️", "Frame"),
            ("🧸", "Teddy Bear"),
            ("🪆", "Doll"),
            ("🎁", "Gift"),
            ("📷", "Camera"),
            ("📸", "Camera Flash"),
            ("📹", "Video"),
            ("📽️", "Film"),
            ("📺", "TV"),
            ("📻", "Radio"),
            ("🎙️", "Microphone"),
            ("☎️", "Phone"),
            ("📞", "Receiver"),
            ("📟", "Pager"),
            ("💻", "Laptop"),
            ("⌨️", "Keyboard"),
            ("🖥️", "Monitor"),
            ("🖨️", "Printer"),
            ("🖱️", "Mouse"),
            ("💾", "Disk"),
            ("💿", "CD"),
            ("📀", "DVD"),
            ("📡", "Satellite"),
            ("🔭", "Telescope"),
            ("🔬", "Microscope"),
            ("⚗️", "Alembic"),
            ("🧪", "Test Tube"),
            ("🧫", "Petri"),
            ("📅", "Calendar"),
            ("📆", "Tear-off Calendar"),
            ("🗓️", "Spiral Calendar"),
            ("⏰", "Alarm Clock"),
            ("🕰️", "Mantel Clock"),
            ("⏳", "Hourglass"),
            ("⌚", "Watch"),
            ("⏱️", "Stopwatch"),
            ("🪙", "Coin"),
            ("💴", "Yen"),
            ("💶", "Euro"),
            ("💷", "Pound"),
            ("💸", "Money with Wings"),
            ("💳", "Credit Card"),
            ("🧾", "Receipt"),
            ("📄", "Document"),
            ("📃", "Page"),
            ("📜", "Scroll"),
            ("📂", "Open Folder"),
            ("🖌️", "Paintbrush"),
            ("✏️", "Pencil"),
            ("🖍️", "Crayon"),
            ("🖊️", "Pen"),
            ("🎨", "Palette"),
        ],
    ),
    "rooms": (
        "Rooms",
        [
            ("🏠", "House"),
            ("🏡", "Garden"),
            ("🚪", "Door"),
            ("🪟", "Window"),
            ("🛋️", "Living Room"),
            ("🪑", "Chair"),
            ("🛏️", "Bedroom"),
            ("🛁", "Bathroom"),
            ("🚿", "Shower"),
            ("🚽", "Toilet"),
            ("🪠", "Plunger"),
            ("🧹", "Broom"),
            ("🧺", "Laundry"),
            ("🪣", "Bucket"),
            ("🧻", "Paper"),
            ("🪞", "Mirror"),
            ("🛠️", "Workshop"),
            ("🔧", "Repair"),
            ("🗂️", "Office"),
            ("📚", "Library"),
            ("🍽️", "Dining Room"),
            ("🥘", "Kitchen"),
            ("🍳", "Cooking"),
            ("🧊", "Freezer"),
            ("♨️", "Hot Spring"),
            ("🛕", "Attic"),
            ("🪜", "Stairs"),
            ("🏗️", "Basement"),
            ("🔑", "Entry"),
            ("🗄️", "Filing"),
            ("📦", "Storage"),
            ("🖼️", "Gallery"),
            ("🎨", "Studio"),
            ("🎭", "Stage"),
            ("🎬", "Screening"),
            ("⛏️", "Cellar"),
        ],
    ),
    "entertainment": (
        "Events",
        [
            ("🎭", "Theater"),
            ("🎪", "Circus"),
            ("🎢", "Coaster"),
            ("🎠", "Carousel"),
            ("🎡", "Ferris Wheel"),
            ("🎬", "Film"),
            ("🎥", "Movie"),
            ("🎞️", "Film Strip"),
            ("📽️", "Projector"),
            ("🎦", "Cinema"),
            ("🎵", "Music"),
            ("🎶", "Notes"),
            ("🎸", "Guitar"),
            ("🥁", "Drums"),
            ("🎹", "Piano"),
            ("🎺", "Trumpet"),
            ("🎻", "Violin"),
            ("🪕", "Banjo"),
            ("🎷", "Saxophone"),
            ("🪗", "Accordion"),
            ("🎤", "Microphone"),
            ("🎧", "Headphones"),
            ("📯", "Horn"),
            ("🎼", "Score"),
            ("🎰", "Slot Machine"),
            ("🎳", "Bowling"),
            ("🎯", "Dart"),
            ("🎱", "Billiards"),
            ("🎲", "Dice"),
            ("🃏", "Cards"),
            ("🀄", "Mahjong"),
            ("🎴", "Flower Cards"),
            ("🎮", "Game"),
            ("🕹️", "Joystick"),
            ("🎈", "Balloon"),
            ("🎉", "Party"),
            ("🎊", "Confetti"),
            ("🎆", "Fireworks"),
            ("🎇", "Sparkler"),
            ("✨", "Sparkles"),
        ],
    ),
    "food": (
        "Food",
        [
            ("🍎", "Apple"),
            ("🍊", "Orange"),
            ("🍋", "Lemon"),
            ("🍇", "Grapes"),
            ("🍓", "Strawberry"),
            ("🫐", "Blueberry"),
            ("🍒", "Cherry"),
            ("🍑", "Peach"),
            ("🥭", "Mango"),
            ("🍍", "Pineapple"),
            ("🥥", "Coconut"),
            ("🍌", "Banana"),
            ("🍕", "Pizza"),
            ("🍔", "Burger"),
            ("🌮", "Taco"),
            ("🌯", "Wrap"),
            ("🥗", "Salad"),
            ("🍜", "Noodles"),
            ("🍱", "Bento"),
            ("🍣", "Sushi"),
            ("🍰", "Cake"),
            ("🎂", "Birthday"),
            ("🧁", "Cupcake"),
            ("🍩", "Donut"),
            ("🍪", "Cookie"),
            ("🍫", "Chocolate"),
            ("🍬", "Candy"),
            ("🍭", "Lollipop"),
            ("☕", "Coffee"),
            ("🍵", "Tea"),
            ("🧃", "Juice"),
            ("🥤", "Drink"),
            ("🍺", "Beer"),
            ("🍷", "Wine"),
            ("🥂", "Champagne"),
            ("🍾", "Bottle"),
        ],
    ),
    "hearts": (
        "Hearts",
        [
            ("❤️", "Red Heart"),
            ("🧡", "Orange Heart"),
            ("💛", "Yellow Heart"),
            ("💚", "Green Heart"),
            ("💙", "Blue Heart"),
            ("💜", "Purple Heart"),
            ("🖤", "Black Heart"),
            ("🤍", "White Heart"),
            ("🤎", "Brown Heart"),
            ("💕", "Two Hearts"),
            ("💞", "Revolving"),
            ("💓", "Beating"),
            ("💗", "Growing"),
            ("💖", "Sparkling"),
            ("💘", "Arrow"),
            ("💝", "Ribbon"),
            ("💟", "Decoration"),
            ("❣️", "Exclamation"),
            ("♥️", "Card Suit"),
            ("💔", "Broken"),
            ("❤️‍🔥", "On Fire"),
            ("❤️‍🩹", "Healing"),
            ("🫀", "Anatomical"),
        ],
    ),
    "stars": (
        "Stars",
        [
            ("⭐", "Star"),
            ("🌟", "Glowing"),
            ("💫", "Dizzy"),
            ("✨", "Sparkles"),
            ("🌠", "Shooting Star"),
            ("⚡", "Lightning"),
            ("🌙", "Crescent Moon"),
            ("🌛", "First Quarter"),
            ("🌜", "Last Quarter"),
            ("🌝", "Full Moon Face"),
            ("🌞", "Sun Face"),
            ("☀️", "Sun"),
            ("🌤️", "Sun Cloud"),
            ("🌈", "Rainbow"),
            ("🌌", "Milky Way"),
            ("🪐", "Saturn"),
            ("🌍", "Earth"),
            ("🌎", "Americas"),
            ("🌏", "Asia"),
            ("🔯", "Star of David"),
            ("✡️", "Jewish Star"),
            ("💥", "Collision"),
            ("🎇", "Sparkler"),
            ("🎆", "Fireworks"),
            ("🏅", "Medal"),
            ("🥇", "Gold"),
            ("🥈", "Silver"),
            ("🥉", "Bronze"),
        ],
    ),
    "symbols": (
        "Symbols",
        [
            ("🛑", "Stop Sign"),
            ("❌", "Cross Mark"),
            ("✖️", "Multiply X"),
            ("❗", "Exclamation"),
            ("❓", "Question"),
            ("‼️", "Double Exclaim"),
            ("⁉️", "Exclaim Question"),
            ("🔴", "Red Circle"),
            ("🟠", "Orange Circle"),
            ("🟡", "Yellow Circle"),
            ("🟢", "Green Circle"),
            ("🔵", "Blue Circle"),
            ("🟣", "Purple Circle"),
            ("🟤", "Brown Circle"),
            ("⚫", "Black Circle"),
            ("⚪", "White Circle"),
            ("🔶", "Orange Diamond"),
            ("🔷", "Blue Diamond"),
            ("🔸", "Small Orange"),
            ("🔹", "Small Blue"),
            ("🔺", "Red Triangle Up"),
            ("🔻", "Red Triangle Down"),
            ("💠", "Diamond Blue"),
            ("🔘", "Radio Button"),
            ("🔲", "Black Square"),
            ("🔳", "White Square"),
            ("⬛", "Black Lg Square"),
            ("⬜", "White Lg Square"),
            ("◼️", "Med Black"),
            ("◻️", "Med White"),
            ("✅", "Check"),
            ("❎", "Cross"),
            ("🆗", "OK"),
            ("🆕", "New"),
            ("🆙", "Up"),
            ("🆒", "Cool"),
            ("🆓", "Free"),
            ("🆖", "NG"),
            ("🅰️", "A Blood"),
            ("🅱️", "B Blood"),
            ("🆎", "AB"),
            ("🅾️", "O Blood"),
            ("🔱", "Trident"),
            ("📛", "Name Badge"),
            ("🔰", "Japanese"),
            ("♻️", "Recycle"),
            ("✳️", "Eight Star"),
            ("❇️", "Sparkle"),
            ("💯", "100"),
            ("🔞", "No Under 18"),
            ("📵", "No Mobile"),
            ("🚫", "Prohibited"),
            ("⛔", "No Entry"),
            ("🚳", "No Bikes"),
            ("🚭", "No Smoking"),
            ("🚯", "No Littering"),
            ("🚱", "Non-Potable"),
            ("♠️", "Spade"),
            ("♥️", "Heart"),
            ("♦️", "Diamond"),
            ("♣️", "Club"),
            ("🎴", "Flower Card"),
            ("🃏", "Joker"),
            ("🀄", "Mahjong"),
            ("🎰", "Slots"),
            ("♾️", "Infinity"),
            ("©️", "Copyright"),
            ("®️", "Registered"),
            ("™️", "Trademark"),
        ],
    ),
    "numbers": (
        "Numbers",
        [
            ("0️⃣", "Zero"),
            ("1️⃣", "One"),
            ("2️⃣", "Two"),
            ("3️⃣", "Three"),
            ("4️⃣", "Four"),
            ("5️⃣", "Five"),
            ("6️⃣", "Six"),
            ("7️⃣", "Seven"),
            ("8️⃣", "Eight"),
            ("9️⃣", "Nine"),
            ("🔟", "Ten"),
            ("🔢", "1234"),
            ("🔣", "Symbols"),
            ("🔤", "ABC"),
            ("🔡", "abcd"),
            ("🔠", "ABCD"),
            ("#️⃣", "Hash"),
            ("*️⃣", "Asterisk"),
        ],
    ),
    "letters": (
        "Letters",
        [
            ("🅰️", "A"),
            ("🅱️", "B"),
            ("🆎", "AB"),
            ("🅾️", "O"),
            ("🆑", "CL"),
            ("🆘", "SOS"),
            ("🆔", "ID"),
            ("🆚", "VS"),
            ("🆕", "NEW"),
            ("🆓", "FREE"),
            ("🆒", "COOL"),
            ("🆗", "OK"),
            ("🆙", "UP"),
            ("🆖", "NG"),
            ("🔤", "ABC"),
            ("🔡", "abc"),
            ("🔠", "ABCD"),
            ("🔣", "Symbols"),
            ("🇦", "A Flag"),
            ("🇧", "B Flag"),
            ("🇨", "C Flag"),
            ("🇩", "D Flag"),
            ("🇪", "E Flag"),
            ("🇫", "F Flag"),
            ("🇬", "G Flag"),
            ("🇭", "H Flag"),
            ("🇮", "I Flag"),
            ("🇯", "J Flag"),
            ("🇰", "K Flag"),
            ("🇱", "L Flag"),
            ("🇲", "M Flag"),
            ("🇳", "N Flag"),
            ("🇴", "O Flag"),
            ("🇵", "P Flag"),
            ("🇶", "Q Flag"),
            ("🇷", "R Flag"),
            ("🇸", "S Flag"),
            ("🇹", "T Flag"),
            ("🇺", "U Flag"),
            ("🇻", "V Flag"),
            ("🇼", "W Flag"),
            ("🇽", "X Flag"),
            ("🇾", "Y Flag"),
            ("🇿", "Z Flag"),
        ],
    ),
    "people": (
        "People",
        [
            ("👤", "Person"),
            ("👥", "People"),
            ("👫", "Couple"),
            ("👬", "Men"),
            ("👭", "Women"),
            ("🧑", "Person"),
            ("👶", "Baby"),
            ("🧒", "Child"),
            ("👦", "Boy"),
            ("👧", "Girl"),
            ("🧑‍🦱", "Curly Hair"),
            ("🧑‍🦰", "Red Hair"),
            ("🧑‍🦳", "White Hair"),
            ("🧑‍🦲", "Bald"),
            ("👱", "Blond"),
            ("🧔", "Beard"),
            ("👴", "Old Man"),
            ("👵", "Old Woman"),
            ("🧓", "Older Person"),
            ("👮", "Police"),
            ("👷", "Construction"),
            ("💂", "Guard"),
            ("🕵️", "Detective"),
            ("🧙", "Wizard"),
            ("🧛", "Vampire"),
            ("🧟", "Zombie"),
            ("🧞", "Genie"),
            ("🧝", "Elf"),
            ("🧚", "Fairy"),
            ("🦸", "Superhero"),
            ("🦹", "Supervillain"),
            ("👻", "Ghost"),
            ("💀", "Skull"),
            ("☠️", "Bones"),
            ("👽", "Alien"),
            ("🤖", "Robot"),
            ("🎃", "Jack-o-lantern"),
            ("💩", "Poo"),
            ("👁️", "Eye"),
            ("👀", "Eyes"),
            ("👂", "Ear"),
            ("👃", "Nose"),
            ("👋", "Wave"),
            ("🤚", "Hand"),
            ("👍", "Thumbs Up"),
            ("👎", "Thumbs Down"),
            ("✌️", "Peace"),
            ("🤞", "Fingers Crossed"),
            ("🤘", "Rock On"),
            ("👊", "Fist"),
            ("✊", "Raised Fist"),
            ("🙌", "Hands"),
            ("🙏", "Pray"),
        ],
    ),
    "status": (
        "Status",
        [
            ("✅", "Visited"),
            ("❎", "Not Done"),
            ("⛔", "Forbidden"),
            ("🚫", "Blocked"),
            ("⚠️", "Warning"),
            ("🚧", "Caution"),
            ("📍", "Pin"),
            ("📌", "Pushpin"),
            ("🚩", "Flag"),
            ("🏁", "Finish"),
            ("🏳️", "Surrender"),
            ("🏴", "Dark"),
            ("🔴", "Red"),
            ("🟠", "Orange"),
            ("🟡", "Yellow"),
            ("🟢", "Green"),
            ("🔵", "Blue"),
            ("🟣", "Purple"),
            ("⚫", "Black"),
            ("⚪", "White"),
            ("🔒", "Locked"),
            ("🔓", "Unlocked"),
            ("🔐", "Key Lock"),
            ("🗝️", "Key"),
            ("🏆", "Trophy"),
            ("🥇", "First"),
            ("🥈", "Second"),
            ("🥉", "Third"),
            ("🎖️", "Medal"),
            ("💎", "Rare"),
            ("🌟", "Featured"),
            ("💫", "Special"),
            ("🆕", "New"),
            ("🆗", "OK"),
            ("🔞", "Adults"),
            ("💯", "Perfect"),
            ("❗", "Important"),
            ("❓", "Unknown"),
            ("💤", "Inactive"),
            ("♾️", "Ongoing"),
        ],
    ),
    "weather": (
        "Weather",
        [
            ("☀️", "Sunny"),
            ("🌤️", "Partly Cloudy"),
            ("⛅", "Cloudy"),
            ("🌥️", "Overcast"),
            ("☁️", "Cloud"),
            ("🌦️", "Rain Sun"),
            ("🌧️", "Rainy"),
            ("⛈️", "Thunder"),
            ("🌩️", "Lightning"),
            ("🌨️", "Snow"),
            ("❄️", "Snowflake"),
            ("⛄", "Snowman"),
            ("🌬️", "Wind"),
            ("💨", "Blow"),
            ("🌪️", "Tornado"),
            ("🌫️", "Fog"),
            ("🌊", "Wave"),
            ("🌈", "Rainbow"),
            ("☔", "Umbrella Rain"),
            ("⛱️", "Umbrella"),
            ("🌡️", "Thermometer"),
            ("🔥", "Hot"),
            ("🧊", "Cold"),
            ("💧", "Wet"),
            ("🌙", "Night"),
            ("🌛", "Crescent"),
            ("🌝", "Full Moon"),
            ("☀️", "Bright"),
            ("🌅", "Sunrise"),
            ("🌄", "Dawn"),
            ("🌇", "Dusk"),
            ("🌆", "Evening"),
        ],
    ),
    "space": (
        "Space",
        [
            ("🌑", "New Moon"),
            ("🌒", "Waxing Crescent"),
            ("🌓", "First Quarter"),
            ("🌔", "Waxing Gibbous"),
            ("🌕", "Full Moon"),
            ("🌖", "Waning Gibbous"),
            ("🌗", "Last Quarter"),
            ("🌘", "Waning Crescent"),
            ("🌙", "Crescent Moon"),
            ("🌛", "First Quarter Face"),
            ("🌜", "Last Quarter Face"),
            ("🌝", "Full Moon Face"),
            ("🌞", "Sun Face"),
            ("☀️", "Sun"),
            ("⭐", "Star"),
            ("🌟", "Glowing Star"),
            ("💫", "Dizzy Star"),
            ("🌠", "Shooting Star"),
            ("☄️", "Comet"),
            ("🌌", "Galaxy"),
            ("🪐", "Ringed Planet"),
            ("🌍", "Earth"),
            ("🌎", "Americas"),
            ("🌏", "Asia Pacific"),
            ("👽", "Alien"),
            ("👾", "Space Invader"),
            ("🛸", "UFO"),
            ("🚀", "Rocket"),
            ("🔭", "Telescope"),
        ],
    ),
    "crafts": (
        "Crafts",
        [
            ("🧵", "Thread"),
            ("🪡", "Sewing Needle"),
            ("🧶", "Yarn"),
            ("✂️", "Scissors"),
            ("🧷", "Safety Pin"),
            ("📐", "Set Square"),
            ("📏", "Ruler"),
            ("🖌️", "Paintbrush"),
            ("✏️", "Pencil"),
            ("🖍️", "Crayon"),
            ("🖊️", "Pen"),
            ("🎨", "Palette"),
            ("🖼️", "Painting"),
            ("🧰", "Toolbox"),
            ("🔨", "Hammer"),
            ("🔧", "Wrench"),
            ("🪛", "Screwdriver"),
            ("⚒️", "Hammer and Pick"),
            ("🛠️", "Hammer and Wrench"),
            ("🔩", "Bolt"),
            ("⚙️", "Gear"),
            ("🪚", "Saw"),
            ("🗜️", "Clamp"),
        ],
    ),
    "vintage": (
        "Vintage",
        [
            ("🏺", "Amphora"),
            ("🪙", "Old Coin"),
            ("👑", "Crown"),
            ("📜", "Scroll"),
            ("🔮", "Crystal Ball"),
            ("⚱️", "Urn"),
            ("🕰️", "Mantel Clock"),
            ("🪬", "Hamsa"),
            ("🧿", "Evil Eye"),
            ("🗿", "Moai"),
            ("🪆", "Nesting Doll"),
            ("🎪", "Carnival"),
            ("🎠", "Carousel"),
            ("🎻", "Violin"),
            ("📯", "Post Horn"),
            ("🔭", "Spyglass"),
            ("🧭", "Compass"),
            ("🗺️", "Old Map"),
            ("🧳", "Old Luggage"),
            ("🎩", "Top Hat"),
            ("👒", "Sun Hat"),
            ("🪞", "Antique Mirror"),
            ("🛢️", "Oil Drum"),
            ("⚙️", "Vintage Gear"),
            ("🪝", "Old Hook"),
            ("🔑", "Old Key"),
            ("🗝️", "Skeleton Key"),
            ("📿", "Beads"),
        ],
    ),
    "religion": (
        "Religion",
        [
            ("✝️", "Cross"),
            ("☪️", "Star and Crescent"),
            ("☸️", "Dharma Wheel"),
            ("✡️", "Star of David"),
            ("☯️", "Yin Yang"),
            ("🕎", "Menorah"),
            ("☦️", "Orthodox Cross"),
            ("🛐", "Place of Worship"),
            ("🙏", "Praying Hands"),
            ("🕉️", "Om"),
            ("☮️", "Peace Symbol"),
            ("🔯", "Hexagram"),
            ("💒", "Wedding Chapel"),
            ("⛪", "Church"),
            ("🕌", "Mosque"),
            ("🕍", "Synagogue"),
            ("🛕", "Temple"),
            ("⛩️", "Shinto Shrine"),
            ("🕋", "Kaaba"),
            ("⚰️", "Coffin"),
            ("🪦", "Gravestone"),
            ("📿", "Prayer Beads"),
            ("🕯️", "Candle"),
            ("📖", "Holy Book"),
        ],
    ),
    "tools": (
        "Tools",
        [
            ("🔨", "Hammer"),
            ("🪓", "Axe"),
            ("⛏️", "Pickaxe"),
            ("⚒️", "Hammer and Pick"),
            ("🛠️", "Hammer and Wrench"),
            ("🔧", "Wrench"),
            ("🪛", "Screwdriver"),
            ("🔩", "Bolt and Nut"),
            ("⚙️", "Gear"),
            ("🪚", "Saw"),
            ("🗜️", "Clamp"),
            ("🪝", "Hook"),
            ("🪜", "Ladder"),
            ("🧲", "Magnet"),
            ("📐", "Set Square"),
            ("📏", "Ruler"),
            ("✂️", "Scissors"),
            ("🔪", "Knife"),
            ("🗡️", "Dagger"),
            ("🪣", "Bucket"),
            ("🧹", "Broom"),
            ("🪠", "Plunger"),
            ("🧯", "Fire Extinguisher"),
            ("🛢️", "Oil Drum"),
            ("⛽", "Fuel"),
            ("🔑", "Key"),
            ("🗝️", "Old Key"),
            ("🔋", "Battery"),
            ("💡", "Light Bulb"),
            ("🔦", "Flashlight"),
            ("🕯️", "Candle"),
            ("📡", "Antenna"),
            ("🧰", "Toolbox"),
            ("🪤", "Mousetrap"),
            ("🪜", "Stepladder"),
            ("🧱", "Bricks"),
            ("🔐", "Padlock Key"),
            ("🔒", "Locked"),
            ("🔓", "Unlocked"),
        ],
    ),
    "flags": (
        "Flags",
        [
            ("🏳️", "White Flag"),
            ("🏴", "Black Flag"),
            ("🚩", "Red Flag"),
            ("🏁", "Checkered Flag"),
            ("🎌", "Crossed Flags"),
            ("🏴‍☠️", "Pirate Flag"),
            ("🇺🇸", "USA"),
            ("🇬🇧", "UK"),
            ("🇨🇦", "Canada"),
            ("🇦🇺", "Australia"),
            ("🇳🇿", "New Zealand"),
            ("🇫🇷", "France"),
            ("🇩🇪", "Germany"),
            ("🇮🇹", "Italy"),
            ("🇪🇸", "Spain"),
            ("🇵🇹", "Portugal"),
            ("🇳🇱", "Netherlands"),
            ("🇧🇪", "Belgium"),
            ("🇨🇭", "Switzerland"),
            ("🇦🇹", "Austria"),
            ("🇸🇪", "Sweden"),
            ("🇳🇴", "Norway"),
            ("🇩🇰", "Denmark"),
            ("🇫🇮", "Finland"),
            ("🇮🇪", "Ireland"),
            ("🇬🇷", "Greece"),
            ("🇵🇱", "Poland"),
            ("🇷🇺", "Russia"),
            ("🇺🇦", "Ukraine"),
            ("🇹🇷", "Turkey"),
            ("🇯🇵", "Japan"),
            ("🇰🇷", "South Korea"),
            ("🇨🇳", "China"),
            ("🇮🇳", "India"),
            ("🇮🇩", "Indonesia"),
            ("🇵🇭", "Philippines"),
            ("🇻🇳", "Vietnam"),
            ("🇹🇭", "Thailand"),
            ("🇲🇾", "Malaysia"),
            ("🇸🇬", "Singapore"),
            ("🇸🇦", "Saudi Arabia"),
            ("🇮🇱", "Israel"),
            ("🇮🇷", "Iran"),
            ("🇮🇶", "Iraq"),
            ("🇪🇬", "Egypt"),
            ("🇿🇦", "South Africa"),
            ("🇳🇬", "Nigeria"),
            ("🇰🇪", "Kenya"),
            ("🇲🇦", "Morocco"),
            ("🇪🇹", "Ethiopia"),
            ("🇧🇷", "Brazil"),
            ("🇦🇷", "Argentina"),
            ("🇨🇱", "Chile"),
            ("🇨🇴", "Colombia"),
            ("🇲🇽", "Mexico"),
            ("🇵🇪", "Peru"),
            ("🇻🇪", "Venezuela"),
            ("🇨🇺", "Cuba"),
            ("🇵🇷", "Puerto Rico"),
            ("🇺🇳", "United Nations"),
            ("🏳️‍🌈", "Rainbow Flag"),
            ("🏳️‍⚧️", "Trans Flag"),
        ],
    ),
    "faces": (
        "Faces",
        [
            ("😀", "Grinning"),
            ("😃", "Big Smile"),
            ("😄", "Grin"),
            ("😁", "Beaming"),
            ("😆", "Laughing"),
            ("😅", "Sweat Smile"),
            ("🤣", "Rolling Laugh"),
            ("😂", "Tears of Joy"),
            ("🙂", "Slight Smile"),
            ("🙃", "Upside Down"),
            ("🫠", "Melting"),
            ("😉", "Winking"),
            ("😊", "Blushing"),
            ("😇", "Angel"),
            ("🥰", "Hearts"),
            ("😍", "Heart Eyes"),
            ("🤩", "Star Struck"),
            ("😘", "Kiss"),
            ("😋", "Savoring"),
            ("😜", "Winking Tongue"),
            ("🤪", "Zany"),
            ("🤑", "Money Mouth"),
            ("🤗", "Hugging"),
            ("🤭", "Hand Over Mouth"),
            ("🫢", "Gasp"),
            ("🤫", "Shushing"),
            ("🤔", "Thinking"),
            ("🫡", "Saluting"),
            ("🤐", "Zipper Mouth"),
            ("🤨", "Raised Eyebrow"),
            ("😐", "Neutral"),
            ("😑", "Expressionless"),
            ("😶", "No Mouth"),
            ("😏", "Smirk"),
            ("😒", "Unamused"),
            ("🙄", "Eye Roll"),
            ("😬", "Grimacing"),
            ("😌", "Relieved"),
            ("😔", "Pensive"),
            ("😪", "Sleepy"),
            ("🤤", "Drooling"),
            ("😴", "Sleeping"),
            ("😷", "Medical Mask"),
            ("🤒", "Sick"),
            ("🤕", "Injured"),
            ("🤢", "Nauseated"),
            ("🤮", "Vomiting"),
            ("🤧", "Sneezing"),
            ("🥵", "Overheated"),
            ("🥶", "Cold Face"),
            ("🥴", "Woozy"),
            ("😵", "Dizzy"),
            ("🤯", "Exploding Head"),
            ("🤠", "Cowboy"),
            ("🥳", "Partying"),
            ("🥸", "Disguised"),
            ("😎", "Sunglasses"),
            ("🤓", "Nerd"),
            ("🧐", "Monocle"),
            ("😕", "Confused"),
            ("😟", "Worried"),
            ("🙁", "Frowning"),
            ("☹️", "Sad"),
            ("😮", "Open Mouth"),
            ("😲", "Astonished"),
            ("😳", "Flushed"),
            ("🥺", "Pleading"),
            ("🥹", "Holding Back Tears"),
            ("😢", "Crying"),
            ("😭", "Loudly Crying"),
            ("😱", "Screaming"),
            ("😡", "Angry"),
            ("🤬", "Cursing"),
            ("😈", "Smiling Devil"),
            ("👿", "Angry Devil"),
            ("💀", "Skull"),
            ("☠️", "Skull Crossbones"),
            ("💩", "Poo"),
            ("🤡", "Clown"),
            ("👹", "Ogre"),
            ("👺", "Goblin"),
            ("👻", "Ghost"),
            ("👽", "Alien"),
            ("🤖", "Robot"),
            ("😺", "Cat Smile"),
            ("😸", "Cat Grin"),
            ("😹", "Cat Joy"),
            ("😻", "Cat Heart Eyes"),
            ("😼", "Cat Smirk"),
            ("😽", "Cat Kiss"),
            ("🙀", "Cat Scream"),
            ("😿", "Cat Crying"),
            ("😾", "Cat Pouting"),
        ],
    ),
}

COLOR_CHOICES = [
    ("#F44336", "Red"),
    ("#E91E63", "Pink"),
    ("#9C27B0", "Purple"),
    ("#673AB7", "Deep Purple"),
    ("#3F51B5", "Indigo"),
    ("#2196F3", "Blue"),
    ("#03A9F4", "Light Blue"),
    ("#00BCD4", "Cyan"),
    ("#009688", "Teal"),
    ("#4CAF50", "Green"),
    ("#8BC34A", "Light Green"),
    ("#CDDC39", "Lime"),
    ("#FFEB3B", "Yellow"),
    ("#FFC107", "Amber"),
    ("#FF9800", "Orange"),
    ("#FF5722", "Deep Orange"),
    ("#795548", "Brown"),
    ("#607D8B", "Blue Grey"),
    ("#9E9E9E", "Grey"),
]


class Tag(abstract.Model):
    """A named label that can be applied to pins.

    Tags are either global (profile=None, visible to all users) or user-specific
    (profile set, only visible to that user and alongside global tags).

    Tags form an arbitrary-depth hierarchy via the parents M2M. Filtering by a tag
    also matches any descendant tags (use get_tag_and_descendants for the full set).

    Tags absorb the functionality of the former PinList model: they carry an icon,
    custom icon, color, description, and ordering weight that feeds into
    Pin.effective_icon's priority chain.
    """

    # NULL = global tag visible to all users; non-null = owned by one user.
    profile = ForeignKey(
        "dashboard.Profile",
        on_delete=CASCADE,
        null=True,
        blank=True,
        related_name="custom_tags",
    )
    name = CharField(max_length=255)
    description = TextField(null=True, blank=True)
    # Hex color string chosen from COLOR_CHOICES (e.g. "#2196F3").
    color = CharField(max_length=50, null=True, blank=True, choices=COLOR_CHOICES)
    icon = CharField(max_length=50, null=True, blank=True)  # emoji char or Material Icons name
    custom_icon = ImageField(upload_to="tag_icons/", null=True, blank=True)
    # Higher order = checked first in the icon priority chain.
    order = IntegerField(default=0)
    # Hierarchical parents - symmetrical=False so parent→child is one direction.
    parents = ManyToManyField(
        "self",
        symmetrical=False,
        blank=True,
        related_name="children",
    )

    objects = TagManager()

    if TYPE_CHECKING:
        profile_id: int | None
        pins: ManyToManyField[Pin, Pin]
        categories: ManyToManyField[Category, Category]

    @classmethod
    def get_tag_and_descendants(cls, tag_id: int) -> set[int]:
        """Return tag_id plus all descendant tag IDs (BFS, cycle-safe).

        Used so that filtering pins by a parent tag also surfaces pins carrying
        any of its descendant tags.
        """
        visited: set[int] = set()
        queue: list[int] = [tag_id]
        while queue:
            current = queue.pop(0)
            if current in visited:
                continue
            visited.add(current)
            children_ids = list(cls.objects.filter(parents__id=current).values_list("id", flat=True))
            queue.extend(children_ids)
        return visited

    def __str__(self) -> str:
        if self.profile_id:
            return f"{self.name} ({self.profile})"
        return f"{self.name} [global]"

    class Meta(abstract.Model.Meta):
        db_table = "dashboard_tags"
        ordering = ["-order", "name"]
        get_latest_by = "updated"
        indexes = [
            Index(fields=["profile"]),
            Index(fields=["profile", "order"]),
        ]
