
KIND_TAG = "tag"
KIND_CATEGORY = "category"
KIND_STATUS = "status"
KIND_USER = "user"
KIND_CHOICES = [
    (KIND_TAG, "Tag"),
    (KIND_CATEGORY, "Category"),
    (KIND_STATUS, "Status"),
    (KIND_USER, "Person"),
]

ICON_CHOICES = [
    ("bookmark", "Bookmark"),
    ("star", "Star"),
    ("heart", "Heart"),
    ("flag", "Flag"),
    ("camera", "Camera"),
    ("home", "Home"),
    ("place", "Place"),
    ("explore", "Explore"),
    ("hiking", "Hiking"),
    ("warning", "Warning"),
    ("check_circle", "Check Circle"),
    ("schedule", "Schedule"),
    ("visibility", "Visibility"),
    ("lock", "Private"),
    ("archive", "Archive"),
    ("label", "Label"),
    ("local_offer", "Tag"),
    ("category", "Category"),
]

# Emoji / icon categories for the picker UI.
# Structure: { cat_id: (label, [(icon, display_label), ...]) }
ICON_CATEGORIES = {
    "places": (
        "Places",
        [
            ("🏠", "House"),
            ("🏡", "Home"),
            ("🏚️", "Abandoned"),
            ("🏢", "Office"),
            ("🏣", "Building"),
            ("🏤", "Post Office"),
            ("🏥", "Hospital"),
            ("🏦", "Bank"),
            ("🏧", "ATM"),
            ("🏨", "Hotel"),
            ("🏩", "Love Hotel"),
            ("🏪", "Shop"),
            ("🏫", "School"),
            ("🏬", "Mall"),
            ("🏭", "Factory"),
            ("🏯", "Fort"),
            ("🏰", "Castle"),
            ("🏯", "Castle Ruins"),
            ("🏛️", "Museum / Courthouse"),
            ("🏛️", "Ancient Ruins"),
            ("🎟️", "Admission Ticket"),
            ("🎫", "Ticket"),
            ("🧾", "Permit / Receipt"),
            ("🪨", "Rubble / Rock Pile"),
            ("🏗️", "Construction"),
            ("🏟️", "Stadium"),
            ("🗼", "Tower"),
            ("🗽", "Monument"),
            ("🗾", "Island"),
            ("🕌", "Mosque"),
            ("🕍", "Synagogue"),
            ("🛕", "Temple"),
            ("⛪", "Church"),
            ("⛩️", "Shrine"),
            ("🕋", "Kaaba"),
            ("⛲", "Fountain"),
            ("⛺", "Tent"),
            ("🏕️", "Campsite"),
            ("🛖", "Hut"),
            ("🏙️", "City"),
            ("🌆", "Cityscape"),
            ("🌇", "Sunset City"),
            ("🌃", "Night City"),
            ("🌉", "Bridge Night"),
            ("🌁", "Fog"),
            ("🏘️", "Houses"),
            ("🏔️", "Mountain"),
            ("⛰️", "Hill"),
            ("🌋", "Volcano"),
        ],
    ),
    "arrows": (
        "Arrows",
        [
            ("⬆️", "Up"),
            ("⬇️", "Down"),
            ("⬅️", "Left"),
            ("➡️", "Right"),
            ("↗️", "Up-Right"),
            ("↘️", "Down-Right"),
            ("↙️", "Down-Left"),
            ("↖️", "Up-Left"),
            ("↕️", "Up-Down"),
            ("↔️", "Left-Right"),
            ("↩️", "Left Hook"),
            ("↪️", "Right Hook"),
            ("🔄", "Counterclockwise"),
            ("🔃", "Clockwise"),
            ("↰", "Up and Left"),
            ("↱", "Up and Right"),
            ("⤴️", "Right Curve Up"),
            ("⤵️", "Right Curve Down"),
            ("🔀", "Shuffle"),
            ("🔁", "Repeat Loop"),
            ("🔂", "Repeat One"),
            ("🔄", "Refresh / Repeat"),
            ("🔃", "Clockwise Repeat"),
            ("▶️", "Play Right"),
            ("◀️", "Play Left"),
            ("⏫", "Fast Up"),
            ("⏬", "Fast Down"),
            ("⏩", "Fast Forward"),
            ("⏪", "Fast Backward"),
        ],
    ),
    "transport": (
        "Transport",
        [
            ("🚂", "Train"),
            ("🚃", "Rail Car"),
            ("🚄", "Bullet Train"),
            ("🚅", "High Speed"),
            ("🚆", "Train"),
            ("🚇", "Metro / Underground"),
            ("🚈", "Light Rail"),
            ("🚉", "Station"),
            ("🕳️", "Tunnel / Hole"),
            ("🚊", "Tram"),
            ("🚝", "Monorail"),
            ("🚞", "Mountain Rail"),
            ("🚋", "Tram Car"),
            ("🚌", "Bus"),
            ("🚍", "Bus"),
            ("🚎", "Trolley"),
            ("🚐", "Minibus"),
            ("🚑", "Ambulance"),
            ("🚒", "Fire Truck"),
            ("🚓", "Police Car"),
            ("🚔", "Police"),
            ("🚕", "Taxi"),
            ("🚖", "Taxi"),
            ("🚗", "Car"),
            ("🚘", "Car"),
            ("🚙", "SUV"),
            ("🚚", "Truck"),
            ("🚛", "Semi Truck"),
            ("🚜", "Tractor"),
            ("🚧", "Bulldozer / Construction"),
            ("🏎️", "Race Car"),
            ("🏍️", "Motorcycle"),
            ("🛵", "Scooter"),
            ("🚲", "Bicycle"),
            ("🛴", "Kick Scooter"),
            ("🛺", "Rickshaw"),
            ("🚁", "Helicopter"),
            ("🛸", "UFO"),
            ("✈️", "Airplane"),
            ("🛩️", "Small Plane"),
            ("🛫", "Takeoff"),
            ("🛬", "Landing"),
            ("🪂", "Parachute"),
            ("🚀", "Rocket"),
            ("🛶", "Canoe"),
            ("⛵", "Sailboat"),
            ("🚤", "Speedboat"),
            ("🛥️", "Motorboat"),
            ("🚢", "Ship"),
            ("⛴️", "Ferry"),
            ("🛳️", "Cruise"),
            ("⚓", "Anchor"),
            ("🌉", "Bridge"),
            ("⛽", "Fuel"),
            ("🛣️", "Road"),
            ("🛤️", "Railway"),
        ],
    ),
    "nature": (
        "Nature",
        [
            ("🌲", "Tree"),
            ("🌳", "Deciduous"),
            ("🌴", "Palm"),
            ("🌵", "Cactus"),
            ("🌾", "Field"),
            ("🌿", "Leaf"),
            ("☘️", "Clover"),
            ("🍀", "Four Leaf"),
            ("🍁", "Maple"),
            ("🍂", "Fallen Leaf / Autumn"),
            ("🍃", "Leaves / Spring"),
            ("🌷", "Spring"),
            ("☀️", "Summer"),
            ("❄️", "Winter"),
            ("🪴", "Plant"),
            ("🌱", "Seedling"),
            ("🌻", "Sunflower"),
            ("🌸", "Blossom"),
            ("🌺", "Flower"),
            ("🌹", "Rose"),
            ("💐", "Bouquet"),
            ("🌊", "Wave"),
            ("💧", "Water Drop"),
            ("🌧️", "Rain"),
            ("❄️", "Snow"),
            ("⛄", "Snowman"),
            ("🌨️", "Snowfall"),
            ("🌩️", "Lightning"),
            ("⚡", "Electric"),
            ("🔥", "Fire"),
            ("💨", "Wind"),
            ("🌪️", "Tornado"),
            ("🌈", "Rainbow"),
            ("☀️", "Sun"),
            ("🌙", "Moon"),
            ("⭐", "Star"),
            ("🌟", "Glowing Star"),
            ("☁️", "Cloud"),
            ("⛅", "Partly Cloudy"),
            ("🌤️", "Sun Behind Cloud"),
            ("🌫️", "Fog"),
            ("🏕️", "Campfire"),
            ("🏖️", "Beach"),
            ("🏜️", "Desert"),
            ("🏝️", "Island"),
            ("🏞️", "Park"),
            ("🗻", "Mount Fuji"),
            ("🪨", "Rocks"),
            ("🌎", "Globe"),
            ("🌍", "Earth"),
            ("💦", "Splashing Water"),
            ("🫗", "Pouring"),
            ("🏊", "Swimming"),
            ("🤿", "Diving"),
            ("🏄", "Surfing"),
            ("🚣", "Rowing"),
        ],
    ),
    "animals": (
        "Animals",
        [
            ("🐶", "Dog"),
            ("🐱", "Cat"),
            ("🐭", "Mouse"),
            ("🐹", "Hamster"),
            ("🐰", "Rabbit"),
            ("🦊", "Fox"),
            ("🐻", "Bear"),
            ("🐼", "Panda"),
            ("🐨", "Koala"),
            ("🐯", "Tiger"),
            ("🦁", "Lion"),
            ("🐮", "Cow"),
            ("🐷", "Pig"),
            ("🐸", "Frog"),
            ("🐵", "Monkey"),
            ("🦆", "Duck"),
            ("🦅", "Eagle"),
            ("🦉", "Owl"),
            ("🦇", "Bat"),
            ("🐺", "Wolf"),
            ("🐗", "Boar"),
            ("🦝", "Raccoon"),
            ("🦨", "Skunk"),
            ("🦡", "Badger"),
            ("🦦", "Otter"),
            ("🦥", "Sloth"),
            ("🐿️", "Chipmunk"),
            ("🦔", "Hedgehog"),
            ("🐢", "Turtle"),
            ("🦎", "Lizard"),
            ("🐍", "Snake"),
            ("🦕", "Dinosaur"),
            ("🦖", "T-Rex"),
            ("🦎", "Gecko"),
            ("🐛", "Caterpillar"),
            ("🦋", "Butterfly"),
            ("🐝", "Bee"),
            ("🐞", "Ladybug"),
            ("🕷️", "Spider"),
            ("🦂", "Scorpion"),
            ("🐟", "Fish"),
            ("🐠", "Tropical Fish"),
            ("🐡", "Blowfish"),
            ("🦈", "Shark"),
            ("🐙", "Octopus"),
            ("🦀", "Crab"),
            ("🦞", "Lobster"),
            ("🦐", "Shrimp"),
            ("🐾", "Paw Prints"),
            ("🦌", "Deer"),
            ("🦬", "Bison"),
            ("🦣", "Mammoth"),
        ],
    ),
    "medical": (
        "Medical",
        [
            ("⚕️", "Rod of Asclepius"),
            ("🌟", "Star of Life"),
            ("➕", "Red Cross"),
            ("❤️‍🩹", "First Aid"),
            ("🩺", "Stethoscope"),
            ("🏥", "Hospital"),
            ("🚑", "Ambulance"),
            ("⛑️", "Rescue Helmet"),
            ("💊", "Pill"),
            ("💉", "Syringe"),
            ("🩻", "X-Ray"),
            ("🩹", "Bandage"),
            ("🧬", "DNA"),
            ("🧪", "Test Tube"),
            ("🔬", "Microscope"),
            ("🧫", "Petri Dish"),
            ("☣️", "Biohazard"),
            ("☢️", "Radioactive"),
            ("🩸", "Blood Drop"),
        ],
    ),
    "urbex": (
        "Urbex",
        [
            ("📷", "Camera"),
            ("📸", "Selfie"),
            ("🔭", "Telescope"),
            ("🔦", "Flashlight"),
            ("🗺️", "Map"),
            ("🧭", "Compass"),
            ("🥾", "Boots"),
            ("🎒", "Backpack"),
            ("🪖", "Hardhat / Helmet"),
            ("👷", "Hardhat Worker"),
            ("⛏️", "Pickaxe"),
            ("🪜", "Ladder"),
            ("🔑", "Key"),
            ("🗝️", "Old Key"),
            ("🧱", "Bricks"),
            ("🕳️", "Underground / Tunnel"),
            ("▦", "Sewer Grate"),
            ("▤", "Drain Grate"),
            ("🚪", "Door"),
            ("🪟", "Window"),
            ("🔐", "Locked"),
            ("🔓", "Unlocked"),
            ("💡", "Light"),
            ("🕯️", "Candle"),
            ("📡", "Antenna"),
            ("🕸️", "Cobweb"),
            ("🦇", "Bat"),
            ("💀", "Skull"),
            ("💪", "Muscle"),
            ("🏋️", "Weights"),
            ("☠️", "Crossbones"),
            ("⚰️", "Coffin"),
            ("🪦", "Grave"),
            ("🔮", "Crystal Ball"),
            ("🧲", "Magnet"),
            ("🔩", "Bolt"),
            ("⚙️", "Gear"),
            ("🪝", "Hook"),
            ("🧰", "Toolbox"),
            ("🔧", "Wrench"),
            ("🔨", "Hammer"),
            ("⛏️", "Pick"),
            ("🪚", "Saw"),
            ("🗜️", "Clamp"),
            ("🧯", "Extinguisher"),
            ("🪣", "Bucket"),
            ("🧪", "Test Tube"),
            ("⚗️", "Flask"),
            ("🔬", "Microscope"),
            ("🏚️", "Abandoned"),
            ("🏛️", "Ruins"),
            ("🪨", "Rubble"),
            ("🏗️", "Construction"),
            ("🕳️", "Hole"),
            ("⛔", "No Entry"),
            ("🚧", "Caution"),
            ("⚠️", "Warning"),
            ("☢️", "Radioactive"),
            ("☣️", "Biohazard"),
        ],
    ),
    "military": (
        "Military",
        [
            ("🎖️", "Medal"),
            ("🏅", "Award"),
            ("🥇", "Gold"),
            ("🥈", "Silver"),
            ("🥉", "Bronze"),
            ("🏆", "Trophy"),
            ("⚔️", "Swords"),
            ("🗡️", "Dagger"),
            ("🛡️", "Shield"),
            ("🪖", "Helmet"),
            ("💂", "Guard"),
            ("🎗️", "Ribbon"),
            ("🏴", "Black Flag"),
            ("🏳️", "White Flag"),
            ("🚩", "Red Flag"),
            ("⚑", "Flag"),
            ("🎌", "Crossed Flags"),
            ("💣", "Bomb"),
            ("🧨", "Firecracker"),
            ("💥", "Explosion"),
            ("🔫", "Pistol"),
            ("🪃", "Boomerang"),
            ("🏹", "Bow"),
            ("🗺️", "Map"),
            ("🧲", "Magnet"),
            ("🔭", "Binoculars"),
            ("📻", "Radio"),
            ("📟", "Pager"),
            ("☢️", "Nuclear"),
            ("☣️", "Biohazard"),
            ("⚡", "Electric"),
            ("🔥", "Fire"),
            ("💨", "Gas"),
            ("🚁", "Helicopter"),
            ("✈️", "Aircraft"),
            ("🛸", "Craft"),
            ("⛽", "Fuel"),
            ("🔋", "Power"),
            ("🛞", "Wheel"),
        ],
    ),
    "objects": (
        "Objects",
        [
            ("📦", "Box"),
            ("📫", "Mailbox"),
            ("📮", "Postbox"),
            ("🗳️", "Ballot Box"),
            ("📝", "Notepad"),
            ("📋", "Clipboard"),
            ("📁", "Folder"),
            ("🗂️", "Files"),
            ("🗃️", "Card Box"),
            ("🗑️", "Wastebasket"),
            ("📌", "Pushpin"),
            ("📍", "Pin"),
            ("📎", "Paperclip"),
            ("🖇️", "Linked"),
            ("📐", "Triangle Ruler"),
            ("📏", "Ruler"),
            ("✂️", "Scissors"),
            ("🔪", "Knife"),
            ("🗡️", "Dagger"),
            ("🔧", "Wrench"),
            ("🪛", "Screwdriver"),
            ("🔨", "Hammer"),
            ("🪝", "Hook"),
            ("🧰", "Toolbox"),
            ("⛏️", "Pickaxe"),
            ("🪚", "Saw"),
            ("🔩", "Nut"),
            ("⚙️", "Gear"),
            ("🧲", "Magnet"),
            ("🔋", "Battery"),
            ("💡", "Bulb"),
            ("🔦", "Flashlight"),
            ("🕯️", "Candle"),
            ("🪔", "Diya Lamp"),
            ("🧯", "Extinguisher"),
            ("🛢️", "Oil Drum"),
            ("⚖️", "Scales / Legal"),
            ("🔨", "Gavel / Hammer"),
            ("💰", "Money Bag"),
            ("💵", "Dollar"),
            ("💎", "Diamond"),
            ("🔐", "Locked"),
            ("🔑", "Key"),
            ("🗝️", "Old Key"),
            ("🔓", "Unlocked"),
            ("🚪", "Door"),
            ("🪟", "Window"),
            ("🪑", "Chair"),
            ("🛋️", "Couch"),
            ("🛏️", "Bed"),
            ("🚿", "Shower"),
            ("🛁", "Bathtub"),
            ("🪠", "Plunger"),
            ("🧹", "Broom"),
            ("🧺", "Basket"),
            ("🪣", "Bucket"),
            ("🧻", "Roll"),
            ("🪞", "Mirror"),
            ("🖼️", "Frame"),
            ("🧸", "Teddy Bear"),
            ("🪆", "Doll"),
            ("🎁", "Gift"),
            ("📷", "Camera"),
            ("📸", "Camera Flash"),
            ("🎞️", "Film Strip"),
            ("🖼️", "Photo Frame"),
            ("📹", "Video"),
            ("📽️", "Film"),
            ("📺", "TV"),
            ("📻", "Radio"),
            ("🎙️", "Microphone"),
            ("☎️", "Phone"),
            ("📞", "Receiver"),
            ("📟", "Pager"),
            ("💻", "Laptop"),
            ("⌨️", "Keyboard"),
            ("🖥️", "Monitor"),
            ("🖨️", "Printer"),
            ("🖱️", "Mouse"),
            ("💾", "Save / Disk"),
            ("💿", "CD"),
            ("📀", "DVD"),
            ("📡", "Satellite"),
            ("🔭", "Telescope"),
            ("🔬", "Microscope"),
            ("⚗️", "Alembic"),
            ("🧪", "Test Tube"),
            ("🧫", "Petri"),
            ("📅", "Calendar"),
            ("📆", "Tear-off Calendar"),
            ("🗓️", "Planner / Date"),
            ("🗓️", "Spiral Calendar"),
            ("🌷", "Spring Season"),
            ("☀️", "Summer Season"),
            ("🍂", "Autumn Season"),
            ("❄️", "Winter Season"),
            ("⏰", "Alarm Clock"),
            ("🕰️", "Mantel Clock"),
            ("⏳", "Hourglass"),
            ("⌚", "Watch"),
            ("⏱️", "Stopwatch"),
            ("🪙", "Coin"),
            ("💴", "Yen"),
            ("💶", "Euro"),
            ("💷", "Pound"),
            ("💸", "Money with Wings"),
            ("💳", "Credit Card"),
            ("🧾", "Receipt"),
            ("📚", "Books"),
            ("📖", "Book"),
            ("🔍", "Magnifying Glass"),
            ("🔎", "Magnifying Glass Tilted"),
            ("👓", "Eyeglasses"),
            ("🕶️", "Sunglasses"),
            ("🏷️", "Tag / Label"),
            ("🔖", "Bookmark"),
            ("🔗", "Share Link"),
            ("📤", "Share / Send"),
            ("📄", "Document"),
            ("📃", "Page"),
            ("📜", "Scroll"),
            ("📂", "Open Folder"),
            ("🧩", "Mosaic Tile"),
            ("◻️", "Ceramic Tile"),
            ("🔲", "Tile Border"),
            ("🖌️", "Paintbrush"),
            ("✏️", "Pencil"),
            ("🖍️", "Crayon"),
            ("🖊️", "Pen"),
            ("🎨", "Palette"),
        ],
    ),
    "rooms": (
        "Rooms",
        [
            ("🏠", "House"),
            ("🏡", "Garden"),
            ("🚪", "Door"),
            ("🪟", "Window"),
            ("🛋️", "Living Room"),
            ("🪑", "Chair"),
            ("🛏️", "Bedroom"),
            ("🛁", "Bathroom"),
            ("🚿", "Shower"),
            ("🚽", "Toilet"),
            ("🪠", "Plunger"),
            ("🧹", "Broom"),
            ("🧺", "Laundry"),
            ("🪣", "Bucket"),
            ("🧻", "Paper"),
            ("🪞", "Mirror"),
            ("🛠️", "Workshop"),
            ("🔧", "Repair"),
            ("🗂️", "Office"),
            ("📚", "Library"),
            ("🍽️", "Dining Room"),
            ("🥘", "Kitchen"),
            ("🍳", "Cooking"),
            ("🧊", "Freezer"),
            ("♨️", "Hot Spring"),
            ("🛕", "Attic"),
            ("🪜", "Stairs"),
            ("🏗️", "Basement"),
            ("🔑", "Entry"),
            ("🗄️", "Filing"),
            ("📦", "Storage"),
            ("🖼️", "Gallery"),
            ("🎨", "Studio"),
            ("🎭", "Stage"),
            ("🎬", "Screening"),
            ("⛏️", "Cellar"),
        ],
    ),
    "entertainment": (
        "Events",
        [
            ("🎭", "Theater"),
            ("🎪", "Circus"),
            ("🎢", "Coaster"),
            ("🎠", "Carousel"),
            ("🎡", "Ferris Wheel"),
            ("🎬", "Film"),
            ("🎥", "Movie"),
            ("🎞️", "Film Strip"),
            ("📽️", "Projector"),
            ("🎦", "Cinema"),
            ("🎵", "Music"),
            ("🎶", "Notes"),
            ("🎸", "Guitar"),
            ("🥁", "Drums"),
            ("🎹", "Piano"),
            ("🎺", "Trumpet"),
            ("🎻", "Violin"),
            ("🪕", "Banjo"),
            ("🎷", "Saxophone"),
            ("🪗", "Accordion"),
            ("🎤", "Microphone"),
            ("🎧", "Headphones"),
            ("📯", "Horn"),
            ("🎼", "Score"),
            ("🎰", "Slot Machine"),
            ("🎳", "Bowling"),
            ("🎯", "Dart"),
            ("🎱", "Billiards"),
            ("🎲", "Dice"),
            ("🃏", "Cards"),
            ("🀄", "Mahjong"),
            ("🎴", "Flower Cards"),
            ("🎮", "Game"),
            ("🕹️", "Joystick"),
            ("🎈", "Balloon"),
            ("🎉", "Party"),
            ("🎊", "Confetti"),
            ("🎆", "Fireworks"),
            ("🎇", "Sparkler"),
            ("✨", "Sparkles"),
        ],
    ),
    "food": (
        "Food",
        [
            ("🍎", "Apple"),
            ("🍊", "Orange"),
            ("🍋", "Lemon"),
            ("🍇", "Grapes"),
            ("🍓", "Strawberry"),
            ("🫐", "Blueberry"),
            ("🍒", "Cherry"),
            ("🍑", "Peach"),
            ("🥭", "Mango"),
            ("🍍", "Pineapple"),
            ("🥥", "Coconut"),
            ("🍌", "Banana"),
            ("🍕", "Pizza"),
            ("🍔", "Burger"),
            ("🌮", "Taco"),
            ("🌯", "Wrap"),
            ("🥗", "Salad"),
            ("🍜", "Noodles"),
            ("🍱", "Bento"),
            ("🍣", "Sushi"),
            ("🍰", "Cake"),
            ("🎂", "Birthday"),
            ("🧁", "Cupcake"),
            ("🍩", "Donut"),
            ("🍪", "Cookie"),
            ("🍫", "Chocolate"),
            ("🍬", "Candy"),
            ("🍭", "Lollipop"),
            ("☕", "Coffee"),
            ("🍵", "Tea"),
            ("🧃", "Juice"),
            ("🥤", "Drink"),
            ("🍺", "Beer"),
            ("🍷", "Wine"),
            ("🥂", "Champagne"),
            ("🍾", "Bottle"),
        ],
    ),
    "hearts": (
        "Hearts",
        [
            ("❤️", "Red Heart"),
            ("🧡", "Orange Heart"),
            ("💛", "Yellow Heart"),
            ("💚", "Green Heart"),
            ("💙", "Blue Heart"),
            ("💜", "Purple Heart"),
            ("🖤", "Black Heart"),
            ("🤍", "White Heart"),
            ("🤎", "Brown Heart"),
            ("💕", "Two Hearts"),
            ("💞", "Revolving"),
            ("💓", "Beating"),
            ("💗", "Growing"),
            ("💖", "Sparkling"),
            ("💘", "Arrow"),
            ("💝", "Ribbon"),
            ("💟", "Decoration"),
            ("❣️", "Exclamation"),
            ("♥️", "Card Suit"),
            ("💔", "Broken"),
            ("❤️‍🔥", "On Fire"),
            ("❤️‍🩹", "Healing"),
            ("🫀", "Anatomical"),
        ],
    ),
    "stars": (
        "Stars",
        [
            ("⭐", "Star"),
            ("🌟", "Glowing"),
            ("💫", "Dizzy"),
            ("✨", "Sparkles"),
            ("🌠", "Shooting Star"),
            ("⚡", "Lightning"),
            ("🌙", "Crescent Moon"),
            ("🌛", "First Quarter"),
            ("🌜", "Last Quarter"),
            ("🌝", "Full Moon Face"),
            ("🌞", "Sun Face"),
            ("☀️", "Sun"),
            ("🌤️", "Sun Cloud"),
            ("🌈", "Rainbow"),
            ("🌌", "Milky Way"),
            ("🪐", "Saturn"),
            ("🌍", "Earth"),
            ("🌎", "Americas"),
            ("🌏", "Asia"),
            ("🔯", "Star of David"),
            ("✡️", "Jewish Star"),
            ("💥", "Collision"),
            ("🎇", "Sparkler"),
            ("🎆", "Fireworks"),
            ("🏅", "Medal"),
            ("🥇", "Gold"),
            ("🥈", "Silver"),
            ("🥉", "Bronze"),
        ],
    ),
    "symbols": (
        "Symbols",
        [
            ("🛑", "Stop Sign"),
            ("❌", "Cross Mark"),
            ("✖️", "Multiply X"),
            ("❗", "Exclamation"),
            ("❓", "Question"),
            ("‼️", "Double Exclaim"),
            ("⁉️", "Exclaim Question"),
            ("🔴", "Red Circle"),
            ("🟠", "Orange Circle"),
            ("🟡", "Yellow Circle"),
            ("🟢", "Green Circle"),
            ("🔵", "Blue Circle"),
            ("🟣", "Purple Circle"),
            ("🟤", "Brown Circle"),
            ("⚫", "Black Circle"),
            ("⚪", "White Circle"),
            ("🔶", "Orange Diamond"),
            ("🔷", "Blue Diamond"),
            ("🔸", "Small Orange"),
            ("🔹", "Small Blue"),
            ("🔺", "Red Triangle Up"),
            ("🔻", "Red Triangle Down"),
            ("▲", "Triangle"),
            ("■", "Square"),
            ("●", "Circle"),
            ("◆", "Diamond"),
            ("⬟", "Pentagon"),
            ("⬢", "Hexagon"),
            ("💠", "Diamond Blue"),
            ("🔘", "Radio Button"),
            ("🔲", "Black Square"),
            ("🔳", "White Square"),
            ("⬛", "Black Lg Square"),
            ("⬜", "White Lg Square"),
            ("◼️", "Med Black"),
            ("◻️", "Med White"),
            ("✅", "Check"),
            ("❎", "Cross"),
            ("🆗", "OK"),
            ("🆕", "New"),
            ("🆙", "Up"),
            ("🆒", "Cool"),
            ("🆓", "Free"),
            ("🆖", "NG"),
            ("🅰️", "A Blood"),
            ("🅱️", "B Blood"),
            ("🆎", "AB"),
            ("🅾️", "O Blood"),
            ("🔱", "Trident"),
            ("📛", "Name Badge"),
            ("🔰", "Japanese"),
            ("♻️", "Recycle"),
            ("✳️", "Eight Star"),
            ("❇️", "Sparkle"),
            ("💯", "100"),
            ("🔞", "No Under 18"),
            ("📵", "No Mobile"),
            ("🚫", "Prohibited"),
            ("⛔", "No Entry"),
            ("🚳", "No Bikes"),
            ("🚭", "No Smoking"),
            ("🚯", "No Littering"),
            ("🚱", "Non-Potable"),
            ("♠️", "Spade"),
            ("♥️", "Heart"),
            ("♦️", "Diamond"),
            ("♣️", "Club"),
            ("🎴", "Flower Card"),
            ("🃏", "Joker"),
            ("🀄", "Mahjong"),
            ("🎰", "Slots"),
            ("♾️", "Infinity / Ouroboros"),
            ("🐍♾️", "Ouroboros Snake"),
            ("⚜️", "Fleur-de-lis"),
            ("©️", "Copyright"),
            ("®️", "Registered"),
            ("™️", "Trademark"),
        ],
    ),
    "numbers": (
        "Numbers",
        [
            ("0️⃣", "Zero"),
            ("1️⃣", "One"),
            ("2️⃣", "Two"),
            ("3️⃣", "Three"),
            ("4️⃣", "Four"),
            ("5️⃣", "Five"),
            ("6️⃣", "Six"),
            ("7️⃣", "Seven"),
            ("8️⃣", "Eight"),
            ("9️⃣", "Nine"),
            ("🔟", "Ten"),
            ("🔢", "1234"),
            ("🔣", "Symbols"),
            ("🔤", "ABC"),
            ("🔡", "abcd"),
            ("🔠", "ABCD"),
            ("#️⃣", "Hash"),
            ("*️⃣", "Asterisk"),
        ],
    ),
    "letters": (
        "Letters",
        [
            ("🅰️", "A"),
            ("🅱️", "B"),
            ("🆎", "AB"),
            ("🅾️", "O"),
            ("🆑", "CL"),
            ("🆘", "SOS"),
            ("🆔", "ID"),
            ("🆚", "VS"),
            ("🆕", "NEW"),
            ("🆓", "FREE"),
            ("🆒", "COOL"),
            ("🆗", "OK"),
            ("🆙", "UP"),
            ("🆖", "NG"),
            ("🔤", "ABC"),
            ("🔡", "abc"),
            ("🔠", "ABCD"),
            ("🔣", "Symbols"),
            ("🇦", "A Flag"),
            ("🇧", "B Flag"),
            ("🇨", "C Flag"),
            ("🇩", "D Flag"),
            ("🇪", "E Flag"),
            ("🇫", "F Flag"),
            ("🇬", "G Flag"),
            ("🇭", "H Flag"),
            ("🇮", "I Flag"),
            ("🇯", "J Flag"),
            ("🇰", "K Flag"),
            ("🇱", "L Flag"),
            ("🇲", "M Flag"),
            ("🇳", "N Flag"),
            ("🇴", "O Flag"),
            ("🇵", "P Flag"),
            ("🇶", "Q Flag"),
            ("🇷", "R Flag"),
            ("🇸", "S Flag"),
            ("🇹", "T Flag"),
            ("🇺", "U Flag"),
            ("🇻", "V Flag"),
            ("🇼", "W Flag"),
            ("🇽", "X Flag"),
            ("🇾", "Y Flag"),
            ("🇿", "Z Flag"),
            ("α", "Greek Alpha"),
            ("β", "Greek Beta"),
            ("γ", "Greek Gamma"),
            ("δ", "Greek Delta"),
            ("π", "Greek Pi"),
            ("Σ", "Greek Sigma"),
            ("Ω", "Greek Omega"),
        ],
    ),
    "languages": (
        "Languages",
        [
            ("💬", "Language / Speech"),
            ("🗣️", "Speaking"),
            ("🌐", "Multilingual"),
            ("🔤", "Latin Alphabet"),
            ("🔠", "Uppercase"),
            ("🔡", "Lowercase"),
            ("あ", "Japanese Kana"),
            ("漢", "Chinese Han"),
            ("한", "Korean Hangul"),
            ("अ", "Devanagari"),
            ("ع", "Arabic"),
            ("א", "Hebrew"),
            ("α", "Greek"),
            ("Я", "Cyrillic"),
        ],
    ),
    "people": (
        "People",
        [
            ("👤", "Person"),
            ("👥", "People"),
            ("👫", "Couple"),
            ("👬", "Men"),
            ("👭", "Women"),
            ("🧑", "Person"),
            ("👶", "Baby"),
            ("🧒", "Child"),
            ("👦", "Boy"),
            ("👧", "Girl"),
            ("🧑‍🦱", "Curly Hair"),
            ("🧑‍🦰", "Red Hair"),
            ("🧑‍🦳", "White Hair"),
            ("🧑‍🦲", "Bald"),
            ("👱", "Blond"),
            ("🧔", "Beard"),
            ("👴", "Old Man"),
            ("👵", "Old Woman"),
            ("🧓", "Older Person"),
            ("👮", "Police"),
            ("👷", "Construction / Hardhat"),
            ("🥷", "Ninja"),
            ("💂", "Guard"),
            ("🕵️", "Detective"),
            ("🧙", "Wizard"),
            ("🧛", "Vampire"),
            ("🧟", "Zombie"),
            ("🧞", "Genie"),
            ("🧝", "Elf"),
            ("🧚", "Fairy"),
            ("🦸", "Superhero"),
            ("🦹", "Supervillain"),
            ("👻", "Ghost"),
            ("💀", "Skull"),
            ("☠️", "Bones"),
            ("👽", "Alien"),
            ("🤖", "Robot"),
            ("🎃", "Jack-o-lantern"),
            ("💩", "Poo"),
            ("👁️", "Eye"),
            ("👀", "Eyes"),
            ("👂", "Ear"),
            ("👃", "Nose"),
            ("👋", "Wave"),
            ("🤚", "Hand"),
            ("👍", "Thumbs Up"),
            ("👎", "Thumbs Down"),
            ("✌️", "Peace"),
            ("🤞", "Fingers Crossed"),
            ("🤘", "Rock On"),
            ("👊", "Fist"),
            ("✊", "Raised Fist"),
            ("🙌", "Hands"),
            ("🙏", "Pray"),
        ],
    ),
    "status": (
        "Status",
        [
            ("✅", "Visited"),
            ("❎", "Not Done"),
            ("⛔", "Forbidden"),
            ("🚫", "Blocked"),
            ("⚠️", "Warning"),
            ("🚧", "Caution"),
            ("📍", "Pin"),
            ("📌", "Pushpin"),
            ("🚩", "Flag"),
            ("🏁", "Finish"),
            ("🏳️", "Surrender"),
            ("🏴", "Dark"),
            ("🔴", "Red"),
            ("🟠", "Orange"),
            ("🟡", "Yellow"),
            ("🟢", "Green"),
            ("🔵", "Blue"),
            ("🟣", "Purple"),
            ("⚫", "Black"),
            ("⚪", "White"),
            ("🔒", "Locked"),
            ("🔓", "Unlocked"),
            ("🔐", "Key Lock"),
            ("🗝️", "Key"),
            ("🏆", "Trophy"),
            ("🥇", "First"),
            ("🥈", "Second"),
            ("🥉", "Third"),
            ("🎖️", "Medal"),
            ("💎", "Rare"),
            ("🌟", "Featured"),
            ("💫", "Special"),
            ("🆕", "New"),
            ("🆗", "OK"),
            ("🔞", "Adults"),
            ("💯", "Perfect"),
            ("❗", "Important"),
            ("❓", "Unknown"),
            ("💤", "Inactive"),
            ("♾️", "Ongoing"),
        ],
    ),
    "weather": (
        "Weather",
        [
            ("☀️", "Sunny"),
            ("🌤️", "Partly Cloudy"),
            ("⛅", "Cloudy"),
            ("🌥️", "Overcast"),
            ("☁️", "Cloud"),
            ("🌦️", "Rain Sun"),
            ("🌧️", "Rainy"),
            ("⛈️", "Thunder"),
            ("🌩️", "Lightning"),
            ("🌨️", "Snow"),
            ("❄️", "Snowflake"),
            ("⛄", "Snowman"),
            ("🌬️", "Wind"),
            ("💨", "Blow"),
            ("🌪️", "Tornado"),
            ("🌫️", "Fog"),
            ("🌊", "Wave"),
            ("🌈", "Rainbow"),
            ("☔", "Umbrella Rain"),
            ("⛱️", "Umbrella"),
            ("🌡️", "Thermometer"),
            ("🔥", "Hot"),
            ("🧊", "Cold"),
            ("💧", "Wet"),
            ("🌙", "Night"),
            ("🌛", "Crescent"),
            ("🌝", "Full Moon"),
            ("☀️", "Bright"),
            ("🌅", "Sunrise"),
            ("🌄", "Dawn"),
            ("🌇", "Dusk"),
            ("🌆", "Evening"),
        ],
    ),
    "space": (
        "Space",
        [
            ("🌑", "New Moon"),
            ("🌒", "Waxing Crescent"),
            ("🌓", "First Quarter"),
            ("🌔", "Waxing Gibbous"),
            ("🌕", "Full Moon"),
            ("🌖", "Waning Gibbous"),
            ("🌗", "Last Quarter"),
            ("🌘", "Waning Crescent"),
            ("🌙", "Crescent Moon"),
            ("🌛", "First Quarter Face"),
            ("🌜", "Last Quarter Face"),
            ("🌝", "Full Moon Face"),
            ("🌞", "Sun Face"),
            ("☀️", "Sun"),
            ("⭐", "Star"),
            ("🌟", "Glowing Star"),
            ("💫", "Dizzy Star"),
            ("🌠", "Shooting Star"),
            ("☄️", "Comet"),
            ("🌌", "Galaxy"),
            ("🪐", "Ringed Planet"),
            ("🌍", "Earth"),
            ("🌎", "Americas"),
            ("🌏", "Asia Pacific"),
            ("👽", "Alien"),
            ("👾", "Space Invader"),
            ("🛸", "UFO"),
            ("🚀", "Rocket"),
            ("🔭", "Telescope"),
        ],
    ),
    "crafts": (
        "Crafts",
        [
            ("🧵", "Thread"),
            ("🪡", "Sewing Needle"),
            ("🧶", "Yarn"),
            ("✂️", "Scissors"),
            ("🧷", "Safety Pin"),
            ("📐", "Set Square"),
            ("📏", "Ruler"),
            ("🧩", "Mosaic Tile"),
            ("◻️", "Ceramic Tile"),
            ("🔲", "Tile Border"),
            ("🖌️", "Paintbrush"),
            ("✏️", "Pencil"),
            ("🖍️", "Crayon"),
            ("🖊️", "Pen"),
            ("🎨", "Palette"),
            ("🖼️", "Painting"),
            ("🧰", "Toolbox"),
            ("🔨", "Hammer"),
            ("🔧", "Wrench"),
            ("🪛", "Screwdriver"),
            ("⚒️", "Hammer and Pick"),
            ("🛠️", "Hammer and Wrench"),
            ("🔩", "Bolt"),
            ("⚙️", "Gear"),
            ("🪚", "Saw"),
            ("🗜️", "Clamp"),
        ],
    ),
    "vintage": (
        "Vintage",
        [
            ("🏺", "Amphora"),
            ("🪙", "Old Coin"),
            ("👑", "Crown"),
            ("📜", "Scroll"),
            ("🔮", "Crystal Ball"),
            ("⚱️", "Urn"),
            ("🕰️", "Mantel Clock"),
            ("🪬", "Hamsa"),
            ("🧿", "Evil Eye"),
            ("🗿", "Moai"),
            ("🪆", "Nesting Doll"),
            ("🎪", "Carnival"),
            ("🎠", "Carousel"),
            ("🎻", "Violin"),
            ("📯", "Post Horn"),
            ("🔭", "Spyglass"),
            ("🧭", "Compass"),
            ("🗺️", "Old Map"),
            ("🧳", "Old Luggage"),
            ("🎩", "Top Hat"),
            ("👒", "Sun Hat"),
            ("🪞", "Antique Mirror"),
            ("🛢️", "Oil Drum"),
            ("⚙️", "Vintage Gear"),
            ("🪝", "Old Hook"),
            ("🔑", "Old Key"),
            ("🗝️", "Skeleton Key"),
            ("📿", "Beads"),
        ],
    ),
    "religion": (
        "Religion",
        [
            ("✝️", "Cross"),
            ("☪️", "Star and Crescent"),
            ("☸️", "Dharma Wheel"),
            ("✡️", "Star of David"),
            ("☯️", "Yin Yang"),
            ("🕎", "Menorah"),
            ("☦️", "Orthodox Cross"),
            ("🛐", "Place of Worship"),
            ("🙏", "Praying Hands"),
            ("🕉️", "Om"),
            ("☮️", "Peace Symbol"),
            ("🔯", "Hexagram"),
            ("💒", "Wedding Chapel"),
            ("⛪", "Church"),
            ("🕌", "Mosque"),
            ("🕍", "Synagogue"),
            ("🛕", "Temple"),
            ("⛩️", "Shinto Shrine"),
            ("🕋", "Kaaba"),
            ("⚰️", "Coffin"),
            ("🪦", "Gravestone"),
            ("☬", "Khanda"),
            ("☫", "Farsi / Islamic Symbol"),
            ("☤", "Caduceus"),
            ("📿", "Prayer Beads"),
            ("🕯️", "Candle"),
            ("📖", "Holy Book"),
        ],
    ),
    "tools": (
        "Tools",
        [
            ("🔨", "Hammer"),
            ("🪓", "Axe"),
            ("⛏️", "Pickaxe"),
            ("⚒️", "Hammer and Pick"),
            ("🛠️", "Hammer and Wrench"),
            ("🔧", "Wrench"),
            ("🪛", "Screwdriver"),
            ("🔩", "Bolt and Nut"),
            ("⚙️", "Gear"),
            ("🪚", "Saw"),
            ("🗜️", "Clamp"),
            ("🪝", "Hook"),
            ("🪜", "Ladder"),
            ("🧲", "Magnet"),
            ("📐", "Set Square"),
            ("📏", "Ruler"),
            ("✂️", "Scissors"),
            ("🔪", "Knife"),
            ("🗡️", "Dagger"),
            ("🪣", "Bucket"),
            ("🧹", "Broom"),
            ("🪠", "Plunger"),
            ("🧯", "Fire Extinguisher"),
            ("🛢️", "Oil Drum"),
            ("⛽", "Fuel"),
            ("🔑", "Key"),
            ("🗝️", "Old Key"),
            ("🔋", "Battery"),
            ("💡", "Light Bulb"),
            ("🔦", "Flashlight"),
            ("🕯️", "Candle"),
            ("📡", "Antenna"),
            ("🧰", "Toolbox"),
            ("🪤", "Mousetrap"),
            ("🪜", "Stepladder"),
            ("🧱", "Bricks"),
            ("🔐", "Padlock Key"),
            ("🔒", "Locked"),
            ("🔓", "Unlocked"),
        ],
    ),
    "flags": (
        "Flags",
        [
            ("🏳️", "White Flag"),
            ("🏴", "Black Flag"),
            ("🚩", "Red Flag"),
            ("🏁", "Checkered Flag"),
            ("🎌", "Crossed Flags"),
            ("🏴‍☠️", "Pirate Flag"),
            ("🇺🇸", "USA"),
            ("🇬🇧", "UK"),
            ("🇨🇦", "Canada"),
            ("🇦🇺", "Australia"),
            ("🇳🇿", "New Zealand"),
            ("🇫🇷", "France"),
            ("🇩🇪", "Germany"),
            ("🇮🇹", "Italy"),
            ("🇪🇸", "Spain"),
            ("🇵🇹", "Portugal"),
            ("🇳🇱", "Netherlands"),
            ("🇧🇪", "Belgium"),
            ("🇨🇭", "Switzerland"),
            ("🇦🇹", "Austria"),
            ("🇸🇪", "Sweden"),
            ("🇳🇴", "Norway"),
            ("🇩🇰", "Denmark"),
            ("🇫🇮", "Finland"),
            ("🇮🇪", "Ireland"),
            ("🇬🇷", "Greece"),
            ("🇵🇱", "Poland"),
            ("🇷🇺", "Russia"),
            ("🇺🇦", "Ukraine"),
            ("🇹🇷", "Turkey"),
            ("🇯🇵", "Japan"),
            ("🇰🇷", "South Korea"),
            ("🇨🇳", "China"),
            ("🇮🇳", "India"),
            ("🇮🇩", "Indonesia"),
            ("🇵🇭", "Philippines"),
            ("🇻🇳", "Vietnam"),
            ("🇹🇭", "Thailand"),
            ("🇲🇾", "Malaysia"),
            ("🇸🇬", "Singapore"),
            ("🇸🇦", "Saudi Arabia"),
            ("🇮🇱", "Israel"),
            ("🇮🇷", "Iran"),
            ("🇮🇶", "Iraq"),
            ("🇪🇬", "Egypt"),
            ("🇿🇦", "South Africa"),
            ("🇳🇬", "Nigeria"),
            ("🇰🇪", "Kenya"),
            ("🇲🇦", "Morocco"),
            ("🇪🇹", "Ethiopia"),
            ("🇧🇷", "Brazil"),
            ("🇦🇷", "Argentina"),
            ("🇨🇱", "Chile"),
            ("🇨🇴", "Colombia"),
            ("🇲🇽", "Mexico"),
            ("🇵🇪", "Peru"),
            ("🇻🇪", "Venezuela"),
            ("🇨🇺", "Cuba"),
            ("🇵🇷", "Puerto Rico"),
            ("🇺🇳", "United Nations"),
            ("🏳️‍🌈", "Rainbow Flag"),
            ("🏳️‍⚧️", "Trans Flag"),
        ],
    ),
    "faces": (
        "Faces",
        [
            ("😀", "Grinning"),
            ("😃", "Big Smile"),
            ("😄", "Grin"),
            ("😁", "Beaming"),
            ("😆", "Laughing"),
            ("😅", "Sweat Smile"),
            ("🤣", "Rolling Laugh"),
            ("😂", "Tears of Joy"),
            ("🙂", "Slight Smile"),
            ("🙃", "Upside Down"),
            ("🫠", "Melting"),
            ("😉", "Winking"),
            ("😊", "Blushing"),
            ("😇", "Angel"),
            ("🥰", "Hearts"),
            ("😍", "Heart Eyes"),
            ("🤩", "Star Struck"),
            ("😘", "Kiss"),
            ("😋", "Savoring"),
            ("😜", "Winking Tongue"),
            ("🤪", "Zany"),
            ("🤑", "Money Mouth"),
            ("🤗", "Hugging"),
            ("🤭", "Hand Over Mouth"),
            ("🫢", "Gasp"),
            ("🤫", "Shushing"),
            ("🤔", "Thinking"),
            ("🫡", "Saluting"),
            ("🤐", "Zipper Mouth"),
            ("🤨", "Raised Eyebrow"),
            ("😐", "Neutral"),
            ("😑", "Expressionless"),
            ("😶", "No Mouth"),
            ("😏", "Smirk"),
            ("😒", "Unamused"),
            ("🙄", "Eye Roll"),
            ("😬", "Grimacing"),
            ("😌", "Relieved"),
            ("😔", "Pensive"),
            ("😪", "Sleepy"),
            ("🤤", "Drooling"),
            ("😴", "Sleeping"),
            ("😷", "Medical Mask"),
            ("🤒", "Sick"),
            ("🤕", "Injured"),
            ("🤢", "Nauseated"),
            ("🤮", "Vomiting"),
            ("🤧", "Sneezing"),
            ("🥵", "Overheated"),
            ("🥶", "Cold Face"),
            ("🥴", "Woozy"),
            ("😵", "Dizzy"),
            ("🤯", "Exploding Head"),
            ("🤠", "Cowboy"),
            ("🥳", "Partying"),
            ("🥸", "Disguised"),
            ("😎", "Sunglasses"),
            ("🤓", "Nerd"),
            ("🧐", "Monocle"),
            ("😕", "Confused"),
            ("😟", "Worried"),
            ("🙁", "Frowning"),
            ("☹️", "Sad"),
            ("😮", "Open Mouth"),
            ("😲", "Astonished"),
            ("😳", "Flushed"),
            ("🥺", "Pleading"),
            ("🥹", "Holding Back Tears"),
            ("😢", "Crying"),
            ("😭", "Loudly Crying"),
            ("😱", "Screaming"),
            ("😡", "Angry"),
            ("🤬", "Cursing"),
            ("😈", "Smiling Devil"),
            ("👿", "Angry Devil"),
            ("💀", "Skull"),
            ("☠️", "Skull Crossbones"),
            ("💩", "Poo"),
            ("🤡", "Clown"),
            ("👹", "Ogre"),
            ("👺", "Goblin"),
            ("👻", "Ghost"),
            ("👽", "Alien"),
            ("🤖", "Robot"),
            ("😺", "Cat Smile"),
            ("😸", "Cat Grin"),
            ("😹", "Cat Joy"),
            ("😻", "Cat Heart Eyes"),
            ("😼", "Cat Smirk"),
            ("😽", "Cat Kiss"),
            ("🙀", "Cat Scream"),
            ("😿", "Cat Crying"),
            ("😾", "Cat Pouting"),
        ],
    ),
}

# Extra search keywords for emoji icons, keyed by the emoji character.
# Each value is a space-separated string of lowercase synonym/alias terms.
# These supplement the display label so that searches for common urbex
# concepts (e.g. "derelict", "industrial", "fire") surface relevant icons
# even when the display label alone wouldn't match.
ICON_KEYWORDS: dict[str, str] = {
    # ── Places ───────────────────────────────────────────────────────────────
    "🏠": "residential home dwelling",
    "🏡": "house residential suburb",
    "🏚️": "derelict ruin empty decrepit rot decay shell gutted wreck",
    "🏢": "commercial building block tower skyscraper high rise",
    "🏣": "building facility structure",
    "🏤": "mail delivery postal sorting",
    "🏥": "medical clinic emergency healthcare ward",
    "🏦": "financial vault safe deposit",
    "🏨": "motel inn hostel lodge accommodation lodging",
    "🏩": "motel accommodation lodging",
    "🏪": "store retail grocery supermarket department",
    "🏫": "education college academy university classroom",
    "🏬": "shopping centre department store retail complex",
    "🏭": "industrial plant mill works warehouse manufacturing production",
    "🏯": "fortress stronghold fortification keep watchtower ruin",
    "🏰": "castle chateau palace fortress medieval ruin",
    "🏛️": "ancient ruins classical temple historic heritage",
    "🪨": "rubble debris stone masonry crumble",
    "🏗️": "scaffolding building site development infrastructure work",
    "🏟️": "arena sports venue grandstand",
    "🗼": "pylon antenna broadcast communications lattice",
    "🗽": "statue memorial landmark",
    "🕌": "islamic arabic mosque worship",
    "🕍": "jewish synagogue worship",
    "🛕": "hindu buddhist shrine worship",
    "⛪": "chapel cathedral worship religion",
    "⛩️": "japanese torii gate shrine",
    "⛲": "water feature park garden public",
    "🏕️": "outdoor camping survival wilderness",
    "🏙️": "urban downtown metropolitan skyline city centre",
    "🌆": "dusk evening urban skyline",
    "🌉": "infrastructure crossing span suspension",
    "🏔️": "peak summit alpine ridge elevation",
    "⛰️": "elevation terrain ridge summit slope",
    "🌋": "eruption lava geological volcanic",
    "🏝️": "coast shore isolated remote",
    "🏜️": "arid barren wasteland dry",
    "🌲": "forest woodland pine timber",
    "🌳": "deciduous park woodland nature",
    "🌊": "water coast ocean river flood surge wave",
    "🏞️": "national park reserve wilderness recreation",
    "⛽": "petrol service station fuel gas",
    "🚿": "bath shower amenity sanitation plumbing water",
    "🚽": "toilet restroom bathroom sanitation",
    "🛁": "bath amenity sanitation",
    "🔑": "lock key entry access",
    "🔐": "secured locked entry restricted",
    "🔒": "locked sealed restricted no entry security",
    "🔓": "open unlocked accessible",
    "🔧": "tool repair maintenance mechanical",
    "🔨": "demolition construction hammer work",
    "⚙️": "machinery gear mechanical industrial",
    "🪛": "tool maintenance repair screw",
    "🪚": "wood cut construction carpentry",
    "🧱": "wall brick block masonry",
    "🪜": "ladder access climb",
    "🚪": "doorway entrance exit entry",
    "🪟": "window aperture opening",
    "🪑": "furniture interior",
    "🛋️": "lounge sofa interior furniture",
    "🛏️": "bedroom interior domestic",
    "💡": "light electricity power utility bulb",
    "🔦": "torch flashlight illumination dark",
    "🕯️": "candle dim light atmospheric",
    "🔋": "power electricity energy battery",
    "🔌": "electrical outlet power utility",
    "📡": "satellite dish antenna broadcast communications relay",
    "🗑️": "rubbish trash bin waste disposal litter",
    "📦": "crate box storage cargo container",
    "🗄️": "filing cabinet storage records archive",
    "📁": "folder file archive records",
    # ── Danger / hazard ──────────────────────────────────────────────────────
    "⚠️": "caution risk alert hazard unsafe",
    "☢️": "radiation toxic nuclear contamination fallout",
    "☣️": "biohazard toxic contamination hazardous waste",
    "🚫": "no entry prohibited banned restricted off limits",
    "⛔": "stop prohibited restricted no entry",
    "🚨": "alarm emergency siren police security alert",
    "🔴": "red stop alert critical urgent",
    "⚡": "electricity shock electrocution live wire hazard",
    "💀": "death toxic lethal risk skull crossbones",
    "🔪": "sharp cut hazard danger",
    "🩸": "injury blood wound",
    "🧯": "fire extinguisher safety suppression",
    "🚒": "fire engine emergency response",
    "🚑": "ambulance emergency medical rescue",
    "🚓": "police patrol enforcement security",
    # ── Fire ─────────────────────────────────────────────────────────────────
    "🔥": "fire flame heat burn scorched arson",
    "🌡️": "temperature heat cold climate",
    "💨": "wind gust air vent exhaust",
    "💧": "water drip leak moisture damp",
    # ── Transport ────────────────────────────────────────────────────────────
    "🚂": "locomotive steam engine traincar historical heritage rail",
    "🚃": "carriage rolling stock rail",
    "🚄": "high speed passenger rail",
    "🚇": "subway metro underground tube",
    "🚉": "platform depot terminal rail hub",
    "🚈": "light rail tram monorail",
    "🚌": "coach bus depot terminal",
    "🚍": "bus coach terminus",
    "🚘": "car auto vehicle",
    "🚗": "car auto vehicle",
    "🛻": "pickup truck utility",
    "🚛": "lorry haulage freight truck",
    "🏎️": "racecar motor circuit",
    "🏍️": "motorcycle motorbike",
    "🛵": "moped scooter",
    "✈️": "plane airport aviation terminal runway",
    "🛩️": "small aircraft hangar airfield",
    "🚀": "launch pad rocket space",
    "🛸": "ufo spacecraft hangar disc aviation",
    "🚢": "ship vessel dock harbour berth",
    "🛳️": "cruise liner dock harbour port",
    "⛴️": "ferry dock crossing",
    "🚤": "speedboat dock marina",
    "⛵": "sailboat marina dock",
    "🛥️": "motorboat marina dock",
    "⚓": "anchor dock harbour port maritime",
    "🚁": "helicopter pad rooftop hangar",
    # ── Nature / terrain ─────────────────────────────────────────────────────
    "🌿": "overgrown vegetation nature reclaimed",
    "🍂": "autumn decay seasonal",
    "🌾": "field farmland rural",
    "🌵": "arid desert dry",
    "🌴": "tropical coastal subtropical",
    "🍄": "fungi mushroom damp dark",
    "🐾": "animal wildlife track footprint",
    "🦅": "raptor bird wildlife",
    "🦉": "nocturnal bird wildlife",
    "🦊": "wildlife mammal forest",
    "🐺": "wildlife mammal predator",
    "🦌": "deer wildlife mammal",
    # ── Status / markers ─────────────────────────────────────────────────────
    "📌": "pin marker location",
    "📍": "pin drop location mark",
    "🟡": "caution warning moderate",
    "🟢": "safe clear good go",
    "⭐": "star favourite highlight important",
    "🌟": "star glow highlight featured",
    "❗": "exclamation important urgent attention",
    "❓": "question unknown uncertain",
    "✅": "checked done complete verified",
    "❌": "removed deleted closed gone",
    "🔵": "blue info note calm",
    "🟠": "orange moderate caution",
    "🏴": "black flag closed danger end",
    "🚩": "flag marker alert danger point",
    "🏁": "finish end complete done",
    "💬": "comment note message talk",
    "💭": "thought note idea",
    "🗣️": "spoken verbal announcement",
    "👁️": "watch observe surveillance monitor",
    "🔍": "search investigate inspect detail",
    "🔎": "search zoom investigate",
    "📷": "photo camera image evidence",
    "📸": "photo shot selfie camera",
    "🎥": "video film footage record",
    "📹": "video camcorder film",
    "🗺️": "map route navigation plan area",
    "🧭": "compass direction navigation orient",
    # ── Tools / investigation ─────────────────────────────────────────────────
    "🪝": "hook attach pull grab",
    "🪢": "rope tie secure restraint",
    "🪤": "trap catch snare",
    "🧰": "toolbox maintenance repair kit",
    "🧲": "magnet attract pull metal",
    "🪣": "bucket container water",
    "🧴": "liquid chemical substance",
    "🧪": "chemical lab test experiment",
    "⚗️": "lab chemistry research science",
    "🔬": "microscope lab detail research",
    "🧫": "specimen culture biology lab",
    "🩺": "medical stethoscope health examination",
    "💊": "medicine pharmacy medical",
    "🩹": "wound injury first aid",
    "🩻": "xray medical scan",
    # ── History / archaeology ─────────────────────────────────────────────────
    "🏺": "artefact antique historical archaeological",
    "🗿": "stone carving prehistoric ancient monument",
    "📜": "scroll document historical archive record",
    "🏅": "medal award achievement",
    "🎖️": "medal military decoration award",
    # - Letters
    "🇦": "A Alpha Letters Characters Words Text",
    "🇧": "B Beta Letters Characters Words Text",
    "🇨": "C Letters Characters Words Text",
    "🇩": "D Delta Letters Characters Words Text",
    "🇪": "E Epsilon Letters Characters Words Text",
    "🇫": "F Letters Characters Words Text",
    "🇬": "G Gamma Letters Characters Words Text",
    "🇭": "H Letters Characters Words Text",
    "🇮": "I Iota Letters Characters Words Text",
    "🇯": "J Jota Letters Characters Words Text",
    "🇰": "K Kappa Letters Characters Words Text",
    "🇱": "L Lambda Letters Characters Words Text",
    "🇲": "M Letters Characters Words Text",
    "🇳": "N Letters Characters Words Text",
    "🇴": "O Letters Characters Words Text",
    "🇵": "P Pi Letters Characters Words Text",
    "🇶": "Q Qeta Letters Characters Words Text",
    "🇷": "R Rho Letters Characters Words Text",
    "🇸": "S Sigma Letters Characters Words Text",
    "🇹": "T Theta Letters Characters Words Text",
    "🇺": "U Upsilon Letters Characters Words Text",
    "🇻": "V Letters Characters Words Text",
    "🇼": "W Letters Characters Words Text",
    "🇽": "X Letters Characters Words Text",
    "🇾": "Y Letters Characters Words Text",
    "🇿": "Z Letters Characters Words Text",
    # ── Requested picker coverage / aliases ──────────────────────────────────
    "🎟️": "admission ticket entry pass legal permit museum",
    "🎫": "ticket admission pass entry",
    "🧾": "receipt permit paperwork legal",
    "⚖️": "legal law justice scales court",
    "▦": "sewer grate drain manhole grid",
    "▤": "sewer grate drain vent louver",
    "🥾": "boots footwear hiking urbex gear",
    "🎒": "backpack bag pack rucksack urbex gear",
    "🪖": "hardhat helmet safety construction",
    "👷": "hardhat construction worker helmet",
    "💪": "muscle strong strength",
    "🏋️": "weights gym lift strength",
    "🥷": "ninja stealth covert",
    "🏷️": "tag label labelled labeled",
    "🔖": "bookmark save label",
    "🔗": "share link chain url",
    "📤": "share send export upload",
    "💾": "save disk floppy",
    "👓": "eyeglasses glasses spectacles",
    "📚": "book books library reading",
    "📖": "book reading holy",
    "🧩": "mosaic ceramic tile tessera",
    "◻️": "ceramic tile square mosaic",
    "🐍♾️": "ouroboros snake infinity cycle",
    "⚜️": "fleur de lis fleur-de-lis heraldry",
    "α": "greek alpha letter language",
    "β": "greek beta letter language",
    "γ": "greek gamma letter language",
    "δ": "greek delta letter language",
    "π": "greek pi letter math",
    "Σ": "greek sigma letter math",
    "Ω": "greek omega letter",
    "🌷": "spring season flower",

}


COLOR_CHOICES = [
    ("#F44336", "Red"),
    ("#E91E63", "Pink"),
    ("#9C27B0", "Purple"),
    ("#673AB7", "Deep Purple"),
    ("#3F51B5", "Indigo"),
    ("#2196F3", "Blue"),
    ("#03A9F4", "Light Blue"),
    ("#00BCD4", "Cyan"),
    ("#009688", "Teal"),
    ("#4CAF50", "Green"),
    ("#8BC34A", "Light Green"),
    ("#CDDC39", "Lime"),
    ("#FFEB3B", "Yellow"),
    ("#FFC107", "Amber"),
    ("#FF9800", "Orange"),
    ("#FF5722", "Deep Orange"),
    ("#795548", "Brown"),
    ("#607D8B", "Blue Grey"),
    ("#9E9E9E", "Grey"),
    ("#FFFFFF", "White"),
    ("#000000", "Black"),
]
